# Generated by Django 5.2.9 on 2026-01-09 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('is_system', models.BooleanField(default=False)),
                ('is_editable', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_roles', to='accounts.account')),
                ('permissions', models.ManyToManyField(blank=True, related_name='workshop_roles', to='auth.permission', verbose_name='Permissões')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('account', 'name'), name='unique_workshop_role_per_account')],
            },
        ),
    ]
