# Generated by Django 6.0 on 2026-03-08 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iam", "0002_alter_workshoprole_atualizado_em_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workshoprole",
            options={
                "verbose_name": "Cargo da Oficina",
                "verbose_name_plural": "Cargos da Oficina",
            },
        ),
    ]
