# Generated by Django 5.2.9 on 2026-01-07 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopmember',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='workshops.workshop'),
        ),
        migrations.AddField(
            model_name='user',
            name='workshops',
            field=models.ManyToManyField(blank=True, related_name='users', through='accounts.WorkshopMember', to='workshops.workshop'),
        ),
        migrations.AddField(
            model_name='workshoprole',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_roles', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='workshoprole',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='workshop_roles', to='auth.permission', verbose_name='Permissões'),
        ),
        migrations.AddField(
            model_name='workshopmember',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workshop_members', to='accounts.workshoprole'),
        ),
        migrations.AddConstraint(
            model_name='workshoprole',
            constraint=models.UniqueConstraint(fields=('account', 'name'), name='unique_workshop_role_per_account'),
        ),
        migrations.AddConstraint(
            model_name='workshopmember',
            constraint=models.UniqueConstraint(fields=('user', 'workshop'), name='unique_user_workshop_member'),
        ),
    ]
