# Generated by Django 5.2.9 on 2026-01-08 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='workshops',
            field=models.ManyToManyField(blank=True, related_name='users', through='workshops.WorkshopMember', to='workshops.workshop'),
        ),
        migrations.AddField(
            model_name='account',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='accounts.account'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('is_account_owner', True)), fields=('cpf',), name='unique_owner_cpf'),
        ),
    ]
