# Generated by Django 5.2.9 on 2025-12-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADM', 'Administrator'), ('MGR', 'Manager'), ('MEC', 'Mechanic')], default='ADM', max_length=3),
        ),
    ]
