# Generated by Django 5.2.9 on 2026-01-07 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopmember',
            name='role',
        ),
        migrations.RemoveField(
            model_name='workshopmember',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workshopmember',
            name='workshop',
        ),
        migrations.RemoveField(
            model_name='workshoprole',
            name='account',
        ),
        migrations.RemoveField(
            model_name='workshoprole',
            name='permissions',
        ),
    ]
