# Generated by Django 6.0 on 2026-03-08 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_account_atualizado_em_alter_account_criado_em"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={"verbose_name": "Conta", "verbose_name_plural": "Contas"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "Usuário", "verbose_name_plural": "Usuários"},
        ),
    ]
