# Generated by Django 5.2.9 on 2026-01-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_workshopmember_role_and_more'),
        ('workshops', '0002_workshopmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='workshops',
            field=models.ManyToManyField(blank=True, related_name='users', through='workshops.WorkshopMember', to='workshops.workshop'),
        ),
        migrations.DeleteModel(
            name='WorkshopMember',
        ),
        migrations.DeleteModel(
            name='WorkshopRole',
        ),
    ]
