# Generated by Django 5.2.9 on 2026-04-24 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_options_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('url', models.CharField(max_length=500, verbose_name='URL da Página')),
                ('position', models.PositiveIntegerField(default=1, verbose_name='Posição')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Página Favorita',
                'verbose_name_plural': 'Páginas Favoritas',
                'ordering': ['position', 'pk'],
                'indexes': [models.Index(fields=['user', 'position'], name='favpage_user_pos_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'url'), name='unique_user_favorite_page_url')],
            },
        ),
    ]
