# Generated by Django 6.0 on 2026-05-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_password_reset_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Número com DDI para envio de mensagens via WhatsApp",
                max_length=20,
                verbose_name="Telefone (WhatsApp)",
            ),
        ),
    ]
