# Generated by Django 6.0 on 2026-05-11 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_logincodetoken"),
    ]

    operations = []
