# Generated by Django 6.0 on 2026-08-01 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_logincode_unused_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritepage',
            options={'ordering': ['position', 'pk'], 'verbose_name': 'Página favorita', 'verbose_name_plural': 'Páginas favoritas'},
        ),
        migrations.AlterField(
            model_name='favoritepage',
            name='url',
            field=models.CharField(max_length=500, verbose_name='URL da página'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Número com DDI para envio de mensagens pelo WhatsApp.', max_length=20, verbose_name='Telefone (WhatsApp)'),
        ),
    ]
