# Generated by Django 6.0 on 2026-03-27 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workshops', '0017_workshop_certificate_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_templates', to='workshops.workshop')),
            ],
            options={
                'verbose_name': 'Mensagem WhatsApp',
                'verbose_name_plural': 'Mensagens WhatsApp',
                'constraints': [models.UniqueConstraint(fields=('workshop', 'name'), name='unique_message_template_name_per_workshop')],
            },
        ),
    ]
