# Generated by Django 5.2.9 on 2026-03-27 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_alter_customer_bairro_alter_customer_cidade'),
        ('messaging', '0001_initial'),
        ('workshops', '0017_workshop_certificate_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMessageGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('message', models.TextField(verbose_name='Mensagem personalizada')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('message_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_message_groups', to='messaging.messagetemplate', verbose_name='Mensagem cadastrada')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_message_groups', to='workshops.workshop')),
            ],
            options={
                'verbose_name': 'Grupo de mensagem',
                'verbose_name_plural': 'Grupos de mensagens',
            },
        ),
        migrations.CreateModel(
            name='CustomerMessageGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_group_memberships', to='customer.customer', verbose_name='Cliente')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='messaging.customermessagegroup', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Cliente do grupo de mensagem',
                'verbose_name_plural': 'Clientes do grupo de mensagem',
            },
        ),
        migrations.AddField(
            model_name='customermessagegroup',
            name='customers',
            field=models.ManyToManyField(blank=True, related_name='message_groups', through='messaging.CustomerMessageGroupMembership', to='customer.customer'),
        ),
        migrations.AddConstraint(
            model_name='customermessagegroupmembership',
            constraint=models.UniqueConstraint(fields=('group', 'customer'), name='unique_customer_message_group_membership'),
        ),
        migrations.AddConstraint(
            model_name='customermessagegroup',
            constraint=models.UniqueConstraint(fields=('workshop', 'name'), name='unique_customer_message_group_name_per_workshop'),
        ),
    ]
