# Generated by Django 6.0 on 2026-06-27 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_customermessagegroup_customermessagegroupmembership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermessagegroup',
            name='filter_criteria',
            field=models.JSONField(blank=True, help_text='Configuração JSON com regras para incluir clientes automaticamente no grupo. Deixe vazio para usar apenas seleção manual.', null=True, verbose_name='Critérios de segmentação'),
        ),
    ]
