# Generated by Django 6.0 on 2026-07-14 21:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_alter_vehicle_engine'),
        ('messaging', '0003_add_filter_criteria_to_message_group'),
        ('scheduling', '0009_messaging_history_outbound_and_alert_lead'),
        ('workshops', '0027_workshop_whatsapp_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageDispatchBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('source', models.CharField(choices=[('group_manual', 'Disparo manual de grupo'), ('appointment_alert', 'Alerta de agendamento'), ('command', 'Comando')], max_length=32, verbose_name='Origem')),
                ('status', models.CharField(choices=[('queued', 'Na fila'), ('processing', 'Processando'), ('completed', 'Concluído'), ('failed', 'Falhou'), ('cancelled', 'Cancelado')], default='queued', max_length=20, verbose_name='Status')),
                ('total_count', models.PositiveIntegerField(default=0, verbose_name='Total')),
                ('queued_count', models.PositiveIntegerField(default=0, verbose_name='Na fila')),
                ('pending_count', models.PositiveIntegerField(default=0, verbose_name='Pendentes')),
                ('sent_count', models.PositiveIntegerField(default=0, verbose_name='Enviadas')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='Falhas')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_batches', to='messaging.customermessagegroup', verbose_name='Grupo')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_dispatch_batches', to=settings.AUTH_USER_MODEL, verbose_name='Disparado por')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_dispatch_batches', to='workshops.workshop')),
            ],
            options={
                'verbose_name': 'Lote de disparo',
                'verbose_name_plural': 'Lotes de disparo',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MessageDispatchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('client_message_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True, verbose_name='ID da mensagem')),
                ('phone', models.CharField(blank=True, default='', max_length=32, verbose_name='Telefone')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('status', models.CharField(choices=[('queued', 'Na fila'), ('pending', 'Pendente'), ('sent', 'Enviada'), ('failed', 'Falhou')], default='queued', max_length=20, verbose_name='Status')),
                ('error', models.TextField(blank=True, default='', verbose_name='Erro')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='messaging.messagedispatchbatch', verbose_name='Lote')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_dispatch_logs', to='customer.customer', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Histórico de mensagem',
                'verbose_name_plural': 'Histórico de mensagens',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScheduledOutboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('phone', models.CharField(blank=True, default='', max_length=32, verbose_name='Telefone')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('run_at', models.DateTimeField(db_index=True, verbose_name='Executar em')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('sent', 'Enviada'), ('cancelled', 'Cancelada'), ('failed', 'Falhou')], default='pending', max_length=20, verbose_name='Status')),
                ('source', models.CharField(choices=[('appointment_alert', 'Alerta de agendamento')], default='appointment_alert', max_length=32, verbose_name='Origem')),
                ('client_message_id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='ID da mensagem')),
                ('error', models.TextField(blank=True, default='', verbose_name='Erro')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_outbound_messages', to='scheduling.appointment', verbose_name='Agendamento')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_messages', to='messaging.messagedispatchbatch', verbose_name='Lote')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_outbound_messages', to='customer.customer', verbose_name='Cliente')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_outbound_messages', to='workshops.workshop')),
            ],
            options={
                'verbose_name': 'Mensagem agendada',
                'verbose_name_plural': 'Mensagens agendadas',
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='messagedispatchbatch',
            index=models.Index(fields=['workshop', '-criado_em'], name='messaging_m_worksho_56a723_idx'),
        ),
        migrations.AddIndex(
            model_name='messagedispatchbatch',
            index=models.Index(fields=['group', '-criado_em'], name='messaging_m_group_i_b4541b_idx'),
        ),
        migrations.AddIndex(
            model_name='messagedispatchlog',
            index=models.Index(fields=['batch', 'status'], name='messaging_m_batch_i_00c705_idx'),
        ),
        migrations.AddIndex(
            model_name='messagedispatchlog',
            index=models.Index(fields=['client_message_id'], name='messaging_m_client__eb1010_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledoutboundmessage',
            index=models.Index(fields=['status', 'run_at'], name='messaging_s_status_841897_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledoutboundmessage',
            index=models.Index(fields=['workshop', 'status', 'run_at'], name='messaging_s_worksho_0ce87c_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledoutboundmessage',
            index=models.Index(fields=['appointment', 'status'], name='messaging_s_appoint_f34289_idx'),
        ),
    ]
