# Generated by Django 6.0 on 2026-07-17 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_messaging_history_outbound_and_alert_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagedispatchbatch',
            name='processing_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Processando'),
        ),
        migrations.AlterField(
            model_name='messagedispatchlog',
            name='status',
            field=models.CharField(choices=[('queued', 'Na fila'), ('pending', 'Pendente'), ('processing', 'Processando'), ('sent', 'Enviada'), ('failed', 'Falhou')], default='queued', max_length=20, verbose_name='Status'),
        ),
    ]
