# Generated by Django 6.0 on 2026-07-23 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_oil_change_tracking'),
        ('messaging', '0006_remove_pending_add_cancelled_dispatch_status'),
        ('scheduling', '0009_messaging_history_outbound_and_alert_lead'),
        ('workshops', '0031_oil_change_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledoutboundmessage',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_outbound_messages', to='customer.vehicle', verbose_name='Veículo'),
        ),
        migrations.AlterField(
            model_name='messagedispatchbatch',
            name='source',
            field=models.CharField(choices=[('group_manual', 'Disparo manual de grupo'), ('appointment_alert', 'Alerta de agendamento'), ('oil_change_alert', 'Alerta de troca de óleo'), ('command', 'Comando')], max_length=32, verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='scheduledoutboundmessage',
            name='source',
            field=models.CharField(choices=[('appointment_alert', 'Alerta de agendamento'), ('oil_change_alert', 'Alerta de troca de óleo')], default='appointment_alert', max_length=32, verbose_name='Origem'),
        ),
        migrations.AddIndex(
            model_name='scheduledoutboundmessage',
            index=models.Index(fields=['vehicle', 'status'], name='messaging_s_vehicle_b2caec_idx'),
        ),
    ]
