# Generated by Django 6.0 on 2026-07-25 06:21

import apps.messaging.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0018_oil_change_tracking"),
        ("messaging", "0007_oil_change_tracking"),
        ("workorder", "0037_wave2_stored_totals"),
        ("workshops", "0031_typed_templates_and_satisfaction_reviews"),
    ]

    operations = [
        migrations.CreateModel(
            name="SatisfactionReview",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="Data de Criação")),
                ("atualizado_em", models.DateTimeField(auto_now=True, verbose_name="Data de Atualização")),
                ("public_token", models.CharField(default=apps.messaging.models.generate_satisfaction_review_token, editable=False, max_length=64, unique=True)),
                ("rating", models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Nota")),
                ("comment", models.TextField(blank=True, default="", verbose_name="Comentário")),
                ("status", models.CharField(choices=[("pending", "Pendente"), ("sent", "Enviada"), ("submitted", "Respondida"), ("expired", "Expirada"), ("cancelled", "Cancelada")], default="pending", max_length=20, verbose_name="Status")),
                ("sent_at", models.DateTimeField(blank=True, null=True, verbose_name="Enviada em")),
                ("submitted_at", models.DateTimeField(blank=True, null=True, verbose_name="Respondida em")),
                ("google_cta_shown", models.BooleanField(default=False, verbose_name="CTA Google exibido")),
            ],
            options={
                "verbose_name": "Avaliação de satisfação",
                "verbose_name_plural": "Avaliações de satisfação",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="messagetemplate",
            name="template_type",
            field=models.CharField(choices=[("generic", "Genérico"), ("oil_change", "Lembrete troca de óleo"), ("birthday", "Aniversário"), ("appointment", "Agendamento")], db_index=True, default="generic", max_length=32, verbose_name="Tipo"),
        ),
        migrations.AlterField(
            model_name="messagedispatchbatch",
            name="source",
            field=models.CharField(
                choices=[("group_manual", "Disparo manual de grupo"), ("appointment_alert", "Alerta de agendamento"), ("oil_change_alert", "Alerta de troca de óleo"), ("birthday_alert", "Alerta de aniversário"), ("satisfaction_survey", "Pesquisa de satisfação"), ("command", "Comando")],
                max_length=32,
                verbose_name="Origem",
            ),
        ),
        migrations.AlterField(
            model_name="scheduledoutboundmessage",
            name="source",
            field=models.CharField(choices=[("appointment_alert", "Alerta de agendamento"), ("oil_change_alert", "Alerta de troca de óleo"), ("birthday_alert", "Alerta de aniversário"), ("satisfaction_survey", "Pesquisa de satisfação")], default="appointment_alert", max_length=32, verbose_name="Origem"),
        ),
        migrations.AddConstraint(
            model_name="messagetemplate",
            constraint=models.UniqueConstraint(condition=models.Q(("is_active", True), models.Q(("template_type", "generic"), _negated=True)), fields=("workshop", "template_type"), name="unique_active_typed_message_template_per_workshop"),
        ),
        migrations.AddField(
            model_name="satisfactionreview",
            name="customer",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="satisfaction_reviews", to="customer.customer"),
        ),
        migrations.AddField(
            model_name="satisfactionreview",
            name="scheduled_message",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="satisfaction_reviews", to="messaging.scheduledoutboundmessage", verbose_name="Mensagem agendada"),
        ),
        migrations.AddField(
            model_name="satisfactionreview",
            name="workorder",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="satisfaction_review", to="workorder.workorder"),
        ),
        migrations.AddField(
            model_name="satisfactionreview",
            name="workshop",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="satisfaction_reviews", to="workshops.workshop"),
        ),
        migrations.AddIndex(
            model_name="satisfactionreview",
            index=models.Index(fields=["workshop", "-criado_em"], name="messaging_s_worksho_70f441_idx"),
        ),
        migrations.AddIndex(
            model_name="satisfactionreview",
            index=models.Index(fields=["workshop", "status"], name="messaging_s_worksho_c7e591_idx"),
        ),
        migrations.AddIndex(
            model_name="satisfactionreview",
            index=models.Index(fields=["public_token"], name="messaging_s_public__143a65_idx"),
        ),
    ]
