# Generated by Django 6.0 on 2026-08-01 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0009_review_plan_and_messaging_updates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customermessagegroup',
            options={'verbose_name': 'Grupo de mensagens', 'verbose_name_plural': 'Grupos de mensagens'},
        ),
        migrations.AlterModelOptions(
            name='customermessagegroupmembership',
            options={'verbose_name': 'Cliente do grupo de mensagens', 'verbose_name_plural': 'Clientes do grupo de mensagens'},
        ),
    ]
