# Generated by Django 6.0 on 2026-08-01 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0010_fix_messaging_ui_verbose_names'),
        ('messaging', '0011_default_templates_primeiro_nome'),
    ]

    operations = [
    ]
