from django.urls import path
from . import views

app_name = "budget"

urlpatterns = [
    path("events/", views.BudgetEventsView.as_view(), name="budget_events"),
    path("", views.BudgetListView.as_view(), name="budget_list"),
    path("create/", views.BudgetCreateView.as_view(), name="budget_create"),
    path("<int:pk>/edit/", views.BudgetUpdateView.as_view(), name="budget_update"),
    path("<int:pk>/delete/", views.BudgetDeleteView.as_view(), name="budget_delete"),
    path("customer-detail/", views.CustomerDetailView.as_view(), name="customer-detail"),
    path("vehicle-detail/", views.VehicleDetailView.as_view(), name="vehicle-detail"),
    path("get-vehicles/", views.VehicleListView.as_view(), name="get-vehicles"),
    path("selection/<int:budget_id>/<str:item_type>/", views.ItemSelectionModalView.as_view(), name="item_selection"),
    path("<int:budget_id>/add-item/<int:item_id>/<str:item_type>/", views.AddItemToBudgetView.as_view(), name="add_item_to_budget"),
    path("<int:budget_id>/remove-item/<int:item_id>/<str:item_type>/", views.RemoveItemFromBudgetView.as_view(), name="remove_item_from_budget"),
    path("<int:budget_id>/remove-budget-item/<int:item_id>/", views.RemoveBudgetItemView.as_view(), name="remove_budget_item"),
    path("<int:budget_id>/remove-products-batch/", views.RemoveProductItemsBatchFromBudgetView.as_view(), name="remove_products_batch"),
    path("<int:budget_id>/remove-services-batch/", views.RemoveServiceItemsBatchFromBudgetView.as_view(), name="remove_services_batch"),
    path("<int:budget_id>/remove-kits-batch/", views.RemoveKitItemsBatchFromBudgetView.as_view(), name="remove_kits_batch"),
    path("<int:budget_id>/item/<int:item_id>/edit/", views.BudgetItemUpdateView.as_view(), name="edit_item"),
    path("<int:budget_id>/item/<int:item_id>/calculate/", views.BudgetItemCalculateView.as_view(), name="calculate_item"),
    # Kit editing URLs
    path("<int:budget_id>/kit/<int:item_id>/edit/", views.BudgetKitEditView.as_view(), name="edit_kit"),
    path("<int:budget_id>/kit/<int:item_id>/product/<int:product_id>/calculate/", views.BudgetKitProductCalculateView.as_view(), name="calculate_kit_product"),
    path("<int:budget_id>/kit/<int:item_id>/service/<int:service_id>/calculate/", views.BudgetKitServiceCalculateView.as_view(), name="calculate_kit_service"),
    path("update_slider/<int:budget_id>/", views.UpdateSliderView.as_view(), name="update_slider"),
    path("mark-step5-calculation-viewed/<int:budget_id>/", views.MarkStep5CalculationViewedView.as_view(), name="mark_step5_calculation_viewed"),
    path("update-budget-discount/<int:budget_id>/", views.UpdateBudgetDiscountView.as_view(), name="update_budget_discount"),
    path("update-status/<int:budget_id>/<str:status>", views.UpdateBudgetStatusView.as_view(), name="update_budget_status"),
    path("send-signature/<int:budget_id>/", views.SendBudgetSignatureView.as_view(), name="send_signature"),
    path("save-observation/", views.SaveObservationView.as_view(), name="save_observation"),
    path("image-view/<int:pk>", views.BudgetImageView.as_view(), name="image_view"),
    path("visualizar-pdf/<int:pk>", views.visualizar_pdf, name="visualizar_pdf"),
    path("visualizar-pdf-checklist/<int:pk>", views.visualizar_pdf_checklist, name="visualizar_pdf_checklist"),
    path("visualizar-pdf-gestor/<int:pk>", views.visualizar_pdf_gestor, name="visualizar_pdf_gestor"),
    path("visualizar-pdf-mecanico/<int:pk>", views.visualizar_pdf_mecanico, name="visualizar_pdf_mecanico"),
    path("signature-preview/<str:token>/", views.signature_preview, name="signature_preview"),
    path("signature-file/<str:token>/", views.signature_file, name="signature_file"),
    path("supersign/webhook/ping/", views.SuperSignWebhookView.as_view(), name="supersign_webhook_ping"),
    path("supersign/webhook/", views.SuperSignWebhookView.as_view(), name="supersign_webhook"),
    path("<int:budget_id>/add-items-batch/<str:item_type>/", views.AddItemsBatchToBudgetView.as_view(), name="add_items_batch"),
    path("<int:budget_id>/summary/", views.BudgetSummaryView.as_view(), name="budget_summary"),
    path("<int:budget_id>/collaborator-field/", views.BudgetStep3CollaboratorFieldView.as_view(), name="collaborator_field"),
    # Local items URLs
    path("<int:budget_id>/create-local/<str:item_type>/", views.CreateLocalItemView.as_view(), name="create_local_item"),
    path("<int:budget_id>/register-local/<int:item_id>/", views.RegisterLocalItemView.as_view(), name="register_local_item"),
    path("<int:budget_id>/calculate-local-service/", views.CalculateLocalServiceView.as_view(), name="calculate_local_service"),
    path("<int:budget_id>/quick-create/<str:item_type>/", views.QuickCreateProductView.as_view(), name="quick_create_item"),
]
