# Generated by Django 6.0 on 2026-09-14 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0009_remove_logincode_unused_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeWebhookEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="Data de Criação")),
                ("atualizado_em", models.DateTimeField(auto_now=True, verbose_name="Data de Atualização")),
                ("event_id", models.CharField(max_length=255, unique=True, verbose_name="ID do evento")),
                ("event_type", models.CharField(max_length=255, verbose_name="Tipo")),
                ("payload", models.JSONField(blank=True, default=dict, verbose_name="Payload")),
                ("processed_at", models.DateTimeField(blank=True, null=True, verbose_name="Processado em")),
            ],
            options={
                "verbose_name": "Evento Webhook Stripe",
                "verbose_name_plural": "Eventos Webhook Stripe",
            },
        ),
        migrations.CreateModel(
            name="AccountSubscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="Data de Criação")),
                ("atualizado_em", models.DateTimeField(auto_now=True, verbose_name="Data de Atualização")),
                ("plan", models.CharField(choices=[("basic", "Orçamento"), ("full", "Completo")], default="basic", max_length=20, verbose_name="Plano")),
                ("status", models.CharField(choices=[("active", "Ativa"), ("past_due", "Pagamento atrasado"), ("canceled", "Cancelada"), ("incomplete", "Aguardando pagamento"), ("grandfathered", "Cortesia (conta antiga)")], default="incomplete", max_length=20, verbose_name="Status")),
                ("stripe_customer_id", models.CharField(blank=True, default="", max_length=255, verbose_name="Cliente Stripe")),
                ("stripe_subscription_id", models.CharField(blank=True, default="", max_length=255, verbose_name="Assinatura Stripe")),
                ("stripe_price_id", models.CharField(blank=True, default="", max_length=255, verbose_name="Preço Stripe")),
                ("current_period_end", models.DateTimeField(blank=True, null=True, verbose_name="Renova em")),
                ("cancel_at_period_end", models.BooleanField(default=False, verbose_name="Cancela no fim do período")),
                ("account", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="subscription", to="accounts.account", verbose_name="Conta")),
            ],
            options={
                "verbose_name": "Assinatura da Conta",
                "verbose_name_plural": "Assinaturas das Contas",
            },
        ),
    ]
