# Generated by Django 6.0 on 2026-09-21 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_logincode_unused_fields'),
        ('billing', '0002_grandfather_existing_accounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('username', models.CharField(max_length=150, verbose_name='Usuário')),
                ('password_hash', models.CharField(max_length=128, verbose_name='Hash da senha')),
                ('first_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Nome')),
                ('last_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Sobrenome')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('plan', models.CharField(choices=[('basic', 'Orçamento'), ('full', 'Completo')], max_length=20, verbose_name='Plano')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('expired', 'Expirado'), ('failed', 'Falhou')], default='pending', max_length=20, verbose_name='Status')),
                ('stripe_customer_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Cliente Stripe')),
                ('stripe_subscription_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Assinatura Stripe')),
                ('stripe_payment_intent_id', models.CharField(blank=True, default='', max_length=255, verbose_name='PaymentIntent Stripe')),
                ('expires_at', models.DateTimeField(verbose_name='Expira em')),
                ('login_token', models.CharField(blank=True, default='', max_length=64, verbose_name='Token de login')),
                ('login_token_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Token usado em')),
                ('created_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_signups', to='accounts.account', verbose_name='Conta criada')),
            ],
            options={
                'verbose_name': 'Cadastro pendente de assinatura',
                'verbose_name_plural': 'Cadastros pendentes de assinatura',
                'indexes': [models.Index(fields=['email', 'status'], name='billing_pen_email_4432aa_idx'), models.Index(fields=['stripe_subscription_id'], name='billing_pen_stripe__c7dbc1_idx'), models.Index(fields=['login_token'], name='billing_pen_login_t_1c8255_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('email',), name='unique_pending_signup_email')],
            },
        ),
    ]
