from .customer_vehicle_views import CustomerDetailView, VehicleDetailView, VehicleListView
from apps.core.documents.webhook import SuperSignWebhookView
from .import_items_views import BudgetImportItemsSearchModalView, BudgetImportItemsSelectModalView, BudgetImportItemsProcessView
from .item_views import (
    AddItemToBudgetView,
    AddItemsBatchToBudgetView,
    BudgetImageView,
    BudgetItemCalculateView,
    BudgetItemUpdateView,
    BudgetStep3CollaboratorFieldView,
    BudgetSummaryView,
    ItemSelectionModalView,
    RemoveBudgetItemView,
    RemoveItemFromBudgetView,
    RemoveKitItemsBatchFromBudgetView,
    RemoveProductItemsBatchFromBudgetView,
    RemoveServiceItemsBatchFromBudgetView,
)
from .kit_views import BudgetKitEditView, BudgetKitProductCalculateView, BudgetKitServiceCalculateView
from .local_item_views import CalculateLocalServiceView, CreateLocalItemView, QuickCreateProductView, RegisterLocalItemView
from .pdf_views import signature_file, signature_preview, visualizar_pdf, visualizar_pdf_assinatura, visualizar_pdf_checklist, visualizar_pdf_gestor, visualizar_pdf_mecanico
from .realtime_views import BudgetEventsView
from .shared import reset_steps_after_step_4
from .workflow_views import BudgetCreateView, BudgetDeleteView, BudgetListView, BudgetStatusReportPdfPreviewView, BudgetStatusReportPdfView, BudgetUpdateView, MarkStep5CalculationViewedView, SaveObservationView, SendBudgetSignatureView, UpdateBudgetDiscountView, UpdateBudgetStatusView, UpdateSliderView

__all__ = [
    "BudgetListView",
    "BudgetCreateView",
    "BudgetUpdateView",
    "BudgetDeleteView",
    "BudgetStatusReportPdfPreviewView",
    "BudgetStatusReportPdfView",
    "CustomerDetailView",
    "VehicleListView",
    "VehicleDetailView",
    "ItemSelectionModalView",
    "AddItemToBudgetView",
    "RemoveItemFromBudgetView",
    "RemoveProductItemsBatchFromBudgetView",
    "RemoveServiceItemsBatchFromBudgetView",
    "RemoveKitItemsBatchFromBudgetView",
    "RemoveBudgetItemView",
    "BudgetItemUpdateView",
    "BudgetItemCalculateView",
    "BudgetKitEditView",
    "BudgetKitProductCalculateView",
    "BudgetKitServiceCalculateView",
    "UpdateSliderView",
    "MarkStep5CalculationViewedView",
    "UpdateBudgetDiscountView",
    "UpdateBudgetStatusView",
    "SaveObservationView",
    "SendBudgetSignatureView",
    "BudgetImageView",
    "visualizar_pdf",
    "visualizar_pdf_assinatura",
    "visualizar_pdf_checklist",
    "visualizar_pdf_gestor",
    "visualizar_pdf_mecanico",
    "signature_preview",
    "signature_file",
    "BudgetEventsView",
    "SuperSignWebhookView",
    "AddItemsBatchToBudgetView",
    "BudgetSummaryView",
    "BudgetStep3CollaboratorFieldView",
    "CreateLocalItemView",
    "RegisterLocalItemView",
    "CalculateLocalServiceView",
    "QuickCreateProductView",
    "reset_steps_after_step_4",
    "BudgetImportItemsSearchModalView",
    "BudgetImportItemsSelectModalView",
    "BudgetImportItemsProcessView",
]
