# Generated by Django 6.0 on 2026-02-09 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0001_initial"),
        ("suppliers", "0006_alter_supplier_bairro_alter_supplier_cep_and_more"),
        ("workshops", "0012_workshop_certificate_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmovement",
            name="stock_product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movements",
                to="stock.stockproduct",
                verbose_name="Peça",
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movements",
                to="suppliers.supplier",
                verbose_name="Fornecedor",
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="type",
            field=models.CharField(
                choices=[("ENTRADA", "Entrada"), ("SAIDA", "Saída")],
                max_length=10,
                verbose_name="Tipo",
            ),
        ),
        migrations.CreateModel(
            name="SefazZipCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=44, unique=True, verbose_name="Chave de Acesso"
                    ),
                ),
                ("nf_number", models.CharField(blank=True, max_length=20, null=True)),
                ("issue_date", models.DateTimeField(blank=True, null=True)),
                (
                    "issuer_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("issuer_cnpj", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "total_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("is_imported", models.BooleanField(default=False)),
                (
                    "workshop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sefaz_caches",
                        to="workshops.workshop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cache SEFAZ",
                "ordering": ["-issue_date"],
            },
        ),
    ]
