# Generated by Django 6.0 on 2026-02-10 15:16

import django.db.models.deletion
import djmoney.models.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0002_alter_stockmovement_stock_product_and_more"),
        ("workshops", "0013_alter_workshop_cnpj"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sefazzipcache",
            options={},
        ),
        migrations.AddField(
            model_name="sefazzipcache",
            name="xml_archive",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="status",
            field=models.CharField(
                choices=[
                    ("AGUARDANDO", "Aguardando Aprovação"),
                    ("APROVADO", "Aprovado"),
                    ("REJEITADO", "Rejeitado"),
                ],
                default="AGUARDANDO",
                max_length=10,
                verbose_name="Status",
            ),
        ),
        migrations.CreateModel(
            name="StockPaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CREDITO", "Cartão de Crédito"),
                            ("DEBITO", "Cartão de Débito"),
                            ("PIX", "Pix"),
                            ("DINHEIRO", "Dinheiro"),
                            ("BOLETO", "Boleto"),
                            ("TRANSFERENCIA", "Transferência/TED"),
                        ],
                        max_length=20,
                        verbose_name="Forma de Pagamento",
                    ),
                ),
                (
                    "installments_count",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Número de Parcelas"
                    ),
                ),
                (
                    "first_installment_amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("BRL", "Real Brasileiro")],
                        default="BRL",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "first_installment_amount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default=Decimal("0.0"),
                        max_digits=14,
                        verbose_name="Valor da primeira parcela",
                    ),
                ),
                (
                    "remaining_installments_amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("BRL", "Real Brasileiro")],
                        default="BRL",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "remaining_installments_amount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default=Decimal("0.0"),
                        max_digits=14,
                        verbose_name="Valor das parcelas restantes",
                    ),
                ),
                (
                    "nf_number",
                    models.CharField(max_length=60, verbose_name="Número da NF"),
                ),
                (
                    "workshop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stockpayments",
                        to="workshops.workshop",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
