# Generated by Django 6.0 on 2026-02-11 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0004_stockpaymentmethod_due_date_stockimport"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockimport",
            name="method",
            field=models.CharField(
                choices=[
                    ("SEFAZ", "SEFAZ"),
                    ("XML", "Arquivo XML"),
                    ("KEY", "Chave de Acesso"),
                ],
                default="XML",
                max_length=30,
                verbose_name="Selecione o método de Importação de Itens",
            ),
        ),
        migrations.AlterField(
            model_name="stockimport",
            name="nf_number",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="NF"
            ),
        ),
        migrations.AlterField(
            model_name="stockimport",
            name="supplier_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Fornecedor"
            ),
        ),
        migrations.AlterField(
            model_name="stockimport",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Aberto por",
            ),
        ),
    ]
