# Generated by Django 6.0 on 2026-02-12 11:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0005_alter_stockimport_method_alter_stockimport_nf_number_and_more"),
        ("workshops", "0013_alter_workshop_cnpj"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="sefazzipcache",
            unique_together={("workshop", "key")},
        ),
        migrations.AddField(
            model_name="stockimport",
            name="nf_key",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=44,
                verbose_name="Chave de Acesso",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sefazzipcache",
            name="key",
            field=models.CharField(max_length=44, verbose_name="Chave de Acesso"),
        ),
        migrations.RemoveField(
            model_name="sefazzipcache",
            name="xml_archive",
        ),
    ]
