# Generated by Django 5.2.9 on 2026-02-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_alter_sefazzipcache_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockimport',
            name='method',
            field=models.CharField(choices=[('SEFAZ', 'SEFAZ'), ('XML', 'Arquivo XML'), ('KEY', 'Chave de Acesso'), ('MANUAL', 'Importar Manualmente')], default='XML', max_length=30, verbose_name='Selecione o método de Importação de Itens'),
        ),
    ]
