# Generated by Django 6.0 on 2026-03-08 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0011_paymentmethod"),
        ("stock", "0007_alter_stockimport_method"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stockimport",
            options={
                "verbose_name": "Importação de Estoque",
                "verbose_name_plural": "Importações de Estoque",
            },
        ),
        migrations.AlterModelOptions(
            name="stockmovement",
            options={
                "verbose_name": "Movimentação de Estoque",
                "verbose_name_plural": "Movimentações de Estoque",
            },
        ),
        migrations.AlterModelOptions(
            name="stockpaymentmethod",
            options={
                "verbose_name": "Forma de Pagamento",
                "verbose_name_plural": "Formas de Pagamento",
            },
        ),
        migrations.AlterModelOptions(
            name="stockproduct",
            options={
                "verbose_name": "Produto do Estoque",
                "verbose_name_plural": "Produtos do Estoque",
            },
        ),
        migrations.AlterField(
            model_name="stockpaymentmethod",
            name="payment_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="finance.paymentmethod",
                verbose_name="Forma de Pagamento",
            ),
        ),
    ]
