# Generated by Django 5.2 on 2026-03-22 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stock", "0008_alter_stockimport_options_and_more"),
        ("workshops", "0016_alter_workshop_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockTransfer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("current_step", models.PositiveIntegerField(default=1)),
                ("items_data", models.JSONField(default=list)),
                ("status", models.CharField(choices=[("RASCUNHO", "Rascunho"), ("CONCLUIDO", "Concluído")], default="RASCUNHO", max_length=20)),
                ("destination_workshop", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="stock_transfers_received", to="workshops.workshop")),
                ("source_workshop", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="stock_transfers_sent", to="workshops.workshop")),
                ("user", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name="Aberto por")),
            ],
            options={
                "verbose_name": "Transferência de Estoque",
                "verbose_name_plural": "Transferências de Estoque",
            },
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="stock_transfer",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="movements", to="stock.stocktransfer"),
        ),
    ]
