# Generated by Django 6.0 on 2026-03-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_stocktransfer_stockmovement_stock_transfer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sefazzipcache',
            options={'verbose_name': 'Cache do Sefaz (zip)', 'verbose_name_plural': 'Cache do Sefaz (zip)'},
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
    ]
