# Generated by Django 6.0 on 2026-03-31 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0010_alter_sefazzipcache_options_and_more"),
        ("workshops", "0017_workshop_certificate_content_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocktransfer",
            name="operation_type",
            field=models.CharField(
                choices=[
                    ("TRANSFER", "Transferência entre oficinas"),
                    ("ADJUSTMENT", "Baixa em estoque"),
                ],
                default="TRANSFER",
                max_length=30,
                verbose_name="Selecione o Tipo de Operação",
            ),
        ),
        migrations.AddField(
            model_name="stocktransfer",
            name="reason",
            field=models.TextField(
                blank=True, null=True, verbose_name="Motivo da Baixa"
            ),
        ),
        migrations.AlterField(
            model_name="stocktransfer",
            name="destination_workshop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_transfers_received",
                to="workshops.workshop",
                verbose_name="Oficina de Destino",
            ),
        ),
        migrations.AlterField(
            model_name="stocktransfer",
            name="source_workshop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_transfers_sent",
                to="workshops.workshop",
                verbose_name="Oficina de Origem",
            ),
        ),
    ]
