# Generated by Django 6.0 on 2026-07-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0012_stockmovement_workorder_reversal_of"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockimport",
            name="xml_file_key",
            field=models.CharField(
                blank=True, default="", max_length=1024, verbose_name="XML no Bucket"
            ),
        ),
    ]
