# Generated by Django 6.0 on 2026-07-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0013_stockimport_xml_file_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockimport",
            name="xml_file_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=1024,
                verbose_name="XML no Bucket",
            ),
        ),
    ]
