# Generated by Django 6.0 on 2026-08-01 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_stockimport_xml_file_key_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockimport',
            name='method',
            field=models.CharField(choices=[('SEFAZ', 'SEFAZ'), ('XML', 'Arquivo XML'), ('KEY', 'Chave de Acesso'), ('MANUAL', 'Importar Manualmente')], default='XML', max_length=30, verbose_name='Método de importação'),
        ),
        migrations.AlterField(
            model_name='stockimport',
            name='xml_file_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=1024, verbose_name='XML no armazenamento'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='operation_type',
            field=models.CharField(choices=[('TRANSFER', 'Transferência entre oficinas'), ('ADJUSTMENT', 'Baixa em estoque')], default='TRANSFER', max_length=30, verbose_name='Tipo de operação'),
        ),
    ]
