# Generated by Django 5.2.9 on 2026-08-03 03:16

from datetime import datetime, time

from django.db import migrations, models
from django.utils import timezone
from django.utils.dateparse import parse_date, parse_datetime


def backfill_fiscal_issued_at(apps, schema_editor):
    stock_import_model = apps.get_model("stock", "StockImport")
    for stock_import in stock_import_model.objects.filter(fiscal_issued_at__isnull=True).iterator(chunk_size=500):
        snapshot = stock_import.fiscal_snapshot if isinstance(stock_import.fiscal_snapshot, dict) else {}
        document = snapshot.get("document") if isinstance(snapshot.get("document"), dict) else {}
        raw_value = str(document.get("issued_at") or "").strip()
        if not raw_value:
            continue
        issued_at = parse_datetime(raw_value)
        if issued_at is None:
            issued_date = parse_date(raw_value)
            issued_at = datetime.combine(issued_date, time.min) if issued_date is not None else None
        if issued_at is None:
            continue
        if timezone.is_naive(issued_at):
            issued_at = timezone.make_aware(issued_at)
        stock_import_model.objects.filter(pk=stock_import.pk).update(fiscal_issued_at=issued_at)


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0016_stockimportfiscalitem_stockimport_fiscal_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockimport',
            name='fiscal_issued_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Data de emissão fiscal'),
        ),
        migrations.RunPython(backfill_fiscal_issued_at, migrations.RunPython.noop),
    ]
