# Generated by Django 6.0 on 2026-08-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0016_fix_merge_staging'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='reason',
            field=models.TextField(blank=True, default='', verbose_name='Motivo'),
        ),
    ]
