# Generated by Django 6.0 on 2026-08-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0017_stockmovement_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmovement",
            name="is_stock_adjustment",
            field=models.BooleanField(default=False, verbose_name="É ajuste de estoque"),
        ),
    ]
