# Generated by Django 5.2.9 on 2026-08-03 03:54

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0089_purchasereturnrequest_stock_error_and_more'),
        ('stock', '0017_stockimport_fiscal_issued_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='fiscal_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='finance.fiscaldocument', verbose_name='Documento fiscal'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='purchase_return_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movement', to='finance.purchasereturnrequestitem', verbose_name='Item da devolução de compra'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(choices=[('STANDARD', 'Movimentação padrão'), ('PURCHASE_RETURN', 'Saída por devolução de compra')], db_index=True, default='STANDARD', max_length=24, verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=15, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='stockproduct',
            name='current_quantity',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15, verbose_name='Estoque Atual'),
        ),
    ]
