# Generated by Django 5.2.9 on 2026-08-24 22:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models

from apps.finance.migrations import _idempotent


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0053_purchase_return_stock_workflow'),
        ('stock', '0017_stockmovement_reason'),
    ]

    operations = [
        _idempotent.AddFieldIfMissing(
            model_name='stockimport',
            name='fiscal_document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_stock_import', to='finance.fiscaldocument', verbose_name='Documento fiscal externo'),
        ),
        _idempotent.AddFieldIfMissing(
            model_name='stockimport',
            name='fiscal_issued_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Data de emissão fiscal'),
        ),
        _idempotent.AddFieldIfMissing(
            model_name='stockimport',
            name='fiscal_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='Snapshot fiscal normalizado'),
        ),
        _idempotent.AddFieldIfMissing(
            model_name='stockimport',
            name='fiscal_validated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Validado fiscalmente em'),
        ),
        _idempotent.AddFieldIfMissing(
            model_name='stockimport',
            name='fiscal_validation_status',
            field=models.CharField(choices=[('unvalidated', 'Não validado'), ('validated', 'Validado'), ('invalid', 'Inválido')], db_index=True, default='unvalidated', max_length=16, verbose_name='Validação fiscal'),
        ),
        _idempotent.AddFieldIfMissing(
            model_name='stockmovement',
            name='fiscal_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='finance.fiscaldocument', verbose_name='Documento fiscal'),
        ),
        _idempotent.AddFieldIfMissing(
            model_name='stockmovement',
            name='purchase_return_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movement', to='finance.purchasereturnrequestitem', verbose_name='Item da Nota de Devolução'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=15, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='stockproduct',
            name='current_quantity',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15, verbose_name='Estoque Atual'),
        ),
        _idempotent.CreateModelIfMissing(
            name='StockImportFiscalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('sequence', models.PositiveSmallIntegerField(verbose_name='Sequencial fiscal')),
                ('product_code', models.CharField(blank=True, default='', max_length=120, verbose_name='Código do produto')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Quantidade comprada')),
                ('unit', models.CharField(blank=True, default='', max_length=12, verbose_name='Unidade')),
                ('unit_value', models.DecimalField(decimal_places=4, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valor unitário')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valor total')),
                ('ncm', models.CharField(blank=True, default='', max_length=10, verbose_name='NCM')),
                ('cfop', models.CharField(blank=True, default='', max_length=8, verbose_name='CFOP')),
                ('tax_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Snapshot tributário')),
                ('stock_import', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_items', to='stock.stockimport', verbose_name='Importação de estoque')),
                ('stock_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_fiscal_items', to='stock.stockproduct', verbose_name='Produto do estoque')),
            ],
            options={
                'verbose_name': 'Item fiscal da importação de estoque',
                'verbose_name_plural': 'Itens fiscais da importação de estoque',
                'abstract': False,
            },
        ),
        _idempotent.AddFieldIfMissing(
            model_name='stockmovement',
            name='source_import_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='stock.stockimportfiscalitem', verbose_name='Item fiscal de origem'),
        ),
        _idempotent.AddIndexIfMissing(
            model_name='stockimportfiscalitem',
            index=models.Index(fields=['stock_import', 'sequence'], name='stock_import_item_sequence_idx'),
        ),
        _idempotent.AddIndexIfMissing(
            model_name='stockimportfiscalitem',
            index=models.Index(fields=['stock_product'], name='stock_import_item_product_idx'),
        ),
        _idempotent.AddConstraintIfMissing(
            model_name='stockimportfiscalitem',
            constraint=models.UniqueConstraint(fields=('stock_import', 'sequence'), name='unique_fiscal_item_sequence_per_stock_import'),
        ),
    ]
