# Generated by Django 5.2.9 on 2026-08-03 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0090_alter_fiscaldocumentlink_role_and_more'),
        ('stock', '0018_stockmovement_fiscal_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='transport_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movement', to='finance.transportrequestitem', verbose_name='Item da Nota de Transporte'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(choices=[('STANDARD', 'Movimentação padrão'), ('PURCHASE_RETURN', 'Saída por devolução de compra'), ('TRANSPORT', 'Saída por Nota de Transporte')], db_index=True, default='STANDARD', max_length=24, verbose_name='Motivo'),
        ),
    ]
