# Generated by Django 5.2.9 on 2026-08-30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0018_purchase_return_stock_workflow"),
        ("stock", "0018_stockmovement_is_stock_adjustment"),
    ]

    operations = []
