# Generated by Django 6.0 on 2026-10-05 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0019_merge_purchase_return_and_stock_adjustment'),
        ('workshops', '0045_add_workshop_commission_limits'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sefazzipcache',
            name='last_manifestation_event',
            field=models.CharField(blank=True, choices=[('210200', 'Confirmação da Operação'), ('210210', 'Ciência da Operação'), ('210220', 'Desconhecimento da Operação'), ('210240', 'Operação não Realizada')], default='', max_length=6, verbose_name='Último evento de manifestação'),
        ),
        migrations.AddField(
            model_name='sefazzipcache',
            name='last_manifestation_status',
            field=models.CharField(blank=True, choices=[('started', 'Iniciado'), ('sent', 'Enviado'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('failed', 'Falhou')], default='', max_length=20, verbose_name='Status da última manifestação'),
        ),
        migrations.AddField(
            model_name='sefazzipcache',
            name='last_manifested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Manifestado em'),
        ),
        migrations.CreateModel(
            name='SefazManifestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('access_key', models.CharField(db_index=True, max_length=44, verbose_name='Chave de Acesso')),
                ('event_code', models.CharField(choices=[('210200', 'Confirmação da Operação'), ('210210', 'Ciência da Operação'), ('210220', 'Desconhecimento da Operação'), ('210240', 'Operação não Realizada')], max_length=6, verbose_name='Evento')),
                ('status', models.CharField(choices=[('started', 'Iniciado'), ('sent', 'Enviado'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('failed', 'Falhou')], db_index=True, default='started', max_length=20, verbose_name='Status')),
                ('remote_uuid', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('justificativa', models.TextField(blank=True, default='', verbose_name='Justificativa')),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('xml_url', models.URLField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sefaz_manifestations', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
                ('sefaz_cache', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manifestations', to='stock.sefazzipcache', verbose_name='Cache SEFAZ')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sefaz_manifestations', to='workshops.workshop')),
            ],
            options={
                'verbose_name': 'Manifestação do destinatário',
                'verbose_name_plural': 'Manifestações do destinatário',
                'abstract': False,
                'indexes': [models.Index(fields=['workshop', 'access_key', 'event_code'], name='stock_sefaz_worksho_dc3e9b_idx'), models.Index(fields=['workshop', 'status'], name='stock_sefaz_worksho_de0777_idx')],
            },
        ),
    ]
