# Generated by Django 6.0 on 2026-10-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0020_sefaz_manifestation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockimport",
            name="method",
            field=models.CharField(
                choices=[
                    ("SEFAZ", "SEFAZ"),
                    ("XML", "Arquivo XML"),
                    ("KEY", "Chave de Acesso"),
                    ("MANUAL", "Importar Manualmente"),
                ],
                default="SEFAZ",
                max_length=30,
                verbose_name="Selecione o método de Importação de Itens",
            ),
        ),
    ]
