# Generated by Django 6.0 on 2026-02-16 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workorder', '0004_workorder_status'),
        ('workshops', '0013_alter_workshop_cnpj'),
    ]

    operations = [
        migrations.CreateModel(
            name='NfseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('current_step', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('waiting_wo', 'Aguardando Ordem de Serviço'), ('checking_client', 'Verificando Cliente'), ('checking_services', 'Verificando Serviços'), ('processing', 'Processando'), ('approved', 'Aprovado'), ('reproved', 'Reprovado'), ('scheduled', 'Agendado'), ('canceled', 'Cancelado'), ('contingency', 'Contingência')], default='waiting_wo', max_length=20)),
                ('service_description', models.TextField(blank=True, default='', verbose_name='Discriminação do Serviço')),
                ('tax_class', models.CharField(default='REF000000', max_length=30, verbose_name='Classe de Imposto')),
                ('workorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workorder.workorder', verbose_name='Ordem de Serviço')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshops.workshop', verbose_name='Oficina')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NfseBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True)),
                ('model', models.CharField(default='lote_rps', max_length=255)),
                ('status', models.CharField(choices=[('processando', 'Processando'), ('processado', 'Processado'), ('agendado', 'Agendado'), ('reprovado', 'Reprovado'), ('cancelado', 'Cancelado'), ('contingencia', 'Contingencia')], default='processando', max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('batch_number', models.CharField(blank=True, default='', max_length=40)),
                ('batch_series', models.CharField(blank=True, default='', max_length=20)),
                ('rps_quantity', models.PositiveIntegerField(default=0)),
                ('protocol', models.CharField(blank=True, default='', max_length=60)),
                ('log_payload', models.JSONField(blank=True, default=dict)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('workorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workorder.workorder', verbose_name='Ordem de Serviço')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshops.workshop', verbose_name='Oficina')),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='finance.nfserequest', verbose_name='Requisição de NFS-e')),
            ],
        ),
        migrations.CreateModel(
            name='NfseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True)),
                ('model', models.CharField(default='nfse', max_length=255)),
                ('status', models.CharField(choices=[('processando', 'Processando'), ('aprovado', 'Aprovado'), ('agendado', 'Agendado'), ('reprovado', 'Reprovado'), ('cancelado', 'Cancelado'), ('contingencia', 'Contingencia')], default='processando', max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('number', models.CharField(blank=True, default='', max_length=40)),
                ('verification_code', models.CharField(blank=True, default='', max_length=60)),
                ('rps_series', models.CharField(blank=True, default='', max_length=20)),
                ('rps_number', models.CharField(blank=True, default='', max_length=40)),
                ('xml_url', models.URLField(blank=True, default='')),
                ('pdf_nfse_url', models.URLField(blank=True, default='')),
                ('pdf_nfse_status', models.CharField(choices=[('processando', 'Processando'), ('processado', 'Processado'), ('indisponivel', 'Indisponivel')], default='processando', max_length=20)),
                ('pdf_rps_url', models.URLField(blank=True, default='')),
                ('log_payload', models.JSONField(blank=True, default=dict)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='finance.nfsebatch', verbose_name='Lote')),
                ('workorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workorder.workorder', verbose_name='Ordem de Serviço')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshops.workshop', verbose_name='Oficina')),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='finance.nfserequest', verbose_name='Requisição de NFS-e')),
            ],
            options={
                'indexes': [models.Index(fields=['workshop', 'status'], name='finance_nfs_worksho_27fc4b_idx')],
                'constraints': [models.UniqueConstraint(fields=('workorder', 'uuid'), name='unique_nfse_item_per_workorder')],
            },
        ),
        migrations.AddIndex(
            model_name='nfsebatch',
            index=models.Index(fields=['workshop', 'status'], name='finance_nfs_worksho_857b67_idx'),
        ),
        migrations.AddConstraint(
            model_name='nfsebatch',
            constraint=models.UniqueConstraint(fields=('workorder', 'uuid'), name='unique_nfse_batch_per_workorder'),
        ),
    ]
