# Generated by Django 6.0 on 2026-02-17 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('workshops', '0013_alter_workshop_cnpj'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxClassSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('synced_once', models.BooleanField(default=False, verbose_name='Sincronização inicial concluída')),
                ('workshop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_class_sync_state', to='workshops.workshop', verbose_name='Oficina')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaxClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('reference', models.CharField(max_length=30, verbose_name='Referência')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Descrição')),
                ('tax_type', models.CharField(blank=True, default='', max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(blank=True, default='', max_length=30, verbose_name='Status')),
                ('remote_date', models.CharField(blank=True, default='', max_length=40, verbose_name='Data')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Payload')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_classes', to='workshops.workshop', verbose_name='Oficina')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['workshop', 'tax_type'], name='finance_tax_worksho_56e0f3_idx'), models.Index(fields=['workshop', 'status'], name='finance_tax_worksho_dfc038_idx')],
                'constraints': [models.UniqueConstraint(fields=('workshop', 'reference'), name='unique_tax_class_per_workshop_reference')],
            },
        ),
    ]
