# Generated by Django 6.0 on 2026-02-17 18:31

import django.db.models.deletion
from decimal import Decimal, InvalidOperation

from django.db import migrations, models


def _clean_string(value):
    return str(value or "").strip()


def _to_decimal(value):
    if value in (None, ""):
        return None

    normalized = str(value).strip().replace(",", ".")
    if not normalized:
        return None

    try:
        return Decimal(normalized)
    except (InvalidOperation, ValueError):
        return None


def _normalize_scenarios(value):
    if not isinstance(value, list):
        return []
    return [dict(item) for item in value if isinstance(item, dict)]


def _digits_only(value):
    raw_value = _clean_string(value)
    if not raw_value:
        return ""
    return "".join(char for char in raw_value if char.isdigit())


def _is_nfse_payload(payload, tax_type):
    if tax_type in {"nfse", "nfs-e", "nsfe"}:
        return True
    return bool(_clean_string(payload.get("tipo_emissao"))) and bool(_clean_string(payload.get("codigo_servico")))


def _migrate_tax_classes(apps, schema_editor):
    TaxClass = apps.get_model("finance", "TaxClass")
    TaxClassNfe = apps.get_model("finance", "TaxClassNfe")
    TaxClassNfse = apps.get_model("finance", "TaxClassNfse")

    for legacy_tax_class in TaxClass.objects.all().iterator():
        payload = legacy_tax_class.payload if isinstance(legacy_tax_class.payload, dict) else {}
        reference = _clean_string(payload.get("referencia")) or _clean_string(legacy_tax_class.reference)
        if not reference:
            continue

        tax_type = _clean_string(payload.get("tipo") or payload.get("type") or legacy_tax_class.tax_type).lower()
        common_defaults = {
            "description": _clean_string(payload.get("descricao")) or _clean_string(legacy_tax_class.description),
            "status": _clean_string(payload.get("status")) or _clean_string(legacy_tax_class.status),
            "remote_date": _clean_string(payload.get("data")) or _clean_string(legacy_tax_class.remote_date),
            "remote_updated_date": _clean_string(payload.get("updated_date")),
            "informacoes_fisco": _clean_string(payload.get("informacoes_fisco")),
            "informacoes_complementares": _clean_string(payload.get("informacoes_complementares")),
        }

        if _is_nfse_payload(payload, tax_type):
            ibs_cbs_raw = payload.get("ibs_cbs")
            ibs_cbs = dict(ibs_cbs_raw) if isinstance(ibs_cbs_raw, dict) else {}
            ibs_estadual_raw = ibs_cbs.get("ibs_estadual")
            ibs_estadual = dict(ibs_estadual_raw) if isinstance(ibs_estadual_raw, dict) else {}
            ibs_municipal_raw = ibs_cbs.get("ibs_municipal")
            ibs_municipal = dict(ibs_municipal_raw) if isinstance(ibs_municipal_raw, dict) else {}
            cbs_raw = ibs_cbs.get("cbs")
            cbs = dict(cbs_raw) if isinstance(cbs_raw, dict) else {}

            TaxClassNfse.objects.update_or_create(
                workshop_id=legacy_tax_class.workshop_id,
                reference=reference,
                defaults={
                    **common_defaults,
                    "tipo_emissao": _clean_string(payload.get("tipo_emissao")),
                    "codigo_servico": _digits_only(payload.get("codigo_servico")) or _clean_string(payload.get("codigo_servico")),
                    "codigo_tributacao_municipio": _digits_only(payload.get("codigo_tributacao_municipio")) or _clean_string(payload.get("codigo_tributacao_municipio")),
                    "tributacao_iss": _clean_string(payload.get("tributacao_iss")),
                    "tipo_imunidade": _clean_string(payload.get("tipo_imunidade")),
                    "retencao_iss": _clean_string(payload.get("retencao_iss") or payload.get("iss_retido")),
                    "cst_pis_cofins": _clean_string(payload.get("cst_pis_cofins")),
                    "retencao_pis_cofins": _clean_string(payload.get("retencao_pis_cofins")),
                    "natureza_operacao": _clean_string(payload.get("natureza_operacao")),
                    "exigibilidade_iss": _clean_string(payload.get("exigibilidade_iss")),
                    "iss_retido": _clean_string(payload.get("iss_retido") or payload.get("retencao_iss")),
                    "responsavel_retencao": _clean_string(payload.get("responsavel_retencao")),
                    "codigo_cnae": _clean_string(payload.get("codigo_cnae")),
                    "iss": _to_decimal(payload.get("iss")),
                    "pis": _to_decimal(payload.get("pis")),
                    "cofins": _to_decimal(payload.get("cofins")),
                    "inss": _to_decimal(payload.get("inss")),
                    "ir": _to_decimal(payload.get("ir")),
                    "csll": _to_decimal(payload.get("csll")),
                    "ibs_situacao_tributaria": _clean_string(ibs_cbs.get("situacao_tributaria")),
                    "ibs_classificacao_tributaria": _clean_string(ibs_cbs.get("classificacao_tributaria")),
                    "ibs_situacao_tributaria_regular": _clean_string(ibs_cbs.get("situacao_tributaria_regular")),
                    "ibs_classificacao_tributaria_regular": _clean_string(ibs_cbs.get("classificacao_tributaria_regular")),
                    "ibs_credito_presumido": _clean_string(ibs_cbs.get("credito_presumido")),
                    "ibs_aliquota_diferimento_estadual": _to_decimal(ibs_estadual.get("aliquota_diferimento")),
                    "ibs_aliquota_diferimento_municipal": _to_decimal(ibs_municipal.get("aliquota_diferimento")),
                    "cbs_aliquota_diferimento": _to_decimal(cbs.get("aliquota_diferimento")),
                },
            )
            continue

        TaxClassNfe.objects.update_or_create(
            workshop_id=legacy_tax_class.workshop_id,
            reference=reference,
            defaults={
                **common_defaults,
                "icms": _normalize_scenarios(payload.get("icms")),
                "ipi": _normalize_scenarios(payload.get("ipi")),
                "pis": _normalize_scenarios(payload.get("pis")),
                "cofins": _normalize_scenarios(payload.get("cofins")),
            },
        )


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0002_taxclasssyncstate_taxclass"),
        ("workshops", "0013_alter_workshop_cnpj"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxClassNfe",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="Data de Criação")),
                ("atualizado_em", models.DateTimeField(auto_now=True, verbose_name="Data de Atualização")),
                ("reference", models.CharField(max_length=30, verbose_name="Referência")),
                ("description", models.CharField(blank=True, default="", max_length=255, verbose_name="Descrição")),
                ("status", models.CharField(blank=True, default="", max_length=30, verbose_name="Status")),
                ("remote_date", models.CharField(blank=True, default="", max_length=40, verbose_name="Data")),
                ("remote_updated_date", models.CharField(blank=True, default="", max_length=40, verbose_name="Data de atualização remota")),
                ("informacoes_fisco", models.TextField(blank=True, default="", verbose_name="Informações ao Fisco")),
                ("informacoes_complementares", models.TextField(blank=True, default="", verbose_name="Informações complementares")),
                ("icms", models.JSONField(blank=True, default=list, verbose_name="Cenários ICMS")),
                ("ipi", models.JSONField(blank=True, default=list, verbose_name="Cenários IPI")),
                ("pis", models.JSONField(blank=True, default=list, verbose_name="Cenários PIS")),
                ("cofins", models.JSONField(blank=True, default=list, verbose_name="Cenários COFINS")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TaxClassNfse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="Data de Criação")),
                ("atualizado_em", models.DateTimeField(auto_now=True, verbose_name="Data de Atualização")),
                ("reference", models.CharField(max_length=30, verbose_name="Referência")),
                ("description", models.CharField(blank=True, default="", max_length=255, verbose_name="Descrição")),
                ("status", models.CharField(blank=True, default="", max_length=30, verbose_name="Status")),
                ("remote_date", models.CharField(blank=True, default="", max_length=40, verbose_name="Data")),
                ("remote_updated_date", models.CharField(blank=True, default="", max_length=40, verbose_name="Data de atualização remota")),
                ("informacoes_fisco", models.TextField(blank=True, default="", verbose_name="Informações ao Fisco")),
                ("informacoes_complementares", models.TextField(blank=True, default="", verbose_name="Informações complementares")),
                ("tipo_emissao", models.CharField(blank=True, default="", max_length=10, verbose_name="Tipo de emissão")),
                ("codigo_servico", models.CharField(blank=True, default="", max_length=20, verbose_name="Código do serviço")),
                ("codigo_tributacao_municipio", models.CharField(blank=True, default="", max_length=20, verbose_name="Código tributação município")),
                ("tributacao_iss", models.CharField(blank=True, default="", max_length=10, verbose_name="Tributação ISS")),
                ("tipo_imunidade", models.CharField(blank=True, default="", max_length=10, verbose_name="Tipo imunidade")),
                ("retencao_iss", models.CharField(blank=True, default="", max_length=10, verbose_name="Retenção ISS")),
                ("cst_pis_cofins", models.CharField(blank=True, default="", max_length=10, verbose_name="CST PIS/COFINS")),
                ("retencao_pis_cofins", models.CharField(blank=True, default="", max_length=10, verbose_name="Retenção PIS/COFINS")),
                ("natureza_operacao", models.CharField(blank=True, default="", max_length=10, verbose_name="Natureza da operação")),
                ("exigibilidade_iss", models.CharField(blank=True, default="", max_length=10, verbose_name="Exigibilidade ISS")),
                ("iss_retido", models.CharField(blank=True, default="", max_length=10, verbose_name="ISS retido")),
                ("responsavel_retencao", models.CharField(blank=True, default="", max_length=10, verbose_name="Responsável retenção")),
                ("codigo_cnae", models.CharField(blank=True, default="", max_length=20, verbose_name="Código CNAE")),
                ("iss", models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name="Alíquota ISS")),
                ("pis", models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name="Alíquota PIS")),
                ("cofins", models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name="Alíquota COFINS")),
                ("inss", models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name="Alíquota INSS")),
                ("ir", models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name="Alíquota IR")),
                ("csll", models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name="Alíquota CSLL")),
                ("ibs_situacao_tributaria", models.CharField(blank=True, default="", max_length=30, verbose_name="IBS/CBS Situação tributária")),
                ("ibs_classificacao_tributaria", models.CharField(blank=True, default="", max_length=30, verbose_name="IBS/CBS Classificação tributária")),
                ("ibs_situacao_tributaria_regular", models.CharField(blank=True, default="", max_length=30, verbose_name="IBS/CBS Situação regular")),
                ("ibs_classificacao_tributaria_regular", models.CharField(blank=True, default="", max_length=30, verbose_name="IBS/CBS Classificação regular")),
                ("ibs_credito_presumido", models.CharField(blank=True, default="", max_length=30, verbose_name="IBS/CBS Crédito presumido")),
                ("ibs_aliquota_diferimento_estadual", models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name="IBS estadual diferimento")),
                ("ibs_aliquota_diferimento_municipal", models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name="IBS municipal diferimento")),
                ("cbs_aliquota_diferimento", models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name="CBS diferimento")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveIndex(
            model_name="taxclass",
            name="finance_tax_worksho_56e0f3_idx",
        ),
        migrations.RemoveIndex(
            model_name="taxclass",
            name="finance_tax_worksho_dfc038_idx",
        ),
        migrations.RemoveConstraint(
            model_name="taxclass",
            name="unique_tax_class_per_workshop_reference",
        ),
        migrations.AddField(
            model_name="taxclassnfe",
            name="workshop",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tax_classes_nfe", to="workshops.workshop", verbose_name="Oficina"),
        ),
        migrations.AddField(
            model_name="taxclassnfse",
            name="workshop",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tax_classes_nfse", to="workshops.workshop", verbose_name="Oficina"),
        ),
        migrations.RunPython(_migrate_tax_classes, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="taxclass",
            name="workshop",
        ),
        migrations.AddIndex(
            model_name="taxclassnfe",
            index=models.Index(fields=["workshop", "status"], name="finance_tax_worksho_d63345_idx"),
        ),
        migrations.AddConstraint(
            model_name="taxclassnfe",
            constraint=models.UniqueConstraint(fields=("workshop", "reference"), name="unique_tax_class_nfe_per_workshop_reference"),
        ),
        migrations.AddIndex(
            model_name="taxclassnfse",
            index=models.Index(fields=["workshop", "status"], name="finance_tax_worksho_f5530e_idx"),
        ),
        migrations.AddConstraint(
            model_name="taxclassnfse",
            constraint=models.UniqueConstraint(fields=("workshop", "reference"), name="unique_tax_class_nfse_per_workshop_reference"),
        ),
        migrations.DeleteModel(
            name="TaxClass",
        ),
    ]
