# Generated by Django 6.0 on 2026-02-17 19:19

import django.db.models.deletion
from django.db import migrations, models


def _normalize_items(value):
    if not isinstance(value, list):
        return []
    return [dict(item) for item in value if isinstance(item, dict)]


def _migrate_nfe_scenarios(apps, schema_editor):
    TaxClassNfe = apps.get_model("finance", "TaxClassNfe")
    TaxClassNfeIcmsScenario = apps.get_model("finance", "TaxClassNfeIcmsScenario")
    TaxClassNfeIpiScenario = apps.get_model("finance", "TaxClassNfeIpiScenario")
    TaxClassNfePisScenario = apps.get_model("finance", "TaxClassNfePisScenario")
    TaxClassNfeCofinsScenario = apps.get_model("finance", "TaxClassNfeCofinsScenario")

    for tax_class in TaxClassNfe.objects.all().iterator():
        scenario_mapping = (
            (TaxClassNfeIcmsScenario, _normalize_items(tax_class.icms)),
            (TaxClassNfeIpiScenario, _normalize_items(tax_class.ipi)),
            (TaxClassNfePisScenario, _normalize_items(tax_class.pis)),
            (TaxClassNfeCofinsScenario, _normalize_items(tax_class.cofins)),
        )
        for model_class, items in scenario_mapping:
            if not items:
                continue
            model_class.objects.bulk_create([model_class(tax_class_id=tax_class.id, position=index, data=item) for index, item in enumerate(items)])


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0003_taxclassnfe_taxclassnfse_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxClassNfeCofinsScenario",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("position", models.PositiveIntegerField(default=0, verbose_name="Posição")),
                ("data", models.JSONField(blank=True, default=dict, verbose_name="Cenário COFINS")),
                ("tax_class", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cofins_scenarios", to="finance.taxclassnfe", verbose_name="Classe NF-e")),
            ],
            options={
                "ordering": ["position", "id"],
                "indexes": [models.Index(fields=["tax_class", "position"], name="finance_tax_tax_cla_25343d_idx")],
            },
        ),
        migrations.CreateModel(
            name="TaxClassNfeIcmsScenario",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("position", models.PositiveIntegerField(default=0, verbose_name="Posição")),
                ("data", models.JSONField(blank=True, default=dict, verbose_name="Cenário ICMS")),
                ("tax_class", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="icms_scenarios", to="finance.taxclassnfe", verbose_name="Classe NF-e")),
            ],
            options={
                "ordering": ["position", "id"],
                "indexes": [models.Index(fields=["tax_class", "position"], name="finance_tax_tax_cla_6a483f_idx")],
            },
        ),
        migrations.CreateModel(
            name="TaxClassNfeIpiScenario",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("position", models.PositiveIntegerField(default=0, verbose_name="Posição")),
                ("data", models.JSONField(blank=True, default=dict, verbose_name="Cenário IPI")),
                ("tax_class", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ipi_scenarios", to="finance.taxclassnfe", verbose_name="Classe NF-e")),
            ],
            options={
                "ordering": ["position", "id"],
                "indexes": [models.Index(fields=["tax_class", "position"], name="finance_tax_tax_cla_4e20ad_idx")],
            },
        ),
        migrations.CreateModel(
            name="TaxClassNfePisScenario",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("position", models.PositiveIntegerField(default=0, verbose_name="Posição")),
                ("data", models.JSONField(blank=True, default=dict, verbose_name="Cenário PIS")),
                ("tax_class", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="pis_scenarios", to="finance.taxclassnfe", verbose_name="Classe NF-e")),
            ],
            options={
                "ordering": ["position", "id"],
                "indexes": [models.Index(fields=["tax_class", "position"], name="finance_tax_tax_cla_91c1e6_idx")],
            },
        ),
        migrations.RunPython(_migrate_nfe_scenarios, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="taxclassnfe",
            name="cofins",
        ),
        migrations.RemoveField(
            model_name="taxclassnfe",
            name="icms",
        ),
        migrations.RemoveField(
            model_name="taxclassnfe",
            name="ipi",
        ),
        migrations.RemoveField(
            model_name="taxclassnfe",
            name="pis",
        ),
    ]
