# Generated by Django 6.0 on 2026-02-17 19:25

from decimal import Decimal, InvalidOperation

from django.db import migrations, models


def _clean_string(value):
    return str(value or "").strip()


def _to_decimal(value):
    if value in (None, ""):
        return None

    normalized = str(value).strip().replace(",", ".")
    if not normalized:
        return None

    try:
        return Decimal(normalized)
    except (InvalidOperation, ValueError):
        return None


def _to_bool(value):
    if value in (None, ""):
        return None
    if isinstance(value, bool):
        return value

    normalized = str(value).strip().lower()
    if normalized in {"1", "true", "yes", "sim"}:
        return True
    if normalized in {"0", "false", "no", "nao", "não"}:
        return False
    return None


def _migrate_scenario_data_to_columns(apps, schema_editor):
    TaxClassNfeIcmsScenario = apps.get_model("finance", "TaxClassNfeIcmsScenario")
    TaxClassNfeIpiScenario = apps.get_model("finance", "TaxClassNfeIpiScenario")
    TaxClassNfePisScenario = apps.get_model("finance", "TaxClassNfePisScenario")
    TaxClassNfeCofinsScenario = apps.get_model("finance", "TaxClassNfeCofinsScenario")

    for scenario in TaxClassNfeIcmsScenario.objects.all().iterator():
        payload = scenario.data if isinstance(scenario.data, dict) else {}
        scenario.tipo_tributacao = _clean_string(payload.get("tipo_tributacao"))
        scenario.cenario = _clean_string(payload.get("cenario"))
        scenario.tipo_pessoa = _clean_string(payload.get("tipo_pessoa"))
        scenario.nao_contribuinte = _to_bool(payload.get("nao_contribuinte"))
        scenario.codigo_cfop = _clean_string(payload.get("codigo_cfop"))
        scenario.situacao_tributaria = _clean_string(payload.get("situacao_tributaria"))
        scenario.aliquota_credito = _to_decimal(payload.get("aliquota_credito"))
        scenario.aliquota_importacao = _to_decimal(payload.get("aliquota_importacao"))
        scenario.save(
            update_fields=[
                "tipo_tributacao",
                "cenario",
                "tipo_pessoa",
                "nao_contribuinte",
                "codigo_cfop",
                "situacao_tributaria",
                "aliquota_credito",
                "aliquota_importacao",
            ]
        )

    for scenario in TaxClassNfeIpiScenario.objects.all().iterator():
        payload = scenario.data if isinstance(scenario.data, dict) else {}
        scenario.cenario = _clean_string(payload.get("cenario"))
        scenario.tipo_pessoa = _clean_string(payload.get("tipo_pessoa"))
        scenario.situacao_tributaria = _clean_string(payload.get("situacao_tributaria"))
        scenario.codigo_enquadramento = _clean_string(payload.get("codigo_enquadramento"))
        scenario.aliquota = _to_decimal(payload.get("aliquota"))
        scenario.save(update_fields=["cenario", "tipo_pessoa", "situacao_tributaria", "codigo_enquadramento", "aliquota"])

    for scenario in TaxClassNfePisScenario.objects.all().iterator():
        payload = scenario.data if isinstance(scenario.data, dict) else {}
        scenario.cenario = _clean_string(payload.get("cenario"))
        scenario.tipo_pessoa = _clean_string(payload.get("tipo_pessoa"))
        scenario.situacao_tributaria = _clean_string(payload.get("situacao_tributaria"))
        scenario.aliquota = _to_decimal(payload.get("aliquota"))
        scenario.save(update_fields=["cenario", "tipo_pessoa", "situacao_tributaria", "aliquota"])

    for scenario in TaxClassNfeCofinsScenario.objects.all().iterator():
        payload = scenario.data if isinstance(scenario.data, dict) else {}
        scenario.cenario = _clean_string(payload.get("cenario"))
        scenario.tipo_pessoa = _clean_string(payload.get("tipo_pessoa"))
        scenario.situacao_tributaria = _clean_string(payload.get("situacao_tributaria"))
        scenario.aliquota = _to_decimal(payload.get("aliquota"))
        scenario.save(update_fields=["cenario", "tipo_pessoa", "situacao_tributaria", "aliquota"])


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0004_remove_taxclassnfe_cofins_remove_taxclassnfe_icms_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxclassnfecofinsscenario",
            name="aliquota",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name="Alíquota"),
        ),
        migrations.AddField(
            model_name="taxclassnfecofinsscenario",
            name="cenario",
            field=models.CharField(blank=True, default="", max_length=30, verbose_name="Cenário"),
        ),
        migrations.AddField(
            model_name="taxclassnfecofinsscenario",
            name="situacao_tributaria",
            field=models.CharField(blank=True, default="", max_length=10, verbose_name="Situação tributária"),
        ),
        migrations.AddField(
            model_name="taxclassnfecofinsscenario",
            name="tipo_pessoa",
            field=models.CharField(blank=True, default="", max_length=20, verbose_name="Tipo pessoa"),
        ),
        migrations.AddField(
            model_name="taxclassnfeicmsscenario",
            name="aliquota_credito",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name="Alíquota crédito"),
        ),
        migrations.AddField(
            model_name="taxclassnfeicmsscenario",
            name="aliquota_importacao",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name="Alíquota importação"),
        ),
        migrations.AddField(
            model_name="taxclassnfeicmsscenario",
            name="cenario",
            field=models.CharField(blank=True, default="", max_length=30, verbose_name="Cenário"),
        ),
        migrations.AddField(
            model_name="taxclassnfeicmsscenario",
            name="codigo_cfop",
            field=models.CharField(blank=True, default="", max_length=20, verbose_name="Código CFOP"),
        ),
        migrations.AddField(
            model_name="taxclassnfeicmsscenario",
            name="nao_contribuinte",
            field=models.BooleanField(blank=True, null=True, verbose_name="Não contribuinte"),
        ),
        migrations.AddField(
            model_name="taxclassnfeicmsscenario",
            name="situacao_tributaria",
            field=models.CharField(blank=True, default="", max_length=10, verbose_name="Situação tributária"),
        ),
        migrations.AddField(
            model_name="taxclassnfeicmsscenario",
            name="tipo_pessoa",
            field=models.CharField(blank=True, default="", max_length=20, verbose_name="Tipo pessoa"),
        ),
        migrations.AddField(
            model_name="taxclassnfeicmsscenario",
            name="tipo_tributacao",
            field=models.CharField(blank=True, default="", max_length=30, verbose_name="Tipo tributação"),
        ),
        migrations.AddField(
            model_name="taxclassnfeipiscenario",
            name="aliquota",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name="Alíquota"),
        ),
        migrations.AddField(
            model_name="taxclassnfeipiscenario",
            name="cenario",
            field=models.CharField(blank=True, default="", max_length=30, verbose_name="Cenário"),
        ),
        migrations.AddField(
            model_name="taxclassnfeipiscenario",
            name="codigo_enquadramento",
            field=models.CharField(blank=True, default="", max_length=10, verbose_name="Código enquadramento"),
        ),
        migrations.AddField(
            model_name="taxclassnfeipiscenario",
            name="situacao_tributaria",
            field=models.CharField(blank=True, default="", max_length=10, verbose_name="Situação tributária"),
        ),
        migrations.AddField(
            model_name="taxclassnfeipiscenario",
            name="tipo_pessoa",
            field=models.CharField(blank=True, default="", max_length=20, verbose_name="Tipo pessoa"),
        ),
        migrations.AddField(
            model_name="taxclassnfepisscenario",
            name="aliquota",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name="Alíquota"),
        ),
        migrations.AddField(
            model_name="taxclassnfepisscenario",
            name="cenario",
            field=models.CharField(blank=True, default="", max_length=30, verbose_name="Cenário"),
        ),
        migrations.AddField(
            model_name="taxclassnfepisscenario",
            name="situacao_tributaria",
            field=models.CharField(blank=True, default="", max_length=10, verbose_name="Situação tributária"),
        ),
        migrations.AddField(
            model_name="taxclassnfepisscenario",
            name="tipo_pessoa",
            field=models.CharField(blank=True, default="", max_length=20, verbose_name="Tipo pessoa"),
        ),
        migrations.RunPython(_migrate_scenario_data_to_columns, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="taxclassnfecofinsscenario",
            name="data",
        ),
        migrations.RemoveField(
            model_name="taxclassnfeicmsscenario",
            name="data",
        ),
        migrations.RemoveField(
            model_name="taxclassnfeipiscenario",
            name="data",
        ),
        migrations.RemoveField(
            model_name="taxclassnfepisscenario",
            name="data",
        ),
    ]
