# Generated by Django 6.0 on 2026-02-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_webmaniacompany_workshop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webmaniacompany',
            name='tipo_tributacao',
            field=models.CharField(blank=True, choices=[('simples_nacional', 'Simples Nacional'), ('lucro_normal', 'Lucro Normal')], default='', max_length=32, verbose_name='Tipo tributação'),
        ),
    ]
