# Generated by Django 6.0 on 2026-02-27 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_encrypt_webmania_company_sensitive_fields'),
        ('workorder', '0007_alter_workorder_status'),
        ('workshops', '0013_alter_workshop_cnpj'),
    ]

    operations = [
        migrations.CreateModel(
            name='NfeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('current_step', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('waiting_wo', 'Aguardando Ordem de Serviço'), ('checking_client', 'Verificando Cliente'), ('checking_products', 'Verificando Produtos'), ('processing', 'Processando'), ('approved', 'Aprovado'), ('reproved', 'Reprovado'), ('denied', 'Denegado'), ('canceled', 'Cancelado'), ('contingency', 'Contingência')], default='waiting_wo', max_length=20)),
                ('tax_class', models.CharField(default='REF000000', max_length=30, verbose_name='Classe de Imposto')),
                ('workorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workorder.workorder', verbose_name='Ordem de Serviço')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshops.workshop', verbose_name='Oficina')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NfeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True)),
                ('model', models.CharField(default='nfe', max_length=255)),
                ('status', models.CharField(choices=[('processando', 'Processando'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('cancelado', 'Cancelado'), ('denegado', 'Denegado'), ('contingencia', 'Contingencia')], default='processando', max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('number', models.CharField(blank=True, default='', max_length=40)),
                ('series', models.CharField(blank=True, default='', max_length=20)),
                ('receipt', models.CharField(blank=True, default='', max_length=40)),
                ('access_key', models.CharField(blank=True, default='', max_length=60)),
                ('xml_url', models.URLField(blank=True, default='')),
                ('danfe_url', models.URLField(blank=True, default='')),
                ('danfe_simple_url', models.URLField(blank=True, default='')),
                ('danfe_label_url', models.URLField(blank=True, default='')),
                ('log_payload', models.JSONField(blank=True, default=dict)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('workorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workorder.workorder', verbose_name='Ordem de Serviço')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workshops.workshop', verbose_name='Oficina')),
                ('request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='finance.nferequest', verbose_name='Requisição de NF-e')),
            ],
            options={
                'indexes': [models.Index(fields=['workshop', 'status'], name='finance_nfe_worksho_fbf865_idx')],
                'constraints': [models.UniqueConstraint(fields=('workorder', 'uuid'), name='unique_nfe_item_per_workorder')],
            },
        ),
    ]
