# Generated by Django 6.0 on 2026-03-09 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_paymentmethod'),
        ('workshops', '0014_alter_workshop_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('code', models.CharField(editable=False, max_length=255, verbose_name='Código')),
                ('sequence', models.PositiveIntegerField(editable=False, verbose_name='Sequência')),
                ('level', models.PositiveIntegerField(editable=False, verbose_name='Nível')),
                ('sort_key', models.CharField(editable=False, max_length=255, verbose_name='Chave de ordenação')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='finance.financialgroup', verbose_name='Grupo pai')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_groups', to='workshops.workshop', verbose_name='Oficina')),
            ],
            options={
                'verbose_name': 'Grupo Financeiro',
                'verbose_name_plural': 'Grupos Financeiros',
                'ordering': ['sort_key', 'id'],
                'abstract': False,
                'indexes': [models.Index(fields=['workshop', 'parent'], name='finance_fin_worksho_9f7b01_idx'), models.Index(fields=['workshop', 'sort_key'], name='finance_fin_worksho_2e400b_idx'), models.Index(fields=['workshop', 'is_active'], name='finance_fin_worksho_532267_idx')],
                'constraints': [models.UniqueConstraint(fields=('workshop', 'parent', 'sequence'), name='unique_financial_group_sequence_per_parent'), models.UniqueConstraint(fields=('workshop', 'code'), name='unique_financial_group_code_per_workshop'), models.UniqueConstraint(fields=('workshop', 'sort_key'), name='unique_financial_group_sort_key_per_workshop')],
            },
        ),
    ]
