# Generated by Django 6.0 on 2026-03-10 20:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_financialgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='nferequest',
            name='pricing_slider',
            field=models.SmallIntegerField(blank=True, help_text='Copia o slider do orcamento na criacao e permanece independente para a emissao.', null=True, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)], verbose_name='Slider de precificacao'),
        ),
        migrations.AddField(
            model_name='nfserequest',
            name='pricing_slider',
            field=models.SmallIntegerField(blank=True, help_text='Copia o slider do orcamento na criacao e permanece independente para a emissao.', null=True, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)], verbose_name='Slider de precificacao'),
        ),
    ]
