# Generated by Django 6.0 on 2026-03-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_financialgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='installments_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Número de Parcelas'),
        ),
    ]
