# Generated by Django 6.0 on 2026-03-13 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_paymentmethod_installments_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxclassnfse',
            name='aliquota_tributos_aproximados',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Alíquota tributos aproximados'),
        ),
        migrations.AddField(
            model_name='taxclassnfse',
            name='cidade_local_prestacao',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Cidade local da prestação'),
        ),
        migrations.AddField(
            model_name='taxclassnfse',
            name='codigo_interno',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Código interno'),
        ),
        migrations.AddField(
            model_name='taxclassnfse',
            name='codigo_nbs',
            field=models.CharField(blank=True, default='', max_length=9, verbose_name='Código NBS'),
        ),
        migrations.AddField(
            model_name='taxclassnfse',
            name='data_competencia',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Data da competência'),
        ),
        migrations.AddField(
            model_name='taxclassnfse',
            name='identificador_beneficio_municipal',
            field=models.CharField(blank=True, default='', max_length=14, verbose_name='Identificador benefício municipal'),
        ),
        migrations.AddField(
            model_name='taxclassnfse',
            name='pis_cofins_retido',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='PIS/COFINS retido'),
        ),
        migrations.AddField(
            model_name='taxclassnfse',
            name='uf_local_prestacao',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='UF local da prestação'),
        ),
    ]
