# Generated by Django 6.0 on 2026-03-12 13:15

import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0013_paymentmethod_installments_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmethod",
            name="tax_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Taxa (%)",
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="tax_value",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                verbose_name="Taxa (R$)",
            ),
        ),
        migrations.AddField(
            model_name="paymentmethod",
            name="tax_value_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("BRL", "Real Brasileiro")],
                default="BRL",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
    ]
