# Generated by Django 6.0 on 2026-03-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_taxclassnfse_aliquota_tributos_aproximados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxclassnfse',
            name='codigo_servico_cliente',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Código do serviço do cliente'),
        ),
        migrations.AddField(
            model_name='taxclassnfse',
            name='modelo',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Modelo NFS-e'),
        ),
    ]
