# Generated by Django 6.0 on 2026-03-13 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "finance",
            "0014_paymentmethod_tax_percentage_paymentmethod_tax_value_and_more",
        ),
        ("workshops", "0014_alter_workshop_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "bank_code",
                    models.CharField(max_length=10, verbose_name="Código do Banco"),
                ),
                (
                    "bank_name",
                    models.CharField(max_length=255, verbose_name="Nome do Banco"),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("CORRENTE", "Conta Corrente"),
                            ("POUPANCA", "Conta Poupança"),
                            ("PAGAMENTO", "Conta Pagamento"),
                            ("OUTRO", "Outro"),
                        ],
                        default="CORRENTE",
                        max_length=20,
                        verbose_name="Tipo de Conta",
                    ),
                ),
                ("agency", models.CharField(max_length=20, verbose_name="Agência")),
                (
                    "account_number",
                    models.CharField(max_length=30, verbose_name="Conta Corrente"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "workshop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_accounts",
                        to="workshops.workshop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conta Bancária",
                "verbose_name_plural": "Contas Bancárias",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workshop", "bank_code", "account_number"),
                        name="unique_account_per_workshop",
                    )
                ],
            },
        ),
    ]
