# Generated by Django 6.0 on 2026-03-13 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_merge_20260312_0001'),
        ('finance', '0015_bankaccount'),
    ]

    operations = [
    ]
