# Generated by Django 6.0 on 2026-03-13 22:47

import django.db.models.deletion
import djmoney.models.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0015_bankaccount"),
        ("sources", "0001_initial"),
        ("workshops", "0014_alter_workshop_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        max_length=255, verbose_name="Descrição do(s) Item(ns)"
                    ),
                ),
                (
                    "items_observation",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observações dos Itens"
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("CREDIT", "Crédito (Entrada)"),
                            ("DEBIT", "Débito (Saída)"),
                        ],
                        default="DEBIT",
                        max_length=10,
                    ),
                ),
                (
                    "nf_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Número da NF",
                    ),
                ),
                (
                    "amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("BRL", "Real Brasileiro")],
                        default="BRL",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "amount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="Valor",
                    ),
                ),
                ("due_date", models.DateField(verbose_name="Data de Vencimento")),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="financial/attachments/",
                        verbose_name="Anexo",
                    ),
                ),
                (
                    "financial_observation",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observação Financeira"
                    ),
                ),
                ("current_step", models.PositiveSmallIntegerField(default=1)),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="finance.bankaccount",
                        verbose_name="Conta Bancária",
                    ),
                ),
                (
                    "budget_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="finance.financialgroup",
                        verbose_name="Plano Orçamentário",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="finance.paymentmethod",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sources.source",
                        verbose_name="Origem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workshop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workshops.workshop",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
