# Generated by Django 6.0 on 2026-03-13 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0016_financialmovement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialmovement",
            name="description",
            field=models.CharField(max_length=255, verbose_name="Descrição dos Itens"),
        ),
        migrations.AlterField(
            model_name="financialmovement",
            name="direction",
            field=models.CharField(
                choices=[("CREDIT", "Crédito"), ("DEBIT", "Débito")],
                default="DEBIT",
                max_length=15,
            ),
        ),
    ]
