# Generated by Django 6.0 on 2026-03-13 23:46

import django.db.models.deletion
import djmoney.models.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0017_alter_financialmovement_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialmovement",
            name="amount",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=14,
                null=True,
                verbose_name="Valor",
            ),
        ),
        migrations.AlterField(
            model_name="financialmovement",
            name="amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("BRL", "Real Brasileiro")],
                default="BRL",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="financialmovement",
            name="bank_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="finance.bankaccount",
                verbose_name="Conta Bancária",
            ),
        ),
        migrations.AlterField(
            model_name="financialmovement",
            name="budget_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="finance.financialgroup",
                verbose_name="Plano Orçamentário",
            ),
        ),
        migrations.AlterField(
            model_name="financialmovement",
            name="description",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Descrição dos Itens",
            ),
        ),
        migrations.AlterField(
            model_name="financialmovement",
            name="direction",
            field=models.CharField(
                blank=True,
                choices=[("CREDIT", "Crédito"), ("DEBIT", "Débito")],
                default="DEBIT",
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="financialmovement",
            name="due_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Vencimento"
            ),
        ),
        migrations.AlterField(
            model_name="financialmovement",
            name="payment_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="finance.paymentmethod",
            ),
        ),
    ]
