# Generated by Django 6.0 on 2026-03-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_request_reserved_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfeitem',
            name='last_reconciled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfeitem',
            name='last_sync_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='nfeitem',
            name='last_webhook_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfsebatch',
            name='last_sync_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='nfsebatch',
            name='last_webhook_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfseitem',
            name='last_reconciled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfseitem',
            name='last_sync_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='nfseitem',
            name='last_webhook_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WebmaniaWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('model', models.CharField(db_index=True, max_length=32)),
                ('event_uuid', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['model', 'event_uuid'], name='finance_web_model_2457a1_idx'), models.Index(fields=['processed_at'], name='finance_web_process_4dbfb3_idx')],
            },
        ),
    ]
