# Generated by Django 6.0 on 2026-03-14 21:48

import django.db.models.deletion
from django.db import migrations, models


def _seed_tax_class_presets(apps, schema_editor):
    Workshop = apps.get_model("workshops", "Workshop")
    TaxClassPreset = apps.get_model("finance", "TaxClassPreset")

    default_presets = {
        "nfe": [
            {
                "name": "Simples Nacional - Revenda padrão",
                "description": "Saída dentro/fora do estado para pessoa física e jurídica com CST 102.",
                "payload": {
                    "descricao": "Classe de impostos para Saída de produtos de revenda",
                    "icms": [
                        {"tipo_tributacao": "simples_nacional", "cenario": "saida_dentro_estado", "tipo_pessoa": "fisica", "codigo_cfop": "5102", "situacao_tributaria": "102"},
                        {"tipo_tributacao": "simples_nacional", "cenario": "saida_fora_estado", "tipo_pessoa": "fisica", "codigo_cfop": "6102", "situacao_tributaria": "102"},
                        {"tipo_tributacao": "simples_nacional", "cenario": "saida_dentro_estado", "tipo_pessoa": "juridica", "codigo_cfop": "5102", "situacao_tributaria": "102"},
                        {"tipo_tributacao": "simples_nacional", "cenario": "saida_fora_estado", "tipo_pessoa": "juridica", "codigo_cfop": "6102", "situacao_tributaria": "102"},
                    ],
                    "ipi": [
                        {"cenario": "padrao", "tipo_pessoa": "fisica", "situacao_tributaria": "99", "codigo_enquadramento": "999", "aliquota": "0.00"},
                        {"cenario": "padrao", "tipo_pessoa": "juridica", "situacao_tributaria": "99", "codigo_enquadramento": "999", "aliquota": "0.00"},
                    ],
                    "pis": [
                        {"cenario": "padrao", "tipo_pessoa": "fisica", "situacao_tributaria": "99", "aliquota": "0.00"},
                        {"cenario": "padrao", "tipo_pessoa": "juridica", "situacao_tributaria": "99", "aliquota": "0.00"},
                    ],
                    "cofins": [
                        {"cenario": "padrao", "tipo_pessoa": "fisica", "situacao_tributaria": "99", "aliquota": "0.00"},
                        {"cenario": "padrao", "tipo_pessoa": "juridica", "situacao_tributaria": "99", "aliquota": "0.00"},
                    ],
                },
            },
            {
                "name": "Simples Nacional - Com crédito",
                "description": "Configuração com CST 101 e alíquota de crédito para destinatário jurídico.",
                "payload": {
                    "descricao": "Classe de impostos SN com crédito de ICMS",
                    "icms": [
                        {"tipo_tributacao": "simples_nacional", "cenario": "saida_dentro_estado", "tipo_pessoa": "juridica", "codigo_cfop": "5102", "situacao_tributaria": "101", "aliquota_credito": "2.00"},
                        {"tipo_tributacao": "simples_nacional", "cenario": "saida_fora_estado", "tipo_pessoa": "juridica", "codigo_cfop": "6102", "situacao_tributaria": "101", "aliquota_credito": "2.00"},
                    ],
                    "ipi": [{"cenario": "padrao", "tipo_pessoa": "juridica", "situacao_tributaria": "99", "codigo_enquadramento": "999", "aliquota": "0.00"}],
                    "pis": [{"cenario": "padrao", "tipo_pessoa": "juridica", "situacao_tributaria": "99", "aliquota": "0.00"}],
                    "cofins": [{"cenario": "padrao", "tipo_pessoa": "juridica", "situacao_tributaria": "99", "aliquota": "0.00"}],
                },
            },
        ],
        "nfse": [
            {
                "name": "NFS-e ABRASF - Serviço padrão",
                "description": "Preset básico com código de serviço no formato XX.XX ou XXXXX.",
                "payload": {
                    "descricao": "Classe de impostos para prestação de serviço",
                    "tipo": "nfse",
                    "type": "nfse",
                    "codigo_servico": "01.05",
                    "natureza_operacao": "1",
                    "exigibilidade_iss": "1",
                    "iss_retido": "2",
                },
            },
            {
                "name": "NFS-e ABRASF - ISS retido",
                "description": "Preset com retenção de ISS pelo tomador.",
                "payload": {
                    "descricao": "Classe de impostos para serviço com ISS retido",
                    "tipo": "nfse",
                    "type": "nfse",
                    "codigo_servico": "01.05",
                    "natureza_operacao": "1",
                    "exigibilidade_iss": "1",
                    "iss_retido": "1",
                    "responsavel_retencao": "1",
                },
            },
        ],
    }

    for workshop in Workshop.objects.all().iterator():
        for kind, presets in default_presets.items():
            for preset in presets:
                TaxClassPreset.objects.update_or_create(
                    workshop_id=workshop.id,
                    kind=kind,
                    name=preset["name"],
                    defaults={
                        "description": preset["description"],
                        "is_active": True,
                        "payload": preset["payload"],
                    },
                )


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0018_nfeitem_last_reconciled_at_nfeitem_last_sync_error_and_more"),
        ("workshops", "0014_alter_workshop_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxClassPreset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="Data de Criação")),
                ("atualizado_em", models.DateTimeField(auto_now=True, verbose_name="Data de Atualização")),
                ("kind", models.CharField(choices=[("nfe", "NF-e"), ("nfse", "NFS-e")], max_length=10, verbose_name="Tipo")),
                ("name", models.CharField(max_length=120, verbose_name="Nome do preset")),
                ("description", models.CharField(blank=True, default="", max_length=255, verbose_name="Descrição do preset")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("payload", models.JSONField(blank=True, default=dict, verbose_name="Payload")),
                ("workshop", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tax_class_presets", to="workshops.workshop", verbose_name="Oficina")),
            ],
            options={
                "ordering": ["kind", "name", "id"],
                "abstract": False,
                "indexes": [models.Index(fields=["workshop", "kind", "is_active"], name="finance_tax_worksho_846f8b_idx")],
                "constraints": [models.UniqueConstraint(fields=("workshop", "kind", "name"), name="unique_tax_class_preset_per_workshop_kind_name")],
            },
        ),
        migrations.RunPython(_seed_tax_class_presets, migrations.RunPython.noop),
    ]
