# Generated by Django 6.0 on 2026-03-15 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_merge_0018_alter_financialmovement_amount_and_more_0019_taxclasspreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialmovement',
            name='direction',
            field=models.CharField(blank=True, choices=[('CREDIT', 'Crédito'), ('DEBIT', 'Débito')], default='DEBIT', max_length=15, null=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='financialmovement',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.paymentmethod', verbose_name='Forma de Pagamento'),
        ),
    ]
