# Generated by Django 5.2.9 on 2026-04-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0026_paymentmethod_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment_type',
            field=models.CharField(choices=[('CREDIT', 'Crédito'), ('DEBIT', 'Débito'), ('BOTH', 'Ambos')], default='BOTH', max_length=10, verbose_name='Natureza da Transação'),
        ),
    ]
