# Generated by Django 6.0 on 2026-04-19 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collaborators", "0006_workshopcollaborator_timestamps"),
        ("finance", "0027_alter_paymentmethod_payment_type"),
        ("sources", "0001_initial"),
        ("suppliers", "0008_alter_supplier_bairro_alter_supplier_cidade"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="financialmovement",
            name="dre_topic",
        ),
        migrations.AddField(
            model_name="financialmovement",
            name="collaborator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="financial_movements",
                to="collaborators.workshopcollaborator",
                verbose_name="Colaborador",
            ),
        ),
        migrations.AddField(
            model_name="financialmovement",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="financial_movements",
                to="suppliers.supplier",
                verbose_name="Fornecedor",
            ),
        ),
        migrations.AlterField(
            model_name="financialmovement",
            name="direction",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CREDIT", "Contas a receber (receita)"),
                    ("DEBIT", "Contas a pagar (despesa)"),
                ],
                default="DEBIT",
                max_length=15,
                null=True,
                verbose_name="Tipo",
            ),
        ),
        migrations.AlterField(
            model_name="financialmovement",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="sources.source",
                verbose_name="Origem",
            ),
        ),
    ]
