# Generated by Django 6.0 on 2026-04-20 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0028_remove_financialmovement_dre_topic_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialmovement",
            name="direction",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CREDIT", "Contas a receber (receita)"),
                    ("DEBIT", "Contas a pagar (despesa)"),
                ],
                max_length=15,
                null=True,
                verbose_name="Tipo",
            ),
        ),
    ]
