# Generated by Django 6.0 on 2026-04-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0029_alter_financialmovement_direction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialmovement",
            name="direction",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CREDIT", "Contas a receber (receita)"),
                    ("DEBIT", "Contas a pagar (despesa)"),
                ],
                max_length=50,
                null=True,
                verbose_name="Tipo",
            ),
        ),
        migrations.AlterField(
            model_name="financialmovement",
            name="movement_kind",
            field=models.CharField(
                choices=[
                    ("DEFAULT", "Padrão"),
                    ("WORKORDER_PARENT", "OS Pai"),
                    ("WORKORDER_CARD_FEE", "Taxa da Maquininha"),
                ],
                default="DEFAULT",
                max_length=50,
            ),
        ),
    ]
