# Generated by Django 6.0 on 2026-04-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0030_alter_financialmovement_direction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialmovement",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Descrição dos Itens"
            ),
        ),
    ]
