# Generated by Django 6.0 on 2026-04-21 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0031_alter_financialmovement_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment_type',
            field=models.CharField(choices=[('CREDIT', 'Entrada de Receita'), ('DEBIT', 'Saída de Receita'), ('BOTH', 'Ambos')], default='BOTH', max_length=10, verbose_name='Natureza da Transação'),
        ),
    ]
