# Generated by Django 6.0 on 2026-04-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0032_alter_paymentmethod_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='nferequest',
            name='additional_information',
            field=models.TextField(blank=True, default='', verbose_name='Informações complementares'),
        ),
        migrations.AddField(
            model_name='nfserequest',
            name='additional_information',
            field=models.TextField(blank=True, default='', verbose_name='Informações complementares'),
        ),
    ]
