# Generated by Django 6.0 on 2026-04-25 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "collaborators",
            "0007_collaboratorbenefit_collaboratorcommissionentry_and_more",
        ),
        ("finance", "0034_alter_taxclassnfecofinsscenario_tax_class_and_more"),
        ("suppliers", "0008_alter_supplier_bairro_alter_supplier_cidade"),
        ("workshops", "0019_reconcile_workshop_file_columns"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialmovement",
            name="movement_kind",
            field=models.CharField(
                choices=[
                    ("DEFAULT", "Padrão"),
                    ("WORKORDER_PARENT", "OS Pai"),
                    ("WORKORDER_CARD_FEE", "Taxa da Maquininha"),
                    ("GROUP_PARENT", "Agrupamento"),
                ],
                default="DEFAULT",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="MovementGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descrição"),
                ),
                ("due_date", models.DateField(verbose_name="Data de Vencimento")),
                (
                    "collaborator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movement_groups",
                        to="collaborators.workshopcollaborator",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movement_groups",
                        to="suppliers.supplier",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workshop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workshops.workshop",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="financialmovement",
            name="movement_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="financial_movements",
                to="finance.movementgroup",
            ),
        ),
    ]
