# Generated by Django 6.0 on 2026-04-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0035_alter_financialmovement_movement_kind_movementgroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nferequest',
            name='invalidated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da inutilização'),
        ),
        migrations.AddField(
            model_name='nferequest',
            name='invalidation_log_payload',
            field=models.JSONField(blank=True, default=dict, verbose_name='Log da inutilização'),
        ),
        migrations.AddField(
            model_name='nferequest',
            name='invalidation_reason',
            field=models.TextField(blank=True, default='', verbose_name='Motivo da inutilização'),
        ),
        migrations.AddField(
            model_name='nferequest',
            name='invalidation_xml_url',
            field=models.URLField(blank=True, default='', verbose_name='XML da inutilização'),
        ),
        migrations.AlterField(
            model_name='nferequest',
            name='status',
            field=models.CharField(choices=[('waiting_wo', 'Aguardando Ordem de Serviço'), ('checking_client', 'Verificando Cliente'), ('checking_products', 'Verificando Produtos'), ('processing', 'Processando'), ('approved', 'Aprovado'), ('reproved', 'Reprovado'), ('denied', 'Denegado'), ('canceled', 'Cancelado'), ('contingency', 'Contingência'), ('invalidated', 'Inutilizada')], default='waiting_wo', max_length=20),
        ),
    ]
