# Generated by Django 6.0 on 2026-05-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0036_nferequest_invalidated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialgroup",
            name="dre_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gross_revenue", "Receita Bruta de Vendas e Serviços"),
                    ("cogs", "Custos Mercadorias Vendidas"),
                    ("financial_revenue", "Receitas Financeiras"),
                    ("financial_expense", "Despesas Financeiras"),
                ],
                max_length=20,
                null=True,
                verbose_name="Tipo DRE",
            ),
        ),
    ]
