# Generated by Django 6.0 on 2026-05-07 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0037_financialgroup_dre_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="financialgroup",
            name="dre_type",
        ),
    ]
