# Generated by Django 6.0 on 2026-05-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0039_financialmovement_reversal_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialmovement',
            name='is_reconciled',
            field=models.BooleanField(default=False, verbose_name='Conciliado'),
        ),
    ]
