# Generated by Django 6.0 on 2026-05-28 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0040_financialmovement_is_reconciled'),
        ('workshops', '0023_workshopcostholiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalEmissionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('document_kind', models.CharField(choices=[('nfe', 'NF-e'), ('nfse', 'NFS-e')], max_length=12)),
                ('request_model', models.CharField(max_length=40)),
                ('request_id', models.PositiveIntegerField()),
                ('idempotency_key', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('started', 'Iniciada'), ('sent', 'Enviada'), ('succeeded', 'Concluida'), ('failed', 'Falhou'), ('uncertain', 'Incerta')], db_index=True, default='started', max_length=20)),
                ('remote_model', models.CharField(blank=True, default='', max_length=32)),
                ('remote_uuid', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('remote_key', models.CharField(blank=True, default='', max_length=80)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='webmaniawebhookevent',
            name='fingerprint',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='webmaniawebhookevent',
            constraint=models.UniqueConstraint(condition=models.Q(('fingerprint', ''), _negated=True), fields=('fingerprint',), name='unique_webmania_webhook_fingerprint'),
        ),
        migrations.AddField(
            model_name='fiscalemissionattempt',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_emission_attempts', to='workshops.workshop', verbose_name='Oficina'),
        ),
        migrations.AddIndex(
            model_name='fiscalemissionattempt',
            index=models.Index(fields=['workshop', 'document_kind', 'status'], name='finance_fis_worksho_6538c0_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalemissionattempt',
            index=models.Index(fields=['request_model', 'request_id'], name='finance_fis_request_53f087_idx'),
        ),
        migrations.AddConstraint(
            model_name='fiscalemissionattempt',
            constraint=models.UniqueConstraint(fields=('workshop', 'document_kind', 'idempotency_key'), name='unique_fiscal_attempt_per_intention'),
        ),
    ]
