# Generated by Django 6.0 on 2026-06-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0040_financialmovement_is_reconciled'),
    ]

    operations = [
        migrations.AddField(
            model_name='nferequest',
            name='discount_type_override',
            field=models.CharField(blank=True, choices=[('products', 'Apenas Produtos'), ('services', 'Apenas Serviços'), ('both', 'Produtos e Serviços')], default='', help_text='Sobrescreve o tipo de desconto da OS apenas para esta emissao. Vazio usa o da OS.', max_length=10, verbose_name='Tipo de Desconto (Emissao)'),
        ),
        migrations.AddField(
            model_name='nfserequest',
            name='discount_type_override',
            field=models.CharField(blank=True, choices=[('products', 'Apenas Produtos'), ('services', 'Apenas Serviços'), ('both', 'Produtos e Serviços')], default='', help_text='Sobrescreve o tipo de desconto da OS apenas para esta emissao. Vazio usa o da OS.', max_length=10, verbose_name='Tipo de Desconto (Emissao)'),
        ),
    ]
