# Generated by Django 6.0 on 2026-06-29 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0041_nferequest_discount_type_override_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxclassnfecofinsscenario',
            name='tax_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cofins_scenarios', to='finance.taxclassnfe', verbose_name='Classe de Nota Fiscal de Produto'),
        ),
        migrations.AlterField(
            model_name='taxclassnfeicmsscenario',
            name='tax_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icms_scenarios', to='finance.taxclassnfe', verbose_name='Classe de Nota Fiscal de Produto'),
        ),
        migrations.AlterField(
            model_name='taxclassnfeipiscenario',
            name='tax_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipi_scenarios', to='finance.taxclassnfe', verbose_name='Classe de Nota Fiscal de Produto'),
        ),
        migrations.AlterField(
            model_name='taxclassnfepisscenario',
            name='tax_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pis_scenarios', to='finance.taxclassnfe', verbose_name='Classe de Nota Fiscal de Produto'),
        ),
        migrations.AlterField(
            model_name='taxclasspreset',
            name='kind',
            field=models.CharField(choices=[('nfe', 'Nota Fiscal de Produto'), ('nfse', 'Nota Fiscal de Serviço')], max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='webmaniacompany',
            name='nfe_numero',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Próximo número da Nota Fiscal de Produto'),
        ),
        migrations.AlterField(
            model_name='webmaniacompany',
            name='nfe_numero_dev',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Próximo número da Nota Fiscal de Produto homologação'),
        ),
        migrations.AlterField(
            model_name='webmaniacompany',
            name='nfe_serie',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Série da Nota Fiscal de Produto'),
        ),
    ]
