# Generated by Django 6.0 on 2026-07-08 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0008_collaboratorbenefit_budget_plan'),
        ('finance', '0042_alter_taxclassnfecofinsscenario_tax_class_and_more'),
        ('sources', '0001_initial'),
        ('suppliers', '0009_alter_supplier_cnpj'),
        ('workorder', '0034_merge_20260708_0001'),
        ('workshops', '0027_workshop_whatsapp_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='financialmovement',
            name='payroll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_movements', to='collaborators.collaboratorpayroll'),
        ),
        migrations.AddField(
            model_name='financialmovement',
            name='payroll_component',
            field=models.CharField(blank=True, choices=[('SALARY', 'Salário'), ('BENEFIT', 'Benefícios'), ('TRANSPORT', 'Vale Transporte'), ('COMMISSION', 'Comissão')], max_length=32, null=True),
        ),
        migrations.AddIndex(
            model_name='financialmovement',
            index=models.Index(fields=['workshop', 'payroll'], name='finance_fin_worksho_9d5e97_idx'),
        ),
        migrations.AddIndex(
            model_name='financialmovement',
            index=models.Index(fields=['workshop', 'payroll_component'], name='finance_fin_worksho_f6ef19_idx'),
        ),
        migrations.AddConstraint(
            model_name='financialmovement',
            constraint=models.UniqueConstraint(condition=models.Q(('payroll__isnull', False), ('payroll_component__isnull', False)), fields=('payroll', 'payroll_component', 'budget_plan'), name='unique_payroll_component_movement'),
        ),
    ]
