# Generated by Django 6.0 on 2026-05-29 01:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_logincode_unused_fields'),
        ('finance', '0043_fiscaldocumentlink_alter_fiscaldocument_options_and_more'),
        ('workshops', '0023_workshopcostholiday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fiscaldocument',
            options={'permissions': [('issue_nfe_return', 'Pode emitir NF-e de devolucao'), ('issue_nfe_reversal', 'Pode emitir NF-e de estorno'), ('download_nfe_return', 'Pode baixar XML/DANFE de NF-e de devolucao ou estorno'), ('issue_nfe_complementary_price_quantity', 'Pode emitir NF-e complementar de preco/quantidade'), ('view_nfe_complementary', 'Pode visualizar NF-e complementar'), ('download_nfe_complementary', 'Pode baixar XML/DANFE de NF-e complementar'), ('view_nfe_complementary_payload', 'Pode visualizar payload de NF-e complementar')]},
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='complementary_type',
            field=models.CharField(blank=True, choices=[('price_quantity', 'Preco/quantidade')], db_index=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='fiscaldocument',
            name='purpose',
            field=models.CharField(choices=[('normal', 'Normal'), ('return', 'Devolucao'), ('reversal', 'Estorno'), ('complementary', 'Complementar')], db_index=True, default='normal', max_length=24),
        ),
        migrations.AlterField(
            model_name='fiscaldocumentlink',
            name='role',
            field=models.CharField(choices=[('returns', 'Devolve'), ('reverses', 'Estorna'), ('complements', 'Complementa')], db_index=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='fiscalemissionattempt',
            name='operation_type',
            field=models.CharField(choices=[('emission', 'Emissao'), ('cce', 'Carta de correcao'), ('return', 'Devolucao'), ('reversal', 'Estorno'), ('complementary_price_quantity', 'Complementar preco/quantidade')], db_index=True, default='emission', max_length=32),
        ),
        migrations.AddIndex(
            model_name='fiscaldocument',
            index=models.Index(fields=['workshop', 'document_type', 'purpose', 'complementary_type'], name='finance_fis_worksho_8f3996_idx'),
        ),
    ]
