# Generated by Django 6.0 on 2026-07-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0043_financialmovement_payroll_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="financialmovement",
            index=models.Index(fields=["workshop", "due_date"], name="fin_mov_ws_due_idx"),
        ),
        migrations.AddIndex(
            model_name="financialmovement",
            index=models.Index(fields=["workshop", "direction", "movement_kind"], name="fin_mov_ws_dir_kind_idx"),
        ),
        migrations.AddIndex(
            model_name="financialmovement",
            index=models.Index(fields=["workshop", "is_paid", "due_date"], name="fin_mov_ws_paid_due_idx"),
        ),
    ]
