# Generated by Django 6.0 on 2026-07-13 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0009_phase3_hot_path_indexes'),
        ('finance', '0044_phase3_hot_path_indexes'),
        ('sources', '0001_initial'),
        ('suppliers', '0009_alter_supplier_cnpj'),
        ('workorder', '0037_wave2_stored_totals'),
        ('workshops', '0027_workshop_whatsapp_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='financialmovement',
            name='unique_payroll_component_movement',
        ),
        migrations.AddField(
            model_name='financialmovement',
            name='payroll_benefit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_financial_movements', to='collaborators.collaboratorbenefit', verbose_name='Benefício da folha'),
        ),
        migrations.AddConstraint(
            model_name='financialmovement',
            constraint=models.UniqueConstraint(condition=models.Q(('payroll__isnull', False), ('payroll_benefit__isnull', True), ('payroll_component__isnull', False)), fields=('payroll', 'payroll_component', 'budget_plan'), name='unique_payroll_component_movement'),
        ),
        migrations.AddConstraint(
            model_name='financialmovement',
            constraint=models.UniqueConstraint(condition=models.Q(('payroll__isnull', False), ('payroll_benefit__isnull', False), ('payroll_component', 'BENEFIT')), fields=('payroll', 'payroll_benefit'), name='unique_payroll_benefit_movement'),
        ),
    ]
