# Generated by Django 6.0 on 2026-05-29 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0045_alter_fiscaldocument_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webmaniacompany',
            name='nfce_enabled',
            field=models.BooleanField(default=False, verbose_name='NFC-e habilitada'),
        ),
        migrations.AlterModelOptions(
            name='fiscaldocument',
            options={'permissions': [('issue_nfe_return', 'Pode emitir NF-e de devolucao'), ('issue_nfe_reversal', 'Pode emitir NF-e de estorno'), ('download_nfe_return', 'Pode baixar XML/DANFE de NF-e de devolucao ou estorno'), ('issue_nfe_complementary_price_quantity', 'Pode emitir NF-e complementar de preco/quantidade'), ('view_nfe_complementary', 'Pode visualizar NF-e complementar'), ('download_nfe_complementary', 'Pode baixar XML/DANFE de NF-e complementar'), ('view_nfe_complementary_payload', 'Pode visualizar payload de NF-e complementar'), ('issue_nfe_adjustment', 'Pode emitir NF-e de ajuste'), ('view_nfe_adjustment', 'Pode visualizar NF-e de ajuste'), ('download_nfe_adjustment', 'Pode baixar XML/DANFE de NF-e de ajuste'), ('view_nfe_adjustment_payload', 'Pode visualizar payload de NF-e de ajuste'), ('issue_nfce', 'Pode emitir NFC-e'), ('view_nfce', 'Pode visualizar NFC-e'), ('download_nfce', 'Pode baixar XML/DANFE de NFC-e'), ('view_nfce_payload', 'Pode visualizar payload de NFC-e')]},
        ),
        migrations.AlterField(
            model_name='fiscaldocument',
            name='document_type',
            field=models.CharField(choices=[('nfe', 'NF-e'), ('nfce', 'NFC-e')], db_index=True, default='nfe', max_length=12),
        ),
        migrations.AlterField(
            model_name='fiscalemissionattempt',
            name='document_kind',
            field=models.CharField(choices=[('nfe', 'NF-e'), ('nfce', 'NFC-e'), ('nfse', 'NFS-e')], max_length=12),
        ),
        migrations.AlterField(
            model_name='fiscalemissionattempt',
            name='operation_type',
            field=models.CharField(choices=[('emission', 'Emissao'), ('cce', 'Carta de correcao'), ('return', 'Devolucao'), ('reversal', 'Estorno'), ('complementary_price_quantity', 'Complementar preco/quantidade'), ('adjustment', 'Ajuste'), ('nfce_emission', 'Emissao NFC-e')], db_index=True, default='emission', max_length=32),
        ),
    ]
