# Generated by Django 5.2.9 on 2026-08-08 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_logincode_unused_fields'),
        ('finance', '0046_revert_staging_merge'),
        ('workshops', '0044_outbound_business_weekdays_all_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('document_type', models.CharField(choices=[('nfe', 'NF-e')], db_index=True, default='nfe', max_length=12)),
                ('remote_uuid', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('access_key', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('series', models.CharField(blank=True, default='', max_length=20)),
                ('number', models.CharField(blank=True, default='', max_length=40)),
                ('environment', models.CharField(blank=True, default='', max_length=10)),
                ('status', models.CharField(choices=[('aprovado', 'Aprovado')], db_index=True, default='aprovado', max_length=20)),
                ('remote_status', models.CharField(blank=True, default='', max_length=40)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_documents', to='accounts.account', verbose_name='Conta')),
                ('legacy_nfe_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_document', to='finance.nfeitem', verbose_name='Item legado NF-e')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_documents', to='workshops.workshop', verbose_name='Oficina')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FiscalDocumentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('event_type', models.CharField(choices=[('cce', 'Carta de correção')], db_index=True, default='cce', max_length=20)),
                ('event_sequence', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('started', 'Iniciado'), ('sent', 'Enviado'), ('succeeded', 'Concluído'), ('processando', 'Processando'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('failed', 'Falhou'), ('uncertain', 'Incerto')], db_index=True, default='started', max_length=20)),
                ('remote_uuid', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('remote_event_id', models.CharField(blank=True, default='', max_length=80)),
                ('remote_model', models.CharField(blank=True, default='cce', max_length=32)),
                ('correction_text', models.TextField(blank=True, default='')),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('xml_url', models.URLField(blank=True, default='')),
                ('dacce_url', models.URLField(blank=True, default='')),
                ('legal_confirmation', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='finance.fiscaldocument', verbose_name='Documento fiscal')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiscal_document_events', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'permissions': [('issue_nfe_correction', 'Pode emitir carta de correção NF-e'), ('download_nfe_correction', 'Pode baixar XML/DACCE de carta de correção NF-e')],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FiscalEmissionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('document_kind', models.CharField(choices=[('nfe', 'NF-e')], default='nfe', max_length=12)),
                ('operation_type', models.CharField(choices=[('cce', 'Carta de correção')], db_index=True, default='cce', max_length=32)),
                ('request_model', models.CharField(max_length=40)),
                ('request_id', models.PositiveIntegerField()),
                ('idempotency_key', models.CharField(max_length=160)),
                ('payload_hash', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('started', 'Iniciada'), ('sent', 'Enviada'), ('succeeded', 'Concluída'), ('failed', 'Falhou'), ('uncertain', 'Incerta')], db_index=True, default='started', max_length=20)),
                ('remote_model', models.CharField(blank=True, default='', max_length=32)),
                ('remote_uuid', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('remote_key', models.CharField(blank=True, default='', max_length=80)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('fiscal_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emission_attempts', to='finance.fiscaldocument', verbose_name='Documento fiscal')),
                ('fiscal_document_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emission_attempts', to='finance.fiscaldocumentevent', verbose_name='Evento fiscal')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_emission_attempts', to='workshops.workshop', verbose_name='Oficina')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='fiscaldocument',
            index=models.Index(fields=['workshop', 'document_type', 'status'], name='finance_fis_worksho_6ce3cb_idx'),
        ),
        migrations.AddConstraint(
            model_name='fiscaldocument',
            constraint=models.UniqueConstraint(fields=('workshop', 'legacy_nfe_item'), name='unique_fiscal_document_per_legacy_nfe_item'),
        ),
        migrations.AddConstraint(
            model_name='fiscaldocument',
            constraint=models.UniqueConstraint(condition=models.Q(('remote_uuid', ''), _negated=True), fields=('workshop', 'document_type', 'remote_uuid'), name='unique_fiscal_document_remote_uuid_per_workshop'),
        ),
        migrations.AddConstraint(
            model_name='fiscaldocument',
            constraint=models.UniqueConstraint(condition=models.Q(('access_key', ''), _negated=True), fields=('workshop', 'document_type', 'access_key'), name='unique_fiscal_document_access_key_per_workshop'),
        ),
        migrations.AddIndex(
            model_name='fiscaldocumentevent',
            index=models.Index(fields=['document', 'event_type', 'status'], name='finance_fis_documen_d315ba_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscaldocumentevent',
            index=models.Index(fields=['remote_model', 'remote_uuid'], name='finance_fis_remote__4af94c_idx'),
        ),
        migrations.AddConstraint(
            model_name='fiscaldocumentevent',
            constraint=models.UniqueConstraint(fields=('document', 'event_type', 'event_sequence'), name='unique_fiscal_document_event_sequence'),
        ),
        migrations.AddConstraint(
            model_name='fiscaldocumentevent',
            constraint=models.UniqueConstraint(condition=models.Q(('remote_uuid', ''), _negated=True), fields=('remote_uuid',), name='unique_fiscal_document_event_remote_uuid'),
        ),
        migrations.AddIndex(
            model_name='fiscalemissionattempt',
            index=models.Index(fields=['workshop', 'document_kind', 'status'], name='finance_fis_worksho_6538c0_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalemissionattempt',
            index=models.Index(fields=['operation_type', 'status'], name='finance_fis_operati_227094_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalemissionattempt',
            index=models.Index(fields=['fiscal_document_event'], name='finance_fis_fiscal__86f5e7_idx'),
        ),
        migrations.AddConstraint(
            model_name='fiscalemissionattempt',
            constraint=models.UniqueConstraint(fields=('workshop', 'document_kind', 'idempotency_key'), name='unique_fiscal_attempt_per_intention'),
        ),
    ]
