# Generated by Django 6.0 on 2026-05-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0046_alter_fiscaldocument_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fiscaldocument',
            options={'permissions': [('issue_nfe_return', 'Pode emitir NF-e de devolucao'), ('issue_nfe_reversal', 'Pode emitir NF-e de estorno'), ('download_nfe_return', 'Pode baixar XML/DANFE de NF-e de devolucao ou estorno'), ('issue_nfe_complementary_price_quantity', 'Pode emitir NF-e complementar de preco/quantidade'), ('view_nfe_complementary', 'Pode visualizar NF-e complementar'), ('download_nfe_complementary', 'Pode baixar XML/DANFE de NF-e complementar'), ('view_nfe_complementary_payload', 'Pode visualizar payload de NF-e complementar'), ('issue_nfe_adjustment', 'Pode emitir NF-e de ajuste'), ('view_nfe_adjustment', 'Pode visualizar NF-e de ajuste'), ('download_nfe_adjustment', 'Pode baixar XML/DANFE de NF-e de ajuste'), ('view_nfe_adjustment_payload', 'Pode visualizar payload de NF-e de ajuste'), ('issue_nfce', 'Pode emitir NFC-e'), ('view_nfce', 'Pode visualizar NFC-e'), ('download_nfce', 'Pode baixar XML/DANFE de NFC-e'), ('view_nfce_payload', 'Pode visualizar payload de NFC-e'), ('cancel_nfce', 'Pode cancelar NFC-e')]},
        ),
        migrations.AlterField(
            model_name='fiscaldocumentevent',
            name='event_type',
            field=models.CharField(choices=[('cce', 'Carta de correcao'), ('cancellation', 'Cancelamento')], db_index=True, default='cce', max_length=20),
        ),
        migrations.AlterField(
            model_name='fiscaldocumentevent',
            name='status',
            field=models.CharField(choices=[('started', 'Iniciado'), ('sent', 'Enviado'), ('succeeded', 'Concluido'), ('processando', 'Processando'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('failed', 'Falhou'), ('uncertain', 'Incerto')], db_index=True, default='started', max_length=20),
        ),
        migrations.AlterField(
            model_name='fiscalemissionattempt',
            name='operation_type',
            field=models.CharField(choices=[('emission', 'Emissao'), ('cce', 'Carta de correcao'), ('return', 'Devolucao'), ('reversal', 'Estorno'), ('complementary_price_quantity', 'Complementar preco/quantidade'), ('adjustment', 'Ajuste'), ('nfce_emission', 'Emissao NFC-e'), ('nfce_cancellation', 'Cancelamento NFC-e')], db_index=True, default='emission', max_length=32),
        ),
    ]
