# Generated by Django 6.0 on 2026-05-29 16:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_logincode_unused_fields'),
        ('finance', '0047_alter_fiscaldocument_options_and_more'),
        ('workshops', '0023_workshopcostholiday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalemissionattempt',
            name='operation_type',
            field=models.CharField(choices=[('emission', 'Emissao'), ('cce', 'Carta de correcao'), ('return', 'Devolucao'), ('reversal', 'Estorno'), ('complementary_price_quantity', 'Complementar preco/quantidade'), ('adjustment', 'Ajuste'), ('nfce_emission', 'Emissao NFC-e'), ('nfce_cancellation', 'Cancelamento NFC-e'), ('nfce_inutilization', 'Inutilizacao NFC-e')], db_index=True, default='emission', max_length=32),
        ),
        migrations.CreateModel(
            name='FiscalNumberInutilization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('document_type', models.CharField(choices=[('nfe', 'NF-e'), ('nfce', 'NFC-e')], db_index=True, default='nfce', max_length=12)),
                ('environment', models.CharField(db_index=True, max_length=2)),
                ('series', models.CharField(db_index=True, max_length=10)),
                ('sequence_start', models.PositiveIntegerField()),
                ('sequence_end', models.PositiveIntegerField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('started', 'Iniciada'), ('sent', 'Enviada'), ('succeeded', 'Concluida'), ('failed', 'Falhou'), ('uncertain', 'Incerta')], db_index=True, default='started', max_length=20)),
                ('remote_status', models.CharField(blank=True, default='', max_length=64)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('remote_uuid', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('protocol', models.CharField(blank=True, default='', max_length=80)),
                ('xml_url', models.URLField(blank=True, default='')),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_number_inutilizations', to='accounts.account', verbose_name='Conta')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiscal_number_inutilizations', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_number_inutilizations', to='workshops.workshop', verbose_name='Oficina')),
            ],
            options={
                'permissions': [('inutilize_nfce_numbering', 'Pode inutilizar numeracao NFC-e'), ('view_nfce_inutilization', 'Pode visualizar inutilizacao NFC-e'), ('download_nfce_inutilization', 'Pode baixar XML de inutilizacao NFC-e'), ('view_nfce_inutilization_payload', 'Pode visualizar payload de inutilizacao NFC-e')],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='fiscalemissionattempt',
            name='fiscal_number_inutilization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emission_attempts', to='finance.fiscalnumberinutilization', verbose_name='Inutilizacao de numeracao'),
        ),
        migrations.AddIndex(
            model_name='fiscalemissionattempt',
            index=models.Index(fields=['fiscal_number_inutilization'], name='finance_fis_fiscal__97c217_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalnumberinutilization',
            index=models.Index(fields=['workshop', 'document_type', 'environment', 'series', 'status'], name='fiscal_inutil_scope_status_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalnumberinutilization',
            index=models.Index(fields=['workshop', 'document_type', 'environment', 'series', 'sequence_start', 'sequence_end'], name='fiscal_inutil_range_idx'),
        ),
        migrations.AddConstraint(
            model_name='fiscalnumberinutilization',
            constraint=models.CheckConstraint(condition=models.Q(('sequence_start__lte', models.F('sequence_end'))), name='valid_fiscal_number_inutilization_range'),
        ),
    ]
