# Generated by Django 5.2.9 on 2026-08-08 01:14

from django.db import migrations, models

from . import _idempotent


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0048_nfe_return_support'),
    ]

    operations = [
        _idempotent.AddFieldIfMissing(
            model_name='nferequest',
            name='freight_mode',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Por conta do emitente (CIF)'), (1, 'Por conta do destinatario (FOB)'), (2, 'Por conta de terceiros'), (3, 'Transporte proprio do emitente'), (4, 'Transporte proprio do destinatario'), (9, 'Sem transporte')], default=9, verbose_name='Modalidade de frete'),
        ),
        _idempotent.AddFieldIfMissing(
            model_name='nferequest',
            name='transport_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='Snapshot de transporte'),
        ),
    ]
