# Generated by Django 6.0 on 2026-05-29 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0048_alter_fiscalemissionattempt_operation_type_and_more'),
        ('workshops', '0023_workshopcostholiday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxclassnfe',
            options={'permissions': [('manage_ibs_cbs_tax_classes', 'Pode configurar IBS/CBS em classes fiscais'), ('view_ibs_cbs_configuration', 'Pode visualizar configuracao IBS/CBS')]},
        ),
        migrations.AddField(
            model_name='taxclassnfe',
            name='ibs_cbs_classificacao_tributaria',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='IBS/CBS Classificação tributária'),
        ),
        migrations.AddField(
            model_name='taxclassnfe',
            name='ibs_cbs_classificacao_tributaria_regular',
            field=models.CharField(blank=True, default='', max_length=6, verbose_name='IBS/CBS Classificação regular'),
        ),
        migrations.AddField(
            model_name='taxclassnfe',
            name='ibs_cbs_configured_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='IBS/CBS configurado em'),
        ),
        migrations.AddField(
            model_name='taxclassnfe',
            name='ibs_cbs_configured_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configured_nfe_tax_classes_ibs_cbs', to=settings.AUTH_USER_MODEL, verbose_name='IBS/CBS configurado por'),
        ),
        migrations.AddField(
            model_name='taxclassnfe',
            name='ibs_cbs_details',
            field=models.JSONField(blank=True, default=dict, verbose_name='IBS/CBS detalhes'),
        ),
        migrations.AddField(
            model_name='taxclassnfe',
            name='ibs_cbs_enabled',
            field=models.BooleanField(default=False, verbose_name='IBS/CBS habilitado'),
        ),
        migrations.AddField(
            model_name='taxclassnfe',
            name='ibs_cbs_situacao_tributaria',
            field=models.CharField(blank=True, default='', max_length=3, verbose_name='IBS/CBS Situação tributária'),
        ),
        migrations.AddField(
            model_name='taxclassnfe',
            name='ibs_cbs_situacao_tributaria_regular',
            field=models.CharField(blank=True, default='', max_length=3, verbose_name='IBS/CBS Situação regular'),
        ),
        migrations.AddIndex(
            model_name='taxclassnfe',
            index=models.Index(fields=['workshop', 'ibs_cbs_enabled'], name='finance_tax_worksho_1b48f9_idx'),
        ),
    ]
