# Generated by Django 6.0 on 2026-08-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0048_nfserequest_codigo_nbs'),
    ]

    operations = [
        migrations.AddField(
            model_name='webmaniacompany',
            name='nfe_enviar_email',
            field=models.BooleanField(default=False, verbose_name='Enviar NF-e por e-mail ao cliente'),
        ),
        migrations.AddField(
            model_name='webmaniacompany',
            name='nfse_enviar_email',
            field=models.BooleanField(default=False, verbose_name='Enviar NFS-e por e-mail ao cliente'),
        ),
    ]
