# Generated by Django 6.0 on 2026-06-02 21:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0049_alter_taxclassnfe_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fiscaldocumentevent',
            options={'permissions': [('issue_nfe_correction', 'Pode emitir carta de correcao NF-e'), ('download_nfe_correction', 'Pode baixar XML/DACCE de carta de correcao NF-e'), ('issue_ibs_cbs_event', 'Pode registrar evento IBS/CBS'), ('view_ibs_cbs_event', 'Pode visualizar evento IBS/CBS'), ('download_ibs_cbs_event', 'Pode baixar XML de evento IBS/CBS'), ('view_ibs_cbs_event_payload', 'Pode visualizar payload de evento IBS/CBS')]},
        ),
        migrations.AddField(
            model_name='fiscaldocumentevent',
            name='event_code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='fiscaldocumentevent',
            name='event_payload_type',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='fiscaldocumentevent',
            name='remote_event_id',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='fiscaldocumentevent',
            name='event_type',
            field=models.CharField(choices=[('cce', 'Carta de correcao'), ('cancellation', 'Cancelamento'), ('ibs_cbs', 'Evento IBS/CBS')], db_index=True, default='cce', max_length=20),
        ),
        migrations.AlterField(
            model_name='fiscalemissionattempt',
            name='operation_type',
            field=models.CharField(choices=[('emission', 'Emissao'), ('cce', 'Carta de correcao'), ('return', 'Devolucao'), ('reversal', 'Estorno'), ('complementary_price_quantity', 'Complementar preco/quantidade'), ('adjustment', 'Ajuste'), ('nfce_emission', 'Emissao NFC-e'), ('nfce_cancellation', 'Cancelamento NFC-e'), ('nfce_inutilization', 'Inutilizacao NFC-e'), ('nfe_ibs_cbs_event', 'Evento IBS/CBS')], db_index=True, default='emission', max_length=32),
        ),
        migrations.AddIndex(
            model_name='fiscaldocumentevent',
            index=models.Index(fields=['document', 'event_type', 'event_code', 'status'], name='finance_fis_documen_bb7027_idx'),
        ),
    ]
