# Generated by Django 5.2.9 on 2026-08-08 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_logincode_unused_fields'),
        ('finance', '0049_nfe_correction_support'),
        ('workshops', '0044_outbound_business_weekdays_all_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalDocumentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('role', models.CharField(choices=[('returns', 'Devolve'), ('reverses', 'Estorna')], db_index=True, max_length=24)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='fiscaldocument',
            options={'permissions': [('issue_nfe_return', 'Pode emitir NF-e de devolução'), ('issue_nfe_reversal', 'Pode emitir NF-e de estorno'), ('download_nfe_return', 'Pode baixar XML/DANFE de NF-e de devolução ou estorno')]},
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='danfe_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='external_confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='external_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='origin',
            field=models.CharField(choices=[('local', 'Local'), ('external', 'Externo'), ('derived', 'Derivado')], db_index=True, default='local', max_length=16),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='purpose',
            field=models.CharField(choices=[('normal', 'Normal'), ('return', 'Devolução'), ('reversal', 'Estorno')], db_index=True, default='normal', max_length=24),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='receipt',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='request_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_fiscal_documents', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante'),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='response_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='xml_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='fiscaldocument',
            name='legacy_nfe_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_document', to='finance.nfeitem', verbose_name='Item legado NF-e'),
        ),
        migrations.AlterField(
            model_name='fiscaldocument',
            name='status',
            field=models.CharField(choices=[('processando', 'Processando'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('cancelado', 'Cancelado'), ('denegado', 'Denegado'), ('contingencia', 'Contingência'), ('uncertain', 'Incerto')], db_index=True, default='aprovado', max_length=20),
        ),
        migrations.AlterField(
            model_name='fiscalemissionattempt',
            name='operation_type',
            field=models.CharField(choices=[('cce', 'Carta de correção'), ('return', 'Devolução'), ('reversal', 'Estorno')], db_index=True, default='cce', max_length=32),
        ),
        migrations.AddIndex(
            model_name='fiscaldocument',
            index=models.Index(fields=['workshop', 'document_type', 'origin', 'purpose'], name='finance_fis_worksho_f0a14e_idx'),
        ),
        migrations.AddField(
            model_name='fiscaldocumentlink',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_from', to='finance.fiscaldocument', verbose_name='Documento derivado'),
        ),
        migrations.AddField(
            model_name='fiscaldocumentlink',
            name='related_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_to', to='finance.fiscaldocument', verbose_name='Documento original'),
        ),
        migrations.AddIndex(
            model_name='fiscaldocumentlink',
            index=models.Index(fields=['related_document', 'role'], name='finance_fis_related_385dc3_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscaldocumentlink',
            index=models.Index(fields=['document', 'role'], name='finance_fis_documen_1707b4_idx'),
        ),
        migrations.AddConstraint(
            model_name='fiscaldocumentlink',
            constraint=models.UniqueConstraint(fields=('document', 'related_document', 'role'), name='unique_fiscal_document_link_role'),
        ),
    ]
