# Generated by Django 6.0 on 2026-08-10 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0047_backfill_workorder_financial_descriptions'),
        ('finance', '0049_nfe_transport_support'),
    ]

    operations = [
    ]
