# Generated by Django 5.2.9 on 2026-08-08 01:14
# Made idempotent: freight_mode/transport_snapshot may already exist on some DBs.
#
# NOTE: Do not depend on 0050_merge_20260810_1742 here. That merge was introduced
# after 0051 had already been applied on staging/prod; depending on it causes
# InconsistentMigrationHistory. The feat/nf leaf is joined later via 0059.

from django.db import migrations, models

from . import _idempotent


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0050_nfe_return_support"),
    ]

    operations = [
        _idempotent.AddFieldIfMissing(
            model_name="nferequest",
            name="freight_mode",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Por conta do emitente (CIF)"),
                    (1, "Por conta do destinatario (FOB)"),
                    (2, "Por conta de terceiros"),
                    (3, "Transporte proprio do emitente"),
                    (4, "Transporte proprio do destinatario"),
                    (9, "Sem transporte"),
                ],
                default=9,
                verbose_name="Modalidade de frete",
            ),
        ),
        _idempotent.AddFieldIfMissing(
            model_name="nferequest",
            name="transport_snapshot",
            field=models.JSONField(blank=True, default=dict, verbose_name="Snapshot de transporte"),
        ),
    ]
