# Generated by Django 6.0 on 2026-06-17 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0050_alter_fiscaldocumentevent_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fiscaldocumentevent',
            options={'permissions': [('issue_nfe_correction', 'Pode emitir carta de correcao NF-e'), ('download_nfe_correction', 'Pode baixar XML/DACCE de carta de correcao NF-e'), ('issue_ibs_cbs_event', 'Pode registrar evento IBS/CBS'), ('cancel_ibs_cbs_event', 'Pode cancelar evento IBS/CBS'), ('view_ibs_cbs_event', 'Pode visualizar evento IBS/CBS'), ('download_ibs_cbs_event', 'Pode baixar XML de evento IBS/CBS'), ('view_ibs_cbs_event_payload', 'Pode visualizar payload de evento IBS/CBS')]},
        ),
        migrations.AddField(
            model_name='fiscaldocumentevent',
            name='related_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_cancellations', to='finance.fiscaldocumentevent', verbose_name='Evento relacionado'),
        ),
        migrations.AlterField(
            model_name='fiscaldocumentevent',
            name='event_type',
            field=models.CharField(choices=[('cce', 'Carta de correcao'), ('cancellation', 'Cancelamento'), ('ibs_cbs', 'Evento IBS/CBS'), ('ibs_cbs_cancellation', 'Cancelamento de evento IBS/CBS')], db_index=True, default='cce', max_length=20),
        ),
        migrations.AlterField(
            model_name='fiscaldocumentevent',
            name='status',
            field=models.CharField(choices=[('started', 'Iniciado'), ('sent', 'Enviado'), ('succeeded', 'Concluido'), ('processando', 'Processando'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('cancelado', 'Cancelado'), ('failed', 'Falhou'), ('uncertain', 'Incerto')], db_index=True, default='started', max_length=20),
        ),
        migrations.AlterField(
            model_name='fiscalemissionattempt',
            name='operation_type',
            field=models.CharField(choices=[('emission', 'Emissao'), ('cce', 'Carta de correcao'), ('return', 'Devolucao'), ('reversal', 'Estorno'), ('complementary_price_quantity', 'Complementar preco/quantidade'), ('adjustment', 'Ajuste'), ('nfce_emission', 'Emissao NFC-e'), ('nfce_cancellation', 'Cancelamento NFC-e'), ('nfce_inutilization', 'Inutilizacao NFC-e'), ('nfe_ibs_cbs_event', 'Evento IBS/CBS'), ('nfe_ibs_cbs_event_cancellation', 'Cancelamento de evento IBS/CBS')], db_index=True, default='emission', max_length=32),
        ),
        migrations.AddIndex(
            model_name='fiscaldocumentevent',
            index=models.Index(fields=['related_event', 'event_type', 'status'], name='finance_fis_related_df37b5_idx'),
        ),
        migrations.AddConstraint(
            model_name='fiscaldocumentevent',
            constraint=models.UniqueConstraint(condition=models.Q(('related_event__isnull', False), ('status__in', ['started', 'sent', 'processando', 'aprovado', 'succeeded', 'cancelado', 'uncertain'])), fields=('related_event', 'event_type'), name='unique_fiscal_event_active_related_event'),
        ),
    ]
