# Generated by Django 5.2.9 on 2026-08-08 01:14
# Made idempotent: freight_mode/transport_snapshot may already exist on some DBs.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0050_nfe_return_support"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="nferequest",
                    name="freight_mode",
                    field=models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Por conta do emitente (CIF)"),
                            (1, "Por conta do destinatario (FOB)"),
                            (2, "Por conta de terceiros"),
                            (3, "Transporte proprio do emitente"),
                            (4, "Transporte proprio do destinatario"),
                            (9, "Sem transporte"),
                        ],
                        default=9,
                        verbose_name="Modalidade de frete",
                    ),
                ),
                migrations.AddField(
                    model_name="nferequest",
                    name="transport_snapshot",
                    field=models.JSONField(blank=True, default=dict, verbose_name="Snapshot de transporte"),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'ALTER TABLE "finance_nferequest" '
                        'ADD COLUMN IF NOT EXISTS "freight_mode" smallint NOT NULL DEFAULT 9;'
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql=(
                        'ALTER TABLE "finance_nferequest" '
                        'ADD COLUMN IF NOT EXISTS "transport_snapshot" jsonb NOT NULL DEFAULT \'{}\'::jsonb;'
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
    ]
