# Generated by Django 6.0 on 2026-06-19 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0051_alter_fiscaldocumentevent_options_and_more'),
        ('stock', '0012_stockmovement_workorder_reversal_of'),
        ('workshops', '0023_workshopcostholiday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='webmaniacompany',
            name='credit_debit_basis_enabled',
            field=models.BooleanField(default=False, verbose_name='Preparacao de base credito/debito habilitada'),
        ),
        migrations.AddField(
            model_name='webmaniacompany',
            name='credit_debit_basis_enabled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Base credito/debito habilitada em'),
        ),
        migrations.AddField(
            model_name='webmaniacompany',
            name='credit_debit_basis_enabled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enabled_credit_debit_basis_companies', to=settings.AUTH_USER_MODEL, verbose_name='Base credito/debito habilitada por'),
        ),
        migrations.CreateModel(
            name='FiscalReferencedBasis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('source_access_key', models.CharField(blank=True, db_index=True, default='', max_length=44, verbose_name='Chave de acesso de origem')),
                ('source_item_sequence', models.PositiveSmallIntegerField(verbose_name='Sequencial fiscal do item')),
                ('source_document_type', models.CharField(choices=[('nfe', 'NF-e'), ('nfce', 'NFC-e')], default='nfe', max_length=12, verbose_name='Tipo do documento de origem')),
                ('basis_type', models.CharField(choices=[('credit', 'Credito'), ('debit', 'Debito')], db_index=True, max_length=12, verbose_name='Tipo da base')),
                ('fiscal_hypothesis', models.CharField(choices=[('credit_fine_interest', 'Credito - multa/juros'), ('credit_zfm_presumed', 'Credito - presumido ZFM'), ('credit_refusal', 'Credito - recusa/nao localizacao'), ('credit_value_reduction', 'Credito - reducao de valores'), ('credit_succession', 'Credito - sucessao'), ('debit_cooperative', 'Debito - cooperativas'), ('debit_exempt_output', 'Debito - saidas imunes/isentas'), ('debit_unprocessed_invoice', 'Debito - NF nao processada'), ('debit_fine_interest', 'Debito - multa/juros'), ('debit_succession', 'Debito - sucessao'), ('debit_advance_payment', 'Debito - pagamento antecipado'), ('debit_stock_loss', 'Debito - perda de estoque'), ('debit_sn_exclusion', 'Debito - desenquadramento do SN')], db_index=True, max_length=48, verbose_name='Hipotese fiscal')),
                ('ibs_cbs_snapshot', models.JSONField(default=dict, verbose_name='Snapshot IBS/CBS')),
                ('external_origin', models.BooleanField(default=False, verbose_name='Origem externa')),
                ('external_xml_validated', models.BooleanField(default=False, verbose_name='XML externo validado')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('ready', 'Pronta para aprovacao'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada'), ('invalid', 'Invalida'), ('archived', 'Arquivada')], db_index=True, default='draft', max_length=16, verbose_name='Status')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Aprovada em')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Evidencias e observacoes')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_fiscal_referenced_bases', to=settings.AUTH_USER_MODEL, verbose_name='Aprovada por')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fiscal_referenced_bases', to=settings.AUTH_USER_MODEL, verbose_name='Criada por')),
                ('financial_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_referenced_bases', to='finance.financialmovement', verbose_name='Movimentacao financeira')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referenced_bases', to='finance.fiscaldocument', verbose_name='Documento fiscal de origem')),
                ('source_nfe_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='referenced_bases', to='finance.nfeitem', verbose_name='NF-e legada de origem')),
                ('stock_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_referenced_bases', to='stock.stockmovement', verbose_name='Movimentacao de estoque')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_referenced_bases', to='workshops.workshop', verbose_name='Oficina')),
            ],
            options={
                'permissions': [('prepare_nfe_credit_debit_basis', 'Pode preparar base fiscal de credito/debito'), ('approve_nfe_credit_debit_basis', 'Pode aprovar base fiscal de credito/debito'), ('view_nfe_credit_debit_basis', 'Pode visualizar base fiscal de credito/debito'), ('view_nfe_credit_debit_basis_payload', 'Pode visualizar payload da base fiscal de credito/debito')],
                'abstract': False,
                'indexes': [models.Index(fields=['workshop', 'status', 'basis_type'], name='fiscal_basis_scope_status_idx'), models.Index(fields=['source_document', 'source_item_sequence'], name='fiscal_basis_source_item_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('source_document__isnull', False)), fields=('workshop', 'source_document', 'source_item_sequence', 'fiscal_hypothesis'), name='unique_local_fiscal_referenced_basis'), models.UniqueConstraint(condition=models.Q(('external_origin', True), models.Q(('source_access_key', ''), _negated=True)), fields=('workshop', 'source_access_key', 'source_item_sequence', 'fiscal_hypothesis'), name='unique_external_fiscal_referenced_basis')],
            },
        ),
    ]
