# Generated by Django 5.2.9 on 2026-08-22 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0051_nfe_transport_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxclassnfse',
            name='codigo_nbs',
            field=models.CharField(blank=True, default='', help_text='Código NBS da classe NFS-e (Padrão Nacional: 9 dígitos).', max_length=9, verbose_name='Código NBS'),
        ),
    ]
