# Generated by Django 6.0 on 2026-06-19 19:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0052_webmaniacompany_credit_debit_basis_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalReferencedBasisItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('source_item_sequence', models.PositiveSmallIntegerField(verbose_name='Sequencial fiscal do item')),
                ('source_item_description', models.CharField(blank=True, default='', max_length=255, verbose_name='Descricao fiscal do item')),
                ('source_item_code', models.CharField(blank=True, default='', max_length=80, verbose_name='Codigo fiscal do item')),
                ('source_item_ncm', models.CharField(blank=True, default='', max_length=8, verbose_name='NCM fiscal do item')),
                ('source_item_cfop', models.CharField(blank=True, default='', max_length=4, verbose_name='CFOP fiscal do item')),
                ('source_quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Quantidade fiscal')),
                ('source_unit', models.CharField(blank=True, default='', max_length=12, verbose_name='Unidade fiscal')),
                ('source_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valor unitario fiscal')),
                ('source_total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valor total fiscal')),
                ('principal_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valor principal')),
                ('fine_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valor de multa')),
                ('interest_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valor de juros')),
                ('other_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Outros valores')),
                ('credit_debit_base_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Base monetaria credito/debito')),
                ('commercial_snapshot', models.JSONField(default=dict, verbose_name='Snapshot comercial')),
                ('monetary_snapshot', models.JSONField(default=dict, verbose_name='Snapshot monetario')),
                ('basis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_item', to='finance.fiscalreferencedbasis', verbose_name='Base fiscal')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['source_item_cfop', 'source_item_ncm'], name='fiscal_basis_item_tax_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('source_quantity__isnull', True), ('source_quantity__gte', 0), _connector='OR'), name='fiscal_basis_item_quantity_nonnegative'), models.CheckConstraint(condition=models.Q(('source_unit_price__isnull', True), ('source_unit_price__gte', 0), _connector='OR'), name='fiscal_basis_item_unit_price_nonnegative'), models.CheckConstraint(condition=models.Q(('source_total_amount__isnull', True), ('source_total_amount__gte', 0), _connector='OR'), name='fiscal_basis_item_total_nonnegative'), models.CheckConstraint(condition=models.Q(('principal_amount__gte', 0), ('fine_amount__gte', 0), ('interest_amount__gte', 0), ('other_amount__gte', 0), ('credit_debit_base_amount__gte', 0)), name='fiscal_basis_item_money_nonnegative')],
            },
        ),
    ]
