# Generated by Django 5.2.9 on 2026-08-24 22:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models

from . import _idempotent


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0052_taxclassnfse_codigo_nbs'),
        ('stock', '0017_stockmovement_reason'),
        ('workshops', '0044_outbound_business_weekdays_all_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        _idempotent.CreateModelIfMissing(
            name='PurchaseReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('current_step', models.PositiveSmallIntegerField(default=1, verbose_name='Etapa atual')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('ready', 'Pronta para emissão'), ('processing', 'Em processamento'), ('authorized', 'Autorizada'), ('rejected', 'Rejeitada'), ('communication_error', 'Erro de comunicação'), ('contingency', 'Contingência'), ('uncertain', 'Aguardando reconciliação'), ('canceled', 'Cancelada')], db_index=True, default='draft', max_length=24, verbose_name='Status')),
                ('ready_at', models.DateTimeField(blank=True, null=True, verbose_name='Intenção criada em')),
                ('operation_nature', models.CharField(default='Devolução de mercadoria', max_length=255, verbose_name='Natureza da operação')),
                ('cfop', models.CharField(blank=True, default='', max_length=8, verbose_name='CFOP')),
                ('tax_class', models.CharField(blank=True, default='', max_length=120, verbose_name='Classe de imposto')),
                ('additional_information', models.TextField(blank=True, default='', verbose_name='Informações complementares')),
                ('stock_status', models.CharField(choices=[('waiting_authorization', 'Aguardando autorização fiscal'), ('pending', 'Aguardando baixa'), ('processed', 'Estoque atualizado'), ('error', 'Erro na atualização do estoque')], db_index=True, default='waiting_authorization', max_length=24, verbose_name='Status do estoque')),
                ('stock_processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Estoque atualizado em')),
                ('stock_error', models.TextField(blank=True, default='', verbose_name='Erro de atualização do estoque')),
                ('fiscal_document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_return_request', to='finance.fiscaldocument', verbose_name='Documento fiscal de devolução')),
                ('original_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_return_requests', to='finance.fiscaldocument', verbose_name='Documento fiscal original')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_return_requests', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
                ('source_stock_import', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_return_requests', to='stock.stockimport', verbose_name='NF-e de compra')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_return_requests', to='workshops.workshop', verbose_name='Oficina')),
            ],
            options={
                'verbose_name': 'Intenção de devolução de compra',
                'verbose_name_plural': 'Intenções de devolução de compra',
                'abstract': False,
            },
        ),
        _idempotent.CreateModelIfMissing(
            name='PurchaseReturnRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('kind', models.CharField(choices=[('stock', 'Vinculado ao estoque'), ('manual', 'Produto avulso')], db_index=True, default='stock', max_length=12, verbose_name='Tipo de item')),
                ('manual_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Snapshot fiscal do produto avulso')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Descrição')),
                ('product_code', models.CharField(blank=True, default='', max_length=120, verbose_name='Código do produto')),
                ('ncm', models.CharField(blank=True, default='', max_length=10, verbose_name='NCM')),
                ('cest', models.CharField(blank=True, default='', max_length=10, verbose_name='CEST')),
                ('unit', models.CharField(blank=True, default='', max_length=12, verbose_name='Unidade')),
                ('cfop', models.CharField(blank=True, default='', max_length=8, verbose_name='CFOP')),
                ('origin', models.PositiveSmallIntegerField(default=0, verbose_name='Origem tributária')),
                ('tax_class', models.CharField(blank=True, default='', max_length=120, verbose_name='Classe de imposto')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Quantidade a devolver')),
                ('unit_value', models.DecimalField(decimal_places=4, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valor unitário')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.purchasereturnrequest', verbose_name='Intenção de devolução')),
            ],
            options={
                'verbose_name': 'Item da intenção de devolução de compra',
                'verbose_name_plural': 'Itens da intenção de devolução de compra',
                'abstract': False,
            },
        ),
    ]
