# Generated by Django 5.2.9 on 2026-08-24 22:22

import django.db.models.deletion
from django.db import migrations, models

from . import _idempotent


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0053_purchase_return_stock_workflow'),
        ('stock', '0018_purchase_return_stock_workflow'),
    ]

    operations = [
        _idempotent.AddFieldIfMissing(
            model_name='purchasereturnrequestitem',
            name='source_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_return_items', to='stock.stockimportfiscalitem', verbose_name='Item fiscal de origem'),
        ),
        _idempotent.AddIndexIfMissing(
            model_name='purchasereturnrequest',
            index=models.Index(fields=['workshop', 'status'], name='purchase_ret_workshop_idx'),
        ),
        _idempotent.AddIndexIfMissing(
            model_name='purchasereturnrequest',
            index=models.Index(fields=['original_document', 'status'], name='purchase_ret_document_idx'),
        ),
        _idempotent.AddConstraintIfMissing(
            model_name='purchasereturnrequestitem',
            constraint=models.UniqueConstraint(condition=models.Q(('source_item__isnull', False)), fields=('request', 'source_item'), name='unique_purchase_return_source_item'),
        ),
    ]
