# Generated by Django 6.0 on 2026-06-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0055_alter_fiscaldocument_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fiscaldocument',
            options={'permissions': [('issue_nfe_return', 'Pode emitir NF-e de devolucao'), ('issue_nfe_reversal', 'Pode emitir NF-e de estorno'), ('download_nfe_return', 'Pode baixar XML/DANFE de NF-e de devolucao ou estorno'), ('issue_nfe_complementary_price_quantity', 'Pode emitir NF-e complementar de preco/quantidade'), ('view_nfe_complementary', 'Pode visualizar NF-e complementar'), ('download_nfe_complementary', 'Pode baixar XML/DANFE de NF-e complementar'), ('view_nfe_complementary_payload', 'Pode visualizar payload de NF-e complementar'), ('issue_nfe_adjustment', 'Pode emitir NF-e de ajuste'), ('view_nfe_adjustment', 'Pode visualizar NF-e de ajuste'), ('download_nfe_adjustment', 'Pode baixar XML/DANFE de NF-e de ajuste'), ('view_nfe_adjustment_payload', 'Pode visualizar payload de NF-e de ajuste'), ('issue_nfce', 'Pode emitir NFC-e'), ('view_nfce', 'Pode visualizar NFC-e'), ('download_nfce', 'Pode baixar XML/DANFE de NFC-e'), ('view_nfce_payload', 'Pode visualizar payload de NFC-e'), ('cancel_nfce', 'Pode cancelar NFC-e'), ('issue_nfe_credit', 'Pode emitir NF-e de credito'), ('view_nfe_credit', 'Pode visualizar NF-e de credito'), ('download_nfe_credit', 'Pode baixar XML/DANFE de NF-e de credito'), ('view_nfe_credit_payload', 'Pode visualizar payload de NF-e de credito'), ('cancel_nfe_credit', 'Pode cancelar NF-e de credito')]},
        ),
        migrations.AlterField(
            model_name='fiscalemissionattempt',
            name='operation_type',
            field=models.CharField(choices=[('emission', 'Emissao'), ('cce', 'Carta de correcao'), ('return', 'Devolucao'), ('reversal', 'Estorno'), ('complementary_price_quantity', 'Complementar preco/quantidade'), ('adjustment', 'Ajuste'), ('nfce_emission', 'Emissao NFC-e'), ('nfce_cancellation', 'Cancelamento NFC-e'), ('nfce_inutilization', 'Inutilizacao NFC-e'), ('nfe_ibs_cbs_event', 'Evento IBS/CBS'), ('nfe_ibs_cbs_event_cancellation', 'Cancelamento de evento IBS/CBS'), ('nfe_credit_emission', 'Emissao NF-e de credito'), ('nfe_credit_cancellation', 'Cancelamento NF-e de credito')], db_index=True, default='emission', max_length=32),
        ),
    ]
