# Generated by Django 6.0 on 2026-06-22 18:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0056_alter_fiscaldocument_options_and_more'),
        ('workshops', '0023_workshopcostholiday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalDebitProductPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('revision', models.PositiveSmallIntegerField(default=1, verbose_name='Revisao')),
                ('operation_type', models.CharField(default='debit', max_length=12, verbose_name='Tipo da operacao')),
                ('fiscal_purpose_type', models.CharField(default='4', max_length=4, verbose_name='Tipo fiscal remoto')),
                ('source_access_key', models.CharField(db_index=True, max_length=44, verbose_name='Chave do DF-e referenciado')),
                ('source_item_sequence', models.PositiveSmallIntegerField(verbose_name='Sequencial fiscal do item')),
                ('dfe_referenciado', models.JSONField(default=dict, verbose_name='DF-e referenciado')),
                ('product_cfop', models.CharField(max_length=4, verbose_name='CFOP validado')),
                ('product_quantity', models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='Quantidade explicita')),
                ('product_unit_price', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor unitario explicito')),
                ('product_total_amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Total explicito')),
                ('product_payload', models.JSONField(default=dict, verbose_name='Produto fiscal validado')),
                ('ibs_cbs_payload', models.JSONField(default=dict, verbose_name='IBS/CBS historico')),
                ('preview_payload', models.JSONField(default=dict, verbose_name='Pre-payload futuro')),
                ('forbidden_tax_groups_detected', models.JSONField(blank=True, default=list, verbose_name='Grupos tributarios proibidos')),
                ('validation_status', models.CharField(choices=[('draft', 'Rascunho'), ('validated', 'Validada'), ('approved', 'Aprovada'), ('invalid', 'Invalida')], db_index=True, default='draft', max_length=16, verbose_name='Status')),
                ('validation_errors', models.JSONField(blank=True, default=list, verbose_name='Erros de validacao')),
                ('explicit_value_confirmation', models.BooleanField(default=False, verbose_name='Valores informados explicitamente')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Aprovada em')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_fiscal_debit_product_previews', to=settings.AUTH_USER_MODEL, verbose_name='Aprovada por')),
                ('basis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debit_product_previews', to='finance.fiscalreferencedbasis', verbose_name='Base fiscal')),
                ('basis_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debit_product_previews', to='finance.fiscalreferencedbasisitem', verbose_name='Item da base')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fiscal_debit_product_previews', to=settings.AUTH_USER_MODEL, verbose_name='Criada por')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_debit_product_previews', to='workshops.workshop', verbose_name='Oficina')),
            ],
            options={
                'permissions': [('prepare_nfe_debit_product_preview', 'Pode preparar previa de produto de debito'), ('approve_nfe_debit_product_preview', 'Pode aprovar previa de produto de debito'), ('view_nfe_debit_product_preview', 'Pode visualizar previa de produto de debito'), ('view_nfe_debit_product_preview_payload', 'Pode visualizar payload da previa de produto de debito')],
                'abstract': False,
                'indexes': [models.Index(fields=['workshop', 'validation_status'], name='fisc_debit_prev_scope_idx'), models.Index(fields=['source_access_key', 'source_item_sequence'], name='fisc_debit_prev_source_idx')],
                'constraints': [models.UniqueConstraint(fields=('basis', 'revision'), name='fisc_debit_prev_revision_uniq'), models.CheckConstraint(condition=models.Q(('product_quantity__gt', 0)), name='fisc_debit_prev_qty_positive'), models.CheckConstraint(condition=models.Q(('product_unit_price__gt', 0)), name='fisc_debit_prev_unit_positive'), models.CheckConstraint(condition=models.Q(('product_total_amount__gt', 0)), name='fisc_debit_prev_total_positive')],
            },
        ),
    ]
