# Generated by Django 6.0 on 2026-06-22 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_logincode_unused_fields'),
        ('finance', '0057_fiscaldebitproductpreview'),
        ('workshops', '0023_workshopcostholiday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fiscaldocument',
            options={'permissions': [('issue_nfe_return', 'Pode emitir NF-e de devolucao'), ('issue_nfe_reversal', 'Pode emitir NF-e de estorno'), ('download_nfe_return', 'Pode baixar XML/DANFE de NF-e de devolucao ou estorno'), ('issue_nfe_complementary_price_quantity', 'Pode emitir NF-e complementar de preco/quantidade'), ('view_nfe_complementary', 'Pode visualizar NF-e complementar'), ('download_nfe_complementary', 'Pode baixar XML/DANFE de NF-e complementar'), ('view_nfe_complementary_payload', 'Pode visualizar payload de NF-e complementar'), ('issue_nfe_adjustment', 'Pode emitir NF-e de ajuste'), ('view_nfe_adjustment', 'Pode visualizar NF-e de ajuste'), ('download_nfe_adjustment', 'Pode baixar XML/DANFE de NF-e de ajuste'), ('view_nfe_adjustment_payload', 'Pode visualizar payload de NF-e de ajuste'), ('issue_nfce', 'Pode emitir NFC-e'), ('view_nfce', 'Pode visualizar NFC-e'), ('download_nfce', 'Pode baixar XML/DANFE de NFC-e'), ('view_nfce_payload', 'Pode visualizar payload de NFC-e'), ('cancel_nfce', 'Pode cancelar NFC-e'), ('issue_nfe_credit', 'Pode emitir NF-e de credito'), ('view_nfe_credit', 'Pode visualizar NF-e de credito'), ('download_nfe_credit', 'Pode baixar XML/DANFE de NF-e de credito'), ('view_nfe_credit_payload', 'Pode visualizar payload de NF-e de credito'), ('cancel_nfe_credit', 'Pode cancelar NF-e de credito'), ('issue_nfe_debit', 'Pode emitir NF-e de debito'), ('view_nfe_debit', 'Pode visualizar NF-e de debito'), ('download_nfe_debit', 'Pode baixar XML/DANFE de NF-e de debito'), ('view_nfe_debit_payload', 'Pode visualizar payload de NF-e de debito')]},
        ),
        migrations.AddField(
            model_name='fiscaldocument',
            name='debit_product_preview',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debit_document', to='finance.fiscaldebitproductpreview', verbose_name='Previa fiscal de debito'),
        ),
        migrations.AddField(
            model_name='webmaniacompany',
            name='nfe_debit_emission_enabled',
            field=models.BooleanField(default=False, verbose_name='Emissao NF-e de debito habilitada'),
        ),
        migrations.AddField(
            model_name='webmaniacompany',
            name='nfe_debit_emission_enabled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Emissao NF-e de debito habilitada em'),
        ),
        migrations.AddField(
            model_name='webmaniacompany',
            name='nfe_debit_emission_enabled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enabled_nfe_debit_emission_companies', to=settings.AUTH_USER_MODEL, verbose_name='Emissao NF-e de debito habilitada por'),
        ),
        migrations.AlterField(
            model_name='fiscaldocument',
            name='purpose',
            field=models.CharField(choices=[('normal', 'Normal'), ('return', 'Devolucao'), ('reversal', 'Estorno'), ('complementary', 'Complementar'), ('adjustment', 'Ajuste'), ('credit', 'Credito'), ('debit', 'Debito')], db_index=True, default='normal', max_length=24),
        ),
        migrations.AlterField(
            model_name='fiscaldocumentlink',
            name='role',
            field=models.CharField(choices=[('returns', 'Devolve'), ('reverses', 'Estorna'), ('complements', 'Complementa'), ('adjusts', 'Ajusta'), ('credits', 'Credita'), ('debits', 'Debita')], db_index=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='fiscalemissionattempt',
            name='operation_type',
            field=models.CharField(choices=[('emission', 'Emissao'), ('cce', 'Carta de correcao'), ('return', 'Devolucao'), ('reversal', 'Estorno'), ('complementary_price_quantity', 'Complementar preco/quantidade'), ('adjustment', 'Ajuste'), ('nfce_emission', 'Emissao NFC-e'), ('nfce_cancellation', 'Cancelamento NFC-e'), ('nfce_inutilization', 'Inutilizacao NFC-e'), ('nfe_ibs_cbs_event', 'Evento IBS/CBS'), ('nfe_ibs_cbs_event_cancellation', 'Cancelamento de evento IBS/CBS'), ('nfe_credit_emission', 'Emissao NF-e de credito'), ('nfe_credit_cancellation', 'Cancelamento NF-e de credito'), ('nfe_debit_emission', 'Emissao NF-e de debito')], db_index=True, default='emission', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='fiscaldocument',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('purpose', 'debit'), _negated=True), models.Q(('debit_product_preview__isnull', False), ('fiscal_purpose_type', '4'), ('origin', 'derived'), ('referenced_basis__isnull', False)), _connector='OR'), name='fiscal_debit_document_requires_basis_preview'),
        ),
    ]
