# Generated by Django 6.0 on 2026-06-23 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0059_alter_fiscaldocument_options_and_more'),
        ('workshops', '0023_workshopcostholiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfsebatch',
            name='remote_updated_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Atualizacao remota canonica'),
        ),
        migrations.AddField(
            model_name='nfseitem',
            name='remote_updated_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Atualizacao remota canonica'),
        ),
        migrations.AddField(
            model_name='webmaniacompany',
            name='nfse_legacy_compatibility_enabled',
            field=models.BooleanField(default=True, verbose_name='Compatibilidade legada NFS-e habilitada'),
        ),
        migrations.CreateModel(
            name='NfseMunicipalCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('city_code', models.CharField(max_length=7, verbose_name='Codigo IBGE do municipio')),
                ('city_name', models.CharField(max_length=120, verbose_name='Municipio')),
                ('state', models.CharField(max_length=2, verbose_name='UF')),
                ('provider', models.CharField(blank=True, default='', max_length=80, verbose_name='Provedor/modelo')),
                ('provider_version', models.CharField(blank=True, default='', max_length=40, verbose_name='Versao do provedor')),
                ('is_active', models.BooleanField(default=True, verbose_name='Capacidade ativa')),
                ('national_standard_enabled', models.BooleanField(default=False, verbose_name='Padrao Nacional')),
                ('legacy_municipal_enabled', models.BooleanField(default=True, verbose_name='Padrao municipal legado')),
                ('emission_enabled', models.BooleanField(default=False, verbose_name='Emissao habilitada')),
                ('query_enabled', models.BooleanField(default=True, verbose_name='Consulta habilitada')),
                ('cancellation_enabled', models.BooleanField(default=False, verbose_name='Cancelamento habilitado')),
                ('substitution_enabled', models.BooleanField(default=False, verbose_name='Substituicao habilitada')),
                ('manifestation_enabled', models.BooleanField(default=False, verbose_name='Manifestacao habilitada')),
                ('batch_required', models.BooleanField(default=False, verbose_name='Lote RPS obrigatorio')),
                ('rps_required', models.BooleanField(default=True, verbose_name='RPS obrigatorio')),
                ('synchronous_emission', models.BooleanField(default=False, verbose_name='Emissao sincrona')),
                ('xml_download_enabled', models.BooleanField(default=True, verbose_name='Download XML disponivel')),
                ('pdf_download_enabled', models.BooleanField(default=True, verbose_name='Download PDF NFS-e disponivel')),
                ('rps_pdf_enabled', models.BooleanField(default=True, verbose_name='Download PDF RPS disponivel')),
                ('requires_municipal_registration', models.BooleanField(default=False, verbose_name='Exige inscricao municipal')),
                ('requires_service_code', models.BooleanField(default=False, verbose_name='Exige codigo de servico')),
                ('requires_cnae', models.BooleanField(default=False, verbose_name='Exige CNAE')),
                ('requires_iss_rate', models.BooleanField(default=False, verbose_name='Exige aliquota ISS')),
                ('remote_payload', models.JSONField(blank=True, default=dict, verbose_name='Payload remoto sanitizado')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Ultima sincronizacao')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observacoes')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nfse_municipal_capabilities', to='finance.webmaniacompany', verbose_name='Empresa Webmania')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfse_municipal_capabilities', to='workshops.workshop', verbose_name='Oficina')),
            ],
            options={
                'permissions': [('manage_nfse_capabilities', 'Pode gerenciar capacidades municipais NFS-e')],
                'abstract': False,
                'indexes': [models.Index(fields=['workshop', 'city_code', 'is_active'], name='nfse_cap_workshop_city_idx'), models.Index(fields=['company', 'state', 'city_name'], name='nfse_cap_company_city_idx')],
                'constraints': [models.UniqueConstraint(fields=('workshop', 'company', 'city_code'), name='unique_nfse_capability_scope')],
            },
        ),
    ]
