# Generated by Django 5.2.9 on 2026-08-25 23:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_service_shipping_service_shipping_currency'),
        ('finance', '0059_purchase_return_fiscal_order_fields'),
        ('workorder', '0046_leftover_courtesy_reason_default'),
        ('workshops', '0044_outbound_business_weekdays_all_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandaloneNfeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('product_code', models.CharField(max_length=120, verbose_name='Código')),
                ('ncm', models.CharField(max_length=10, verbose_name='NCM')),
                ('cest', models.CharField(blank=True, default='', max_length=10, verbose_name='CEST')),
                ('unit', models.CharField(default='UN', max_length=12, verbose_name='Unidade')),
                ('origin', models.PositiveSmallIntegerField(default=0, verbose_name='Origem tributária')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Quantidade')),
                ('unit_value', models.DecimalField(decimal_places=4, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valor unitário')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Linha avulsa de NF-e',
                'verbose_name_plural': 'Linhas avulsas de NF-e',
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StandaloneNfseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Quantidade')),
                ('unit_value', models.DecimalField(decimal_places=4, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valor unitário')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Linha avulsa de NFS-e',
                'verbose_name_plural': 'Linhas avulsas de NFS-e',
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
        migrations.RemoveConstraint(
            model_name='nfeitem',
            name='unique_nfe_item_per_workorder',
        ),
        migrations.RemoveConstraint(
            model_name='nfsebatch',
            name='unique_nfse_batch_per_workorder',
        ),
        migrations.RemoveConstraint(
            model_name='nfseitem',
            name='unique_nfse_item_per_workorder',
        ),
        migrations.AddField(
            model_name='nferequest',
            name='recipient_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Nome do destinatário'),
        ),
        migrations.AddField(
            model_name='nferequest',
            name='recipient_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='Snapshot do destinatário'),
        ),
        migrations.AddField(
            model_name='nfserequest',
            name='recipient_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Nome do destinatário'),
        ),
        migrations.AddField(
            model_name='nfserequest',
            name='recipient_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='Snapshot do destinatário'),
        ),
        migrations.AlterField(
            model_name='nfeitem',
            name='workorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workorder.workorder', verbose_name='Ordem de Serviço'),
        ),
        migrations.AlterField(
            model_name='nferequest',
            name='workorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workorder.workorder', verbose_name='Ordem de Serviço'),
        ),
        migrations.AlterField(
            model_name='nfsebatch',
            name='workorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workorder.workorder', verbose_name='Ordem de Serviço'),
        ),
        migrations.AlterField(
            model_name='nfseitem',
            name='workorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workorder.workorder', verbose_name='Ordem de Serviço'),
        ),
        migrations.AlterField(
            model_name='nfserequest',
            name='workorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workorder.workorder', verbose_name='Ordem de Serviço'),
        ),
        migrations.AddConstraint(
            model_name='nfeitem',
            constraint=models.UniqueConstraint(fields=('uuid',), name='unique_nfe_item_uuid'),
        ),
        migrations.AddConstraint(
            model_name='nfsebatch',
            constraint=models.UniqueConstraint(fields=('uuid',), name='unique_nfse_batch_uuid'),
        ),
        migrations.AddConstraint(
            model_name='nfseitem',
            constraint=models.UniqueConstraint(fields=('uuid',), name='unique_nfse_item_uuid'),
        ),
        migrations.AddField(
            model_name='standalonenfeline',
            name='nfe_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standalone_lines', to='finance.nferequest', verbose_name='Requisição NF-e'),
        ),
        migrations.AddField(
            model_name='standalonenfeline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standalone_nfe_lines', to='catalog.product', verbose_name='Produto'),
        ),
        migrations.AddField(
            model_name='standalonenfseline',
            name='nfse_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standalone_lines', to='finance.nfserequest', verbose_name='Requisição NFS-e'),
        ),
        migrations.AddField(
            model_name='standalonenfseline',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standalone_nfse_lines', to='catalog.service', verbose_name='Serviço'),
        ),
    ]
