# Generated by Django 6.0 on 2026-06-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0060_nfsebatch_remote_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nfsemunicipalcapability',
            options={'permissions': [('manage_nfse_capabilities', 'Pode gerenciar capacidades municipais NFS-e'), ('query_nfse_status', 'Pode consultar status municipal NFS-e')]},
        ),
        migrations.AlterModelOptions(
            name='nfserequest',
            options={'permissions': [('query_nfse', 'Pode consultar NFS-e por UUID'), ('query_nfse_batch', 'Pode consultar lote RPS por UUID')]},
        ),
        migrations.AddField(
            model_name='nfsebatch',
            name='last_reconciled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ultima consulta'),
        ),
        migrations.AddField(
            model_name='nfsebatch',
            name='last_update_source',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Origem da ultima atualizacao'),
        ),
        migrations.AddField(
            model_name='nfseitem',
            name='last_update_source',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Origem da ultima atualizacao'),
        ),
        migrations.AddField(
            model_name='nfsemunicipalcapability',
            name='last_status_error',
            field=models.TextField(blank=True, default='', verbose_name='Ultimo erro de consulta'),
        ),
        migrations.AddField(
            model_name='nfsemunicipalcapability',
            name='remote_status',
            field=models.BooleanField(blank=True, null=True, verbose_name='Status remoto do municipio'),
        ),
    ]
