# Generated by Django 6.0 on 2026-06-23 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0061_alter_nfsemunicipalcapability_options_and_more'),
        ('workshops', '0023_workshopcostholiday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nfserequest',
            options={'permissions': [('query_nfse', 'Pode consultar NFS-e por UUID'), ('query_nfse_batch', 'Pode consultar lote RPS por UUID'), ('cancel_nfse', 'Pode cancelar NFS-e')]},
        ),
        migrations.AlterField(
            model_name='fiscalemissionattempt',
            name='operation_type',
            field=models.CharField(choices=[('emission', 'Emissao'), ('cce', 'Carta de correcao'), ('return', 'Devolucao'), ('reversal', 'Estorno'), ('complementary_price_quantity', 'Complementar preco/quantidade'), ('adjustment', 'Ajuste'), ('nfce_emission', 'Emissao NFC-e'), ('nfce_cancellation', 'Cancelamento NFC-e'), ('nfce_inutilization', 'Inutilizacao NFC-e'), ('nfe_ibs_cbs_event', 'Evento IBS/CBS'), ('nfe_ibs_cbs_event_cancellation', 'Cancelamento de evento IBS/CBS'), ('nfe_credit_emission', 'Emissao NF-e de credito'), ('nfe_credit_cancellation', 'Cancelamento NF-e de credito'), ('nfe_debit_emission', 'Emissao NF-e de debito'), ('nfe_debit_cancellation', 'Cancelamento NF-e de debito'), ('nfse_cancellation', 'Cancelamento NFS-e')], db_index=True, default='emission', max_length=32),
        ),
        migrations.CreateModel(
            name='NfseCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('status', models.CharField(choices=[('started', 'Iniciada'), ('sent', 'Enviada'), ('succeeded', 'Concluida'), ('failed', 'Falhou'), ('uncertain', 'Incerta')], db_index=True, default='started', max_length=20)),
                ('reason_code', models.PositiveSmallIntegerField(verbose_name='Motivo')),
                ('reason_label', models.CharField(max_length=80)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('xml_url', models.URLField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cancellations', to='finance.nfseitem', verbose_name='NFS-e')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellations', to='finance.nfserequest', verbose_name='Requisicao NFS-e')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfse_cancellations', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfse_cancellations', to='workshops.workshop', verbose_name='Oficina')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['workshop', 'status'], name='nfse_cancel_scope_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['started', 'sent', 'succeeded', 'uncertain'])), fields=('item',), name='unique_active_nfse_cancellation')],
            },
        ),
    ]
