# Generated by Django 6.0 on 2026-08-27 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0062_merge_ticket240_discounts_and_homol"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fiscaldocument",
            options={
                "permissions": [
                    ("issue_nfe_return", "Pode emitir NF-e de devolução"),
                    ("issue_nfe_reversal", "Pode emitir NF-e de estorno"),
                    (
                        "download_nfe_return",
                        "Pode baixar XML/DANFE de NF-e de devolução ou estorno",
                    ),
                ],
                "verbose_name": "Documento fiscal",
                "verbose_name_plural": "Documentos fiscais",
            },
        ),
        migrations.AlterModelOptions(
            name="fiscaldocumentevent",
            options={
                "permissions": [
                    ("issue_nfe_correction", "Pode emitir carta de correção NF-e"),
                    (
                        "download_nfe_correction",
                        "Pode baixar XML/DACCE de carta de correção NF-e",
                    ),
                ],
                "verbose_name": "Evento fiscal",
                "verbose_name_plural": "Eventos fiscais",
            },
        ),
    ]
