# Generated by Django 6.0 on 2026-06-23 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0062_alter_nfserequest_options_and_more'),
        ('workshops', '0023_workshopcostholiday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='webmaniacompany',
            name='nfse_substitution_preview_enabled',
            field=models.BooleanField(default=False, verbose_name='Preview de substituicao NFS-e habilitada'),
        ),
        migrations.CreateModel(
            name='NfseSubstitutionPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('original_uuid', models.UUIDField(db_index=True, verbose_name='UUID original')),
                ('original_verification_code', models.CharField(max_length=60, verbose_name='Codigo de verificacao original')),
                ('original_xml_snapshot', models.JSONField(default=dict, verbose_name='Snapshot do XML original')),
                ('environment', models.CharField(choices=[('1', 'Producao'), ('2', 'Homologacao')], max_length=1, verbose_name='Ambiente')),
                ('reason_code', models.PositiveSmallIntegerField(choices=[(1, 'Erro na emissao'), (2, 'Servico nao prestado'), (4, 'Duplicidade da nota')], verbose_name='Motivo')),
                ('rps_payload', models.JSONField(default=dict, verbose_name='Novo RPS congelado')),
                ('request_payload', models.JSONField(default=dict, verbose_name='Pre-payload de substituicao')),
                ('validation_status', models.CharField(choices=[('draft', 'Rascunho'), ('validated', 'Validada'), ('approved', 'Aprovada'), ('invalid', 'Invalida')], db_index=True, default='draft', max_length=16, verbose_name='Status')),
                ('validation_errors', models.JSONField(blank=True, default=list, verbose_name='Erros de validacao')),
                ('forbidden_fields_detected', models.JSONField(blank=True, default=list, verbose_name='Campos proibidos detectados')),
                ('is_approved', models.BooleanField(db_index=True, default=False, verbose_name='Aprovada')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Aprovada em')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_nfse_substitution_previews', to=settings.AUTH_USER_MODEL, verbose_name='Aprovada por')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_nfse_substitution_previews', to=settings.AUTH_USER_MODEL, verbose_name='Criada por')),
                ('original_nfse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='substitution_previews', to='finance.nfseitem', verbose_name='NFS-e original')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfse_substitution_previews', to='workshops.workshop', verbose_name='Oficina')),
            ],
            options={
                'permissions': [('prepare_nfse_substitution', 'Pode preparar substituicao NFS-e'), ('approve_nfse_substitution', 'Pode aprovar substituicao NFS-e'), ('view_nfse_substitution_preview', 'Pode visualizar preview de substituicao NFS-e'), ('view_nfse_substitution_preview_payload', 'Pode visualizar payload da preview de substituicao NFS-e')],
                'abstract': False,
                'indexes': [models.Index(fields=['workshop', 'validation_status'], name='nfse_subst_prev_scope_idx'), models.Index(fields=['original_nfse', 'is_approved'], name='nfse_subst_prev_orig_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_approved', True)), fields=('original_nfse',), name='unique_approved_nfse_subst_preview')],
            },
        ),
    ]
