# Generated by Django 6.0 on 2026-06-24 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0063_webmaniacompany_nfse_substitution_preview_enabled_and_more'),
        ('workshops', '0023_workshopcostholiday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalemissionattempt',
            name='operation_type',
            field=models.CharField(choices=[('emission', 'Emissao'), ('cce', 'Carta de correcao'), ('return', 'Devolucao'), ('reversal', 'Estorno'), ('complementary_price_quantity', 'Complementar preco/quantidade'), ('adjustment', 'Ajuste'), ('nfce_emission', 'Emissao NFC-e'), ('nfce_cancellation', 'Cancelamento NFC-e'), ('nfce_inutilization', 'Inutilizacao NFC-e'), ('nfe_ibs_cbs_event', 'Evento IBS/CBS'), ('nfe_ibs_cbs_event_cancellation', 'Cancelamento de evento IBS/CBS'), ('nfe_credit_emission', 'Emissao NF-e de credito'), ('nfe_credit_cancellation', 'Cancelamento NF-e de credito'), ('nfe_debit_emission', 'Emissao NF-e de debito'), ('nfe_debit_cancellation', 'Cancelamento NF-e de debito'), ('nfse_cancellation', 'Cancelamento NFS-e'), ('nfse_substitution', 'Substituicao NFS-e')], db_index=True, default='emission', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfseitem',
            name='status',
            field=models.CharField(choices=[('processando', 'Processando'), ('aprovado', 'Aprovado'), ('agendado', 'Agendado'), ('reprovado', 'Reprovado'), ('cancelado', 'Cancelado'), ('contingencia', 'Contingencia'), ('substituido', 'Substituido')], default='processando', max_length=20),
        ),
        migrations.CreateModel(
            name='NfseSubstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('uuid_original', models.UUIDField(db_index=True, verbose_name='UUID original')),
                ('uuid_replacement', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='UUID substituta')),
                ('original_verification_code', models.CharField(max_length=60, verbose_name='Codigo de verificacao original')),
                ('reason_code', models.PositiveSmallIntegerField(verbose_name='Motivo')),
                ('request_payload', models.JSONField(default=dict, verbose_name='Payload enviado')),
                ('response_payload', models.JSONField(blank=True, default=dict, verbose_name='Resposta remota')),
                ('original_xml_snapshot', models.JSONField(default=dict, verbose_name='Snapshot XML original')),
                ('replacement_xml_url', models.URLField(blank=True, default='', verbose_name='XML substituta')),
                ('replacement_pdf_url', models.URLField(blank=True, default='', verbose_name='PDF substituta')),
                ('status', models.CharField(choices=[('started', 'Iniciada'), ('sent', 'Enviada'), ('succeeded', 'Concluida'), ('failed', 'Falhou'), ('uncertain', 'Incerta')], db_index=True, default='started', max_length=20)),
                ('is_uncertain', models.BooleanField(db_index=True, default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('original_nfse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_substitutions', to='finance.nfseitem', verbose_name='NFS-e original')),
                ('preview', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='substitution', to='finance.nfsesubstitutionpreview', verbose_name='Preview aprovada')),
                ('replacement_nfse', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_substitution', to='finance.nfseitem', verbose_name='NFS-e substituta')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfse_substitutions', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfse_substitutions', to='workshops.workshop', verbose_name='Oficina')),
            ],
            options={
                'permissions': [('substitute_nfse', 'Pode substituir NFS-e'), ('view_nfse_substitution_payload', 'Pode visualizar payload da substituicao NFS-e'), ('download_nfse_substitution', 'Pode baixar documentos da substituicao NFS-e')],
                'abstract': False,
                'indexes': [models.Index(fields=['workshop', 'status'], name='nfse_subst_scope_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['started', 'sent', 'succeeded', 'uncertain'])), fields=('original_nfse',), name='unique_active_nfse_substitution')],
            },
        ),
    ]
