# Generated by Django 6.0 on 2026-08-28 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0062_merge_ticket240_discounts_and_homol'),
        ('finance', '0064_financial_movement_installment_plan'),
    ]

    operations = [
    ]
