# Generated by Django 6.0 on 2026-08-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0065_merge_20260828_1017"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE finance_financialmovement "
                        "ADD COLUMN IF NOT EXISTS partial_payment_of_id bigint "
                        "NULL REFERENCES finance_financialmovement(id) ON DELETE SET NULL;"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="financialmovement",
                    name="partial_payment_of",
                    field=models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name="partial_payment_balances", to="finance.financialmovement", verbose_name="Pagamento parcial de"),
                ),
            ],
        ),
    ]
