# Generated by Django 5.2.9 on 2026-06-28 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0065_nfsemanifestation_and_operation_type'),
        ('workshops', '0023_workshopcostholiday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nfsemunicipalcapability',
            name='manual_emission_enabled',
            field=models.BooleanField(default=False, verbose_name='Emissao manual habilitada'),
        ),
        migrations.AddField(
            model_name='webmaniacompany',
            name='nfse_manual_emission_preview_enabled',
            field=models.BooleanField(default=False, verbose_name='Preview de emissao manual NFS-e habilitada'),
        ),
        migrations.CreateModel(
            name='NfseManualEmissionPreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('environment', models.CharField(choices=[('1', 'Producao'), ('2', 'Homologacao')], max_length=1, verbose_name='Ambiente')),
                ('rps_number', models.PositiveIntegerField(verbose_name='Numero RPS')),
                ('rps_series', models.CharField(max_length=20, verbose_name='Serie RPS')),
                ('rps_payload', models.JSONField(default=dict, verbose_name='RPS congelado')),
                ('request_payload', models.JSONField(default=dict, verbose_name='Payload planejado')),
                ('taker_snapshot', models.JSONField(default=dict, verbose_name='Snapshot do tomador')),
                ('service_snapshot', models.JSONField(default=dict, verbose_name='Snapshot do servico')),
                ('values_snapshot', models.JSONField(default=dict, verbose_name='Snapshot de valores')),
                ('taxation_snapshot', models.JSONField(default=dict, verbose_name='Snapshot de tributacao')),
                ('retention_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Snapshot de retencoes')),
                ('ibs_cbs_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Snapshot IBS/CBS')),
                ('validation_status', models.CharField(choices=[('draft', 'Rascunho'), ('validated', 'Validada'), ('approved', 'Aprovada'), ('invalid', 'Invalida')], db_index=True, default='draft', max_length=16, verbose_name='Status')),
                ('validation_errors', models.JSONField(blank=True, default=list, verbose_name='Erros de validacao')),
                ('forbidden_fields_detected', models.JSONField(blank=True, default=list, verbose_name='Campos proibidos detectados')),
                ('is_approved', models.BooleanField(db_index=True, default=False, verbose_name='Aprovada')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Aprovada em')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_nfse_manual_emission_previews', to=settings.AUTH_USER_MODEL, verbose_name='Aprovada por')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nfse_manual_emission_previews', to='finance.webmaniacompany', verbose_name='Empresa Webmania')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_nfse_manual_emission_previews', to=settings.AUTH_USER_MODEL, verbose_name='Criada por')),
                ('municipal_capability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_emission_previews', to='finance.nfsemunicipalcapability', verbose_name='Capacidade municipal')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfse_manual_emission_previews', to='workshops.workshop', verbose_name='Oficina')),
            ],
            options={
                'permissions': [('prepare_nfse_manual_emission_preview', 'Pode preparar preview de emissao manual NFS-e'), ('approve_nfse_manual_emission_preview', 'Pode aprovar preview de emissao manual NFS-e'), ('view_nfse_manual_emission_preview', 'Pode visualizar preview de emissao manual NFS-e'), ('view_nfse_manual_emission_preview_payload', 'Pode visualizar payload da preview de emissao manual NFS-e')],
                'abstract': False,
                'indexes': [models.Index(fields=['workshop', 'validation_status'], name='nfse_manual_prev_scope_idx'), models.Index(fields=['company', 'environment', 'rps_number', 'rps_series'], name='nfse_manual_prev_rps_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_approved', True)), fields=('company', 'environment', 'rps_number', 'rps_series'), name='unique_approved_nfse_manual_rps')],
            },
        ),
    ]
