# Generated by Django 6.0 on 2026-08-28 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0063_alter_fiscaldocument_options_and_more"),
        ("finance", "0066_financialmovement_partial_payment_of"),
    ]

    operations = []
