# Generated by Django 5.2.9 on 2026-06-28 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0066_nfsemunicipalcapability_manual_emission_enabled_and_more'),
        ('workorder', '0025_backfill_workorder_budget_type'),
        ('workshops', '0023_workshopcostholiday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='webmaniacompany',
            name='nfse_manual_emission_enabled',
            field=models.BooleanField(default=False, verbose_name='Emissao manual NFS-e habilitada'),
        ),
        migrations.AlterField(
            model_name='fiscalemissionattempt',
            name='operation_type',
            field=models.CharField(choices=[('emission', 'Emissao'), ('cce', 'Carta de correcao'), ('return', 'Devolucao'), ('reversal', 'Estorno'), ('complementary_price_quantity', 'Complementar preco/quantidade'), ('adjustment', 'Ajuste'), ('nfce_emission', 'Emissao NFC-e'), ('nfce_cancellation', 'Cancelamento NFC-e'), ('nfce_inutilization', 'Inutilizacao NFC-e'), ('nfe_ibs_cbs_event', 'Evento IBS/CBS'), ('nfe_ibs_cbs_event_cancellation', 'Cancelamento de evento IBS/CBS'), ('nfe_credit_emission', 'Emissao NF-e de credito'), ('nfe_credit_cancellation', 'Cancelamento NF-e de credito'), ('nfe_debit_emission', 'Emissao NF-e de debito'), ('nfe_debit_cancellation', 'Cancelamento NF-e de debito'), ('nfse_cancellation', 'Cancelamento NFS-e'), ('nfse_substitution', 'Substituicao NFS-e'), ('nfse_manifestation', 'Manifestacao NFS-e'), ('nfse_manual_emission', 'Emissao manual NFS-e')], db_index=True, default='emission', max_length=32),
        ),
        migrations.AlterField(
            model_name='nfseitem',
            name='workorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workorder.workorder', verbose_name='Ordem de Serviço'),
        ),
        migrations.CreateModel(
            name='NfseManualEmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('environment', models.CharField(choices=[('1', 'Producao'), ('2', 'Homologacao')], max_length=1, verbose_name='Ambiente')),
                ('rps_number', models.PositiveIntegerField(verbose_name='Numero RPS')),
                ('rps_series', models.CharField(max_length=20, verbose_name='Serie RPS')),
                ('request_payload', models.JSONField(default=dict, verbose_name='Payload enviado')),
                ('response_payload', models.JSONField(blank=True, default=dict, verbose_name='Resposta remota')),
                ('remote_uuid', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='UUID remoto')),
                ('verification_code', models.CharField(blank=True, default='', max_length=60, verbose_name='Codigo de verificacao')),
                ('xml_nfse', models.URLField(blank=True, default='', verbose_name='XML NFS-e')),
                ('danfse_pdf', models.URLField(blank=True, default='', verbose_name='DANFSE/PDF')),
                ('status', models.CharField(choices=[('started', 'Iniciada'), ('sent', 'Enviada'), ('succeeded', 'Concluida'), ('failed', 'Falhou'), ('uncertain', 'Incerta')], db_index=True, default='started', max_length=20)),
                ('is_uncertain', models.BooleanField(db_index=True, default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nfse_manual_emissions', to='finance.webmaniacompany', verbose_name='Empresa Webmania')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfse_manual_emissions', to=settings.AUTH_USER_MODEL, verbose_name='Criada por')),
                ('nfse_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manual_emission', to='finance.nfseitem', verbose_name='NFS-e emitida')),
                ('preview', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='manual_emission', to='finance.nfsemanualemissionpreview', verbose_name='Preview aprovada')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfse_manual_emissions', to='workshops.workshop', verbose_name='Oficina')),
            ],
            options={
                'permissions': [('issue_nfse_manual_emission', 'Pode emitir NFS-e manual'), ('view_nfse_manual_emission', 'Pode visualizar emissao manual NFS-e'), ('download_nfse_manual_emission', 'Pode baixar documentos da emissao manual NFS-e'), ('view_nfse_manual_emission_payload', 'Pode visualizar payload da emissao manual NFS-e')],
                'abstract': False,
                'indexes': [models.Index(fields=['workshop', 'status'], name='nfse_manual_emit_scope_idx'), models.Index(fields=['company', 'environment', 'rps_number', 'rps_series'], name='nfse_manual_emit_rps_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['started', 'sent', 'succeeded', 'uncertain'])), fields=('company', 'environment', 'rps_number', 'rps_series'), name='unique_active_nfse_manual_rps')],
            },
        ),
    ]
