# Generated by Django 5.2.9 on 2026-06-28 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0067_webmaniacompany_nfse_manual_emission_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfsecancellation',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cancellations', to='finance.nfserequest', verbose_name='Requisicao NFS-e'),
        ),
    ]
