# Generated by Django 6.0 on 2026-09-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0068_purchase_return_supplier_ie"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="financialmovement",
            index=models.Index(
                fields=["workshop", "amount"], name="fin_mov_ws_amt_idx"
            ),
        ),
    ]