# Generated by Django 5.2.9 on 2026-06-29 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0068_alter_nfsecancellation_request'),
        ('workshops', '0023_workshopcostholiday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='webmaniacompany',
            name='nfse_received_import_enabled',
            field=models.BooleanField(default=False, verbose_name='Importacao de NFS-e recebida habilitada'),
        ),
        migrations.CreateModel(
            name='NfseReceivedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('source', models.CharField(choices=[('xml_upload', 'Upload XML')], db_index=True, default='xml_upload', max_length=24, verbose_name='Origem')),
                ('xml_snapshot', models.TextField(verbose_name='XML original')),
                ('xml_hash', models.CharField(db_index=True, max_length=64, verbose_name='Hash do XML')),
                ('uuid', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='UUID remoto')),
                ('access_key_or_identifier', models.CharField(blank=True, db_index=True, default='', max_length=80, verbose_name='Chave/identificador')),
                ('verification_code', models.CharField(blank=True, default='', max_length=80, verbose_name='Codigo de verificacao')),
                ('provider_tax_id', models.CharField(blank=True, db_index=True, default='', max_length=14, verbose_name='CPF/CNPJ prestador')),
                ('taker_tax_id', models.CharField(blank=True, db_index=True, default='', max_length=14, verbose_name='CPF/CNPJ tomador')),
                ('intermediary_tax_id', models.CharField(blank=True, db_index=True, default='', max_length=14, verbose_name='CPF/CNPJ intermediario')),
                ('municipality_code', models.CharField(blank=True, default='', max_length=20, verbose_name='Codigo municipio')),
                ('environment', models.CharField(blank=True, choices=[('', 'Nao informado'), ('1', 'Producao'), ('2', 'Homologacao')], default='', max_length=1, verbose_name='Ambiente')),
                ('issue_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de emissao')),
                ('service_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor do servico')),
                ('status', models.CharField(db_index=True, default='received', max_length=20, verbose_name='Status local')),
                ('remote_status', models.CharField(blank=True, default='', max_length=40, verbose_name='Status remoto')),
                ('role', models.CharField(choices=[('taker', 'Tomador'), ('intermediary', 'Intermediario'), ('provider', 'Prestador'), ('unknown', 'Desconhecido'), ('multiple', 'Multiplos papeis')], db_index=True, default='unknown', max_length=16, verbose_name='Papel da oficina')),
                ('validation_status', models.CharField(choices=[('draft', 'Rascunho'), ('validated', 'Validado'), ('rejected', 'Rejeitado')], db_index=True, default='draft', max_length=16, verbose_name='Status de validacao')),
                ('validation_errors', models.JSONField(blank=True, default=list, verbose_name='Erros de validacao')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='Payload parseado')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nfse_received_documents', to='finance.webmaniacompany', verbose_name='Empresa Webmania')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfse_received_documents', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfse_received_documents', to='workshops.workshop', verbose_name='Oficina')),
            ],
            options={
                'permissions': [('import_nfse_received', 'Pode importar NFS-e recebida'), ('view_nfse_received', 'Pode visualizar NFS-e recebida'), ('view_nfse_received_payload', 'Pode visualizar payload da NFS-e recebida'), ('download_nfse_received_xml', 'Pode baixar XML da NFS-e recebida')],
                'abstract': False,
                'indexes': [models.Index(fields=['workshop', 'validation_status'], name='nfse_received_scope_status_idx'), models.Index(fields=['workshop', 'role'], name='nfse_received_scope_role_idx')],
                'constraints': [models.UniqueConstraint(fields=('workshop', 'xml_hash'), name='unique_nfse_received_xml_hash_workshop'), models.UniqueConstraint(condition=models.Q(('uuid', ''), _negated=True), fields=('workshop', 'uuid'), name='unique_nfse_received_uuid_workshop'), models.UniqueConstraint(condition=models.Q(('access_key_or_identifier', ''), _negated=True), fields=('workshop', 'access_key_or_identifier'), name='unique_nfse_received_identifier_workshop')],
            },
        ),
    ]
