# Generated by Django 6.0 on 2026-09-04 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0067_repair_webmania_webhook_fingerprint_column'),
        ('finance', '0068_financialtransfer_reversal'),
    ]

    operations = [
    ]
