# Generated by Django 5.2.9 on 2026-06-29 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0069_webmaniacompany_nfse_received_import_enabled_and_more'),
        ('workshops', '0023_workshopcostholiday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='nfsemanifestation',
            name='unique_active_nfse_manifestation',
        ),
        migrations.AddField(
            model_name='nfsemanifestation',
            name='received_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manifestations', to='finance.nfsereceiveddocument', verbose_name='NFS-e recebida'),
        ),
        migrations.AlterField(
            model_name='nfsemanifestation',
            name='nfse_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manifestations', to='finance.nfseitem', verbose_name='NFS-e'),
        ),
        migrations.AddIndex(
            model_name='nfsemanifestation',
            index=models.Index(fields=['received_document', 'manifestation_code', 'manifestor'], name='nfse_man_recv_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='nfsemanifestation',
            constraint=models.UniqueConstraint(condition=models.Q(('nfse_item__isnull', False), ('status__in', ['started', 'sent', 'succeeded', 'uncertain'])), fields=('nfse_item', 'manifestation_code', 'manifestor'), name='unique_active_nfse_manifestation'),
        ),
        migrations.AddConstraint(
            model_name='nfsemanifestation',
            constraint=models.UniqueConstraint(condition=models.Q(('received_document__isnull', False), ('status__in', ['started', 'sent', 'succeeded', 'uncertain'])), fields=('received_document', 'manifestation_code', 'manifestor'), name='uniq_active_nfse_recv_man'),
        ),
        migrations.AddConstraint(
            model_name='nfsemanifestation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('nfse_item__isnull', False), ('received_document__isnull', True)), models.Q(('nfse_item__isnull', True), ('received_document__isnull', False)), _connector='OR'), name='nfse_manifest_single_origin'),
        ),
    ]
