# Generated by Django 6.0 on 2026-09-22 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0068_financialtransfer_reversal"),
        ("finance", "0070_nfserequest_consumidor_final"),
    ]

    operations = []
