# Generated by Django 5.2.9 on 2026-06-29 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0070_remove_nfsemanifestation_unique_active_nfse_manifestation_and_more'),
        ('workshops', '0023_workshopcostholiday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='webmaniacompany',
            name='nfse_received_consultation_enabled',
            field=models.BooleanField(default=False, verbose_name='Consulta de NFS-e recebida habilitada'),
        ),
        migrations.CreateModel(
            name='NfseReceivedDocumentConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('identifier', models.CharField(db_index=True, max_length=120, verbose_name='Identificador consultado')),
                ('identifier_source', models.CharField(max_length=32, verbose_name='Origem do identificador')),
                ('request_metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados da consulta')),
                ('response_payload', models.JSONField(blank=True, default=dict, verbose_name='Resposta sanitizada')),
                ('remote_status', models.CharField(blank=True, default='', max_length=60, verbose_name='Status remoto consultado')),
                ('remote_uuid', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='UUID remoto consultado')),
                ('remote_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Atualizacao remota consultada')),
                ('national_standard_confirmed', models.BooleanField(blank=True, null=True, verbose_name='Padrao Nacional confirmado pela consulta')),
                ('divergences', models.JSONField(blank=True, default=list, verbose_name='Divergencias consultivas')),
                ('validation_errors', models.JSONField(blank=True, default=list, verbose_name='Erros da consulta')),
                ('consulted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfse_received_consultations', to=settings.AUTH_USER_MODEL, verbose_name='Consultado por')),
                ('received_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='finance.nfsereceiveddocument', verbose_name='NFS-e recebida')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfse_received_consultations', to='workshops.workshop', verbose_name='Oficina')),
            ],
            options={
                'permissions': [('consult_nfse_received', 'Pode consultar NFS-e recebida na Webmania'), ('view_nfse_received_consultation', 'Pode visualizar consultas de NFS-e recebida'), ('view_nfse_received_consultation_payload', 'Pode visualizar payload de consulta de NFS-e recebida')],
                'abstract': False,
                'indexes': [models.Index(fields=['workshop', 'received_document', '-criado_em'], name='nfse_recv_cons_doc_time_idx'), models.Index(fields=['workshop', 'remote_uuid'], name='nfse_recv_cons_uuid_idx')],
            },
        ),
    ]
