# Generated by Django 6.0 on 2026-09-24 16:21

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0071_merge_20260922_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='nferequest',
            name='discount_value_override',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, help_text='Sobrescreve o valor do desconto da OS apenas para esta emissao. Vazio usa o da OS.', max_digits=14, null=True, verbose_name='Desconto (Emissao)'),
        ),
        migrations.AddField(
            model_name='nferequest',
            name='discount_value_override_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('BRL', 'Real Brasileiro')], default='BRL', editable=False, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='nfserequest',
            name='discount_value_override',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, help_text='Sobrescreve o valor do desconto da OS apenas para esta emissao. Vazio usa o da OS.', max_digits=14, null=True, verbose_name='Desconto (Emissao)'),
        ),
        migrations.AddField(
            model_name='nfserequest',
            name='discount_value_override_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('BRL', 'Real Brasileiro')], default='BRL', editable=False, max_length=3, null=True),
        ),
    ]
