# Generated by Django 5.2.9 on 2026-06-29 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0071_webmaniacompany_nfse_received_consultation_enabled_and_more'),
        ('workshops', '0023_workshopcostholiday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NfseReceivedImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('source', models.CharField(choices=[('xml_upload', 'Upload XML')], db_index=True, default='xml_upload', max_length=24, verbose_name='Origem')),
                ('status', models.CharField(choices=[('processing', 'Processando'), ('completed', 'Concluido'), ('completed_with_errors', 'Concluido com erros'), ('failed', 'Falhou')], db_index=True, default='processing', max_length=32, verbose_name='Status')),
                ('total_files', models.PositiveIntegerField(default=0, verbose_name='Total de arquivos')),
                ('success_count', models.PositiveIntegerField(default=0, verbose_name='Importados')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='Erros')),
                ('duplicate_count', models.PositiveIntegerField(default=0, verbose_name='Duplicados')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nfse_received_import_batches', to='finance.webmaniacompany', verbose_name='Empresa Webmania')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfse_received_import_batches', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfse_received_import_batches', to='workshops.workshop', verbose_name='Oficina')),
            ],
            options={
                'permissions': [('import_nfse_received_batch', 'Pode importar lote de XML de NFS-e recebida'), ('view_nfse_received_batch', 'Pode visualizar lote de NFS-e recebida')],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NfseReceivedImportBatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('filename', models.CharField(max_length=255, verbose_name='Arquivo')),
                ('xml_hash', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Hash do XML')),
                ('status', models.CharField(choices=[('imported', 'Importado'), ('rejected', 'Rejeitado'), ('duplicate', 'Duplicado'), ('invalid_xml', 'XML invalido'), ('invalid_tenant', 'Oficina/CNPJ invalido'), ('error', 'Erro')], db_index=True, max_length=24, verbose_name='Status')),
                ('error_code', models.CharField(blank=True, default='', max_length=40, verbose_name='Codigo do erro')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Mensagem do erro')),
                ('validation_errors', models.JSONField(blank=True, default=list, verbose_name='Erros de validacao')),
                ('raw_summary', models.JSONField(blank=True, default=dict, verbose_name='Resumo parseado')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.nfsereceivedimportbatch', verbose_name='Lote')),
                ('received_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_items', to='finance.nfsereceiveddocument', verbose_name='NFS-e recebida')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='nfsereceivedimportbatch',
            index=models.Index(fields=['workshop', '-criado_em'], name='nfse_recv_batch_time_idx'),
        ),
        migrations.AddIndex(
            model_name='nfsereceivedimportbatch',
            index=models.Index(fields=['workshop', 'status'], name='nfse_recv_batch_status_idx'),
        ),
        migrations.AddIndex(
            model_name='nfsereceivedimportbatchitem',
            index=models.Index(fields=['batch', 'status'], name='nfse_recv_bi_status_idx'),
        ),
        migrations.AddIndex(
            model_name='nfsereceivedimportbatchitem',
            index=models.Index(fields=['batch', 'xml_hash'], name='nfse_recv_bi_hash_idx'),
        ),
    ]
