# Generated by Django 6.0 on 2026-09-22 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0071_merge_20260922_1329"),
        ("finance", "0072_merge_nfse_consumidor_final_and_staging"),
    ]

    operations = []
