# Generated by Django 5.2.9 on 2026-06-30 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0072_nfsereceivedimportbatch_nfsereceivedimportbatchitem_and_more'),
        ('workshops', '0023_workshopcostholiday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='webmaniacompany',
            name='nfse_external_xml_inbox_enabled',
            field=models.BooleanField(default=False, verbose_name='Inbox externa de XML NFS-e habilitada'),
        ),
        migrations.CreateModel(
            name='NfseExternalXmlInbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('source_type', models.CharField(choices=[('manual_upload', 'Upload manual')], db_index=True, default='manual_upload', max_length=32, verbose_name='Tipo de origem')),
                ('source_label', models.CharField(blank=True, default='', max_length=120, verbose_name='Origem declarada')),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('partially_processed', 'Parcialmente processada'), ('processed', 'Processada'), ('closed', 'Fechada'), ('failed', 'Falhou')], db_index=True, default='open', max_length=32, verbose_name='Status')),
                ('total_items', models.PositiveIntegerField(default=0, verbose_name='Total de itens')),
                ('pending_count', models.PositiveIntegerField(default=0, verbose_name='Pendentes')),
                ('approved_count', models.PositiveIntegerField(default=0, verbose_name='Aprovados')),
                ('discarded_count', models.PositiveIntegerField(default=0, verbose_name='Descartados')),
                ('processed_count', models.PositiveIntegerField(default=0, verbose_name='Processados')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='Erros')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processado em')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nfse_external_xml_inboxes', to='finance.webmaniacompany', verbose_name='Empresa Webmania')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nfse_external_xml_inboxes', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_nfse_external_xml_inboxes', to=settings.AUTH_USER_MODEL, verbose_name='Processado por')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfse_external_xml_inboxes', to='workshops.workshop', verbose_name='Oficina')),
            ],
            options={
                'permissions': [('view_nfse_external_xml_inbox', 'Pode visualizar inbox externa de XML NFS-e'), ('upload_nfse_external_xml_inbox', 'Pode enviar XML para inbox externa NFS-e'), ('approve_nfse_external_xml_inbox', 'Pode aprovar XML da inbox externa NFS-e'), ('process_nfse_external_xml_inbox', 'Pode processar inbox externa de XML NFS-e'), ('discard_nfse_external_xml_inbox', 'Pode descartar XML da inbox externa NFS-e'), ('view_nfse_external_xml_payload', 'Pode visualizar XML da inbox externa NFS-e')],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NfseExternalXmlInboxItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Nome original')),
                ('safe_filename', models.CharField(max_length=255, verbose_name='Nome seguro')),
                ('content_type', models.CharField(blank=True, default='', max_length=120, verbose_name='Tipo de conteudo')),
                ('xml_snapshot', models.TextField(blank=True, default='', verbose_name='XML candidato')),
                ('xml_hash', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='Hash do XML')),
                ('size_bytes', models.PositiveIntegerField(default=0, verbose_name='Tamanho em bytes')),
                ('source_metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados da origem')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('invalid', 'Invalido'), ('duplicate', 'Duplicado'), ('approved', 'Aprovado'), ('discarded', 'Descartado'), ('processed', 'Processado'), ('error', 'Erro')], db_index=True, default='pending', max_length=24, verbose_name='Status')),
                ('validation_errors', models.JSONField(blank=True, default=list, verbose_name='Erros de validacao')),
                ('parsed_summary', models.JSONField(blank=True, default=dict, verbose_name='Resumo parseado')),
                ('discard_reason', models.TextField(blank=True, default='', verbose_name='Motivo de descarte')),
                ('discarded_at', models.DateTimeField(blank=True, null=True, verbose_name='Descartado em')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Aprovado em')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processado em')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_nfse_external_xml_items', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por')),
                ('discarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discarded_nfse_external_xml_items', to=settings.AUTH_USER_MODEL, verbose_name='Descartado por')),
                ('inbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.nfseexternalxmlinbox', verbose_name='Inbox')),
                ('linked_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_inbox_items', to='finance.nfsereceivedimportbatch', verbose_name='Lote vinculado')),
                ('linked_batch_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_inbox_items', to='finance.nfsereceivedimportbatchitem', verbose_name='Item de lote vinculado')),
                ('linked_received_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_inbox_items', to='finance.nfsereceiveddocument', verbose_name='NFS-e recebida vinculada')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_nfse_external_xml_items', to=settings.AUTH_USER_MODEL, verbose_name='Processado por')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='nfseexternalxmlinbox',
            index=models.Index(fields=['workshop', '-criado_em'], name='nfse_ext_inbox_time_idx'),
        ),
        migrations.AddIndex(
            model_name='nfseexternalxmlinbox',
            index=models.Index(fields=['workshop', 'status'], name='nfse_ext_inbox_status_idx'),
        ),
        migrations.AddIndex(
            model_name='nfseexternalxmlinboxitem',
            index=models.Index(fields=['inbox', 'status'], name='nfse_ext_item_status_idx'),
        ),
        migrations.AddIndex(
            model_name='nfseexternalxmlinboxitem',
            index=models.Index(fields=['inbox', 'xml_hash'], name='nfse_ext_item_hash_idx'),
        ),
        migrations.AddIndex(
            model_name='nfseexternalxmlinboxitem',
            index=models.Index(fields=['status', 'xml_hash'], name='nfse_ext_active_hash_idx'),
        ),
    ]
