# Generated by Django 6.0 on 2026-09-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0072_nferequest_discount_value_override_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxclassnfse',
            name='cod_indicador_operacao',
            field=models.CharField(blank=True, default='', help_text='Obrigatório no Padrão Nacional (ex.: 100501). Consulte a planilha da Webmania.', max_length=6, verbose_name='Código indicador da operação'),
        ),
        migrations.AddField(
            model_name='taxclassnfse',
            name='finalidade',
            field=models.CharField(blank=True, default='', help_text='Padrão Nacional: 0=Normal, 1=Substituta, 2=Complementar.', max_length=1, verbose_name='Finalidade da NFS-e'),
        ),
    ]
