# Generated by Django 6.0 on 2026-09-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0073_taxclassnfse_cod_indicador_operacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxclassnfse',
            name='cod_indicador_operacao',
            field=models.CharField(blank=True, default='', help_text='Obrigatório no Padrão Nacional (cIndOp). Ex.: 050101 para serviço sobre bem móvel no estabelecimento.', max_length=6, verbose_name='Código indicador da operação'),
        ),
    ]
