# Generated by Django 5.2.9 on 2026-06-30 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0073_webmaniacompany_nfse_external_xml_inbox_enabled_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nfseexternalxmlinbox',
            options={'permissions': [('view_nfse_external_xml_inbox', 'Pode visualizar inbox externa de XML NFS-e'), ('upload_nfse_external_xml_inbox', 'Pode enviar XML para inbox externa NFS-e'), ('approve_nfse_external_xml_inbox', 'Pode aprovar XML da inbox externa NFS-e'), ('process_nfse_external_xml_inbox', 'Pode processar inbox externa de XML NFS-e'), ('discard_nfse_external_xml_inbox', 'Pode descartar XML da inbox externa NFS-e'), ('view_nfse_external_xml_payload', 'Pode visualizar XML da inbox externa NFS-e'), ('export_nfse_external_xml_inbox', 'Pode exportar relatorio da inbox externa NFS-e'), ('bulk_manage_nfse_external_xml_inbox', 'Pode executar acoes em massa na inbox externa NFS-e')]},
        ),
    ]
