# Generated by Django 6.0 on 2026-09-24 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0073_merge_20260922_1835'),
        ('finance', '0074_alter_taxclassnfse_cod_indicador_help_text'),
    ]

    operations = [
    ]
