# Generated by Django 6.0 on 2026-07-02 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0074_alter_nfseexternalxmlinbox_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fiscaldocument',
            options={'permissions': [('issue_nfe_return', 'Pode emitir NF-e de devolucao'), ('issue_nfe_reversal', 'Pode emitir NF-e de estorno'), ('download_nfe_return', 'Pode baixar XML/DANFE de NF-e de devolucao ou estorno'), ('view_nfe_return_payload', 'Pode visualizar payload de NF-e de devolucao ou estorno'), ('issue_nfe_complementary_price_quantity', 'Pode emitir NF-e complementar de preco/quantidade'), ('view_nfe_complementary', 'Pode visualizar NF-e complementar'), ('download_nfe_complementary', 'Pode baixar XML/DANFE de NF-e complementar'), ('view_nfe_complementary_payload', 'Pode visualizar payload de NF-e complementar'), ('issue_nfe_adjustment', 'Pode emitir NF-e de ajuste'), ('view_nfe_adjustment', 'Pode visualizar NF-e de ajuste'), ('download_nfe_adjustment', 'Pode baixar XML/DANFE de NF-e de ajuste'), ('view_nfe_adjustment_payload', 'Pode visualizar payload de NF-e de ajuste'), ('issue_nfce', 'Pode emitir NFC-e'), ('view_nfce', 'Pode visualizar NFC-e'), ('download_nfce', 'Pode baixar XML/DANFE de NFC-e'), ('view_nfce_payload', 'Pode visualizar payload de NFC-e'), ('cancel_nfce', 'Pode cancelar NFC-e'), ('issue_nfe_credit', 'Pode emitir NF-e de credito'), ('view_nfe_credit', 'Pode visualizar NF-e de credito'), ('download_nfe_credit', 'Pode baixar XML/DANFE de NF-e de credito'), ('view_nfe_credit_payload', 'Pode visualizar payload de NF-e de credito'), ('cancel_nfe_credit', 'Pode cancelar NF-e de credito'), ('issue_nfe_debit', 'Pode emitir NF-e de debito'), ('view_nfe_debit', 'Pode visualizar NF-e de debito'), ('download_nfe_debit', 'Pode baixar XML/DANFE de NF-e de debito'), ('view_nfe_debit_payload', 'Pode visualizar payload de NF-e de debito'), ('cancel_nfe_debit', 'Pode cancelar NF-e de debito')]},
        ),
    ]
