# Generated by Django 6.0 on 2026-09-24 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0074_alter_taxclassnfse_cod_indicador_help_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='nferequest',
            name='line_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='Alterações de itens/componentes aplicadas só nesta emissão, sem gravar na O.S.', verbose_name='Overrides de itens (emissão)'),
        ),
        migrations.AddField(
            model_name='nferequest',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Apagado em'),
        ),
        migrations.AddField(
            model_name='nferequest',
            name='soft_deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soft_deleted_nfe_requests', to=settings.AUTH_USER_MODEL, verbose_name='Apagado por'),
        ),
        migrations.AddField(
            model_name='nfserequest',
            name='line_overrides',
            field=models.JSONField(blank=True, default=dict, help_text='Alterações de itens/componentes aplicadas só nesta emissão, sem gravar na O.S.', verbose_name='Overrides de itens (emissão)'),
        ),
        migrations.AddField(
            model_name='nfserequest',
            name='soft_deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Apagado em'),
        ),
        migrations.AddField(
            model_name='nfserequest',
            name='soft_deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soft_deleted_nfse_requests', to=settings.AUTH_USER_MODEL, verbose_name='Apagado por'),
        ),
    ]
