# Generated by Django 6.0 on 2026-09-24 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0075_merge_20260924_1516'),
        ('finance', '0075_soft_delete_and_line_overrides'),
    ]

    operations = [
    ]
