# Generated by Django 6.0 on 2026-07-02 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0075_alter_fiscaldocument_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fiscaldocumentevent',
            options={'permissions': [('issue_nfe_correction', 'Pode emitir carta de correcao NF-e'), ('download_nfe_correction', 'Pode baixar XML/DACCE de carta de correcao NF-e'), ('view_nfe_correction_payload', 'Pode visualizar payload de carta de correcao NF-e'), ('issue_ibs_cbs_event', 'Pode registrar evento IBS/CBS'), ('cancel_ibs_cbs_event', 'Pode cancelar evento IBS/CBS'), ('view_ibs_cbs_event', 'Pode visualizar evento IBS/CBS'), ('download_ibs_cbs_event', 'Pode baixar XML de evento IBS/CBS'), ('view_ibs_cbs_event_payload', 'Pode visualizar payload de evento IBS/CBS')]},
        ),
    ]
