# Generated by Django 6.0 on 2026-07-07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0041_nferequest_discount_type_override_and_more"),
        ("finance", "0076_alter_fiscaldocumentevent_options"),
    ]

    operations = []
