# Generated by Django 6.0 on 2026-09-30 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0069_merge_20260904_1810'),
        ('finance', '0077_clear_legacy_consumidor_final_default'),
    ]

    operations = [
    ]
