# Generated by Django 5.2.9 on 2026-07-08 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0078_alter_taxclassnfecofinsscenario_tax_class_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nferequest',
            options={'permissions': [('cancel_nferequest', 'Pode cancelar NF-e normal'), ('invalidate_nferequest_numbering', 'Pode inutilizar numeracao de NF-e normal'), ('download_nferequest_xml', 'Pode baixar XML de NF-e normal'), ('download_nferequest_pdf', 'Pode baixar DANFE/PDF de NF-e normal'), ('view_nferequest_payload', 'Pode visualizar payload de NF-e normal'), ('view_nferequest_remote_response', 'Pode visualizar resposta remota de NF-e normal')]},
        ),
    ]
