# Generated by Django 6.0 on 2026-09-30 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0078_merge_20260930_0933"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasereturnrequest",
            name="soft_deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Apagado em"),
        ),
        migrations.AddField(
            model_name="purchasereturnrequest",
            name="soft_deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="soft_deleted_purchase_return_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Apagado por",
            ),
        ),
    ]
