# Generated by Django 6.0 on 2026-09-30 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0069_financialmovement_fin_mov_ws_amt_idx"),
        ("finance", "0079_purchasereturnrequest_soft_delete"),
    ]

    operations = []
