# Generated by Django 6.0 on 2026-09-30 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0076_merge_20260924'),
        ('finance', '0079_purchasereturnrequest_soft_delete'),
    ]

    operations = [
    ]
