# Generated by Django 6.0 on 2026-07-28 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0045_financialmovement_payroll_benefit'),
        ('finance', '0080_nferequest_freight_mode_and_more'),
    ]

    operations = [
    ]
