# Generated by Django 6.0 on 2026-09-30 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0080_merge_20260930_1058'),
        ('finance', '0080_purchasereturnrequest_ipi_fields'),
    ]

    operations = [
    ]
