# Generated by Django 6.0 on 2026-07-31 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0081_merge_20260728_0043'),
        ('workorder', '0037_wave2_stored_totals'),
    ]

    operations = [
        migrations.AddField(
            model_name='nferequest',
            name='emission_origin',
            field=models.CharField(choices=[('work_order', 'Ordem de Serviço'), ('manual', 'Manual')], db_index=True, default='work_order', max_length=16, verbose_name='Origem da emissão'),
        ),
        migrations.AlterField(
            model_name='nferequest',
            name='workorder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workorder.workorder', verbose_name='Ordem de Serviço'),
        ),
        migrations.AddConstraint(
            model_name='nferequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('emission_origin', 'work_order'), ('workorder__isnull', False)), models.Q(('emission_origin', 'manual'), ('workorder__isnull', True)), _connector='OR'), name='nfe_request_origin_matches_workorder'),
        ),
    ]
