# Generated by Django 6.0 on 2026-08-01 00:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_service_shipping_service_shipping_currency'),
        ('customer', '0017_alter_vehicle_engine'),
        ('finance', '0082_nferequest_emission_origin_and_more'),
        ('workorder', '0037_wave2_stored_totals'),
    ]

    operations = [
        migrations.CreateModel(
            name='NfeRequestManualItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Quantidade')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor unitário')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveConstraint(
            model_name='nferequest',
            name='nfe_request_origin_matches_workorder',
        ),
        migrations.AddField(
            model_name='nferequest',
            name='manual_recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manual_nfe_requests', to='customer.customer', verbose_name='Destinatário manual'),
        ),
        migrations.AlterField(
            model_name='nfeitem',
            name='workorder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workorder.workorder', verbose_name='Ordem de Serviço'),
        ),
        migrations.AddConstraint(
            model_name='nfeitem',
            constraint=models.UniqueConstraint(condition=models.Q(('workorder__isnull', True)), fields=('request', 'uuid'), name='unique_manual_nfe_item_per_request'),
        ),
        migrations.AddConstraint(
            model_name='nferequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('emission_origin', 'work_order'), ('manual_recipient__isnull', True), ('workorder__isnull', False)), models.Q(('emission_origin', 'manual'), ('manual_recipient__isnull', False), ('workorder__isnull', True)), _connector='OR'), name='nfe_request_origin_matches_workorder'),
        ),
        migrations.AddField(
            model_name='nferequestmanualitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_nfe_request_items', to='catalog.product', verbose_name='Produto'),
        ),
        migrations.AddField(
            model_name='nferequestmanualitem',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_items', to='finance.nferequest', verbose_name='Requisição de NF-e'),
        ),
        migrations.AddConstraint(
            model_name='nferequestmanualitem',
            constraint=models.UniqueConstraint(fields=('request', 'product'), name='unique_product_per_manual_nfe_request'),
        ),
    ]
