# Generated by Django 6.0 on 2026-10-05 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0080_merge_staging_and_purchase_return_soft_delete"),
        ("finance", "0083_purchasereturnrequest_icms_situacao_tributaria"),
    ]

    operations = []
