# Generated by Django 6.0 on 2026-08-01 21:19

import django.db.models.deletion
from django.db import migrations, models


def update_consult_nfse_received_permission_name(apps, schema_editor) -> None:
    Permission = apps.get_model("auth", "Permission")
    Permission.objects.filter(
        content_type__app_label="finance",
        content_type__model="nfsereceiveddocumentconsultation",
        codename="consult_nfse_received",
    ).update(name="Pode consultar NFS-e recebida")


def revert_consult_nfse_received_permission_name(apps, schema_editor) -> None:
    Permission = apps.get_model("auth", "Permission")
    Permission.objects.filter(
        content_type__app_label="finance",
        content_type__model="nfsereceiveddocumentconsultation",
        codename="consult_nfse_received",
    ).update(name="Pode consultar NFS-e recebida na Webmania")


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0083_nferequestmanualitem_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nfsereceiveddocumentconsultation",
            options={
                "permissions": [
                    ("consult_nfse_received", "Pode consultar NFS-e recebida"),
                    ("view_nfse_received_consultation", "Pode visualizar consultas de NFS-e recebida"),
                    ("view_nfse_received_consultation_payload", "Pode visualizar payload de consulta de NFS-e recebida"),
                ]
            },
        ),
        migrations.AlterField(
            model_name="nfseexternalxmlinbox",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="nfse_external_xml_inboxes",
                to="finance.webmaniacompany",
                verbose_name="Empresa emissora",
            ),
        ),
        migrations.AlterField(
            model_name="nfsemanualemission",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="nfse_manual_emissions",
                to="finance.webmaniacompany",
                verbose_name="Empresa emissora",
            ),
        ),
        migrations.AlterField(
            model_name="nfsemanualemissionpreview",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="nfse_manual_emission_previews",
                to="finance.webmaniacompany",
                verbose_name="Empresa emissora",
            ),
        ),
        migrations.AlterField(
            model_name="nfsemunicipalcapability",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="nfse_municipal_capabilities",
                to="finance.webmaniacompany",
                verbose_name="Empresa emissora",
            ),
        ),
        migrations.AlterField(
            model_name="nfsereceiveddocument",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="nfse_received_documents",
                to="finance.webmaniacompany",
                verbose_name="Empresa emissora",
            ),
        ),
        migrations.AlterField(
            model_name="nfsereceivedimportbatch",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="nfse_received_import_batches",
                to="finance.webmaniacompany",
                verbose_name="Empresa emissora",
            ),
        ),
        migrations.AlterField(
            model_name="webmaniacompany",
            name="webmania_company_id",
            field=models.CharField(blank=True, default="", max_length=32, verbose_name="ID da empresa"),
        ),
        migrations.RunPython(update_consult_nfse_received_permission_name, revert_consult_nfse_received_permission_name),
    ]
