# Generated by Django 5.2.9 on 2026-08-01 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_service_shipping_service_shipping_currency'),
        ('finance', '0083_nferequestmanualitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nferequestmanualitem',
            name='fiscal_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='Snapshot fiscal do produto'),
        ),
        migrations.AddField(
            model_name='nferequestmanualitem',
            name='item_origin',
            field=models.CharField(choices=[('catalog', 'Produto do catálogo'), ('temporary', 'Produto temporário')], default='catalog', max_length=16, verbose_name='Origem do item'),
        ),
        migrations.AlterField(
            model_name='nferequestmanualitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manual_nfe_request_items', to='catalog.product', verbose_name='Produto'),
        ),
        migrations.AddConstraint(
            model_name='nferequestmanualitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('item_origin', 'catalog'), ('product__isnull', False)), models.Q(('item_origin', 'temporary'), ('product__isnull', True), models.Q(('fiscal_snapshot', {}), _negated=True)), _connector='OR'), name='nfe_manual_item_origin_matches_product'),
        ),
    ]
