# Generated by Django 6.0 on 2026-08-01 22:03

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0084_omit_webmania_from_ui_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fiscalcreditproductpreview',
            options={'permissions': [('prepare_nfe_credit_product_preview', 'Pode preparar prévia de produto de crédito'), ('approve_nfe_credit_product_preview', 'Pode aprovar prévia de produto de crédito'), ('view_nfe_credit_product_preview', 'Pode visualizar prévia de produto de crédito'), ('view_nfe_credit_product_preview_payload', 'Pode visualizar payload da prévia de produto de crédito')]},
        ),
        migrations.AlterModelOptions(
            name='fiscaldebitproductpreview',
            options={'permissions': [('prepare_nfe_debit_product_preview', 'Pode preparar prévia de produto de débito'), ('approve_nfe_debit_product_preview', 'Pode aprovar prévia de produto de débito'), ('view_nfe_debit_product_preview', 'Pode visualizar prévia de produto de débito'), ('view_nfe_debit_product_preview_payload', 'Pode visualizar payload da prévia de produto de débito')]},
        ),
        migrations.AlterModelOptions(
            name='fiscaldocument',
            options={'permissions': [('issue_nfe_return', 'Pode emitir NF-e de devolução'), ('issue_nfe_reversal', 'Pode emitir NF-e de estorno'), ('download_nfe_return', 'Pode baixar XML/DANFE de NF-e de devolução ou estorno'), ('view_nfe_return_payload', 'Pode visualizar payload de NF-e de devolução ou estorno'), ('issue_nfe_complementary_price_quantity', 'Pode emitir NF-e complementar de preço/quantidade'), ('view_nfe_complementary', 'Pode visualizar NF-e complementar'), ('download_nfe_complementary', 'Pode baixar XML/DANFE de NF-e complementar'), ('view_nfe_complementary_payload', 'Pode visualizar payload de NF-e complementar'), ('issue_nfe_adjustment', 'Pode emitir NF-e de ajuste'), ('view_nfe_adjustment', 'Pode visualizar NF-e de ajuste'), ('download_nfe_adjustment', 'Pode baixar XML/DANFE de NF-e de ajuste'), ('view_nfe_adjustment_payload', 'Pode visualizar payload de NF-e de ajuste'), ('issue_nfce', 'Pode emitir NFC-e'), ('view_nfce', 'Pode visualizar NFC-e'), ('download_nfce', 'Pode baixar XML/DANFE de NFC-e'), ('view_nfce_payload', 'Pode visualizar payload de NFC-e'), ('cancel_nfce', 'Pode cancelar NFC-e'), ('issue_nfe_credit', 'Pode emitir NF-e de crédito'), ('view_nfe_credit', 'Pode visualizar NF-e de crédito'), ('download_nfe_credit', 'Pode baixar XML/DANFE de NF-e de crédito'), ('view_nfe_credit_payload', 'Pode visualizar payload de NF-e de crédito'), ('cancel_nfe_credit', 'Pode cancelar NF-e de crédito'), ('issue_nfe_debit', 'Pode emitir NF-e de débito'), ('view_nfe_debit', 'Pode visualizar NF-e de débito'), ('download_nfe_debit', 'Pode baixar XML/DANFE de NF-e de débito'), ('view_nfe_debit_payload', 'Pode visualizar payload de NF-e de débito'), ('cancel_nfe_debit', 'Pode cancelar NF-e de débito')]},
        ),
        migrations.AlterModelOptions(
            name='fiscaldocumentevent',
            options={'permissions': [('issue_nfe_correction', 'Pode emitir carta de correção NF-e'), ('download_nfe_correction', 'Pode baixar XML/DACCE de carta de correção NF-e'), ('view_nfe_correction_payload', 'Pode visualizar payload de carta de correção NF-e'), ('issue_ibs_cbs_event', 'Pode registrar evento IBS/CBS'), ('cancel_ibs_cbs_event', 'Pode cancelar evento IBS/CBS'), ('view_ibs_cbs_event', 'Pode visualizar evento IBS/CBS'), ('download_ibs_cbs_event', 'Pode baixar XML de evento IBS/CBS'), ('view_ibs_cbs_event_payload', 'Pode visualizar payload de evento IBS/CBS')]},
        ),
        migrations.AlterModelOptions(
            name='fiscalnumberinutilization',
            options={'permissions': [('inutilize_nfce_numbering', 'Pode inutilizar numeração NFC-e'), ('view_nfce_inutilization', 'Pode visualizar inutilização NFC-e'), ('download_nfce_inutilization', 'Pode baixar XML de inutilização NFC-e'), ('view_nfce_inutilization_payload', 'Pode visualizar payload de inutilização NFC-e')]},
        ),
        migrations.AlterModelOptions(
            name='fiscalreferencedbasis',
            options={'permissions': [('prepare_nfe_credit_debit_basis', 'Pode preparar base fiscal de crédito/débito'), ('approve_nfe_credit_debit_basis', 'Pode aprovar base fiscal de crédito/débito'), ('view_nfe_credit_debit_basis', 'Pode visualizar base fiscal de crédito/débito'), ('view_nfe_credit_debit_basis_payload', 'Pode visualizar payload da base fiscal de crédito/débito')]},
        ),
        migrations.AlterModelOptions(
            name='nferequest',
            options={'permissions': [('cancel_nferequest', 'Pode cancelar NF-e normal'), ('invalidate_nferequest_numbering', 'Pode inutilizar numeração de NF-e normal'), ('download_nferequest_xml', 'Pode baixar XML de NF-e normal'), ('download_nferequest_pdf', 'Pode baixar DANFE/PDF de NF-e normal'), ('view_nferequest_payload', 'Pode visualizar payload de NF-e normal'), ('view_nferequest_remote_response', 'Pode visualizar resposta remota de NF-e normal')]},
        ),
        migrations.AlterModelOptions(
            name='nfseexternalxmlinbox',
            options={'permissions': [('view_nfse_external_xml_inbox', 'Pode visualizar inbox externa de XML NFS-e'), ('upload_nfse_external_xml_inbox', 'Pode enviar XML para inbox externa NFS-e'), ('approve_nfse_external_xml_inbox', 'Pode aprovar XML da inbox externa NFS-e'), ('process_nfse_external_xml_inbox', 'Pode processar inbox externa de XML NFS-e'), ('discard_nfse_external_xml_inbox', 'Pode descartar XML da inbox externa NFS-e'), ('view_nfse_external_xml_payload', 'Pode visualizar XML da inbox externa NFS-e'), ('export_nfse_external_xml_inbox', 'Pode exportar relatório da inbox externa NFS-e'), ('bulk_manage_nfse_external_xml_inbox', 'Pode executar ações em massa na inbox externa NFS-e')]},
        ),
        migrations.AlterModelOptions(
            name='nfsemanifestation',
            options={'permissions': [('issue_nfse_manifestation', 'Pode manifestar NFS-e'), ('view_nfse_manifestation', 'Pode visualizar manifestação NFS-e'), ('download_nfse_manifestation', 'Pode baixar documentos da manifestação NFS-e'), ('view_nfse_manifestation_payload', 'Pode visualizar payload da manifestação NFS-e')]},
        ),
        migrations.AlterModelOptions(
            name='nfsemanualemission',
            options={'permissions': [('issue_nfse_manual_emission', 'Pode emitir NFS-e manual'), ('view_nfse_manual_emission', 'Pode visualizar emissão manual NFS-e'), ('download_nfse_manual_emission', 'Pode baixar documentos da emissão manual NFS-e'), ('view_nfse_manual_emission_payload', 'Pode visualizar payload da emissão manual NFS-e')]},
        ),
        migrations.AlterModelOptions(
            name='nfsemanualemissionpreview',
            options={'permissions': [('prepare_nfse_manual_emission_preview', 'Pode preparar prévia de emissão manual NFS-e'), ('approve_nfse_manual_emission_preview', 'Pode aprovar prévia de emissão manual NFS-e'), ('view_nfse_manual_emission_preview', 'Pode visualizar prévia de emissão manual NFS-e'), ('view_nfse_manual_emission_preview_payload', 'Pode visualizar payload da prévia de emissão manual NFS-e')]},
        ),
        migrations.AlterModelOptions(
            name='nfsesubstitution',
            options={'permissions': [('substitute_nfse', 'Pode substituir NFS-e'), ('view_nfse_substitution_payload', 'Pode visualizar payload da substituição NFS-e'), ('download_nfse_substitution', 'Pode baixar documentos da substituição NFS-e')]},
        ),
        migrations.AlterModelOptions(
            name='nfsesubstitutionpreview',
            options={'permissions': [('prepare_nfse_substitution', 'Pode preparar substituição NFS-e'), ('approve_nfse_substitution', 'Pode aprovar substituição NFS-e'), ('view_nfse_substitution_preview', 'Pode visualizar prévia de substituição NFS-e'), ('view_nfse_substitution_preview_payload', 'Pode visualizar payload da prévia de substituição NFS-e')]},
        ),
        migrations.AlterModelOptions(
            name='taxclassnfe',
            options={'permissions': [('manage_ibs_cbs_tax_classes', 'Pode configurar IBS/CBS em classes fiscais'), ('view_ibs_cbs_configuration', 'Pode visualizar configuração IBS/CBS')]},
        ),
        migrations.AlterField(
            model_name='fiscalcreditproductpreview',
            name='operation_type',
            field=models.CharField(default='credit', max_length=12, verbose_name='Tipo da operação'),
        ),
        migrations.AlterField(
            model_name='fiscalcreditproductpreview',
            name='product_unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor unitário explicito'),
        ),
        migrations.AlterField(
            model_name='fiscalcreditproductpreview',
            name='revision',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Revisão'),
        ),
        migrations.AlterField(
            model_name='fiscalcreditproductpreview',
            name='validation_status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('validated', 'Validada'), ('approved', 'Aprovada'), ('invalid', 'Inválida')], db_index=True, default='draft', max_length=16, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='fiscaldebitproductpreview',
            name='operation_type',
            field=models.CharField(default='debit', max_length=12, verbose_name='Tipo da operação'),
        ),
        migrations.AlterField(
            model_name='fiscaldebitproductpreview',
            name='product_unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor unitário explicito'),
        ),
        migrations.AlterField(
            model_name='fiscaldebitproductpreview',
            name='revision',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Revisão'),
        ),
        migrations.AlterField(
            model_name='fiscaldebitproductpreview',
            name='validation_status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('validated', 'Validada'), ('approved', 'Aprovada'), ('invalid', 'Inválida')], db_index=True, default='draft', max_length=16, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='fiscaldocument',
            name='complementary_type',
            field=models.CharField(blank=True, choices=[('price_quantity', 'Preço/quantidade')], db_index=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='fiscaldocument',
            name='credit_product_preview',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_document', to='finance.fiscalcreditproductpreview', verbose_name='Prévia fiscal de crédito'),
        ),
        migrations.AlterField(
            model_name='fiscaldocument',
            name='debit_product_preview',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debit_document', to='finance.fiscaldebitproductpreview', verbose_name='Prévia fiscal de débito'),
        ),
        migrations.AlterField(
            model_name='fiscaldocument',
            name='purpose',
            field=models.CharField(choices=[('normal', 'Normal'), ('return', 'Devolução'), ('reversal', 'Estorno'), ('complementary', 'Complementar'), ('adjustment', 'Ajuste'), ('credit', 'Crédito'), ('debit', 'Débito')], db_index=True, default='normal', max_length=24),
        ),
        migrations.AlterField(
            model_name='fiscaldocument',
            name='status',
            field=models.CharField(choices=[('processando', 'Processando'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('cancelado', 'Cancelado'), ('denegado', 'Denegado'), ('contingencia', 'Contingência'), ('uncertain', 'Incerto')], db_index=True, default='processando', max_length=20),
        ),
        migrations.AlterField(
            model_name='fiscaldocumentevent',
            name='event_type',
            field=models.CharField(choices=[('cce', 'Carta de correção'), ('cancellation', 'Cancelamento'), ('ibs_cbs', 'Evento IBS/CBS'), ('ibs_cbs_cancellation', 'Cancelamento de evento IBS/CBS')], db_index=True, default='cce', max_length=20),
        ),
        migrations.AlterField(
            model_name='fiscaldocumentevent',
            name='status',
            field=models.CharField(choices=[('started', 'Iniciado'), ('sent', 'Enviado'), ('succeeded', 'Concluído'), ('processando', 'Processando'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('cancelado', 'Cancelado'), ('failed', 'Falhou'), ('uncertain', 'Incerto')], db_index=True, default='started', max_length=20),
        ),
        migrations.AlterField(
            model_name='fiscalemissionattempt',
            name='fiscal_number_inutilization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emission_attempts', to='finance.fiscalnumberinutilization', verbose_name='Inutilização de numeração'),
        ),
        migrations.AlterField(
            model_name='fiscalemissionattempt',
            name='operation_type',
            field=models.CharField(choices=[('emission', 'Emissão'), ('cce', 'Carta de correção'), ('return', 'Devolução'), ('reversal', 'Estorno'), ('complementary_price_quantity', 'Complementar preço/quantidade'), ('adjustment', 'Ajuste'), ('nfce_emission', 'Emissão NFC-e'), ('nfce_cancellation', 'Cancelamento NFC-e'), ('nfce_inutilization', 'Inutilização NFC-e'), ('nfe_ibs_cbs_event', 'Evento IBS/CBS'), ('nfe_ibs_cbs_event_cancellation', 'Cancelamento de evento IBS/CBS'), ('nfe_credit_emission', 'Emissão NF-e de crédito'), ('nfe_credit_cancellation', 'Cancelamento NF-e de crédito'), ('nfe_debit_emission', 'Emissão NF-e de débito'), ('nfe_debit_cancellation', 'Cancelamento NF-e de débito'), ('nfse_cancellation', 'Cancelamento NFS-e'), ('nfse_substitution', 'Substituição NFS-e'), ('nfse_manifestation', 'Manifestação NFS-e'), ('nfse_manual_emission', 'Emissão manual NFS-e')], db_index=True, default='emission', max_length=32),
        ),
        migrations.AlterField(
            model_name='fiscalemissionattempt',
            name='status',
            field=models.CharField(choices=[('started', 'Iniciada'), ('sent', 'Enviada'), ('succeeded', 'Concluída'), ('failed', 'Falhou'), ('uncertain', 'Incerta')], db_index=True, default='started', max_length=20),
        ),
        migrations.AlterField(
            model_name='fiscalnumberinutilization',
            name='status',
            field=models.CharField(choices=[('started', 'Iniciada'), ('sent', 'Enviada'), ('succeeded', 'Concluída'), ('failed', 'Falhou'), ('uncertain', 'Incerta')], db_index=True, default='started', max_length=20),
        ),
        migrations.AlterField(
            model_name='fiscalreferencedbasis',
            name='basis_type',
            field=models.CharField(choices=[('credit', 'Crédito'), ('debit', 'Débito')], db_index=True, max_length=12, verbose_name='Tipo da base'),
        ),
        migrations.AlterField(
            model_name='fiscalreferencedbasis',
            name='fiscal_hypothesis',
            field=models.CharField(choices=[('credit_fine_interest', 'Crédito - multa/juros'), ('credit_zfm_presumed', 'Crédito - presumido ZFM'), ('credit_refusal', 'Crédito - recusa/não localização'), ('credit_value_reduction', 'Crédito - redução de valores'), ('credit_succession', 'Crédito - sucessão'), ('debit_cooperative', 'Débito - cooperativas'), ('debit_exempt_output', 'Débito - saídas imunes/isentas'), ('debit_unprocessed_invoice', 'Débito - NF não processada'), ('debit_fine_interest', 'Débito - multa/juros'), ('debit_succession', 'Débito - sucessão'), ('debit_advance_payment', 'Débito - pagamento antecipado'), ('debit_stock_loss', 'Débito - perda de estoque'), ('debit_sn_exclusion', 'Débito - desenquadramento do SN')], db_index=True, max_length=48, verbose_name='Hipótese fiscal'),
        ),
        migrations.AlterField(
            model_name='fiscalreferencedbasis',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Evidências e observações'),
        ),
        migrations.AlterField(
            model_name='fiscalreferencedbasis',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('ready', 'Pronta para aprovação'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada'), ('invalid', 'Inválida'), ('archived', 'Arquivada')], db_index=True, default='draft', max_length=16, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='fiscalreferencedbasisitem',
            name='credit_debit_base_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Base monetária crédito/débito'),
        ),
        migrations.AlterField(
            model_name='fiscalreferencedbasisitem',
            name='source_item_code',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Código fiscal do item'),
        ),
        migrations.AlterField(
            model_name='fiscalreferencedbasisitem',
            name='source_item_description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Descrição fiscal do item'),
        ),
        migrations.AlterField(
            model_name='fiscalreferencedbasisitem',
            name='source_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valor unitário fiscal'),
        ),
        migrations.AlterField(
            model_name='nferequest',
            name='discount_type_override',
            field=models.CharField(blank=True, choices=[('products', 'Apenas Produtos'), ('services', 'Apenas Serviços'), ('both', 'Produtos e Serviços')], default='', help_text='Sobrescreve o tipo de desconto da OS apenas para esta emissão. Vazio usa o da OS.', max_length=10, verbose_name='Tipo de desconto (emissão)'),
        ),
        migrations.AlterField(
            model_name='nferequest',
            name='pricing_slider',
            field=models.SmallIntegerField(blank=True, help_text='Copia o slider do orçamento na criação e permanece independente para a emissão.', null=True, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)], verbose_name='Slider de precificacao'),
        ),
        migrations.AlterField(
            model_name='nfsebatch',
            name='last_reconciled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última consulta'),
        ),
        migrations.AlterField(
            model_name='nfsebatch',
            name='last_update_source',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Origem da última atualizacao'),
        ),
        migrations.AlterField(
            model_name='nfsecancellation',
            name='status',
            field=models.CharField(choices=[('started', 'Iniciada'), ('sent', 'Enviada'), ('succeeded', 'Concluída'), ('failed', 'Falhou'), ('uncertain', 'Incerta')], db_index=True, default='started', max_length=20),
        ),
        migrations.AlterField(
            model_name='nfseexternalxmlinboxitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('invalid', 'Inválido'), ('duplicate', 'Duplicado'), ('approved', 'Aprovado'), ('discarded', 'Descartado'), ('processed', 'Processado'), ('error', 'Erro')], db_index=True, default='pending', max_length=24, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='nfseitem',
            name='last_update_source',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Origem da última atualizacao'),
        ),
        migrations.AlterField(
            model_name='nfsemanifestation',
            name='manifestation_type',
            field=models.CharField(choices=[('confirmation', 'Confirmação'), ('rejection', 'Rejeição')], db_index=True, max_length=16, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='nfsemanifestation',
            name='manifestor',
            field=models.PositiveSmallIntegerField(verbose_name='Código do manifestador'),
        ),
        migrations.AlterField(
            model_name='nfsemanifestation',
            name='rejection_justification',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Justificativa de rejeição'),
        ),
        migrations.AlterField(
            model_name='nfsemanifestation',
            name='rejection_reason',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Motivo de rejeição'),
        ),
        migrations.AlterField(
            model_name='nfsemanifestation',
            name='remote_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='UUID remoto da manifestação'),
        ),
        migrations.AlterField(
            model_name='nfsemanifestation',
            name='status',
            field=models.CharField(choices=[('started', 'Iniciada'), ('sent', 'Enviada'), ('succeeded', 'Concluída'), ('failed', 'Falhou'), ('uncertain', 'Incerta')], db_index=True, default='started', max_length=20),
        ),
        migrations.AlterField(
            model_name='nfsemanifestation',
            name='xml_manifestation',
            field=models.URLField(blank=True, default='', verbose_name='XML/artefato da manifestação'),
        ),
        migrations.AlterField(
            model_name='nfsemanualemission',
            name='environment',
            field=models.CharField(choices=[('1', 'Producao'), ('2', 'Homologação')], max_length=1, verbose_name='Ambiente'),
        ),
        migrations.AlterField(
            model_name='nfsemanualemission',
            name='preview',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='manual_emission', to='finance.nfsemanualemissionpreview', verbose_name='Prévia aprovada'),
        ),
        migrations.AlterField(
            model_name='nfsemanualemission',
            name='rps_number',
            field=models.PositiveIntegerField(verbose_name='Número RPS'),
        ),
        migrations.AlterField(
            model_name='nfsemanualemission',
            name='status',
            field=models.CharField(choices=[('started', 'Iniciada'), ('sent', 'Enviada'), ('succeeded', 'Concluída'), ('failed', 'Falhou'), ('uncertain', 'Incerta')], db_index=True, default='started', max_length=20),
        ),
        migrations.AlterField(
            model_name='nfsemanualemission',
            name='verification_code',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Código de verificacao'),
        ),
        migrations.AlterField(
            model_name='nfsemanualemissionpreview',
            name='environment',
            field=models.CharField(choices=[('1', 'Producao'), ('2', 'Homologação')], max_length=1, verbose_name='Ambiente'),
        ),
        migrations.AlterField(
            model_name='nfsemanualemissionpreview',
            name='rps_number',
            field=models.PositiveIntegerField(verbose_name='Número RPS'),
        ),
        migrations.AlterField(
            model_name='nfsemanualemissionpreview',
            name='service_snapshot',
            field=models.JSONField(default=dict, verbose_name='Snapshot do serviço'),
        ),
        migrations.AlterField(
            model_name='nfsemanualemissionpreview',
            name='taxation_snapshot',
            field=models.JSONField(default=dict, verbose_name='Snapshot de tributação'),
        ),
        migrations.AlterField(
            model_name='nfsemanualemissionpreview',
            name='validation_status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('validated', 'Validada'), ('approved', 'Aprovada'), ('invalid', 'Inválida')], db_index=True, default='draft', max_length=16, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='nfsemunicipalcapability',
            name='batch_required',
            field=models.BooleanField(default=False, verbose_name='Lote RPS obrigatório'),
        ),
        migrations.AlterField(
            model_name='nfsemunicipalcapability',
            name='city_code',
            field=models.CharField(max_length=7, verbose_name='Código IBGE do município'),
        ),
        migrations.AlterField(
            model_name='nfsemunicipalcapability',
            name='city_name',
            field=models.CharField(max_length=120, verbose_name='Município'),
        ),
        migrations.AlterField(
            model_name='nfsemunicipalcapability',
            name='emission_enabled',
            field=models.BooleanField(default=False, verbose_name='Emissão habilitada'),
        ),
        migrations.AlterField(
            model_name='nfsemunicipalcapability',
            name='last_status_error',
            field=models.TextField(blank=True, default='', verbose_name='Último erro de consulta'),
        ),
        migrations.AlterField(
            model_name='nfsemunicipalcapability',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última sincronização'),
        ),
        migrations.AlterField(
            model_name='nfsemunicipalcapability',
            name='legacy_municipal_enabled',
            field=models.BooleanField(default=True, verbose_name='Padrão municipal legado'),
        ),
        migrations.AlterField(
            model_name='nfsemunicipalcapability',
            name='manifestation_enabled',
            field=models.BooleanField(default=False, verbose_name='Manifestação habilitada'),
        ),
        migrations.AlterField(
            model_name='nfsemunicipalcapability',
            name='manual_emission_enabled',
            field=models.BooleanField(default=False, verbose_name='Emissão manual habilitada'),
        ),
        migrations.AlterField(
            model_name='nfsemunicipalcapability',
            name='national_standard_enabled',
            field=models.BooleanField(default=False, verbose_name='Padrão Nacional'),
        ),
        migrations.AlterField(
            model_name='nfsemunicipalcapability',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='nfsemunicipalcapability',
            name='pdf_download_enabled',
            field=models.BooleanField(default=True, verbose_name='Download PDF NFS-e disponível'),
        ),
        migrations.AlterField(
            model_name='nfsemunicipalcapability',
            name='provider_version',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Versão do provedor'),
        ),
        migrations.AlterField(
            model_name='nfsemunicipalcapability',
            name='remote_status',
            field=models.BooleanField(blank=True, null=True, verbose_name='Status remoto do município'),
        ),
        migrations.AlterField(
            model_name='nfsemunicipalcapability',
            name='requires_service_code',
            field=models.BooleanField(default=False, verbose_name='Exige código de serviço'),
        ),
        migrations.AlterField(
            model_name='nfsemunicipalcapability',
            name='rps_pdf_enabled',
            field=models.BooleanField(default=True, verbose_name='Download PDF RPS disponível'),
        ),
        migrations.AlterField(
            model_name='nfsemunicipalcapability',
            name='rps_required',
            field=models.BooleanField(default=True, verbose_name='RPS obrigatório'),
        ),
        migrations.AlterField(
            model_name='nfsemunicipalcapability',
            name='substitution_enabled',
            field=models.BooleanField(default=False, verbose_name='Substituição habilitada'),
        ),
        migrations.AlterField(
            model_name='nfsemunicipalcapability',
            name='synchronous_emission',
            field=models.BooleanField(default=False, verbose_name='Emissão sincrona'),
        ),
        migrations.AlterField(
            model_name='nfsemunicipalcapability',
            name='xml_download_enabled',
            field=models.BooleanField(default=True, verbose_name='Download XML disponível'),
        ),
        migrations.AlterField(
            model_name='nfsereceiveddocument',
            name='environment',
            field=models.CharField(blank=True, choices=[('', 'Não informado'), ('1', 'Producao'), ('2', 'Homologação')], default='', max_length=1, verbose_name='Ambiente'),
        ),
        migrations.AlterField(
            model_name='nfsereceiveddocument',
            name='issue_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de emissão'),
        ),
        migrations.AlterField(
            model_name='nfsereceiveddocument',
            name='municipality_code',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Código município'),
        ),
        migrations.AlterField(
            model_name='nfsereceiveddocument',
            name='service_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor do serviço'),
        ),
        migrations.AlterField(
            model_name='nfsereceiveddocument',
            name='verification_code',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Código de verificacao'),
        ),
        migrations.AlterField(
            model_name='nfsereceiveddocumentconsultation',
            name='divergences',
            field=models.JSONField(blank=True, default=list, verbose_name='Divergências consultivas'),
        ),
        migrations.AlterField(
            model_name='nfsereceiveddocumentconsultation',
            name='national_standard_confirmed',
            field=models.BooleanField(blank=True, null=True, verbose_name='Padrão Nacional confirmado pela consulta'),
        ),
        migrations.AlterField(
            model_name='nfsereceivedimportbatch',
            name='status',
            field=models.CharField(choices=[('processing', 'Processando'), ('completed', 'Concluído'), ('completed_with_errors', 'Concluído com erros'), ('failed', 'Falhou')], db_index=True, default='processing', max_length=32, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='nfsereceivedimportbatchitem',
            name='error_code',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Código do erro'),
        ),
        migrations.AlterField(
            model_name='nfsereceivedimportbatchitem',
            name='status',
            field=models.CharField(choices=[('imported', 'Importado'), ('rejected', 'Rejeitado'), ('duplicate', 'Duplicado'), ('invalid_xml', 'XML inválido'), ('invalid_tenant', 'Oficina/CNPJ inválido'), ('error', 'Erro')], db_index=True, max_length=24, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='nfserequest',
            name='discount_type_override',
            field=models.CharField(blank=True, choices=[('products', 'Apenas Produtos'), ('services', 'Apenas Serviços'), ('both', 'Produtos e Serviços')], default='', help_text='Sobrescreve o tipo de desconto da OS apenas para esta emissão. Vazio usa o da OS.', max_length=10, verbose_name='Tipo de desconto (emissão)'),
        ),
        migrations.AlterField(
            model_name='nfserequest',
            name='pricing_slider',
            field=models.SmallIntegerField(blank=True, help_text='Copia o slider do orçamento na criação e permanece independente para a emissão.', null=True, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)], verbose_name='Slider de precificacao'),
        ),
        migrations.AlterField(
            model_name='nfsesubstitution',
            name='original_verification_code',
            field=models.CharField(max_length=60, verbose_name='Código de verificacao original'),
        ),
        migrations.AlterField(
            model_name='nfsesubstitution',
            name='preview',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='substitution', to='finance.nfsesubstitutionpreview', verbose_name='Prévia aprovada'),
        ),
        migrations.AlterField(
            model_name='nfsesubstitution',
            name='status',
            field=models.CharField(choices=[('started', 'Iniciada'), ('sent', 'Enviada'), ('succeeded', 'Concluída'), ('failed', 'Falhou'), ('uncertain', 'Incerta')], db_index=True, default='started', max_length=20),
        ),
        migrations.AlterField(
            model_name='nfsesubstitutionpreview',
            name='environment',
            field=models.CharField(choices=[('1', 'Producao'), ('2', 'Homologação')], max_length=1, verbose_name='Ambiente'),
        ),
        migrations.AlterField(
            model_name='nfsesubstitutionpreview',
            name='original_verification_code',
            field=models.CharField(max_length=60, verbose_name='Código de verificacao original'),
        ),
        migrations.AlterField(
            model_name='nfsesubstitutionpreview',
            name='reason_code',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Erro na emissão'), (2, 'Serviço não prestado'), (4, 'Duplicidade da nota')], verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='nfsesubstitutionpreview',
            name='request_payload',
            field=models.JSONField(default=dict, verbose_name='Pre-payload de substituição'),
        ),
        migrations.AlterField(
            model_name='nfsesubstitutionpreview',
            name='validation_status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('validated', 'Validada'), ('approved', 'Aprovada'), ('invalid', 'Inválida')], db_index=True, default='draft', max_length=16, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='webmaniacompany',
            name='credit_debit_basis_enabled',
            field=models.BooleanField(default=False, verbose_name='Preparação de base crédito/débito habilitada'),
        ),
        migrations.AlterField(
            model_name='webmaniacompany',
            name='credit_debit_basis_enabled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Base crédito/débito habilitada em'),
        ),
        migrations.AlterField(
            model_name='webmaniacompany',
            name='credit_debit_basis_enabled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enabled_credit_debit_basis_companies', to=settings.AUTH_USER_MODEL, verbose_name='Base crédito/débito habilitada por'),
        ),
        migrations.AlterField(
            model_name='webmaniacompany',
            name='nfe_debit_emission_enabled',
            field=models.BooleanField(default=False, verbose_name='Emissão NF-e de débito habilitada'),
        ),
        migrations.AlterField(
            model_name='webmaniacompany',
            name='nfe_debit_emission_enabled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Emissão NF-e de débito habilitada em'),
        ),
        migrations.AlterField(
            model_name='webmaniacompany',
            name='nfe_debit_emission_enabled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enabled_nfe_debit_emission_companies', to=settings.AUTH_USER_MODEL, verbose_name='Emissão NF-e de débito habilitada por'),
        ),
        migrations.AlterField(
            model_name='webmaniacompany',
            name='nfse_manual_emission_enabled',
            field=models.BooleanField(default=False, verbose_name='Emissão manual NFS-e habilitada'),
        ),
        migrations.AlterField(
            model_name='webmaniacompany',
            name='nfse_manual_emission_preview_enabled',
            field=models.BooleanField(default=False, verbose_name='Prévia de emissão manual NFS-e habilitada'),
        ),
        migrations.AlterField(
            model_name='webmaniacompany',
            name='nfse_substitution_preview_enabled',
            field=models.BooleanField(default=False, verbose_name='Prévia de substituição NFS-e habilitada'),
        ),
    ]
