# Generated by Django 5.2.9 on 2026-08-01 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0084_nferequestmanualitem_fiscal_snapshot_and_more'),
        ('finance', '0085_fix_finance_ui_verbose_names'),
    ]

    operations = [
    ]
