# Generated by Django 5.2.9 on 2026-08-03 02:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0086_merge_20260801_1957'),
        ('stock', '0016_stockimportfiscalitem_stockimport_fiscal_document_and_more'),
        ('workshops', '0036_merge_20260731_1613'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('current_step', models.PositiveSmallIntegerField(default=1, verbose_name='Etapa atual')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('ready', 'Intenção criada')], db_index=True, default='draft', max_length=16, verbose_name='Status')),
                ('ready_at', models.DateTimeField(blank=True, null=True, verbose_name='Intenção criada em')),
                ('fiscal_document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_return_request', to='finance.fiscaldocument', verbose_name='Documento fiscal de devolução')),
                ('original_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_return_requests', to='finance.fiscaldocument', verbose_name='Documento fiscal original')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_return_requests', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
                ('source_stock_import', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_return_requests', to='stock.stockimport', verbose_name='NF-e de compra')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_return_requests', to='workshops.workshop', verbose_name='Oficina')),
            ],
            options={
                'verbose_name': 'Intenção de devolução de compra',
                'verbose_name_plural': 'Intenções de devolução de compra',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Quantidade a devolver')),
                ('unit_value', models.DecimalField(decimal_places=4, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valor unitário')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.purchasereturnrequest', verbose_name='Intenção de devolução')),
                ('source_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_return_items', to='stock.stockimportfiscalitem', verbose_name='Item fiscal de origem')),
            ],
            options={
                'verbose_name': 'Item da intenção de devolução de compra',
                'verbose_name_plural': 'Itens da intenção de devolução de compra',
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='purchasereturnrequest',
            index=models.Index(fields=['workshop', 'status'], name='purchase_ret_workshop_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereturnrequest',
            index=models.Index(fields=['original_document', 'status'], name='purchase_ret_document_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchasereturnrequestitem',
            constraint=models.UniqueConstraint(fields=('request', 'source_item'), name='unique_purchase_return_source_item'),
        ),
    ]
