# Generated by Django 5.2.9 on 2026-08-03 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0087_purchasereturnrequest_purchasereturnrequestitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereturnrequest',
            name='additional_information',
            field=models.TextField(blank=True, default='', verbose_name='Informações complementares'),
        ),
        migrations.AddField(
            model_name='purchasereturnrequest',
            name='cfop',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='CFOP'),
        ),
        migrations.AddField(
            model_name='purchasereturnrequest',
            name='operation_nature',
            field=models.CharField(default='Devolução de mercadoria', max_length=255, verbose_name='Natureza da operação'),
        ),
        migrations.AddField(
            model_name='purchasereturnrequest',
            name='tax_class',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Classe de imposto'),
        ),
        migrations.AlterField(
            model_name='purchasereturnrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('ready', 'Pronta para emissão'), ('processing', 'Em processamento'), ('authorized', 'Autorizada'), ('rejected', 'Rejeitada'), ('communication_error', 'Erro de comunicação'), ('contingency', 'Contingência'), ('uncertain', 'Aguardando reconciliação'), ('canceled', 'Cancelada')], db_index=True, default='draft', max_length=24, verbose_name='Status'),
        ),
    ]
