# Generated by Django 5.2.9 on 2026-08-03 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0088_purchasereturnrequest_additional_information_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereturnrequest',
            name='stock_error',
            field=models.TextField(blank=True, default='', verbose_name='Erro de atualização do estoque'),
        ),
        migrations.AddField(
            model_name='purchasereturnrequest',
            name='stock_processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Estoque atualizado em'),
        ),
        migrations.AddField(
            model_name='purchasereturnrequest',
            name='stock_status',
            field=models.CharField(choices=[('waiting_authorization', 'Aguardando autorização fiscal'), ('pending', 'Aguardando baixa'), ('processed', 'Estoque atualizado'), ('error', 'Erro na atualização do estoque')], db_index=True, default='waiting_authorization', max_length=24, verbose_name='Status do estoque'),
        ),
    ]
