# Generated by Django 5.2.9 on 2026-08-03 05:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0089_purchasereturnrequest_stock_error_and_more'),
        ('stock', '0018_stockmovement_fiscal_document_and_more'),
        ('suppliers', '0010_fix_suppliers_ui_verbose_names'),
        ('workshops', '0042_merge_synplaisign_and_cost_leaves'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscaldocumentlink',
            name='role',
            field=models.CharField(choices=[('returns', 'Devolve'), ('reverses', 'Estorna'), ('complements', 'Complementa'), ('adjusts', 'Ajusta'), ('credits', 'Credita'), ('debits', 'Debita'), ('transports', 'Transporta')], db_index=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='fiscalemissionattempt',
            name='operation_type',
            field=models.CharField(choices=[('emission', 'Emissão'), ('cce', 'Carta de correção'), ('return', 'Devolução'), ('transport', 'Nota de Transporte'), ('reversal', 'Estorno'), ('complementary_price_quantity', 'Complementar preço/quantidade'), ('adjustment', 'Ajuste'), ('nfce_emission', 'Emissão NFC-e'), ('nfce_cancellation', 'Cancelamento NFC-e'), ('nfce_inutilization', 'Inutilização NFC-e'), ('nfe_ibs_cbs_event', 'Evento IBS/CBS'), ('nfe_ibs_cbs_event_cancellation', 'Cancelamento de evento IBS/CBS'), ('nfe_credit_emission', 'Emissão NF-e de crédito'), ('nfe_credit_cancellation', 'Cancelamento NF-e de crédito'), ('nfe_debit_emission', 'Emissão NF-e de débito'), ('nfe_debit_cancellation', 'Cancelamento NF-e de débito'), ('nfse_cancellation', 'Cancelamento NFS-e'), ('nfse_substitution', 'Substituição NFS-e'), ('nfse_manifestation', 'Manifestação NFS-e'), ('nfse_manual_emission', 'Emissão manual NFS-e')], db_index=True, default='emission', max_length=32),
        ),
        migrations.CreateModel(
            name='TransportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('current_step', models.PositiveSmallIntegerField(default=1, verbose_name='Etapa atual')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('ready', 'Pronta para emissão'), ('processing', 'Em processamento'), ('authorized', 'Autorizada'), ('rejected', 'Rejeitada'), ('communication_error', 'Erro de comunicação'), ('contingency', 'Contingência'), ('uncertain', 'Aguardando reconciliação'), ('canceled', 'Cancelada')], db_index=True, default='draft', max_length=24, verbose_name='Status')),
                ('ready_at', models.DateTimeField(blank=True, null=True, verbose_name='Intenção criada em')),
                ('operation_nature', models.CharField(default='Remessa para transporte', max_length=255, verbose_name='Natureza da operação')),
                ('cfop', models.CharField(blank=True, default='', max_length=8, verbose_name='CFOP')),
                ('tax_class', models.CharField(blank=True, default='', max_length=120, verbose_name='Classe de imposto')),
                ('additional_information', models.TextField(blank=True, default='', verbose_name='Informações complementares')),
                ('freight_mode', models.PositiveSmallIntegerField(default=3, verbose_name='Modalidade de frete')),
                ('transport_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Snapshot do transporte')),
                ('stock_status', models.CharField(choices=[('waiting_authorization', 'Aguardando autorização fiscal'), ('pending', 'Aguardando baixa'), ('processed', 'Estoque atualizado'), ('error', 'Erro na atualização do estoque')], db_index=True, default='waiting_authorization', max_length=24, verbose_name='Status do estoque')),
                ('stock_processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Estoque atualizado em')),
                ('stock_error', models.TextField(blank=True, default='', verbose_name='Erro de atualização do estoque')),
                ('fiscal_document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transport_request', to='finance.fiscaldocument', verbose_name='Documento fiscal de transporte')),
                ('original_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transport_requests', to='finance.fiscaldocument', verbose_name='Documento fiscal original')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_requests', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
                ('source_stock_import', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transport_requests', to='stock.stockimport', verbose_name='NF-e de entrada')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transport_requests', to='suppliers.supplier', verbose_name='Destinatário')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_requests', to='workshops.workshop', verbose_name='Oficina')),
            ],
            options={
                'verbose_name': 'Intenção de Nota de Transporte',
                'verbose_name_plural': 'Intenções de Nota de Transporte',
                'permissions': [('issue_nfe_transport', 'Pode emitir Nota de Transporte')],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransportRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))], verbose_name='Quantidade a transportar')),
                ('unit_value', models.DecimalField(decimal_places=4, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valor unitário')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.transportrequest', verbose_name='Intenção de transporte')),
                ('source_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transport_request_items', to='stock.stockimportfiscalitem', verbose_name='Item fiscal de origem')),
            ],
            options={
                'verbose_name': 'Item da intenção de transporte',
                'verbose_name_plural': 'Itens da intenção de transporte',
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='transportrequest',
            index=models.Index(fields=['workshop', 'status'], name='transport_req_workshop_idx'),
        ),
        migrations.AddIndex(
            model_name='transportrequest',
            index=models.Index(fields=['original_document', 'status'], name='transport_req_document_idx'),
        ),
        migrations.AddConstraint(
            model_name='transportrequestitem',
            constraint=models.UniqueConstraint(fields=('request', 'source_item'), name='unique_transport_request_source_item'),
        ),
    ]
