# Generated by Django 6.0 on 2026-08-10 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0047_backfill_workorder_financial_descriptions"),
        ("finance", "0091_merge_historical_fiscal_and_revert"),
    ]

    operations = []
