# Generated by Django 5.2.9 on 2026-01-08 01:54

import django.db.models.deletion
import localflavor.br.models
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('iam', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('cnpj', localflavor.br.models.BRCNPJField(blank=True, max_length=18, null=True, unique=True, verbose_name='CNPJ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workshops', to='accounts.account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkshopEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('cpf', localflavor.br.models.BRCPFField(max_length=14, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=50, verbose_name='RG')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('sex', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, verbose_name='Sexo')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Cargo')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Salário')),
                ('admission_date', models.DateField(blank=True, null=True, verbose_name='Data de Admissão')),
                ('termination_date', models.DateField(blank=True, null=True, verbose_name='Data de Saída')),
                ('employee_type', models.CharField(blank=True, choices=[('A', 'Administrativo'), ('P', 'Produtivo')], max_length=1, verbose_name='Tipo')),
                ('receives_commission', models.BooleanField(default=False, verbose_name='Recebe Comissão')),
                ('commission_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentual (0 a 100)', max_digits=5, null=True, verbose_name='Percentual de Comissão')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('system_access', models.BooleanField(default=False, verbose_name='Acesso ao Sistema')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshop_employee', to=settings.AUTH_USER_MODEL)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='workshops.workshop')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('workshop', 'cpf'), name='unique_employee_cpf_per_workshop'), models.CheckConstraint(condition=models.Q(('commission_percentage__isnull', True), models.Q(('commission_percentage__gte', 0), ('commission_percentage__lte', 100)), _connector='OR'), name='employee_commission_percentage_range')],
            },
        ),
        migrations.CreateModel(
            name='WorkshopMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workshop_members', to='iam.workshoprole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_members', to=settings.AUTH_USER_MODEL)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='workshops.workshop')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'workshop'), name='unique_user_workshop_member')],
            },
        ),
    ]
