# Generated by Django 5.2.9 on 2026-01-07 19:42

import django.db.models.deletion
import localflavor.br.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('cnpj', localflavor.br.models.BRCNPJField(blank=True, max_length=18, null=True, unique=True, verbose_name='CNPJ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workshops', to='accounts.account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
