# Generated by Django 5.2.9 on 2026-01-13 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_editable', models.BooleanField(default=True, verbose_name='Editável')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_costs', to='workshops.workshop')),
            ],
            options={
                'verbose_name': 'Custo Mensal',
                'verbose_name_plural': 'Custos Mensais',
                'constraints': [models.UniqueConstraint(fields=('workshop', 'name'), name='unique_monthly_cost_name_per_workshop')],
            },
        ),
    ]
