# Generated by Django 5.2.9 on 2026-01-13 19:35

import django.core.validators
import django.db.models.deletion
import djmoney.models.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0002_monthlycost'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('month', models.PositiveIntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], verbose_name='Mês')),
                ('year', models.PositiveIntegerField(verbose_name='Ano')),
                ('mechanic_quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Qtd. Mecânicos Produtivos')),
                ('work_hours_per_day', models.DurationField(verbose_name='Horas de trabalho/dia')),
                ('work_days_per_month', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)], verbose_name='Dias úteis/mês')),
                ('productivity_average', models.DecimalField(decimal_places=2, default=0.6, help_text='Ex: 0.60 para 60%', max_digits=5, verbose_name='Produtividade Média')),
                ('card_rate', models.DecimalField(decimal_places=6, default=0, max_digits=7, verbose_name='Taxa Cartão')),
                ('tax_rate', models.DecimalField(decimal_places=6, default=0, max_digits=7, verbose_name='Impostos')),
                ('profit_margin', models.DecimalField(decimal_places=6, default=0, max_digits=7, verbose_name='Margem de Lucro')),
                ('commission_rate', models.DecimalField(decimal_places=6, default=0, max_digits=7, verbose_name='Comissão')),
                ('risk_coefficient', models.DecimalField(decimal_places=2, default=1.0, help_text='1.0 a 1.2 para veículo popular, 1.2 a 1.4 para SUVs e 1.5 para premium, está relacionado ao risco da oficina.', max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(1.5)], verbose_name='Coeficiente de Risco')),
                ('parts_purchase_cap_currency', djmoney.models.fields.CurrencyField(choices=[('BRL', 'Real Brasileiro')], default='BRL', editable=False, max_length=3)),
                ('parts_purchase_cap', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14, verbose_name='Teto Compras Peças')),
                ('freight_cost_currency', djmoney.models.fields.CurrencyField(choices=[('BRL', 'Real Brasileiro')], default='BRL', editable=False, max_length=3)),
                ('freight_cost', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14, verbose_name='Frete')),
                ('third_party_service_cap_currency', djmoney.models.fields.CurrencyField(choices=[('BRL', 'Real Brasileiro')], default='BRL', editable=False, max_length=3)),
                ('third_party_service_cap', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14, verbose_name='Teto Serviços Terceiros')),
                ('total_value_currency', djmoney.models.fields.CurrencyField(choices=[('BRL', 'Real Brasileiro')], default='BRL', editable=False, max_length=3)),
                ('total_value', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Valor Total')),
                ('total_monthly_costs_currency', djmoney.models.fields.CurrencyField(choices=[('BRL', 'Real Brasileiro')], default='BRL', editable=False, max_length=3)),
                ('total_monthly_costs', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Total Custos Mensais')),
                ('profit_target_currency', djmoney.models.fields.CurrencyField(choices=[('BRL', 'Real Brasileiro')], default='BRL', editable=False, max_length=3)),
                ('profit_target', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Meta de Lucro')),
                ('gross_revenue_target_currency', djmoney.models.fields.CurrencyField(choices=[('BRL', 'Real Brasileiro')], default='BRL', editable=False, max_length=3)),
                ('gross_revenue_target', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Faturamento Bruto Meta')),
                ('profitability_multiplier', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Multiplicador Lucratividade')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_costs', to='workshops.workshop')),
            ],
            options={
                'verbose_name': 'Custo da Oficina',
                'verbose_name_plural': 'Custos da Oficina',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='WorkshopCostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('BRL', 'Real Brasileiro')], default='BRL', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14, verbose_name='Valor')),
                ('monthly_cost', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workshops.monthlycost')),
                ('workshop_cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='workshops.workshopcost')),
            ],
        ),
        migrations.AddConstraint(
            model_name='workshopcost',
            constraint=models.UniqueConstraint(fields=('workshop', 'month', 'year'), name='unique_workshop_cost_reference'),
        ),
        migrations.AlterUniqueTogether(
            name='workshopcostitem',
            unique_together={('workshop_cost', 'monthly_cost')},
        ),
    ]
