# Generated by Django 6.0 on 2026-01-14 14:13

import datetime
import django.core.validators
import djmoney.models.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshops", "0003_workshopcost_workshopcostitem_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workshopcost",
            name="card_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                default=0,
                max_digits=7,
                null=True,
                verbose_name="Taxa Cartão",
            ),
        ),
        migrations.AlterField(
            model_name="workshopcost",
            name="commission_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                default=0,
                help_text="Máximo 10%",
                max_digits=7,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(0.1),
                ],
                verbose_name="Comissão",
            ),
        ),
        migrations.AlterField(
            model_name="workshopcost",
            name="freight_cost",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                verbose_name="Frete",
            ),
        ),
        migrations.AlterField(
            model_name="workshopcost",
            name="freight_cost_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("BRL", "Real Brasileiro")],
                default="BRL",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="workshopcost",
            name="gross_revenue_target",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                max_digits=14,
                null=True,
                verbose_name="Faturamento Bruto Meta",
            ),
        ),
        migrations.AlterField(
            model_name="workshopcost",
            name="gross_revenue_target_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("BRL", "Real Brasileiro")],
                default="BRL",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="workshopcost",
            name="parts_purchase_cap",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                verbose_name="Teto Compras Peças",
            ),
        ),
        migrations.AlterField(
            model_name="workshopcost",
            name="parts_purchase_cap_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("BRL", "Real Brasileiro")],
                default="BRL",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="workshopcost",
            name="productivity_average",
            field=models.DecimalField(
                decimal_places=2,
                default=0.6,
                help_text="50% a 80%",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0.5),
                    django.core.validators.MaxValueValidator(0.8),
                ],
                verbose_name="Produtividade Média",
            ),
        ),
        migrations.AlterField(
            model_name="workshopcost",
            name="profit_margin",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                default=0,
                max_digits=7,
                null=True,
                verbose_name="Margem de Lucro",
            ),
        ),
        migrations.AlterField(
            model_name="workshopcost",
            name="profit_target",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                max_digits=14,
                null=True,
                verbose_name="Meta de Lucro",
            ),
        ),
        migrations.AlterField(
            model_name="workshopcost",
            name="profit_target_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("BRL", "Real Brasileiro")],
                default="BRL",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="workshopcost",
            name="profitability_multiplier",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="Multiplicador Lucratividade",
            ),
        ),
        migrations.AlterField(
            model_name="workshopcost",
            name="risk_coefficient",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=1.0,
                help_text="1.0 a 1.2 para veículo popular, 1.2 a 1.4 para SUVs e 1.5 para premium, está relacionado ao risco da oficina.",
                max_digits=3,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(1.5),
                ],
                verbose_name="Coeficiente de Risco",
            ),
        ),
        migrations.AlterField(
            model_name="workshopcost",
            name="tax_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                default=0,
                max_digits=7,
                null=True,
                verbose_name="Impostos",
            ),
        ),
        migrations.AlterField(
            model_name="workshopcost",
            name="third_party_service_cap",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                verbose_name="Teto Serviços Terceiros",
            ),
        ),
        migrations.AlterField(
            model_name="workshopcost",
            name="third_party_service_cap_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("BRL", "Real Brasileiro")],
                default="BRL",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="workshopcost",
            name="total_monthly_costs",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                max_digits=14,
                null=True,
                verbose_name="Total Custos Mensais",
            ),
        ),
        migrations.AlterField(
            model_name="workshopcost",
            name="total_monthly_costs_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("BRL", "Real Brasileiro")],
                default="BRL",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="workshopcost",
            name="total_value",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                max_digits=14,
                null=True,
                verbose_name="Valor Total",
            ),
        ),
        migrations.AlterField(
            model_name="workshopcost",
            name="total_value_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("BRL", "Real Brasileiro")],
                default="BRL",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="workshopcost",
            name="work_days_per_month",
            field=models.IntegerField(
                default=22,
                help_text="Máximo 31 dias",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(31),
                ],
                verbose_name="Dias úteis/mês",
            ),
        ),
        migrations.AlterField(
            model_name="workshopcost",
            name="work_hours_per_day",
            field=models.DurationField(
                default=8,
                help_text="Máximo 24h",
                validators=[
                    django.core.validators.MinValueValidator(datetime.timedelta(0)),
                    django.core.validators.MaxValueValidator(
                        datetime.timedelta(days=1)
                    ),
                ],
                verbose_name="Horas de trabalho/dia",
            ),
        ),
    ]
