# Generated by Django 6.0 on 2026-01-28 23:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0005_alter_monthlycost_atualizado_em_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopcost',
            name='productivity_average',
            field=models.DecimalField(decimal_places=4, default=0.6, help_text='50% a 80%', max_digits=5, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(0.8)], verbose_name='Produtividade Média'),
        ),
        migrations.AlterField(
            model_name='workshopcost',
            name='profitability_multiplier',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Multiplicador Lucratividade'),
        ),
    ]
