# Generated by Django 6.0 on 2026-01-29 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshops", "0005_alter_monthlycost_atualizado_em_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshop",
            name="pdf_observation",
            field=models.CharField(
                default="", max_length=250, verbose_name="Observação"
            ),
        ),
    ]
