# Generated by Django 6.0 on 2026-01-30 20:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshops", "0006_workshop_pdf_observation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workshopcost",
            name="productivity_average",
            field=models.DecimalField(
                decimal_places=4,
                default=0.6,
                help_text="50% a 80%",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0.5),
                    django.core.validators.MaxValueValidator(0.8),
                ],
                verbose_name="Produtividade Média",
            ),
        ),
        migrations.AlterField(
            model_name="workshopcost",
            name="profitability_multiplier",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                null=True,
                verbose_name="Multiplicador Lucratividade",
            ),
        ),
        migrations.AlterField(
            model_name="workshopcost",
            name="risk_coefficient",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=1.0,
                help_text="1,00 a 1,20 para veículo popular, 1,20 a 1,40 para SUVs e 1,50 para premium, está relacionado ao risco da oficina.",
                max_digits=3,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1.0),
                    django.core.validators.MaxValueValidator(1.5),
                ],
                verbose_name="Coeficiente de Risco",
            ),
        ),
    ]
