# Generated by Django 6.0 on 2026-02-04 18:26

import djmoney.models.fields
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0007_alter_workshopcost_productivity_average_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopcost',
            name='hourly_cost_value',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, null=True, verbose_name='Valor Sua Hora'),
        ),
        migrations.AddField(
            model_name='workshopcost',
            name='hourly_cost_value_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('BRL', 'Real Brasileiro')], default='BRL', editable=False, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='workshopcost',
            name='minimum_hourly_cost',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, null=True, verbose_name='Custo Hora Minímo'),
        ),
        migrations.AddField(
            model_name='workshopcost',
            name='minimum_hourly_cost_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('BRL', 'Real Brasileiro')], default='BRL', editable=False, max_length=3, null=True),
        ),
    ]
