# Generated by Django 6.0 on 2026-02-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0008_workshopcost_hourly_cost_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopcost',
            name='working_hours_per_month',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Horas Úteis/Mês'),
        ),
    ]
