# Generated by Django 6.0 on 2026-02-05 03:21

import datetime
import django.core.validators
import djmoney.models.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0009_workshopcost_working_hours_per_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopcost',
            name='minimum_hourly_cost',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, null=True, verbose_name='Custo Hora Mínimo'),
        ),
        migrations.AlterField(
            model_name='workshopcost',
            name='work_hours_per_day',
            field=models.DurationField(default=datetime.timedelta(seconds=28800), help_text='Máximo 24h', validators=[django.core.validators.MinValueValidator(datetime.timedelta(0)), django.core.validators.MaxValueValidator(datetime.timedelta(days=1))], verbose_name='Horas de trabalho/dia'),
        ),
        migrations.AlterField(
            model_name='workshopcost',
            name='working_hours_per_month',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Horas úteis/mês'),
        ),
    ]
