# Generated by Django 5.2.9 on 2026-02-08 00:00

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0010_alter_workshopcost_minimum_hourly_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshop",
            name="address",
            field=models.CharField(default="Não informado", max_length=255, verbose_name="Endereço"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workshop",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(default="+5511999999999", max_length=20, region="BR", verbose_name="Telefone"),
            preserve_default=False,
        ),
    ]
