# Generated by Django 6.0 on 2026-02-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshops", "0011_workshop_phone_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshop",
            name="certificate_password",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Senha do Certificado",
            ),
        ),
        migrations.AddField(
            model_name="workshop",
            name="last_nsu_sefaz",
            field=models.CharField(blank=True, default="0", null=True),
        ),
        migrations.AddField(
            model_name="workshop",
            name="last_sefaz_search_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workshop",
            name="pfx_certificate",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="certificados/",
                verbose_name="Certificado PFX",
            ),
        ),
        migrations.AddField(
            model_name="workshop",
            name="uf",
            field=models.CharField(default="SP", max_length=2, verbose_name="UF"),
        ),
    ]
