# Generated by Django 6.0 on 2026-02-10 15:16

import localflavor.br.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workshops", "0012_workshop_certificate_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workshop",
            name="cnpj",
            field=localflavor.br.models.BRCNPJField(
                max_length=18, unique=True, verbose_name="CNPJ"
            ),
        ),
    ]
