# Generated by Django 6.0 on 2026-03-08 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workshops", "0013_alter_workshop_cnpj"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workshop",
            options={"verbose_name": "Oficina", "verbose_name_plural": "Oficinas"},
        ),
        migrations.AlterModelOptions(
            name="workshopcostitem",
            options={
                "verbose_name": "Custo dos Itens da Oficina",
                "verbose_name_plural": "Custos dos Itens da Oficina",
            },
        ),
    ]
