# Generated by Django 6.0 on 2026-03-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0016_alter_workshop_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='certificate_content_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='workshop',
            name='certificate_file_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='workshop',
            name='certificate_mongo_file_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='workshop',
            name='certificate_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workshop',
            name='logo_content_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='workshop',
            name='logo_file_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='workshop',
            name='logo_mongo_file_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='workshop',
            name='logo_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
