# Generated by Django 6.0 on 2026-06-02 01:26

import calendar

import django.db.models.deletion
from django.db import migrations, models


def convert_holidays_to_work_days(apps, schema_editor):
    WorkshopCost = apps.get_model("workshops", "WorkshopCost")
    WorkshopCostHoliday = apps.get_model("workshops", "WorkshopCostHoliday")
    WorkshopCostWorkDay = apps.get_model("workshops", "WorkshopCostWorkDay")

    for workshop_cost in WorkshopCost.objects.all():
        holiday_dates = set(WorkshopCostHoliday.objects.filter(workshop_cost=workshop_cost).values_list("date", flat=True))
        year = workshop_cost.year
        month = workshop_cost.month
        days_in_month = calendar.monthrange(year, month)[1]
        work_days_to_create = []
        for day in range(1, days_in_month + 1):
            from datetime import date
            current_date = date(year, month, day)
            if current_date.weekday() < 5 and current_date not in holiday_dates:
                work_days_to_create.append(WorkshopCostWorkDay(workshop_cost=workshop_cost, date=current_date))
        if work_days_to_create:
            WorkshopCostWorkDay.objects.bulk_create(work_days_to_create)
        workshop_cost.work_days_per_month = len(work_days_to_create)
        workshop_cost.save(update_fields=["work_days_per_month"])


def convert_work_days_to_holidays(apps, schema_editor):
    WorkshopCost = apps.get_model("workshops", "WorkshopCost")
    WorkshopCostHoliday = apps.get_model("workshops", "WorkshopCostHoliday")
    WorkshopCostWorkDay = apps.get_model("workshops", "WorkshopCostWorkDay")

    for workshop_cost in WorkshopCost.objects.all():
        work_day_dates = set(WorkshopCostWorkDay.objects.filter(workshop_cost=workshop_cost).values_list("date", flat=True))
        year = workshop_cost.year
        month = workshop_cost.month
        days_in_month = calendar.monthrange(year, month)[1]
        holidays_to_create = []
        for day in range(1, days_in_month + 1):
            from datetime import date
            current_date = date(year, month, day)
            if current_date.weekday() < 5 and current_date not in work_day_dates:
                holidays_to_create.append(WorkshopCostHoliday(workshop_cost=workshop_cost, date=current_date))
        if holidays_to_create:
            WorkshopCostHoliday.objects.bulk_create(holidays_to_create)


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0023_workshopcostholiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopCostWorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data do dia trabalhado')),
                ('description', models.CharField(blank=True, max_length=120, verbose_name='Descricao')),
            ],
            options={
                'verbose_name': 'Dia Trabalhado do Custo da Oficina',
                'verbose_name_plural': 'Dias Trabalhados do Custo da Oficina',
                'ordering': ['date', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='workshopcostworkday',
            name='workshop_cost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_days', to='workshops.workshopcost'),
        ),
        migrations.AddConstraint(
            model_name='workshopcostworkday',
            constraint=models.UniqueConstraint(fields=('workshop_cost', 'date'), name='unique_workshop_cost_work_day_date'),
        ),
        migrations.RunPython(convert_holidays_to_work_days, convert_work_days_to_holidays),
        migrations.RemoveConstraint(
            model_name='workshopcostholiday',
            name='unique_workshop_cost_holiday_date',
        ),
        migrations.RemoveField(
            model_name='workshopcostholiday',
            name='workshop_cost',
        ),
        migrations.DeleteModel(
            name='WorkshopCostHoliday',
        ),
    ]
