# Generated by Django 6.0 on 2026-06-03 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0024_rename_workshopcostholiday_to_workday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='pdf_observation',
            field=models.TextField(default='', verbose_name='Observação'),
        ),
    ]
