# Generated by Django 6.0 on 2026-06-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0025_alter_workshop_pdf_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='whatsapp_instance_name',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Nome da instância WhatsApp'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='whatsapp_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone Assistente Virtual'),
        ),
    ]
