# Generated by Django 6.0 on 2026-06-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0026_add_whatsapp_instance_name"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='ALTER TABLE "workshops_workshop" ADD COLUMN IF NOT EXISTS "whatsapp_phone" varchar(20) NOT NULL DEFAULT \'\';',
                    reverse_sql='ALTER TABLE "workshops_workshop" DROP COLUMN IF EXISTS "whatsapp_phone";',
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="workshop",
                    name="whatsapp_phone",
                    field=models.CharField(blank=True, default="", max_length=20, verbose_name="Telefone Assistente Virtual"),
                ),
            ],
        ),
    ]
