# Generated by Django 6.0 on 2026-07-23 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0030_unify_transport_allowance_monthly_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='OilType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('validity_days', models.PositiveIntegerField(verbose_name='Validade do óleo (dias)')),
                ('validity_km', models.PositiveIntegerField(verbose_name='Validade do óleo (km)')),
                ('notification_lead_days', models.PositiveIntegerField(default=7, verbose_name='Antecedência da notificação (dias)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oil_types', to='workshops.workshop')),
            ],
            options={
                'verbose_name': 'Tipo de óleo',
                'verbose_name_plural': 'Tipos de óleo',
                'constraints': [models.UniqueConstraint(fields=('workshop', 'name'), name='unique_oil_type_name_per_workshop')],
            },
        ),
    ]
