# Generated by Django 6.0 on 2026-07-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0032_satisfaction_survey_delay_allow_immediate_nonprod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='satisfaction_survey_delay_days',
            field=models.SmallIntegerField(default=1, help_text='Quantidade de dias após o fechamento da O.S. para enviar o link de avaliação.', verbose_name='Dias após entrega para enviar pesquisa'),
        ),
    ]
