# Generated by Django 6.0 on 2026-07-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0033_workshop_outbound_business_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='google_review_min_rating',
            field=models.PositiveSmallIntegerField(default=4, help_text='Se a nota do cliente for igual ou maior que este valor (1–5), exibe o link do Google.', verbose_name='Nota mínima para pedir avaliação no Google'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='google_review_url',
            field=models.URLField(blank=True, default='', help_text='URL do Google Maps / Place para pedir avaliação pública.', max_length=500, verbose_name='Link de avaliação no Google'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='satisfaction_survey_delay_days',
            field=models.PositiveSmallIntegerField(default=1, help_text='Quantidade de dias após o fechamento da O.S. para enviar o link de avaliação.', verbose_name='Dias após entrega para enviar pesquisa'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='satisfaction_survey_enabled',
            field=models.BooleanField(default=False, verbose_name='Ativar pesquisa de satisfação'),
        ),
    ]
