# Generated by Django 6.0 on 2026-07-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0033_satisfaction_survey_delay_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='satisfaction_survey_send_immediately',
            field=models.BooleanField(default=False, help_text='Disponível apenas fora de produção. Agenda o envio no momento do fechamento da O.S.', verbose_name='Enviar pesquisa imediatamente'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='satisfaction_survey_delay_days',
            field=models.PositiveSmallIntegerField(default=1, help_text='Quantidade de dias após o fechamento da O.S. para enviar o link de avaliação.', verbose_name='Dias após entrega para enviar pesquisa'),
        ),
    ]
