# Generated by Django 6.0 on 2026-07-25 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0034_typed_templates_and_satisfaction_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='satisfaction_survey_delay_days',
            field=models.SmallIntegerField(default=1, help_text='Quantidade de dias após o fechamento da O.S. para enviar o link de avaliação. Em ambientes não produtivos, use -1 para enviar imediatamente.', verbose_name='Dias após entrega para enviar pesquisa'),
        ),
    ]
