# Generated by Django 5.2.9 on 2026-08-01 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0031_alter_workshopcost_total_monthly_costs_and_more'),
        ('workshops', '0035_review_plan_and_messaging_updates'),
    ]

    operations = [
    ]
