# Generated by Django 6.0 on 2026-07-31 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workshops", "0030_unify_transport_allowance_monthly_cost"),
        ("workshops", "0035_review_plan_and_messaging_updates"),
    ]

    operations = []
