# Generated by Django 5.2.9 on 2026-08-01 02:50

import djmoney.models.fields
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0036_merge_20260731_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopcost',
            name='total_monthly_costs',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, null=True, verbose_name='Total Custos Mensais'),
        ),
        migrations.AlterField(
            model_name='workshopcost',
            name='total_value',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, null=True, verbose_name='Valor Total'),
        ),
    ]
