# Generated by Django 6.0 on 2026-08-01 02:32

import djmoney.models.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshops", "0036_merge_20260731_1613"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workshopcost",
            name="gross_revenue_target",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                max_digits=14,
                null=True,
                verbose_name="Meta de Faturamento Mensal",
            ),
        ),
        migrations.AlterField(
            model_name="workshopcost",
            name="profit_margin",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                default=0,
                max_digits=7,
                null=True,
                verbose_name="Margem de lucro desejada sobre a hora",
            ),
        ),
        migrations.AlterField(
            model_name="workshopcost",
            name="profit_target",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                max_digits=14,
                null=True,
                verbose_name="Meta de Lucro Mensal",
            ),
        ),
        migrations.AlterField(
            model_name="workshopcost",
            name="total_monthly_costs",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                max_digits=14,
                null=True,
                verbose_name="Total Despesas Mensais + Impostos + Taxas e Coeficiente de Risco",
            ),
        ),
        migrations.AlterField(
            model_name="workshopcost",
            name="total_value",
            field=djmoney.models.fields.MoneyField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                max_digits=14,
                null=True,
                verbose_name="Total",
            ),
        ),
    ]
