# Generated by Django 6.0 on 2026-08-01 22:36

import django.core.validators
import djmoney.models.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0037_alter_workshopcost_total_monthly_costs_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlycost',
            options={'verbose_name': 'Custo mensal', 'verbose_name_plural': 'Custos mensais'},
        ),
        migrations.AlterModelOptions(
            name='workshopcost',
            options={'ordering': ['-year', '-month'], 'verbose_name': 'Custo da oficina', 'verbose_name_plural': 'Custos da oficina'},
        ),
        migrations.AlterModelOptions(
            name='workshopcostitem',
            options={'verbose_name': 'Custo dos itens da oficina', 'verbose_name_plural': 'Custos dos itens da oficina'},
        ),
        migrations.AlterModelOptions(
            name='workshopcostworkday',
            options={'ordering': ['date', 'pk'], 'verbose_name': 'Dia trabalhado do custo da oficina', 'verbose_name_plural': 'Dias trabalhados do custo da oficina'},
        ),
        migrations.AlterField(
            model_name='workshop',
            name='certificate_password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Senha do certificado'),
        ),
        migrations.AlterField(
            model_name='workshopcost',
            name='card_rate',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=7, null=True, verbose_name='Taxa cartão'),
        ),
        migrations.AlterField(
            model_name='workshopcost',
            name='gross_revenue_target',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, null=True, verbose_name='Faturamento bruto meta'),
        ),
        migrations.AlterField(
            model_name='workshopcost',
            name='hourly_cost_value',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, null=True, verbose_name='Valor sua hora'),
        ),
        migrations.AlterField(
            model_name='workshopcost',
            name='mechanic_quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Qtd. mecânicos produtivos'),
        ),
        migrations.AlterField(
            model_name='workshopcost',
            name='minimum_hourly_cost',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, null=True, verbose_name='Custo hora mínimo'),
        ),
        migrations.AlterField(
            model_name='workshopcost',
            name='parts_purchase_cap',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Teto compras peças'),
        ),
        migrations.AlterField(
            model_name='workshopcost',
            name='productivity_average',
            field=models.DecimalField(decimal_places=4, default=0.6, help_text='50% a 80%', max_digits=5, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(0.8)], verbose_name='Produtividade média'),
        ),
        migrations.AlterField(
            model_name='workshopcost',
            name='profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=7, null=True, verbose_name='Margem de lucro'),
        ),
        migrations.AlterField(
            model_name='workshopcost',
            name='profit_target',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, null=True, verbose_name='Meta de lucro'),
        ),
        migrations.AlterField(
            model_name='workshopcost',
            name='profitability_multiplier',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Multiplicador lucratividade'),
        ),
        migrations.AlterField(
            model_name='workshopcost',
            name='risk_coefficient',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, help_text='1,00 a 1,20 para veículo popular, 1,20 a 1,40 para SUVs e 1,50 para premium, está relacionado ao risco da oficina.', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(1.5)], verbose_name='Coeficiente de risco'),
        ),
        migrations.AlterField(
            model_name='workshopcost',
            name='third_party_service_cap',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Teto serviços terceiros'),
        ),
        migrations.AlterField(
            model_name='workshopcost',
            name='total_monthly_costs',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, null=True, verbose_name='Total custos mensais'),
        ),
        migrations.AlterField(
            model_name='workshopcost',
            name='total_value',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, null=True, verbose_name='Valor total'),
        ),
        migrations.AlterField(
            model_name='workshopcostworkday',
            name='description',
            field=models.CharField(blank=True, max_length=120, verbose_name='Descrição'),
        ),
    ]
