# Generated by Django 6.0 on 2026-08-02 22:49

import djmoney.models.fields
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0037_workshop_synplaisign_credentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopcost',
            name='total_monthly_costs',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, null=True, verbose_name='Total Despesas Mensais'),
        ),
        migrations.AlterField(
            model_name='workshopcost',
            name='total_value',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, null=True, verbose_name='Total Metas e Indicadores'),
        ),
    ]
