# Generated by Django 5.2.9 on 2026-08-01 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0037_alter_workshopcost_gross_revenue_target_and_more'),
        ('workshops', '0037_alter_workshopcost_total_monthly_costs_and_more'),
    ]

    operations = [
    ]
