# Generated by Django 5.2.9 on 2026-08-01 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0036_merge_20260731_1613'),
        ('workshops', '0037_alter_workshopcost_total_monthly_costs_and_more'),
    ]

    operations = [
    ]
