# Generated by Django 5.2.9 on 2026-08-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0038_merge_20260801_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopcost',
            name='profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=7, null=True, verbose_name='Margem de Lucro Desejada Sobre a Hora'),
        ),
    ]
