# Generated by Django 5.2.9 on 2026-08-01 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0038_fix_workshops_ui_verbose_names'),
        ('workshops', '0038_merge_20260801_1921'),
    ]

    operations = [
    ]
