# Generated by Django 6.0 on 2026-08-03 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0039_workshop_synplaisign_owner_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='google_review_min_rating',
            field=models.PositiveSmallIntegerField(default=4, help_text='Se a nota do cliente for igual ou maior que este valor (1-5), exibe o link do Google.', verbose_name='Nota mínima para pedir avaliação no Google'),
        ),
    ]
