# Generated by Django 6.0 on 2026-08-03 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0037_alter_workshopcost_gross_revenue_target_and_more'),
        ('workshops', '0040_alter_workshop_google_review_min_rating'),
    ]

    operations = [
    ]
