# Generated by Django 6.0 on 2026-08-03 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0041_merge_workshopcost_and_synplaisign_branches'),
        ('workshops', '0042_merge_synplaisign_and_cost_leaves'),
    ]

    operations = [
    ]
