# Generated by Django 6.0 on 2026-08-16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshops", "0044_outbound_business_weekdays_all_days"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkshopCommissionSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "workorder_commission_enabled",
                    models.BooleanField(
                        default=False, verbose_name="Comissão por OS habilitada"
                    ),
                ),
                (
                    "workorder_commission_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=7,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                        verbose_name="Percentual da Comissão por OS",
                    ),
                ),
                (
                    "workshop",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commission_settings",
                        to="workshops.workshop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de Comissão da Oficina",
                "verbose_name_plural": "Configurações de Comissão da Oficina",
                "abstract": False,
            },
        ),
    ]