# Generated by Django 6.0 on 2026-08-18 21:55

import djmoney.models.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0044_outbound_business_weekdays_all_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopcost',
            name='profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=7, null=True, verbose_name='Margem de Lucro Desejada Sobre a Hora'),
        ),
        migrations.AlterField(
            model_name='workshopcost',
            name='total_monthly_costs',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, null=True, verbose_name='Total Despesas Mensais + Impostos + Taxas e Coeficiente de Risco'),
        ),
        migrations.AlterField(
            model_name='workshopcost',
            name='total_value',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=14, null=True, verbose_name='Total'),
        ),
    ]
