# Generated by Django 5.2.9 on 2026-09-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workshops", "0045_add_workshop_commission_limits"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshop",
            name="last_sefaz_sync_attempt_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workshop",
            name="last_sefaz_sync_message",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="workshop",
            name="last_sefaz_sync_status",
            field=models.CharField(choices=[("NEVER", "Nunca sincronizada"), ("SUCCESS", "Sincronizada"), ("ERROR", "Falha na sincronização")], default="NEVER", max_length=16),
        ),
    ]
