# Generated by Django 6.0 on 2026-08-22 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("budget", "0069_merge_budget_cancellation_responsible"),
        ("workshops", "0044_outbound_business_weekdays_all_days"),
    ]

    operations = [
        migrations.CreateModel(
            name="TermTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="Data de Criação")),
                ("atualizado_em", models.DateTimeField(auto_now=True, verbose_name="Data de Atualização")),
                ("name", models.CharField(max_length=255, verbose_name="Nome do termo")),
                ("kind", models.CharField(choices=[("receipt", "Termo de Recebimento"), ("warranty", "Termo de Garantia"), ("other", "Outro")], default="receipt", max_length=20, verbose_name="Tipo")),
                ("source", models.CharField(choices=[("html", "Texto na plataforma"), ("pdf", "Arquivo PDF")], default="html", max_length=10, verbose_name="Origem")),
                ("body_html", models.TextField(blank=True, default="", verbose_name="Conteúdo")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                ("pdf_file_key", models.CharField(blank=True, default="", max_length=512)),
                ("pdf_file_name", models.CharField(blank=True, default="", max_length=255)),
                ("pdf_content_type", models.CharField(blank=True, default="", max_length=100)),
                ("pdf_uploaded_at", models.DateTimeField(blank=True, null=True)),
                ("workshop", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="term_templates", to="workshops.workshop")),
            ],
            options={
                "verbose_name": "Termo",
                "verbose_name_plural": "Termos",
                "ordering": ("-criado_em",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BudgetTermSigning",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="Data de Criação")),
                ("atualizado_em", models.DateTimeField(auto_now=True, verbose_name="Data de Atualização")),
                ("rendered_html", models.TextField(blank=True, default="")),
                ("signature_request_status", models.CharField(choices=[("not_sent", "Não Enviado"), ("sending", "Enviando"), ("sent", "Enviado"), ("failed", "Falha no Envio"), ("approved", "Assinado"), ("declined", "Recusado")], default="not_sent", max_length=20)),
                ("signature_external_id", models.CharField(blank=True, default="", max_length=255)),
                ("signature_document_id", models.CharField(blank=True, default="", max_length=255)),
                ("signature_sent_at", models.DateTimeField(blank=True, null=True)),
                ("budget", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="term_signings", to="budget.budget")),
                ("workshop", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="budget_term_signings", to="workshops.workshop")),
                ("template", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="signings", to="terms.termtemplate")),
            ],
            options={
                "verbose_name": "Assinatura de termo",
                "verbose_name_plural": "Assinaturas de termos",
                "abstract": False,
                "constraints": [models.UniqueConstraint(fields=("budget", "template"), name="unique_budget_term_template_signing")],
            },
        ),
    ]
