# Generated by Django 6.0 on 2026-08-30 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget', '0071_merge_excluded_composition_and_freight'),
        ('workorder', '0055_merge_warranty_origin_and_os_tip'),
        ('workshops', '0045_add_workshop_commission_limits'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopTermTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('template_type', models.CharField(choices=[('vehicle_receipt', 'Termo de Recebimento de Veículo'), ('warranty', 'Termo de Garantia')], max_length=32, verbose_name='Tipo')),
                ('name', models.CharField(max_length=120, verbose_name='Nome interno')),
                ('document_title', models.CharField(max_length=255, verbose_name='Título do documento')),
                ('subtitle', models.CharField(blank=True, default='', max_length=255, verbose_name='Subtítulo')),
                ('intro_text', models.TextField(blank=True, default='', verbose_name='Texto de introdução')),
                ('primary_color', models.CharField(default='#000000', max_length=7, verbose_name='Cor principal')),
                ('accent_color', models.CharField(default='#DC2626', max_length=7, verbose_name='Cor de destaque')),
                ('text_color', models.CharField(default='#111827', max_length=7, verbose_name='Cor do texto')),
                ('muted_color', models.CharField(default='#6B7280', max_length=7, verbose_name='Cor secundária')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_default', models.BooleanField(default=False, verbose_name='Padrão')),
                ('content', models.JSONField(blank=True, default=dict, verbose_name='Conteúdo')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_templates', to='workshops.workshop', verbose_name='Oficina')),
            ],
            options={
                'verbose_name': 'Termo da oficina',
                'verbose_name_plural': 'Termos da oficina',
                'ordering': ('template_type', 'name'),
            },
        ),
        migrations.CreateModel(
            name='WorkOrderTermSigning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('signature_token_version', models.PositiveIntegerField(default=1, verbose_name='Versão do token')),
                ('signature_token_active', models.BooleanField(default=True, verbose_name='Token ativo')),
                ('signature_request_status', models.CharField(choices=[('not_sent', 'Não Enviado'), ('sending', 'Enviando'), ('sent', 'Enviado'), ('failed', 'Falha no Envio'), ('approved', 'Aprovado')], default='not_sent', max_length=30)),
                ('signature_external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('signature_document_id', models.CharField(blank=True, max_length=255, null=True)),
                ('signature_sent_at', models.DateTimeField(blank=True, null=True)),
                ('content_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Snapshot do conteúdo')),
                ('workorder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='term_signing', to='workorder.workorder', verbose_name='Ordem de serviço')),
                ('term_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workorder_signings', to='terms.workshoptermtemplate', verbose_name='Termo selecionado')),
            ],
            options={
                'verbose_name': 'Assinatura de termo da ordem de serviço',
                'verbose_name_plural': 'Assinaturas de termo da ordem de serviço',
            },
        ),
        migrations.CreateModel(
            name='BudgetTermSigning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('signature_token_version', models.PositiveIntegerField(default=1, verbose_name='Versão do token')),
                ('signature_token_active', models.BooleanField(default=True, verbose_name='Token ativo')),
                ('signature_request_status', models.CharField(choices=[('not_sent', 'Não Enviado'), ('sending', 'Enviando'), ('sent', 'Enviado'), ('failed', 'Falha no Envio'), ('approved', 'Aprovado')], default='not_sent', max_length=30)),
                ('signature_external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('signature_document_id', models.CharField(blank=True, max_length=255, null=True)),
                ('signature_sent_at', models.DateTimeField(blank=True, null=True)),
                ('content_snapshot', models.JSONField(blank=True, default=dict, verbose_name='Snapshot do conteúdo')),
                ('budget', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='term_signing', to='budget.budget', verbose_name='Orçamento')),
                ('term_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_signings', to='terms.workshoptermtemplate', verbose_name='Termo selecionado')),
            ],
            options={
                'verbose_name': 'Assinatura de termo do orçamento',
                'verbose_name_plural': 'Assinaturas de termo do orçamento',
            },
        ),
        migrations.AddIndex(
            model_name='workshoptermtemplate',
            index=models.Index(fields=['workshop', 'template_type', 'is_active'], name='terms_works_worksho_840857_idx'),
        ),
    ]
