# Generated by Django 6.0 on 2026-08-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshoptermtemplate',
            name='accent_color',
            field=models.CharField(default='#E30613', max_length=7, verbose_name='Cor de destaque'),
        ),
    ]
