# Generated by Django 6.0 on 2026-08-22 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("terms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="termtemplate",
            name="intro_text",
            field=models.TextField(blank=True, default="", help_text="Aparece após os dados do veículo. Use linguagem simples; os dados do cliente e do veículo entram sozinhos no documento.", verbose_name="Texto de introdução"),
        ),
        migrations.CreateModel(
            name="TermTopic",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, verbose_name="Tópico")),
                ("order", models.PositiveIntegerField(default=0)),
                ("template", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="topics", to="terms.termtemplate")),
            ],
            options={
                "verbose_name": "Tópico do termo",
                "verbose_name_plural": "Tópicos do termo",
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="TermBullet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField(verbose_name="Texto")),
                ("order", models.PositiveIntegerField(default=0)),
                ("topic", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="bullets", to="terms.termtopic")),
            ],
            options={
                "verbose_name": "Texto do tópico",
                "verbose_name_plural": "Textos do tópico",
                "ordering": ("order", "id"),
            },
        ),
    ]
