# Generated by Django 6.0 on 2026-08-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0002_term_topics_and_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='termtemplate',
            name='accent_color',
            field=models.CharField(default='#e30613', help_text='Usada em faixas, numeração e marcadores do documento.', max_length=7, verbose_name='Cor de destaque'),
        ),
        migrations.AddField(
            model_name='termtemplate',
            name='primary_color',
            field=models.CharField(default='#000000', help_text='Usada no cabeçalho e barras escuras do documento.', max_length=7, verbose_name='Cor principal'),
        ),
    ]
