from __future__ import annotations

from .financial_group import FinancialGroupCreateView, FinancialGroupDeleteView, FinancialGroupListView, FinancialGroupUpdateView
from .fiscal_referenced_basis import FiscalReferencedBasisApproveView, FiscalReferencedBasisCreateView, FiscalReferencedBasisDetailView, FiscalReferencedBasisFeatureToggleView, FiscalReferencedBasisListView, FiscalReferencedBasisPayloadView
from .fiscal_credit_product_preview import FiscalCreditProductPreviewApproveView, FiscalCreditProductPreviewCreateView, FiscalCreditProductPreviewDetailView, FiscalCreditProductPreviewListView, FiscalCreditProductPreviewPayloadView
from .fiscal_debit_product_preview import (
    FiscalDebitProductPreviewApproveView as FiscalDebitProductPreviewApproveView,
    FiscalDebitProductPreviewCreateView as FiscalDebitProductPreviewCreateView,
    FiscalDebitProductPreviewDetailView as FiscalDebitProductPreviewDetailView,
    FiscalDebitProductPreviewListView as FiscalDebitProductPreviewListView,
    FiscalDebitProductPreviewPayloadView as FiscalDebitProductPreviewPayloadView,
)
from .nfe_credit import NfeCreditCancellationDownloadView, NfeCreditCancellationPayloadView, NfeCreditCancellationView, NfeCreditDownloadView, NfeCreditIssueView, NfeCreditPayloadView
from .nfe_debit import NfeDebitCancellationDownloadView as NfeDebitCancellationDownloadView, NfeDebitCancellationPayloadView as NfeDebitCancellationPayloadView, NfeDebitCancellationView as NfeDebitCancellationView, NfeDebitDownloadView as NfeDebitDownloadView, NfeDebitEmissionFeatureToggleView as NfeDebitEmissionFeatureToggleView, NfeDebitIssueView as NfeDebitIssueView, NfeDebitPayloadView as NfeDebitPayloadView
from .common import DirectorWorkshopAccessMixin
from .emission import EmissionPreviewView, EmissionRequestCreateView, EmissionWorkOrderItemUpdateView, EmissionWorkOrderKitComponentUpdateView, NfeCreateRedirectView, NfseCreateRedirectView
from .fiscal_gateway import FiscalOperationGatewayView, NfeEmissionOriginGatewayView
from .nfe_manual import NfeManualEmissionCreateView, NfeManualQuickProductCreateView, NfeManualTransmissionView
from .purchase_return import PurchaseReturnCreateView, PurchaseReturnPreviewPdfView, PurchaseReturnPreviewView, PurchaseReturnTransmitView, PurchaseReturnWorkflowView
from .transport_request import TransportCreateView, TransportPreviewPdfView, TransportPreviewView, TransportTransmitView, TransportWorkflowView
from .issued_documents import IssuedDocumentsArchiveDownloadView, IssuedDocumentsListView
from .commissions import CommissionReportView, CommissionReportPdfView
from .nfe import (
    NfeAdjustmentDownloadView,
    NfeAdjustmentIssueView,
    NfeComplementaryDownloadView,
    NfeComplementaryPriceQuantityIssueView,
    NfeCorrectionDownloadView,
    NfeCorrectionIssueView,
    NfeCorrectionPayloadView,
    NfeDocumentDownloadView,
    NfeIbsCbsEvent112110CancelView,
    NfeIbsCbsEvent112110IssueView,
    NfeIbsCbsEvent112130CancelView,
    NfeIbsCbsEvent112130IssueView,
    NfeIbsCbsEvent112150CancelView,
    NfeIbsCbsEvent112150IssueView,
    NfeIbsCbsEventDownloadView,
    NfeIbsCbsEventPayloadView,
    NfePreviewPdfView,
    NfeRequestCancelView,
    NfeRequestCreateView,
    NfeRequestDetailView,
    NfeRequestInvalidateView,
    NfeRequestListView,
    NfeRequestReconcileView,
    NfeRequestUpdateView,
    NfeReturnDownloadView,
    NfeReturnIssueView,
    NfeReturnPayloadView,
)
from .nfce import (
    NfceCancellationDownloadView,
    NfceCancellationView,
    NfceDocumentDownloadView,
    NfceDocumentListView,
    NfceDocumentPayloadView,
    NfceInutilizationDownloadView,
    NfceInutilizationPayloadView,
    NfceInutilizationView,
    NfceManualEmissionView,
)
from .nfse import (
    NfseBatchReconcileView,
    NfseCancellationDownloadView,
    NfseCancellationPayloadView,
    NfseDocumentDownloadView,
    NfseManifestationDownloadView,
    NfseManifestationIssueView,
    NfseManifestationPayloadView,
    NfsePreviewPdfView,
    NfseRequestCancelView,
    NfseRequestCreateView,
    NfseRequestDetailView,
    NfseRequestListView,
    NfseRequestReconcileView,
    NfseRequestUpdateView,
)
from .nfse_capabilities import NfseMunicipalCapabilityCreateView, NfseMunicipalCapabilityListView, NfseMunicipalCapabilityStatusView, NfseMunicipalCapabilityUpdateView
from .nfse_manual_emission import (
    NfseManualEmissionCancelView,
    NfseManualEmissionCancellationDownloadView,
    NfseManualEmissionCancellationPayloadView,
    NfseManualEmissionDetailView,
    NfseManualEmissionDownloadView,
    NfseManualEmissionIssueView,
    NfseManualEmissionListView,
    NfseManualEmissionPayloadView,
    NfseManualEmissionReconcileView,
)
from .nfse_manual_emission_preview import (
    NfseManualEmissionPreviewApproveView,
    NfseManualEmissionPreviewCreateView,
    NfseManualEmissionPreviewDetailView,
    NfseManualEmissionPreviewListView,
    NfseManualEmissionPreviewPayloadView,
)
from .nfse_received import (
    NfseExternalXmlInboxBulkActionView,
    NfseExternalXmlInboxDetailView,
    NfseExternalXmlInboxExportView,
    NfseExternalXmlInboxItemApproveView,
    NfseExternalXmlInboxItemDiscardView,
    NfseExternalXmlInboxItemPayloadView,
    NfseExternalXmlInboxListView,
    NfseExternalXmlInboxProcessView,
    NfseExternalXmlInboxUploadView,
    NfseReceivedDocumentBatchImportView,
    NfseReceivedDocumentConsultationIssueView,
    NfseReceivedDocumentConsultationPayloadView,
    NfseReceivedDocumentDetailView,
    NfseReceivedDocumentImportView,
    NfseReceivedDocumentListView,
    NfseReceivedDocumentManifestationDownloadView,
    NfseReceivedDocumentManifestationIssueView,
    NfseReceivedDocumentManifestationPayloadView,
    NfseReceivedDocumentPayloadView,
    NfseReceivedDocumentXmlDownloadView,
    NfseReceivedImportBatchDetailView,
)
from .nfse_substitution_preview import (
    NfseSubstitutionDownloadView,
    NfseSubstitutionIssueView,
    NfseSubstitutionPayloadView,
    NfseSubstitutionPreviewApproveView,
    NfseSubstitutionPreviewCreateView,
    NfseSubstitutionPreviewDetailView,
    NfseSubstitutionPreviewListView,
    NfseSubstitutionPreviewPayloadView,
)
from .payroll import PayrollBulkConciliateView, PayrollBulkPayView, PayrollBulkUnpayView, PayrollEditModalView, PayrollListView, PayrollRefreshView
from .reports import FinancialReportsHomeView, ReportMovementEditView, ReportMovementDeleteView
from .tax_class import TaxClassCreateView, TaxClassDeleteView, TaxClassListView, TaxClassManagerView, TaxClassPresetCreateView, TaxClassPresetListView, TaxClassPresetUpdateView, TaxClassUpdateView
from .webhook import WebhookView
from .webmania import (
    WebmaniaCompanyDetailView,
    WebmaniaCompanyListView,
    WebmaniaCompanySyncView,
    WebmaniaCompanyUpdateView,
    WebmaniaRequestsView,
)
from .dre import DreExcelView, DrePdfPreviewView, DrePdfView, DreReportView, DreResultsView


def sync_b2b_companies_to_database(*args, **kwargs):
    from apps.core.infrastructure.providers import get_fiscal_service

    return get_fiscal_service().sync_b2b_companies_to_database(*args, **kwargs)


__all__ = [
    "DirectorWorkshopAccessMixin",
    "EmissionPreviewView",
    "EmissionRequestCreateView",
    "FiscalOperationGatewayView",
    "NfeEmissionOriginGatewayView",
    "NfeManualEmissionCreateView",
    "NfeManualQuickProductCreateView",
    "NfeManualTransmissionView",
    "PurchaseReturnCreateView",
    "PurchaseReturnPreviewPdfView",
    "PurchaseReturnPreviewView",
    "PurchaseReturnTransmitView",
    "PurchaseReturnWorkflowView",
    "TransportCreateView",
    "TransportPreviewPdfView",
    "TransportPreviewView",
    "TransportTransmitView",
    "TransportWorkflowView",
    "EmissionWorkOrderKitComponentUpdateView",
    "EmissionWorkOrderItemUpdateView",
    "FinancialGroupCreateView",
    "FinancialGroupDeleteView",
    "FinancialGroupListView",
    "FinancialReportsHomeView",
    "ReportMovementEditView",
    "ReportMovementDeleteView",
    "PayrollBulkConciliateView",
    "PayrollBulkPayView",
    "PayrollBulkUnpayView",
    "PayrollEditModalView",
    "PayrollListView",
    "PayrollRefreshView",
    "FinancialGroupUpdateView",
    "FiscalReferencedBasisApproveView",
    "FiscalReferencedBasisCreateView",
    "FiscalReferencedBasisDetailView",
    "FiscalReferencedBasisFeatureToggleView",
    "FiscalReferencedBasisListView",
    "FiscalReferencedBasisPayloadView",
    "FiscalCreditProductPreviewApproveView",
    "FiscalCreditProductPreviewCreateView",
    "FiscalCreditProductPreviewDetailView",
    "FiscalCreditProductPreviewListView",
    "FiscalCreditProductPreviewPayloadView",
    "NfeCreditDownloadView",
    "NfeCreditIssueView",
    "NfeCreditPayloadView",
    "NfeCreditCancellationView",
    "NfeCreditCancellationPayloadView",
    "NfeCreditCancellationDownloadView",
    "IssuedDocumentsArchiveDownloadView",
    "IssuedDocumentsListView",
    "CommissionReportView",
    "CommissionReportPdfView",
    "NfeCreateRedirectView",
    "NfeAdjustmentDownloadView",
    "NfeAdjustmentIssueView",
    "NfeComplementaryDownloadView",
    "NfeComplementaryPriceQuantityIssueView",
    "NfeCorrectionDownloadView",
    "NfeCorrectionIssueView",
    "NfeCorrectionPayloadView",
    "NfeDocumentDownloadView",
    "NfeIbsCbsEvent112110CancelView",
    "NfeIbsCbsEvent112110IssueView",
    "NfeIbsCbsEvent112130CancelView",
    "NfeIbsCbsEvent112130IssueView",
    "NfeIbsCbsEvent112150CancelView",
    "NfeIbsCbsEvent112150IssueView",
    "NfeIbsCbsEventDownloadView",
    "NfeIbsCbsEventPayloadView",
    "NfePreviewPdfView",
    "NfeRequestCancelView",
    "NfeRequestCreateView",
    "NfeRequestDetailView",
    "NfeRequestInvalidateView",
    "NfeRequestListView",
    "NfeRequestReconcileView",
    "NfeRequestUpdateView",
    "NfeReturnDownloadView",
    "NfeReturnIssueView",
    "NfeReturnPayloadView",
    "NfceDocumentDownloadView",
    "NfceDocumentListView",
    "NfceDocumentPayloadView",
    "NfceInutilizationDownloadView",
    "NfceInutilizationPayloadView",
    "NfceInutilizationView",
    "NfceManualEmissionView",
    "NfceCancellationDownloadView",
    "NfceCancellationView",
    "NfseCreateRedirectView",
    "NfseRequestCancelView",
    "NfseCancellationPayloadView",
    "NfseCancellationDownloadView",
    "NfseBatchReconcileView",
    "NfseDocumentDownloadView",
    "NfseManifestationDownloadView",
    "NfseManifestationIssueView",
    "NfseManifestationPayloadView",
    "NfsePreviewPdfView",
    "NfseRequestCreateView",
    "NfseRequestDetailView",
    "NfseRequestListView",
    "NfseRequestReconcileView",
    "NfseRequestUpdateView",
    "NfseMunicipalCapabilityCreateView",
    "NfseMunicipalCapabilityListView",
    "NfseMunicipalCapabilityStatusView",
    "NfseMunicipalCapabilityUpdateView",
    "NfseManualEmissionPreviewApproveView",
    "NfseManualEmissionPreviewCreateView",
    "NfseManualEmissionPreviewDetailView",
    "NfseManualEmissionPreviewListView",
    "NfseManualEmissionPreviewPayloadView",
    "NfseManualEmissionDetailView",
    "NfseManualEmissionDownloadView",
    "NfseManualEmissionCancelView",
    "NfseManualEmissionCancellationDownloadView",
    "NfseManualEmissionCancellationPayloadView",
    "NfseManualEmissionIssueView",
    "NfseManualEmissionListView",
    "NfseManualEmissionPayloadView",
    "NfseManualEmissionReconcileView",
    "NfseExternalXmlInboxDetailView",
    "NfseExternalXmlInboxBulkActionView",
    "NfseExternalXmlInboxExportView",
    "NfseExternalXmlInboxItemApproveView",
    "NfseExternalXmlInboxItemDiscardView",
    "NfseExternalXmlInboxItemPayloadView",
    "NfseExternalXmlInboxListView",
    "NfseExternalXmlInboxProcessView",
    "NfseExternalXmlInboxUploadView",
    "NfseReceivedDocumentConsultationIssueView",
    "NfseReceivedDocumentConsultationPayloadView",
    "NfseReceivedDocumentBatchImportView",
    "NfseReceivedDocumentDetailView",
    "NfseReceivedDocumentImportView",
    "NfseReceivedDocumentListView",
    "NfseReceivedDocumentManifestationDownloadView",
    "NfseReceivedDocumentManifestationIssueView",
    "NfseReceivedDocumentManifestationPayloadView",
    "NfseReceivedDocumentPayloadView",
    "NfseReceivedDocumentXmlDownloadView",
    "NfseReceivedImportBatchDetailView",
    "NfseSubstitutionPreviewApproveView",
    "NfseSubstitutionPreviewCreateView",
    "NfseSubstitutionPreviewDetailView",
    "NfseSubstitutionPreviewListView",
    "NfseSubstitutionPreviewPayloadView",
    "NfseSubstitutionIssueView",
    "NfseSubstitutionPayloadView",
    "NfseSubstitutionDownloadView",
    "TaxClassCreateView",
    "TaxClassDeleteView",
    "TaxClassListView",
    "TaxClassManagerView",
    "TaxClassPresetCreateView",
    "TaxClassPresetListView",
    "TaxClassPresetUpdateView",
    "TaxClassUpdateView",
    "WebhookView",
    "WebmaniaCompanyDetailView",
    "WebmaniaCompanyListView",
    "WebmaniaCompanySyncView",
    "WebmaniaCompanyUpdateView",
    "WebmaniaRequestsView",
    "sync_b2b_companies_to_database",
    "DreReportView",
    "DreResultsView",
    "DrePdfView",
    "DrePdfPreviewView",
    "DreExcelView",
]
