# Generated by Django 6.0 on 2026-06-09 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EditingLock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "session_key",
                    models.CharField(max_length=255, verbose_name="Chave da Sessão"),
                ),
                (
                    "locked_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Bloqueado em"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bloqueio de Edição",
                "verbose_name_plural": "Bloqueios de Edição",
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="core_editin_content_654073_idx",
                    )
                ],
                "unique_together": {("content_type", "object_id")},
            },
        ),
    ]
