# Generated by Django 6.0 on 2026-07-12 14:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_create_editinglock'),
        ('workshops', '0027_workshop_whatsapp_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundJob',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(db_index=True, max_length=100, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Concluído'), ('failed', 'Falhou'), ('pending_reconciliation', 'Aguardando Reconciliação'), ('cancelled', 'Cancelado')], db_index=True, default='pending', max_length=30, verbose_name='Status')),
                ('attempts', models.PositiveIntegerField(default=0, verbose_name='Tentativas')),
                ('payload', models.JSONField(blank=True, null=True, verbose_name='Payload')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='Resultado')),
                ('error', models.TextField(blank=True, null=True, verbose_name='Erro')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Início')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('correlation_id', models.CharField(blank=True, db_index=True, help_text='Usado para idempotência e rastreamento', max_length=100, null=True, verbose_name='Correlation ID')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Solicitante')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background_jobs', to='workshops.workshop', verbose_name='Oficina')),
            ],
            options={
                'verbose_name': 'Job Assíncrono',
                'verbose_name_plural': 'Jobs Assíncronos',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['status', 'job_type'], name='core_backgr_status_b85ec9_idx'), models.Index(fields=['workshop', 'status'], name='core_backgr_worksho_754bde_idx')],
            },
        ),
    ]
