# Generated by Django 6.0 on 2026-08-06 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_backfill_fixed_budget_stored_totals"),
        ("workshops", "0044_outbound_business_weekdays_all_days"),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMonthlySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('year', models.PositiveIntegerField(verbose_name='Ano')),
                ('month', models.PositiveSmallIntegerField(verbose_name='Mês')),
                ('closed_at', models.DateTimeField(verbose_name='Fechamento oficial')),
                ('captured_at', models.DateTimeField(verbose_name='Capturado em')),
                ('cars_this_month', models.PositiveIntegerField(default=0)),
                ('warranty_courtesy_cars', models.PositiveIntegerField(default=0)),
                ('average_ticket', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_sold_to_date', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('projection', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('projection_warning', models.TextField(blank=True, default='')),
                ('elapsed_days', models.PositiveIntegerField(default=0)),
                ('remaining_days', models.PositiveIntegerField(default=0)),
                ('configured_working_days', models.PositiveIntegerField(blank=True, null=True)),
                ('business_holidays', models.PositiveIntegerField(default=0)),
                ('accumulated_profitability', models.DecimalField(decimal_places=6, default=0, max_digits=14)),
                ('accumulated_markup', models.DecimalField(decimal_places=6, default=0, max_digits=14)),
                ('accumulated_markup_progress', models.PositiveSmallIntegerField(default=0)),
                ('warranty_return_rate', models.DecimalField(decimal_places=6, default=0, max_digits=14)),
                ('approval_rate', models.DecimalField(decimal_places=6, default=0, max_digits=14)),
                ('total_pending_receivable', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('monthly_pending_receivable', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('previous_months_pending_receivable', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_general_pending_receivable', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_pending_budgets', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('monthly_pending_budgets', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('previous_months_pending_budgets', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_general_pending_budgets', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_rejected_budgets', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gross_revenue_target', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('daily_revenue_target', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('actual_daily_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('today_sales', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('projection_vs_target', models.JSONField(blank=True, default=dict)),
                ('actual_daily_revenue_vs_target', models.JSONField(blank=True, default=dict)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_monthly_snapshots', to='workshops.workshop', verbose_name='Oficina')),
            ],
            options={
                'verbose_name': 'Snapshot mensal do dashboard',
                'verbose_name_plural': 'Snapshots mensais do dashboard',
                'ordering': ('-year', '-month', 'workshop_id'),
                'indexes': [models.Index(fields=['workshop', 'year', 'month'], name='dash_snap_ws_ym_idx')],
                'constraints': [models.UniqueConstraint(fields=('workshop', 'year', 'month'), name='unique_dashboard_monthly_snapshot_per_workshop_month')],
            },
        ),
    ]
