# Generated by Django 5.2.9 on 2026-01-12 16:40

import django.db.models.deletion
import djmoney.models.fields
import localflavor.br.models
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workshops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('cpf', localflavor.br.models.BRCPFField(max_length=14, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=9, null=True, verbose_name='RG')),
                ('birth_date', models.DateField(verbose_name='Data de Nascimento')),
                ('sex', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, verbose_name='Sexo')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Cargo')),
                ('salary_currency', djmoney.models.fields.CurrencyField(choices=[('BRL', 'Real Brasileiro')], default='BRL', editable=False, max_length=3)),
                ('salary', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14, verbose_name='Salário')),
                ('admission_date', models.DateField(verbose_name='Data de Admissão')),
                ('termination_date', models.DateField(blank=True, null=True, verbose_name='Data de Saída')),
                ('collaborator_type', models.CharField(choices=[('A', 'Administrativo'), ('P', 'Produtivo')], max_length=1, verbose_name='Tipo')),
                ('receives_commission', models.BooleanField(default=False, verbose_name='Recebe Comissão')),
                ('commission_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Percentual de Comissão')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('system_access', models.BooleanField(default=False, verbose_name='Acesso ao Sistema')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshop_collaborator', to=settings.AUTH_USER_MODEL)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='workshops.workshop')),
            ],
        ),
    ]
