# Generated by Django 5.2.9 on 2026-01-12 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collaborators', '0001_initial'),
        ('iam', '0001_initial'),
        ('workshops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopmember',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workshop_members', to='iam.workshoprole'),
        ),
        migrations.AddField(
            model_name='workshopmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workshopmember',
            name='workshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='workshops.workshop'),
        ),
        migrations.AddConstraint(
            model_name='workshopcollaborator',
            constraint=models.UniqueConstraint(fields=('workshop', 'cpf'), name='unique_collaborator_cpf_per_workshop'),
        ),
        migrations.AddConstraint(
            model_name='workshopcollaborator',
            constraint=models.CheckConstraint(condition=models.Q(('commission_percentage__isnull', True), models.Q(('commission_percentage__gte', 0), ('commission_percentage__lte', 100)), _connector='OR'), name='collaborator_commission_percentage_range'),
        ),
        migrations.AddConstraint(
            model_name='workshopmember',
            constraint=models.UniqueConstraint(fields=('user', 'workshop'), name='unique_user_workshop_member'),
        ),
    ]
