# Generated by Django 5.2.9 on 2026-01-13 13:44

from decimal import Decimal

from django.db import migrations, models
from django.db.models import Q


def forwards_convert_percent_to_fraction(apps, schema_editor):
    WorkshopCollaborator = apps.get_model("collaborators", "WorkshopCollaborator")

    qs = WorkshopCollaborator.objects.exclude(commission_percentage__isnull=True)
    for collaborator in qs.iterator():
        value = collaborator.commission_percentage
        # Migração defensiva: se o valor antigo estava em percentual (ex.: 10 = 10%),
        # converte para fração (0.10). Se já estiver em fração (<= 1), mantém.
        if value is not None and value > 1:
            collaborator.commission_percentage = value / Decimal("100")
            collaborator.save(update_fields=["commission_percentage"])


def backwards_convert_fraction_to_percent(apps, schema_editor):
    WorkshopCollaborator = apps.get_model("collaborators", "WorkshopCollaborator")

    qs = WorkshopCollaborator.objects.exclude(commission_percentage__isnull=True)
    for collaborator in qs.iterator():
        value = collaborator.commission_percentage
        if value is not None and value <= 1:
            collaborator.commission_percentage = value * Decimal("100")
            collaborator.save(update_fields=["commission_percentage"])


class Migration(migrations.Migration):
    dependencies = [
        ("collaborators", "0002_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="workshopcollaborator",
            name="collaborator_commission_percentage_range",
        ),
        migrations.AlterField(
            model_name="workshopcollaborator",
            name="commission_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=7,
                null=True,
                verbose_name="Percentual de Comissão",
            ),
        ),
        migrations.RunPython(
            forwards_convert_percent_to_fraction,
            backwards_convert_fraction_to_percent,
        ),
        migrations.AddConstraint(
            model_name="workshopcollaborator",
            constraint=models.CheckConstraint(
                condition=Q(commission_percentage__isnull=True) | (Q(commission_percentage__gte=0) & Q(commission_percentage__lte=1)),
                name="collaborator_commission_percentage_range",
            ),
        ),
    ]
