# Generated by Django 6.0 on 2026-02-04 18:26

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0003_commission_percentage_fraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopcollaborator',
            name='salary',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=14, verbose_name='Salário'),
        ),
    ]
