# Generated by Django 6.0 on 2026-03-08 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("collaborators", "0004_alter_workshopcollaborator_salary"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workshopcollaborator",
            options={
                "verbose_name": "Colaborador da Oficina",
                "verbose_name_plural": "Colaboradores da Oficina",
            },
        ),
        migrations.AlterModelOptions(
            name="workshopmember",
            options={
                "verbose_name": "Membro da Oficina",
                "verbose_name_plural": "Membros da Oficina",
            },
        ),
    ]
