# Generated by Django 5.2.9 on 2026-03-10 12:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collaborators", "0005_alter_workshopcollaborator_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshopcollaborator",
            name="criado_em",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name="Data de Criação"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workshopcollaborator",
            name="atualizado_em",
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name="Data de Atualização"),
            preserve_default=False,
        ),
    ]
