# Generated by Django 6.0 on 2026-04-24 21:50

import django.db.models.deletion
import djmoney.models.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collaborators", "0006_workshopcollaborator_timestamps"),
        ("finance", "0033_nferequest_additional_information_and_more"),
        ("workorder", "0013_workorder_km_final"),
        ("workshops", "0019_reconcile_workshop_file_columns"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CollaboratorBenefit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="Data de Criação")),
                ("atualizado_em", models.DateTimeField(auto_now=True, verbose_name="Data de Atualização")),
                ("name", models.CharField(max_length=255, verbose_name="Nome do benefício")),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                ("monthly_amount_currency", djmoney.models.fields.CurrencyField(choices=[("BRL", "Real Brasileiro")], default="BRL", editable=False, max_length=3)),
                ("monthly_amount", djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal("0.00"), max_digits=14, verbose_name="Valor mensal")),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
            ],
            options={
                "verbose_name": "Benefício do Colaborador",
                "verbose_name_plural": "Benefícios do Colaborador",
                "ordering": ["id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CollaboratorCommissionEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="Data de Criação")),
                ("atualizado_em", models.DateTimeField(auto_now=True, verbose_name="Data de Atualização")),
                ("reference_year", models.PositiveIntegerField(verbose_name="Ano de referência")),
                ("reference_month", models.PositiveSmallIntegerField(verbose_name="Mês de referência")),
                ("percentage", models.DecimalField(decimal_places=6, max_digits=7, verbose_name="Percentual")),
                ("base_amount_currency", djmoney.models.fields.CurrencyField(choices=[("BRL", "Real Brasileiro")], default="BRL", editable=False, max_length=3)),
                ("base_amount", djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal("0.00"), max_digits=14, verbose_name="Base de cálculo")),
                ("commission_amount_currency", djmoney.models.fields.CurrencyField(choices=[("BRL", "Real Brasileiro")], default="BRL", editable=False, max_length=3)),
                ("commission_amount", djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal("0.00"), max_digits=14, verbose_name="Valor da comissão")),
                ("status", models.CharField(choices=[("FORECAST", "Previsto"), ("PAID", "Pago")], default="FORECAST", max_length=16, verbose_name="Status")),
                ("paid_at", models.DateField(blank=True, null=True, verbose_name="Pago em")),
            ],
            options={
                "verbose_name": "Lançamento de Comissão do Colaborador",
                "verbose_name_plural": "Lançamentos de Comissão do Colaborador",
                "ordering": ["-reference_year", "-reference_month", "-id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CollaboratorPayroll",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="Data de Criação")),
                ("atualizado_em", models.DateTimeField(auto_now=True, verbose_name="Data de Atualização")),
                ("reference_year", models.PositiveIntegerField(verbose_name="Ano de referência")),
                ("reference_month", models.PositiveSmallIntegerField(verbose_name="Mês de referência")),
                ("due_date", models.DateField(verbose_name="Data prevista para pagamento")),
                ("salary_amount_currency", djmoney.models.fields.CurrencyField(choices=[("BRL", "Real Brasileiro")], default="BRL", editable=False, max_length=3)),
                ("salary_amount", djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal("0.00"), max_digits=14, verbose_name="Salário")),
                ("transport_allowance_amount_currency", djmoney.models.fields.CurrencyField(choices=[("BRL", "Real Brasileiro")], default="BRL", editable=False, max_length=3)),
                ("transport_allowance_amount", djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal("0.00"), max_digits=14, verbose_name="Vale Transporte")),
                ("benefits_amount_currency", djmoney.models.fields.CurrencyField(choices=[("BRL", "Real Brasileiro")], default="BRL", editable=False, max_length=3)),
                ("benefits_amount", djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal("0.00"), max_digits=14, verbose_name="Benefícios")),
                ("commission_amount_currency", djmoney.models.fields.CurrencyField(choices=[("BRL", "Real Brasileiro")], default="BRL", editable=False, max_length=3)),
                ("commission_amount", djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal("0.00"), max_digits=14, verbose_name="Comissão")),
                ("total_amount_currency", djmoney.models.fields.CurrencyField(choices=[("BRL", "Real Brasileiro")], default="BRL", editable=False, max_length=3)),
                ("total_amount", djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal("0.00"), max_digits=14, verbose_name="Valor total")),
            ],
            options={
                "verbose_name": "Folha do Colaborador",
                "verbose_name_plural": "Folhas dos Colaboradores",
                "ordering": ["-reference_year", "-reference_month", "-id"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CollaboratorPayrollItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="Data de Criação")),
                ("atualizado_em", models.DateTimeField(auto_now=True, verbose_name="Data de Atualização")),
                ("item_type", models.CharField(choices=[("SALARY", "Salário"), ("TRANSPORT", "Vale Transporte"), ("BENEFIT", "Benefício"), ("COMMISSION", "Comissão")], max_length=32, verbose_name="Tipo")),
                ("title", models.CharField(max_length=255, verbose_name="Título")),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                ("amount_currency", djmoney.models.fields.CurrencyField(choices=[("BRL", "Real Brasileiro")], default="BRL", editable=False, max_length=3)),
                ("amount", djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal("0.00"), max_digits=14, verbose_name="Valor")),
            ],
            options={
                "verbose_name": "Item da Folha do Colaborador",
                "verbose_name_plural": "Itens da Folha do Colaborador",
                "ordering": ["id"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="workshopcollaborator",
            name="payment_day_of_month",
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Dia do pagamento"),
        ),
        migrations.AddField(
            model_name="workshopcollaborator",
            name="payment_day_type",
            field=models.CharField(choices=[("FIFTH_BUSINESS_DAY", "5o dia util"), ("FIXED_DAY", "Data de pagamento")], default="FIFTH_BUSINESS_DAY", max_length=32, verbose_name="Tipo de pagamento"),
        ),
        migrations.AddField(
            model_name="workshopcollaborator",
            name="transport_allowance_daily",
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal("0.00"), max_digits=14, verbose_name="Vale Transporte Diário"),
        ),
        migrations.AddField(
            model_name="workshopcollaborator",
            name="transport_allowance_daily_currency",
            field=djmoney.models.fields.CurrencyField(choices=[("BRL", "Real Brasileiro")], default="BRL", editable=False, max_length=3),
        ),
        migrations.AddConstraint(
            model_name="workshopcollaborator",
            constraint=models.CheckConstraint(
                condition=models.Q(models.Q(("payment_day_of_month__isnull", True), ("payment_day_type", "FIFTH_BUSINESS_DAY")), models.Q(("payment_day_of_month__gte", 1), ("payment_day_of_month__lte", 31), ("payment_day_type", "FIXED_DAY")), _connector="OR"), name="collaborator_payment_day_configuration_valid"
            ),
        ),
        migrations.AddField(
            model_name="collaboratorbenefit",
            name="collaborator",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="benefits", to="collaborators.workshopcollaborator"),
        ),
        migrations.AddField(
            model_name="collaboratorcommissionentry",
            name="collaborator",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="commission_entries", to="collaborators.workshopcollaborator"),
        ),
        migrations.AddField(
            model_name="collaboratorcommissionentry",
            name="workorder",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="commission_entries", to="workorder.workorder"),
        ),
        migrations.AddField(
            model_name="collaboratorcommissionentry",
            name="workshop",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="collaborator_commission_entries", to="workshops.workshop"),
        ),
        migrations.AddField(
            model_name="collaboratorpayroll",
            name="collaborator",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="payrolls", to="collaborators.workshopcollaborator"),
        ),
        migrations.AddField(
            model_name="collaboratorpayroll",
            name="financial_movement",
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="collaborator_payroll", to="finance.financialmovement", verbose_name="Movimentação Financeira"),
        ),
        migrations.AddField(
            model_name="collaboratorpayroll",
            name="workshop",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="collaborator_payrolls", to="workshops.workshop"),
        ),
        migrations.AddField(
            model_name="collaboratorcommissionentry",
            name="payroll",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="commission_entries", to="collaborators.collaboratorpayroll"),
        ),
        migrations.AddField(
            model_name="collaboratorpayrollitem",
            name="payroll",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="collaborators.collaboratorpayroll"),
        ),
        migrations.AddConstraint(
            model_name="collaboratorpayroll",
            constraint=models.UniqueConstraint(fields=("collaborator", "reference_year", "reference_month"), name="unique_collaborator_payroll_reference"),
        ),
        migrations.AddConstraint(
            model_name="collaboratorcommissionentry",
            constraint=models.UniqueConstraint(fields=("collaborator", "workorder"), name="unique_collaborator_commission_workorder"),
        ),
    ]
