# Generated by Django 6.0 on 2026-07-08 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0007_collaboratorbenefit_collaboratorcommissionentry_and_more'),
        ('finance', '0042_alter_taxclassnfecofinsscenario_tax_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboratorbenefit',
            name='budget_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collaborator_benefits', to='finance.financialgroup', verbose_name='Plano Orçamentário'),
        ),
    ]
