# Generated by Django 6.0 on 2026-07-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collaborators", "0008_collaboratorbenefit_budget_plan"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="collaboratorcommissionentry",
            index=models.Index(fields=["collaborator", "reference_year", "reference_month"], name="collab_comm_ref_idx"),
        ),
        migrations.AddIndex(
            model_name="collaboratorcommissionentry",
            index=models.Index(fields=["workshop", "reference_year", "reference_month"], name="collab_comm_ws_ref_idx"),
        ),
        migrations.AddIndex(
            model_name="collaboratorpayroll",
            index=models.Index(fields=["workshop", "reference_year", "reference_month"], name="collab_payroll_ws_ref_idx"),
        ),
    ]
