# Generated by Django 6.0 on 2026-07-14 17:05

from django.db import migrations, models


def backfill_payroll_work_days(apps, schema_editor):
    CollaboratorPayroll = apps.get_model("collaborators", "CollaboratorPayroll")
    WorkshopCost = apps.get_model("workshops", "WorkshopCost")

    workshop_days = {
        (cost.workshop_id, cost.year, cost.month): int(cost.work_days_per_month or 0)
        for cost in WorkshopCost.objects.only("workshop_id", "year", "month", "work_days_per_month")
    }

    payrolls_to_update: list = []
    for payroll in CollaboratorPayroll.objects.only("id", "workshop_id", "reference_year", "reference_month", "work_days"):
        work_days = workshop_days.get((payroll.workshop_id, payroll.reference_year, payroll.reference_month), 0)
        if int(payroll.work_days or 0) == work_days:
            continue
        payroll.work_days = work_days
        payrolls_to_update.append(payroll)

    if payrolls_to_update:
        CollaboratorPayroll.objects.bulk_update(payrolls_to_update, ["work_days"], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ("collaborators", "0009_phase3_hot_path_indexes"),
        ("workshops", "0027_workshop_whatsapp_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="collaboratorpayroll",
            name="work_days",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Dias úteis"),
        ),
        migrations.AddField(
            model_name="collaboratorpayroll",
            name="work_days_is_custom",
            field=models.BooleanField(default=False, verbose_name="Dias úteis personalizados"),
        ),
        migrations.RunPython(backfill_payroll_work_days, migrations.RunPython.noop),
    ]
