# Generated by Django 6.0 on 2026-07-14 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0010_collaboratorpayroll_work_days'),
        ('workshops', '0027_workshop_whatsapp_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaboratorPayrollComponentOmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('reference_year', models.PositiveIntegerField(verbose_name='Ano de referência')),
                ('reference_month', models.PositiveSmallIntegerField(verbose_name='Mês de referência')),
                ('component', models.CharField(max_length=32, verbose_name='Componente')),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_component_omissions', to='collaborators.workshopcollaborator')),
                ('payroll_benefit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payroll_omissions', to='collaborators.collaboratorbenefit')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_component_omissions', to='workshops.workshop')),
            ],
            options={
                'verbose_name': 'Omissão de Componente da Folha',
                'verbose_name_plural': 'Omissões de Componentes da Folha',
                'abstract': False,
                'indexes': [models.Index(fields=['collaborator', 'reference_year', 'reference_month'], name='collab_omit_ref_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('payroll_benefit__isnull', True)), fields=('collaborator', 'reference_year', 'reference_month', 'component'), name='unique_payroll_component_omission'), models.UniqueConstraint(condition=models.Q(('payroll_benefit__isnull', False)), fields=('collaborator', 'reference_year', 'reference_month', 'component', 'payroll_benefit'), name='unique_payroll_benefit_omission')],
            },
        ),
    ]
