# Generated by Django 6.0 on 2026-07-15 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0009_collaboratorpayroll_view_payroll_details_permission'),
        ('collaborators', '0011_collaboratorpayrollcomponentomission'),
    ]

    operations = [
    ]
