# Generated by Django 6.0 on 2026-07-25 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0011_collaboratorpayrollcomponentomission'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='collaboratorpayrollcomponentomission',
            name='collab_omit_ref_idx',
        ),
        migrations.RemoveConstraint(
            model_name='collaboratorpayrollcomponentomission',
            name='unique_payroll_component_omission',
        ),
        migrations.RemoveConstraint(
            model_name='collaboratorpayrollcomponentomission',
            name='unique_payroll_benefit_omission',
        ),
        migrations.DeleteModel(
            name='CollaboratorPayrollComponentOmission',
        ),
    ]
