# Generated by Django 6.0 on 2026-08-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0012_remove_collaboratorpayrollcomponentomission_collab_omit_ref_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopcollaborator',
            name='admission_date',
            field=models.DateField(verbose_name='Data de admissão'),
        ),
        migrations.AlterField(
            model_name='workshopcollaborator',
            name='birth_date',
            field=models.DateField(verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='workshopcollaborator',
            name='payment_day_type',
            field=models.CharField(choices=[('FIFTH_BUSINESS_DAY', '5º dia útil'), ('FIXED_DAY', 'Data de pagamento')], default='FIFTH_BUSINESS_DAY', max_length=32, verbose_name='Tipo de pagamento'),
        ),
        migrations.AlterField(
            model_name='workshopcollaborator',
            name='system_access',
            field=models.BooleanField(default=False, verbose_name='Acesso ao sistema'),
        ),
    ]
