# Generated by Django 6.0 on 2026-07-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0012_remove_collaboratorpayrollcomponentomission_collab_omit_ref_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopcollaborator',
            name='collaborator_type',
            field=models.CharField(choices=[('A', 'Administrativo'), ('P', 'Produtivo'), ('L', 'Pró Labore')], max_length=1, verbose_name='Tipo'),
        ),
    ]
