# Generated by Django 6.0 on 2026-07-22 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0012_merge_20260715_0157'),
        ('collaborators', '0013_add_pro_labore_collaborator_type'),
    ]

    operations = [
    ]
