# Generated by Django 6.0 on 2026-08-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0013_fix_collaborators_ui_verbose_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopcollaborator',
            name='collaborator_type',
            field=models.CharField(choices=[('A', 'Administrativo'), ('P', 'Produtivo'), ('L', 'Pró Labore')], max_length=1, verbose_name='Tipo'),
        ),
    ]
