# Generated by Django 6.0 on 2026-08-19 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0014_merge_20260722_1538'),
        ('finance', '0048_nfserequest_codigo_nbs'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopcollaborator',
            name='transport_budget_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='collaborator_transport_allowances', to='finance.financialgroup', verbose_name='Plano orçamentário do vale transporte'),
        ),
    ]
