# Generated by Django 6.0 on 2026-08-16

import django.core.validators
import django.db.models.deletion
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collaborators", "0014_merge_20260722_1538"),
        ("workorder", "0043_workorder_signature_decline_pending"),
        ("workshops", "0045_workshopcommissionsettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollaboratorCommissionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("service", "Serviço"), ("product", "Produto")],
                        max_length=10,
                        verbose_name="Escopo",
                    ),
                ),
                (
                    "modality",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentual (%)"),
                            ("fixed", "Valor Fixo (R$)"),
                        ],
                        max_length=12,
                        verbose_name="Modalidade",
                    ),
                ),
                (
                    "apply_scope",
                    models.CharField(
                        choices=[
                            ("participation", "Por Participação"),
                            ("global", "Global"),
                        ],
                        default="participation",
                        max_length=14,
                        verbose_name="Aplicação",
                    ),
                ),
                (
                    "base",
                    models.CharField(
                        choices=[
                            ("gross_sale", "Valor de Venda Bruta"),
                            ("profitability", "Lucratividade / Líquido"),
                        ],
                        max_length=16,
                        verbose_name="Base de cálculo",
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=7,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                        verbose_name="Percentual de Comissão",
                    ),
                ),
                (
                    "fixed_amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("BRL", "Real Brasileiro")],
                        default="BRL",
                        editable=False,
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "fixed_amount",
                    djmoney.models.fields.MoneyField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Valor Fixo",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativa")),
            ],
            options={
                "verbose_name": "Regra de Comissão do Colaborador",
                "verbose_name_plural": "Regras de Comissão do Colaborador",
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="collaboratorcommissionrule",
            name="collaborator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commission_rules",
                to="collaborators.workshopcollaborator",
            ),
        ),
        migrations.AddConstraint(
            model_name="collaboratorcommissionrule",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("collaborator", "scope"),
                name="unique_active_commission_rule_per_collaborator_scope",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="collaboratorcommissionentry",
            name="unique_collaborator_commission_workorder",
        ),
        migrations.AddField(
            model_name="collaboratorcommissionentry",
            name="commission_origin",
            field=models.CharField(
                choices=[
                    ("workorder_rate", "Comissão por OS (Oficina)"),
                    ("service_rule", "Regra de Serviço (Manual)"),
                    ("product_rule", "Regra de Produto (Manual)"),
                ],
                default="workorder_rate",
                max_length=16,
                verbose_name="Origem",
            ),
        ),
        migrations.AddField(
            model_name="collaboratorcommissionentry",
            name="is_fixed_amount",
            field=models.BooleanField(default=False, verbose_name="Valor Fixo"),
        ),
        migrations.AddField(
            model_name="collaboratorcommissionentry",
            name="commission_rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="commission_entries",
                to="collaborators.collaboratorcommissionrule",
            ),
        ),
        migrations.AddConstraint(
            model_name="collaboratorcommissionentry",
            constraint=models.UniqueConstraint(
                fields=("collaborator", "workorder", "commission_origin"),
                name="unique_collaborator_commission_per_origin",
            ),
        ),
    ]