# Generated by Django 6.0 on 2026-08-21 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0015_workshopcollaborator_transport_budget_plan'),
        ('workorder', '0050_migrate_waiting_delivery_to_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboratorbenefit',
            name='source_payroll',
            field=models.ForeignKey(blank=True, help_text='Quando preenchido, o benefício vale só para esta competência e não entra no cadastro.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='one_off_benefits', to='collaborators.collaboratorpayroll', verbose_name='Folha de origem'),
        ),
        migrations.AddField(
            model_name='collaboratorcommissionentry',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AddField(
            model_name='collaboratorcommissionentry',
            name='origin',
            field=models.CharField(choices=[('WORKORDER', 'Ordem de serviço'), ('MANUAL', 'Manual')], default='WORKORDER', max_length=16, verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='collaboratorcommissionentry',
            name='workorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_entries', to='workorder.workorder'),
        ),
    ]
