# Generated by Django 6.0 on 2026-08-27 22:29

import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collaborators", "0018_create_commission_rule_and_allocation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collaboratorcommissionentry",
            name="pool_amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("BRL", "Real Brasileiro")],
                default="BRL",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="collaboratorcommissionrule",
            name="atualizado_em",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Data de Atualização"
            ),
        ),
        migrations.AlterField(
            model_name="collaboratorcommissionrule",
            name="criado_em",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Data de Criação"
            ),
        ),
        migrations.AlterField(
            model_name="collaboratorcommissionrule",
            name="fixed_amount_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("BRL", "Real Brasileiro")],
                default="BRL",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="workordercommissionallocation",
            name="atualizado_em",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Data de Atualização"
            ),
        ),
        migrations.AlterField(
            model_name="workordercommissionallocation",
            name="criado_em",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Data de Criação"
            ),
        ),
    ]
