# Generated by Django 6.0 on 2026-08-30 20:43

import django.core.validators
import djmoney.models.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0019_alter_collaboratorcommissionentry_pool_amount_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboratorcommissionentry',
            name='commission_origin',
            field=models.CharField(blank=True, choices=[('service_pct_pool', 'Serviço % (Pool)'), ('service_fixed', 'Serviço Fixo'), ('product_pct_pool', 'Produto % (Pool)'), ('product_fixed', 'Produto Fixo'), ('service_global', 'Serviço Global'), ('product_global', 'Produto Global'), ('workorder_rate', 'Comissão por OS (Oficina)'), ('service_rule', 'Regra de Serviço'), ('product_rule', 'Regra de Produto')], help_text='Escopo + modalidade + aplicação da comissão no montante de distribuição percentual de comissão.', max_length=32, null=True, verbose_name='Origem da Comissão (v3)'),
        ),
        migrations.AlterField(
            model_name='collaboratorcommissionentry',
            name='pool_amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Valor do montante de distribuição percentual de comissão'),
        ),
        migrations.AlterField(
            model_name='workordercommissionallocation',
            name='distribution_percentage',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='Percentual da distribuição do montante de distribuição percentual de comissão para este colaborador no escopo.', max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Base (%)'),
        ),
    ]
