# Generated by Django 6.0 on 2026-09-03 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0023_backfill_global_collaborators_in_workorders'),
        ('collaborators', '0024_merge_discounted_and_august_global_commissions'),
    ]

    operations = [
    ]
