# Generated by Django 6.0 on 2026-10-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0025_merge_20260903_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopcollaborator',
            name='is_developer',
            field=models.BooleanField(default=False, verbose_name='Desenvolvedor'),
        ),
    ]
