from django.urls import path
from django.views.generic import RedirectView

from apps.finance.views import (
    EmissionPreviewView,
    EmissionRequestCreateView,
    EmissionWorkOrderKitComponentUpdateView,
    EmissionWorkOrderItemUpdateView,
    CommissionReportView,
    CommissionReportPdfView,
    FinancialGroupBulkDeleteView,
    FinancialGroupCreateView,
    FinancialGroupDeleteView,
    FinancialGroupListView,
    FinancialReportsHomeView,
    FinancialGroupUpdateView,
    IssuedDocumentsArchiveDownloadView,
    IssuedDocumentsListView,
    NfeCreateRedirectView,
    NfeDocumentDownloadView,
    NfePreviewPdfView,
    NfeRequestCancelView,
    NfeRequestDetailView,
    NfeRequestInvalidateView,
    NfeRequestListView,
    NfeRequestReconcileView,
    NfeRequestUpdateView,
    NfseCreateRedirectView,
    NfseRequestCancelView,
    NfseDocumentDownloadView,
    NfsePreviewPdfView,
    NfseRequestDetailView,
    NfseRequestListView,
    NfseRequestReconcileView,
    NfseRequestUpdateView,
    PayrollBulkConciliateView,
    PayrollBulkPayView,
    PayrollBulkUnpayView,
    PayrollEditModalView,
    PayrollListView,
    PayrollRefreshView,
    TaxClassCreateView,
    TaxClassDeleteView,
    TaxClassListView,
    TaxClassPresetCreateView,
    TaxClassPresetListView,
    TaxClassPresetUpdateView,
    TaxClassUpdateView,
    WebhookView,
    WebmaniaCompanyDetailView,
    WebmaniaCompanyListView,
    WebmaniaCompanySyncView,
    WebmaniaCompanyUpdateView,
    DrePdfPreviewView,
    DrePdfView,
    DreExcelView,
    DreReportView,
    DreResultsView,
)

from apps.finance.views.cash_flow import CashFlowView
from apps.finance.views.bank_account import BankAccountListView, BankAccountUpdateView, BankAccountCreateView
from apps.finance.views.emission import EmissionCheckWorkorderView
from apps.finance.views.financial_movement import (
    FinancialMovementCreateView,
    FinancialMovementDeleteView,
    FinancialMovementListView,
    FinancialMovementRemovePayrollLinkView,
    FinancialMovementUpdateView,
    EntityListView,
    EntityDetailView,
    financial_movement_pdf,
)
from apps.finance.views.payment_method import PaymentMethodListView, PaymentMethodCreateView, PaymentMethodUpdateView
from apps.finance.views.reports import (
    BatchConciliateModalView,
    BatchConciliateView,
    ReportMovementEditView,
    ReportMovementDeleteView,
    FinancialBulkPayView,
)
from apps.finance.views.movement_group import GroupMovementWizardView, GroupMovementDeleteView

app_name = "finance"

urlpatterns = [
    path("reports/", FinancialReportsHomeView.as_view(), name="reports_home"),
    path("reports/movement/<int:pk>/edit/", ReportMovementEditView.as_view(), name="report_movement_edit"),
    path("reports/movement/<int:pk>/delete/", ReportMovementDeleteView.as_view(), name="report_movement_delete"),
    path("reports/batch-conciliate/modal/", BatchConciliateModalView.as_view(), name="batch_conciliate_modal"),
    path("reports/batch-conciliate/", BatchConciliateView.as_view(), name="batch_conciliate"),
    path("reports/bulk-pay/", FinancialBulkPayView.as_view(), name="bulk_pay"),
    path("reports/group/wizard/", GroupMovementWizardView.as_view(), name="group_movement_wizard"),
    path("reports/group/<int:pk>/delete/", GroupMovementDeleteView.as_view(), name="group_movement_delete"),
    path("folha-pagamento/", PayrollListView.as_view(), name="payroll_list"),
    path("folha-pagamento/atualizar/", PayrollRefreshView.as_view(), name="payroll_refresh"),
    path("folha-pagamento/bulk-pay/", PayrollBulkPayView.as_view(), name="payroll_bulk_pay"),
    path("folha-pagamento/bulk-conciliate/", PayrollBulkConciliateView.as_view(), name="payroll_bulk_conciliate"),
    path("folha-pagamento/bulk-unpay/", PayrollBulkUnpayView.as_view(), name="payroll_bulk_unpay"),
    path("folha-pagamento/<int:pk>/edit/", PayrollEditModalView.as_view(), name="payroll_edit_modal"),
    path("folha-pagamento/collaborator/<int:collaborator_pk>/edit/", PayrollEditModalView.as_view(), name="payroll_edit_modal_for_collaborator"),
    path("comissoes/", CommissionReportView.as_view(), name="commission_report"),
    path("comissoes/pdf/", CommissionReportPdfView.as_view(), name="commission_report_pdf"),
    path("notas-emitidas/", IssuedDocumentsListView.as_view(), name="issued_documents_list"),
    path("notas-emitidas/download/<str:document_group>/", IssuedDocumentsArchiveDownloadView.as_view(), name="issued_documents_download"),
    # Financial Groups
    path("financial-groups/", FinancialGroupListView.as_view(), name="financial_groups_list"),
    path("financial-groups/create/", FinancialGroupCreateView.as_view(), name="financial_groups_create"),
    path("financial-groups/<int:pk>/update/", FinancialGroupUpdateView.as_view(), name="financial_groups_update"),
    path("financial-groups/<int:pk>/delete/", FinancialGroupDeleteView.as_view(), name="financial_groups_delete"),
    path("financial-groups/bulk-delete/", FinancialGroupBulkDeleteView.as_view(), name="financial_groups_bulk_delete"),
    # Payment Method
    path("payment-methods/", PaymentMethodListView.as_view(), name="payment_methods_list"),
    path("payment-methods/create/", PaymentMethodCreateView.as_view(), name="payment_methods_create"),
    path("payment-methods/<int:pk>/update/", PaymentMethodUpdateView.as_view(), name="payment_methods_update"),
    # Unified emission
    path("emissao/preview/", EmissionPreviewView.as_view(), name="emission_preview"),
    path("emissao/workorder/<int:workorder_pk>/item/<int:item_id>/edit/", EmissionWorkOrderItemUpdateView.as_view(), name="emission_workorder_item_edit"),
    path("emissao/workorder/<int:workorder_pk>/kit-item/<int:item_id>/<str:component_type>/<int:component_id>/edit/", EmissionWorkOrderKitComponentUpdateView.as_view(), name="emission_workorder_kit_component_edit"),
    path("emissao/check-workorder/", EmissionCheckWorkorderView.as_view(), name="emission_check_workorder"),
    path("emissao/", EmissionRequestCreateView.as_view(), name="emission_create"),
    # NFE
    path("nfe/", NfeRequestListView.as_view(), name="nfe_emit"),
    path("nfe/list/", NfeRequestListView.as_view(), name="nfe_list"),
    path("nfe/create/", NfeCreateRedirectView.as_view(), name="nfe_create"),
    path("nfe/<int:pk>/", NfeRequestDetailView.as_view(), name="nfe_detail"),
    path("nfe/<int:pk>/reconciliar/", NfeRequestReconcileView.as_view(), name="nfe_reconcile"),
    path("nfe/<int:pk>/inutilizar/", NfeRequestInvalidateView.as_view(), name="nfe_invalidate"),
    path("nfe/<int:pk>/cancelar/", NfeRequestCancelView.as_view(), name="nfe_cancel"),
    path("nfe/<int:pk>/documentos/<str:document>/", NfeDocumentDownloadView.as_view(), name="nfe_document_download"),
    path("nfe/<int:pk>/previa/pdf/", NfePreviewPdfView.as_view(), name="nfe_preview_pdf"),
    path("nfe/<int:pk>/edit/", NfeRequestUpdateView.as_view(), name="nfe_update"),
    # Classe Imposto
    path("classe-imposto/", TaxClassListView.as_view(), name="tax_class_list"),
    path("classe-imposto/", TaxClassListView.as_view(), name="tax_class_manager"),
    path("classe-imposto/create/", TaxClassCreateView.as_view(), name="tax_class_create"),
    path("classe-imposto/<str:reference>/edit/", TaxClassUpdateView.as_view(), name="tax_class_update"),
    path("classe-imposto/<str:reference>/delete/", TaxClassDeleteView.as_view(), name="tax_class_delete"),
    path("classe-imposto/presets/", TaxClassPresetListView.as_view(), name="tax_class_preset_list"),
    path("classe-imposto/presets/create/", TaxClassPresetCreateView.as_view(), name="tax_class_preset_create"),
    path("classe-imposto/presets/<int:pk>/edit/", TaxClassPresetUpdateView.as_view(), name="tax_class_preset_update"),
    # Conta Bancária
    path("bank-account/", BankAccountListView.as_view(), name="bank_account_list"),
    path("bank-account/create/", BankAccountCreateView.as_view(), name="bank_account_create"),
    path("bank-account/<int:pk>/update/", BankAccountUpdateView.as_view(), name="bank_account_update"),
    # Movimentação Financeira
    path("financial-movement/", FinancialMovementListView.as_view(), name="financial_movement_list"),
    path("movimentacao/pdf/", financial_movement_pdf, name="financial_movement_pdf"),
    path("financial-movement/create/", FinancialMovementCreateView.as_view(), name="financial_movement_create"),
    path("financial-movement/<int:pk>/update/", FinancialMovementUpdateView.as_view(), name="financial_movement_update"),
    path("financial-movement/<int:pk>/delete/", FinancialMovementDeleteView.as_view(), name="financial_movement_delete"),
    path("financial-movement/<int:pk>/remove-payroll-link/", FinancialMovementRemovePayrollLinkView.as_view(), name="financial_movement_remove_payroll_link"),
    path("entities", EntityListView.as_view(), name="entities"),
    path("entity_details", EntityDetailView.as_view(), name="entity_details"),
    # NFS-e
    path("nfse/", NfseRequestListView.as_view(), name="nfse_list"),
    path("nfse/create/", NfseCreateRedirectView.as_view(), name="nfse_create"),
    path("nfse/<int:pk>/", NfseRequestDetailView.as_view(), name="nfse_detail"),
    path("nfse/<int:pk>/reconciliar/", NfseRequestReconcileView.as_view(), name="nfse_reconcile"),
    path("nfse/<int:pk>/cancelar/", NfseRequestCancelView.as_view(), name="nfse_cancel"),
    path("nfse/<int:pk>/documentos/<str:document>/", NfseDocumentDownloadView.as_view(), name="nfse_document_download"),
    path("nfse/<int:pk>/previa/pdf/", NfsePreviewPdfView.as_view(), name="nfse_preview_pdf"),
    path("nfse/<int:pk>/edit/", NfseRequestUpdateView.as_view(), name="nfse_update"),
    # WebMania
    path("webmania/empresas/", WebmaniaCompanyListView.as_view(), name="webmania_company_list"),
    path("webmania/empresas/sync/", WebmaniaCompanySyncView.as_view(), name="webmania_company_sync"),
    path("webmania/empresas/<int:pk>/", WebmaniaCompanyDetailView.as_view(), name="webmania_company_detail"),
    path("webmania/empresas/<int:pk>/editar/", WebmaniaCompanyUpdateView.as_view(), name="webmania_company_update"),
    path("webmania/requisicoes/", RedirectView.as_view(pattern_name="workshops:emission_history", permanent=False), name="webmania_requests"),
    path("webmania/webhook/ping/", WebhookView.as_view(), name="webhook_ping"),
    path("webmania/webhook/", WebhookView.as_view(), name="webhook"),
    # Fluxo de Contas
    path("fluxo-de-contas/", CashFlowView.as_view(), name="cash_flow"),
    # DRE
    path("dre/", DreReportView.as_view(), name="dre_report"),
    path("dre/resultados/", DreResultsView.as_view(), name="dre_results"),
    path("dre/pdf/preview/", DrePdfPreviewView.as_view(), name="dre_pdf_preview"),
    path("dre/pdf/", DrePdfView.as_view(), name="dre_pdf"),
    path("dre/excel/", DreExcelView.as_view(), name="dre_excel"),
]
