from django.urls import path
from django.views.generic import RedirectView

from apps.finance.views import (
    EmissionPreviewView,
    EmissionRequestCreateView,
    EmissionWorkOrderKitComponentUpdateView,
    EmissionWorkOrderItemUpdateView,
    CommissionReportView,
    FinancialGroupCreateView,
    FinancialGroupDeleteView,
    FinancialGroupListView,
    FinancialReportsHomeView,
    FinancialGroupUpdateView,
    FiscalReferencedBasisApproveView,
    FiscalReferencedBasisCreateView,
    FiscalReferencedBasisDetailView,
    FiscalReferencedBasisFeatureToggleView,
    FiscalReferencedBasisListView,
    FiscalReferencedBasisPayloadView,
    FiscalCreditProductPreviewApproveView,
    FiscalCreditProductPreviewCreateView,
    FiscalCreditProductPreviewDetailView,
    FiscalCreditProductPreviewListView,
    FiscalCreditProductPreviewPayloadView,
    FiscalDebitProductPreviewApproveView,
    FiscalDebitProductPreviewCreateView,
    FiscalDebitProductPreviewDetailView,
    FiscalDebitProductPreviewListView,
    FiscalDebitProductPreviewPayloadView,
    IssuedDocumentsArchiveDownloadView,
    IssuedDocumentsListView,
    NfeCreateRedirectView,
    NfeCreditDownloadView,
    NfeCreditCancellationDownloadView,
    NfeCreditCancellationPayloadView,
    NfeCreditCancellationView,
    NfeCreditIssueView,
    NfeCreditPayloadView,
    NfeDebitDownloadView,
    NfeDebitCancellationDownloadView,
    NfeDebitCancellationPayloadView,
    NfeDebitCancellationView,
    NfeDebitEmissionFeatureToggleView,
    NfeDebitIssueView,
    NfeDebitPayloadView,
    NfeAdjustmentDownloadView,
    NfeAdjustmentIssueView,
    NfeComplementaryDownloadView,
    NfeComplementaryPriceQuantityIssueView,
    NfeCorrectionDownloadView,
    NfeCorrectionIssueView,
    NfeCorrectionPayloadView,
    NfeDocumentDownloadView,
    NfeIbsCbsEvent112110CancelView,
    NfeIbsCbsEvent112110IssueView,
    NfeIbsCbsEvent112130CancelView,
    NfeIbsCbsEvent112130IssueView,
    NfeIbsCbsEvent112150CancelView,
    NfeIbsCbsEvent112150IssueView,
    NfeIbsCbsEventDownloadView,
    NfeIbsCbsEventPayloadView,
    NfePreviewPdfView,
    NfeRequestCancelView,
    NfeRequestDetailView,
    NfeRequestInvalidateView,
    NfeRequestListView,
    NfeRequestReconcileView,
    NfeRequestUpdateView,
    NfeReturnDownloadView,
    NfeReturnIssueView,
    NfeReturnPayloadView,
    NfceDocumentDownloadView,
    NfceDocumentListView,
    NfceInutilizationDownloadView,
    NfceInutilizationPayloadView,
    NfceInutilizationView,
    NfceManualEmissionView,
    NfceCancellationDownloadView,
    NfceCancellationView,
    NfceDocumentPayloadView,
    NfseCreateRedirectView,
    NfseBatchReconcileView,
    NfseRequestCancelView,
    NfseCancellationPayloadView,
    NfseCancellationDownloadView,
    NfseDocumentDownloadView,
    NfseManifestationDownloadView,
    NfseManifestationIssueView,
    NfseManifestationPayloadView,
    NfseManualEmissionDetailView,
    NfseManualEmissionDownloadView,
    NfseManualEmissionCancelView,
    NfseManualEmissionCancellationDownloadView,
    NfseManualEmissionCancellationPayloadView,
    NfseManualEmissionIssueView,
    NfseManualEmissionListView,
    NfseManualEmissionPayloadView,
    NfseManualEmissionPreviewApproveView,
    NfseManualEmissionPreviewCreateView,
    NfseManualEmissionPreviewDetailView,
    NfseManualEmissionPreviewListView,
    NfseManualEmissionPreviewPayloadView,
    NfseManualEmissionReconcileView,
    NfseExternalXmlInboxDetailView,
    NfseExternalXmlInboxBulkActionView,
    NfseExternalXmlInboxExportView,
    NfseExternalXmlInboxItemApproveView,
    NfseExternalXmlInboxItemDiscardView,
    NfseExternalXmlInboxItemPayloadView,
    NfseExternalXmlInboxListView,
    NfseExternalXmlInboxProcessView,
    NfseExternalXmlInboxUploadView,
    NfseReceivedDocumentDetailView,
    NfseReceivedDocumentBatchImportView,
    NfseReceivedDocumentImportView,
    NfseReceivedDocumentListView,
    NfseReceivedDocumentConsultationIssueView,
    NfseReceivedDocumentConsultationPayloadView,
    NfseReceivedDocumentManifestationDownloadView,
    NfseReceivedDocumentManifestationIssueView,
    NfseReceivedDocumentManifestationPayloadView,
    NfseReceivedDocumentPayloadView,
    NfseReceivedDocumentXmlDownloadView,
    NfseReceivedImportBatchDetailView,
    NfsePreviewPdfView,
    NfseRequestDetailView,
    NfseRequestListView,
    NfseRequestReconcileView,
    NfseRequestUpdateView,
    NfseSubstitutionPreviewApproveView,
    NfseSubstitutionPreviewCreateView,
    NfseSubstitutionPreviewDetailView,
    NfseSubstitutionPreviewListView,
    NfseSubstitutionPreviewPayloadView,
    NfseSubstitutionIssueView,
    NfseSubstitutionPayloadView,
    NfseSubstitutionDownloadView,
    NfseMunicipalCapabilityCreateView,
    NfseMunicipalCapabilityListView,
    NfseMunicipalCapabilityStatusView,
    NfseMunicipalCapabilityUpdateView,
    TaxClassCreateView,
    TaxClassListView,
    TaxClassPresetCreateView,
    TaxClassPresetListView,
    TaxClassPresetUpdateView,
    TaxClassUpdateView,
    WebhookView,
    WebmaniaCompanyDetailView,
    WebmaniaCompanyListView,
    WebmaniaCompanySyncView,
    WebmaniaCompanyUpdateView,
    DrePdfPreviewView,
    DrePdfView,
    DreExcelView,
    DreReportView,
    DreResultsView,
)

from apps.finance.views.cash_flow import CashFlowView
from apps.finance.views.bank_account import BankAccountListView, BankAccountUpdateView, BankAccountCreateView
from apps.finance.views.financial_movement import (
    FinancialMovementCreateView,
    FinancialMovementDeleteView,
    FinancialMovementUpdateView,
    EntityListView,
    EntityDetailView,
)
from apps.finance.views.payment_method import PaymentMethodListView, PaymentMethodCreateView, PaymentMethodUpdateView
from apps.finance.views.reports import (
    BatchConciliateModalView,
    BatchConciliateView,
    ReportMovementEditView,
    ReportMovementDeleteView,
    FinancialBulkPayView,
)
from apps.finance.views.movement_group import GroupMovementWizardView, GroupMovementDeleteView

app_name = "finance"

urlpatterns = [
    path("fiscal/previas-debito-multa-juros/", FiscalDebitProductPreviewListView.as_view(), name="fiscal_debit_product_preview_list"),
    path("fiscal/previas-debito-multa-juros/criar/", FiscalDebitProductPreviewCreateView.as_view(), name="fiscal_debit_product_preview_create"),
    path("fiscal/previas-debito-multa-juros/<int:pk>/", FiscalDebitProductPreviewDetailView.as_view(), name="fiscal_debit_product_preview_detail"),
    path("fiscal/previas-debito-multa-juros/<int:pk>/aprovar/", FiscalDebitProductPreviewApproveView.as_view(), name="fiscal_debit_product_preview_approve"),
    path("fiscal/previas-debito-multa-juros/<int:pk>/payload/", FiscalDebitProductPreviewPayloadView.as_view(), name="fiscal_debit_product_preview_payload"),
    path("fiscal/previas-debito-multa-juros/habilitacao/", NfeDebitEmissionFeatureToggleView.as_view(), name="nfe_debit_emission_toggle"),
    path("fiscal/previas-debito-multa-juros/<int:pk>/emitir/", NfeDebitIssueView.as_view(), name="nfe_debit_issue"),
    path("fiscal/debitos/<int:pk>/payload/", NfeDebitPayloadView.as_view(), name="nfe_debit_payload"),
    path("fiscal/debitos/<int:pk>/cancelar/", NfeDebitCancellationView.as_view(), name="nfe_debit_cancel"),
    path("fiscal/debitos/<int:pk>/cancelamento/<int:event_pk>/payload/", NfeDebitCancellationPayloadView.as_view(), name="nfe_debit_cancellation_payload"),
    path("fiscal/debitos/<int:pk>/cancelamento/<int:event_pk>/xml/", NfeDebitCancellationDownloadView.as_view(), name="nfe_debit_cancellation_download"),
    path("fiscal/debitos/<int:pk>/<str:document>/", NfeDebitDownloadView.as_view(), name="nfe_debit_download"),
    path("fiscal/previas-credito-multa-juros/", FiscalCreditProductPreviewListView.as_view(), name="fiscal_credit_product_preview_list"),
    path("fiscal/previas-credito-multa-juros/criar/", FiscalCreditProductPreviewCreateView.as_view(), name="fiscal_credit_product_preview_create"),
    path("fiscal/previas-credito-multa-juros/<int:pk>/", FiscalCreditProductPreviewDetailView.as_view(), name="fiscal_credit_product_preview_detail"),
    path("fiscal/previas-credito-multa-juros/<int:pk>/aprovar/", FiscalCreditProductPreviewApproveView.as_view(), name="fiscal_credit_product_preview_approve"),
    path("fiscal/previas-credito-multa-juros/<int:pk>/payload/", FiscalCreditProductPreviewPayloadView.as_view(), name="fiscal_credit_product_preview_payload"),
    path("fiscal/previas-credito-multa-juros/<int:pk>/emitir/", NfeCreditIssueView.as_view(), name="nfe_credit_issue"),
    path("fiscal/creditos/<int:pk>/payload/", NfeCreditPayloadView.as_view(), name="nfe_credit_payload"),
    path("fiscal/creditos/<int:pk>/cancelar/", NfeCreditCancellationView.as_view(), name="nfe_credit_cancel"),
    path("fiscal/creditos/<int:pk>/cancelamento/<int:event_pk>/payload/", NfeCreditCancellationPayloadView.as_view(), name="nfe_credit_cancellation_payload"),
    path("fiscal/creditos/<int:pk>/cancelamento/<int:event_pk>/xml/", NfeCreditCancellationDownloadView.as_view(), name="nfe_credit_cancellation_download"),
    path("fiscal/creditos/<int:pk>/<str:document>/", NfeCreditDownloadView.as_view(), name="nfe_credit_download"),
    path("fiscal/bases-credito-debito/", FiscalReferencedBasisListView.as_view(), name="fiscal_referenced_basis_list"),
    path("fiscal/bases-credito-debito/criar/", FiscalReferencedBasisCreateView.as_view(), name="fiscal_referenced_basis_create"),
    path("fiscal/bases-credito-debito/habilitacao/", FiscalReferencedBasisFeatureToggleView.as_view(), name="fiscal_referenced_basis_toggle"),
    path("fiscal/bases-credito-debito/<int:pk>/", FiscalReferencedBasisDetailView.as_view(), name="fiscal_referenced_basis_detail"),
    path("fiscal/bases-credito-debito/<int:pk>/aprovar/", FiscalReferencedBasisApproveView.as_view(), name="fiscal_referenced_basis_approve"),
    path("fiscal/bases-credito-debito/<int:pk>/payload/", FiscalReferencedBasisPayloadView.as_view(), name="fiscal_referenced_basis_payload"),
    path("reports/", FinancialReportsHomeView.as_view(), name="reports_home"),
    path("reports/movement/<int:pk>/edit/", ReportMovementEditView.as_view(), name="report_movement_edit"),
    path("reports/movement/<int:pk>/delete/", ReportMovementDeleteView.as_view(), name="report_movement_delete"),
    path("reports/batch-conciliate/modal/", BatchConciliateModalView.as_view(), name="batch_conciliate_modal"),
    path("reports/batch-conciliate/", BatchConciliateView.as_view(), name="batch_conciliate"),
    path("reports/bulk-pay/", FinancialBulkPayView.as_view(), name="bulk_pay"),
    path("reports/group/wizard/", GroupMovementWizardView.as_view(), name="group_movement_wizard"),
    path("reports/group/<int:pk>/delete/", GroupMovementDeleteView.as_view(), name="group_movement_delete"),
    path("comissoes/", CommissionReportView.as_view(), name="commission_report"),
    path("notas-emitidas/", IssuedDocumentsListView.as_view(), name="issued_documents_list"),
    path("notas-emitidas/download/<str:document_group>/", IssuedDocumentsArchiveDownloadView.as_view(), name="issued_documents_download"),
    # Financial Groups
    path("financial-groups/", FinancialGroupListView.as_view(), name="financial_groups_list"),
    path("financial-groups/create/", FinancialGroupCreateView.as_view(), name="financial_groups_create"),
    path("financial-groups/<int:pk>/update/", FinancialGroupUpdateView.as_view(), name="financial_groups_update"),
    path("financial-groups/<int:pk>/delete/", FinancialGroupDeleteView.as_view(), name="financial_groups_delete"),
    # Payment Method
    path("payment-methods/", PaymentMethodListView.as_view(), name="payment_methods_list"),
    path("payment-methods/create/", PaymentMethodCreateView.as_view(), name="payment_methods_create"),
    path("payment-methods/<int:pk>/update/", PaymentMethodUpdateView.as_view(), name="payment_methods_update"),
    # Unified emission
    path("emissao/preview/", EmissionPreviewView.as_view(), name="emission_preview"),
    path("emissao/workorder/<int:workorder_pk>/item/<int:item_id>/edit/", EmissionWorkOrderItemUpdateView.as_view(), name="emission_workorder_item_edit"),
    path("emissao/workorder/<int:workorder_pk>/kit-item/<int:item_id>/<str:component_type>/<int:component_id>/edit/", EmissionWorkOrderKitComponentUpdateView.as_view(), name="emission_workorder_kit_component_edit"),
    path("emissao/", EmissionRequestCreateView.as_view(), name="emission_create"),
    # NFE
    path("nfe/", NfeRequestListView.as_view(), name="nfe_emit"),
    path("nfe/list/", NfeRequestListView.as_view(), name="nfe_list"),
    path("nfe/create/", NfeCreateRedirectView.as_view(), name="nfe_create"),
    path("nfe/<int:pk>/", NfeRequestDetailView.as_view(), name="nfe_detail"),
    path("nfe/<int:pk>/reconciliar/", NfeRequestReconcileView.as_view(), name="nfe_reconcile"),
    path("nfe/<int:pk>/inutilizar/", NfeRequestInvalidateView.as_view(), name="nfe_invalidate"),
    path("nfe/<int:pk>/cancelar/", NfeRequestCancelView.as_view(), name="nfe_cancel"),
    path("nfe/<int:pk>/carta-correcao/", NfeCorrectionIssueView.as_view(), name="nfe_correction_issue"),
    path("nfe/<int:pk>/carta-correcao/<int:event_pk>/payload/", NfeCorrectionPayloadView.as_view(), name="nfe_correction_payload"),
    path("nfe/<int:pk>/carta-correcao/<int:event_pk>/<str:document>/", NfeCorrectionDownloadView.as_view(), name="nfe_correction_download"),
    path("nfe/<int:pk>/evento-ibs-cbs/112110/", NfeIbsCbsEvent112110IssueView.as_view(), name="nfe_ibs_cbs_event_112110_issue"),
    path("nfe/<int:pk>/evento-ibs-cbs/112130/", NfeIbsCbsEvent112130IssueView.as_view(), name="nfe_ibs_cbs_event_112130_issue"),
    path("nfe/<int:pk>/evento-ibs-cbs/112150/", NfeIbsCbsEvent112150IssueView.as_view(), name="nfe_ibs_cbs_event_112150_issue"),
    path("nfe/<int:pk>/evento-ibs-cbs/112110/<int:event_pk>/cancelar/", NfeIbsCbsEvent112110CancelView.as_view(), name="nfe_ibs_cbs_event_112110_cancel"),
    path("nfe/<int:pk>/evento-ibs-cbs/112130/<int:event_pk>/cancelar/", NfeIbsCbsEvent112130CancelView.as_view(), name="nfe_ibs_cbs_event_112130_cancel"),
    path("nfe/<int:pk>/evento-ibs-cbs/112150/<int:event_pk>/cancelar/", NfeIbsCbsEvent112150CancelView.as_view(), name="nfe_ibs_cbs_event_112150_cancel"),
    path("nfe/<int:pk>/evento-ibs-cbs/<int:event_pk>/xml/", NfeIbsCbsEventDownloadView.as_view(), name="nfe_ibs_cbs_event_download"),
    path("nfe/<int:pk>/evento-ibs-cbs/<int:event_pk>/payload/", NfeIbsCbsEventPayloadView.as_view(), name="nfe_ibs_cbs_event_payload"),
    path("nfe/<int:pk>/devolucao-estorno/", NfeReturnIssueView.as_view(), name="nfe_return_issue"),
    path("nfe/<int:pk>/devolucao-estorno/<int:document_pk>/payload/", NfeReturnPayloadView.as_view(), name="nfe_return_payload"),
    path("nfe/<int:pk>/devolucao-estorno/<int:document_pk>/<str:document>/", NfeReturnDownloadView.as_view(), name="nfe_return_download"),
    path("nfe/<int:pk>/complementar/preco-quantidade/", NfeComplementaryPriceQuantityIssueView.as_view(), name="nfe_complementary_price_quantity_issue"),
    path("nfe/<int:pk>/complementar/<int:document_pk>/<str:document>/", NfeComplementaryDownloadView.as_view(), name="nfe_complementary_download"),
    path("nfe/<int:pk>/ajuste/", NfeAdjustmentIssueView.as_view(), name="nfe_adjustment_issue"),
    path("nfe/<int:pk>/ajuste/<int:document_pk>/<str:document>/", NfeAdjustmentDownloadView.as_view(), name="nfe_adjustment_download"),
    path("nfe/<int:pk>/documentos/<str:document>/", NfeDocumentDownloadView.as_view(), name="nfe_document_download"),
    path("nfe/<int:pk>/previa/pdf/", NfePreviewPdfView.as_view(), name="nfe_preview_pdf"),
    path("nfe/<int:pk>/edit/", NfeRequestUpdateView.as_view(), name="nfe_update"),
    # NFC-e
    path("nfce/", NfceDocumentListView.as_view(), name="nfce_list"),
    path("nfce/manual/", NfceManualEmissionView.as_view(), name="nfce_manual_emit"),
    path("nfce/inutilizar/", NfceInutilizationView.as_view(), name="nfce_inutilization_create"),
    path("nfce/inutilizacoes/<int:pk>/xml/", NfceInutilizationDownloadView.as_view(), name="nfce_inutilization_download"),
    path("nfce/inutilizacoes/<int:pk>/payload/", NfceInutilizationPayloadView.as_view(), name="nfce_inutilization_payload"),
    path("nfce/<int:pk>/cancelar/", NfceCancellationView.as_view(), name="nfce_cancel"),
    path("nfce/<int:pk>/cancelamento/<int:event_pk>/xml/", NfceCancellationDownloadView.as_view(), name="nfce_cancellation_download"),
    path("nfce/<int:pk>/documentos/<str:document>/", NfceDocumentDownloadView.as_view(), name="nfce_document_download"),
    path("nfce/<int:pk>/payload/", NfceDocumentPayloadView.as_view(), name="nfce_payload"),
    # Classe Imposto
    path("classe-imposto/", TaxClassListView.as_view(), name="tax_class_list"),
    path("classe-imposto/", TaxClassListView.as_view(), name="tax_class_manager"),
    path("classe-imposto/create/", TaxClassCreateView.as_view(), name="tax_class_create"),
    path("classe-imposto/<str:reference>/edit/", TaxClassUpdateView.as_view(), name="tax_class_update"),
    path("classe-imposto/presets/", TaxClassPresetListView.as_view(), name="tax_class_preset_list"),
    path("classe-imposto/presets/create/", TaxClassPresetCreateView.as_view(), name="tax_class_preset_create"),
    path("classe-imposto/presets/<int:pk>/edit/", TaxClassPresetUpdateView.as_view(), name="tax_class_preset_update"),
    # Conta Bancária
    path("bank-account/", BankAccountListView.as_view(), name="bank_account_list"),
    path("bank-account/create/", BankAccountCreateView.as_view(), name="bank_account_create"),
    path("bank-account/<int:pk>/update/", BankAccountUpdateView.as_view(), name="bank_account_update"),
    # Movimentação Financeira
    path("financial-movement/create/", FinancialMovementCreateView.as_view(), name="financial_movement_create"),
    path("financial-movement/<int:pk>/update/", FinancialMovementUpdateView.as_view(), name="financial_movement_update"),
    path("financial-movement/<int:pk>/delete/", FinancialMovementDeleteView.as_view(), name="financial_movement_delete"),
    path("entities", EntityListView.as_view(), name="entities"),
    path("entity_details", EntityDetailView.as_view(), name="entity_details"),
    # NFS-e
    path("nfse/", NfseRequestListView.as_view(), name="nfse_list"),
    path("nfse/create/", NfseCreateRedirectView.as_view(), name="nfse_create"),
    path("nfse/<int:pk>/", NfseRequestDetailView.as_view(), name="nfse_detail"),
    path("nfse/<int:pk>/reconciliar/", NfseRequestReconcileView.as_view(), name="nfse_reconcile"),
    path("nfse/<int:pk>/reconciliar-lote/", NfseBatchReconcileView.as_view(), name="nfse_batch_reconcile"),
    path("nfse/<int:pk>/cancelar/", NfseRequestCancelView.as_view(), name="nfse_cancel"),
    path("nfse/<int:pk>/cancelamento/<int:cancellation_pk>/payload/", NfseCancellationPayloadView.as_view(), name="nfse_cancellation_payload"),
    path("nfse/<int:pk>/cancelamento/<int:cancellation_pk>/xml/", NfseCancellationDownloadView.as_view(), name="nfse_cancellation_download"),
    path("nfse/<int:pk>/manifestar/", NfseManifestationIssueView.as_view(), name="nfse_manifestation_issue"),
    path("nfse/<int:pk>/manifestacoes/<int:manifestation_pk>/payload/", NfseManifestationPayloadView.as_view(), name="nfse_manifestation_payload"),
    path("nfse/<int:pk>/manifestacoes/<int:manifestation_pk>/xml/", NfseManifestationDownloadView.as_view(), name="nfse_manifestation_download"),
    path("nfse/<int:pk>/documentos/<str:document>/", NfseDocumentDownloadView.as_view(), name="nfse_document_download"),
    path("nfse/<int:pk>/previa/pdf/", NfsePreviewPdfView.as_view(), name="nfse_preview_pdf"),
    path("nfse/<int:pk>/edit/", NfseRequestUpdateView.as_view(), name="nfse_update"),
    path("nfse/recebidas/", NfseReceivedDocumentListView.as_view(), name="nfse_received_document_list"),
    path("nfse/recebidas/importar/", NfseReceivedDocumentImportView.as_view(), name="nfse_received_document_import"),
    path("nfse/recebidas/importar-lote/", NfseReceivedDocumentBatchImportView.as_view(), name="nfse_received_batch_import"),
    path("nfse/recebidas/lotes/<int:pk>/", NfseReceivedImportBatchDetailView.as_view(), name="nfse_received_batch_detail"),
    path("nfse/recebidas/inbox/", NfseExternalXmlInboxListView.as_view(), name="nfse_external_xml_inbox_list"),
    path("nfse/recebidas/inbox/exportar/", NfseExternalXmlInboxExportView.as_view(), name="nfse_external_xml_inbox_export"),
    path("nfse/recebidas/inbox/nova/", NfseExternalXmlInboxUploadView.as_view(), name="nfse_external_xml_inbox_upload"),
    path("nfse/recebidas/inbox/<int:pk>/", NfseExternalXmlInboxDetailView.as_view(), name="nfse_external_xml_inbox_detail"),
    path("nfse/recebidas/inbox/<int:pk>/acoes-em-massa/", NfseExternalXmlInboxBulkActionView.as_view(), name="nfse_external_xml_inbox_bulk_action"),
    path("nfse/recebidas/inbox/<int:pk>/processar/", NfseExternalXmlInboxProcessView.as_view(), name="nfse_external_xml_inbox_process"),
    path("nfse/recebidas/inbox/<int:pk>/itens/<int:item_pk>/aprovar/", NfseExternalXmlInboxItemApproveView.as_view(), name="nfse_external_xml_inbox_item_approve"),
    path("nfse/recebidas/inbox/<int:pk>/itens/<int:item_pk>/descartar/", NfseExternalXmlInboxItemDiscardView.as_view(), name="nfse_external_xml_inbox_item_discard"),
    path("nfse/recebidas/inbox/<int:pk>/itens/<int:item_pk>/payload/", NfseExternalXmlInboxItemPayloadView.as_view(), name="nfse_external_xml_inbox_item_payload"),
    path("nfse/recebidas/<int:pk>/", NfseReceivedDocumentDetailView.as_view(), name="nfse_received_document_detail"),
    path("nfse/recebidas/<int:pk>/consultar/", NfseReceivedDocumentConsultationIssueView.as_view(), name="nfse_received_document_consultation_issue"),
    path("nfse/recebidas/<int:pk>/consultas/<int:consultation_pk>/payload/", NfseReceivedDocumentConsultationPayloadView.as_view(), name="nfse_received_document_consultation_payload"),
    path("nfse/recebidas/<int:pk>/manifestar/", NfseReceivedDocumentManifestationIssueView.as_view(), name="nfse_received_document_manifestation_issue"),
    path("nfse/recebidas/<int:pk>/manifestacoes/<int:manifestation_pk>/payload/", NfseReceivedDocumentManifestationPayloadView.as_view(), name="nfse_received_document_manifestation_payload"),
    path("nfse/recebidas/<int:pk>/manifestacoes/<int:manifestation_pk>/xml/", NfseReceivedDocumentManifestationDownloadView.as_view(), name="nfse_received_document_manifestation_download"),
    path("nfse/recebidas/<int:pk>/payload/", NfseReceivedDocumentPayloadView.as_view(), name="nfse_received_document_payload"),
    path("nfse/recebidas/<int:pk>/xml/", NfseReceivedDocumentXmlDownloadView.as_view(), name="nfse_received_document_xml"),
    path("nfse/capacidades/", NfseMunicipalCapabilityListView.as_view(), name="nfse_capability_list"),
    path("nfse/capacidades/nova/", NfseMunicipalCapabilityCreateView.as_view(), name="nfse_capability_create"),
    path("nfse/capacidades/<int:pk>/editar/", NfseMunicipalCapabilityUpdateView.as_view(), name="nfse_capability_update"),
    path("nfse/capacidades/<int:pk>/consultar-status/", NfseMunicipalCapabilityStatusView.as_view(), name="nfse_capability_status"),
    path("nfse/emissao-manual/previews/", NfseManualEmissionPreviewListView.as_view(), name="nfse_manual_emission_preview_list"),
    path("nfse/emissao-manual/previews/nova/", NfseManualEmissionPreviewCreateView.as_view(), name="nfse_manual_emission_preview_create"),
    path("nfse/emissao-manual/previews/<int:pk>/", NfseManualEmissionPreviewDetailView.as_view(), name="nfse_manual_emission_preview_detail"),
    path("nfse/emissao-manual/previews/<int:pk>/aprovar/", NfseManualEmissionPreviewApproveView.as_view(), name="nfse_manual_emission_preview_approve"),
    path("nfse/emissao-manual/previews/<int:pk>/payload/", NfseManualEmissionPreviewPayloadView.as_view(), name="nfse_manual_emission_preview_payload"),
    path("nfse/emissao-manual/previews/<int:preview_pk>/emitir/", NfseManualEmissionIssueView.as_view(), name="nfse_manual_emission_issue"),
    path("nfse/emissao-manual/emissoes/", NfseManualEmissionListView.as_view(), name="nfse_manual_emission_list"),
    path("nfse/emissao-manual/emissoes/<int:pk>/", NfseManualEmissionDetailView.as_view(), name="nfse_manual_emission_detail"),
    path("nfse/emissao-manual/emissoes/<int:pk>/payload/", NfseManualEmissionPayloadView.as_view(), name="nfse_manual_emission_payload"),
    path("nfse/emissao-manual/emissoes/<int:pk>/cancelar/", NfseManualEmissionCancelView.as_view(), name="nfse_manual_emission_cancel"),
    path("nfse/emissao-manual/emissoes/<int:pk>/cancelamento/<int:cancellation_pk>/payload/", NfseManualEmissionCancellationPayloadView.as_view(), name="nfse_manual_emission_cancellation_payload"),
    path("nfse/emissao-manual/emissoes/<int:pk>/cancelamento/<int:cancellation_pk>/xml/", NfseManualEmissionCancellationDownloadView.as_view(), name="nfse_manual_emission_cancellation_download"),
    path("nfse/emissao-manual/emissoes/<int:pk>/reconciliar/", NfseManualEmissionReconcileView.as_view(), name="nfse_manual_emission_reconcile"),
    path("nfse/emissao-manual/emissoes/<int:pk>/<str:kind>/", NfseManualEmissionDownloadView.as_view(), name="nfse_manual_emission_download"),
    path("nfse/substituicoes/previews/", NfseSubstitutionPreviewListView.as_view(), name="nfse_substitution_preview_list"),
    path("nfse/substituicoes/previews/nova/", NfseSubstitutionPreviewCreateView.as_view(), name="nfse_substitution_preview_create"),
    path("nfse/substituicoes/previews/<int:pk>/", NfseSubstitutionPreviewDetailView.as_view(), name="nfse_substitution_preview_detail"),
    path("nfse/substituicoes/previews/<int:pk>/aprovar/", NfseSubstitutionPreviewApproveView.as_view(), name="nfse_substitution_preview_approve"),
    path("nfse/substituicoes/previews/<int:pk>/payload/", NfseSubstitutionPreviewPayloadView.as_view(), name="nfse_substitution_preview_payload"),
    path("nfse/substituicoes/previews/<int:pk>/substituir/", NfseSubstitutionIssueView.as_view(), name="nfse_substitution_issue"),
    path("nfse/substituicoes/previews/<int:pk>/transmissoes/<int:substitution_pk>/payload/", NfseSubstitutionPayloadView.as_view(), name="nfse_substitution_payload"),
    path("nfse/substituicoes/previews/<int:pk>/transmissoes/<int:substitution_pk>/<str:document>/", NfseSubstitutionDownloadView.as_view(), name="nfse_substitution_download"),
    # WebMania
    path("webmania/empresas/", WebmaniaCompanyListView.as_view(), name="webmania_company_list"),
    path("webmania/empresas/sync/", WebmaniaCompanySyncView.as_view(), name="webmania_company_sync"),
    path("webmania/empresas/<int:pk>/", WebmaniaCompanyDetailView.as_view(), name="webmania_company_detail"),
    path("webmania/empresas/<int:pk>/editar/", WebmaniaCompanyUpdateView.as_view(), name="webmania_company_update"),
    path("webmania/requisicoes/", RedirectView.as_view(pattern_name="workshops:emission_history", permanent=False), name="webmania_requests"),
    path("webmania/webhook/ping/", WebhookView.as_view(), name="webhook_ping"),
    path("webmania/webhook/", WebhookView.as_view(), name="webhook"),
    # Fluxo de Contas
    path("fluxo-de-contas/", CashFlowView.as_view(), name="cash_flow"),
    # DRE
    path("dre/", DreReportView.as_view(), name="dre_report"),
    path("dre/resultados/", DreResultsView.as_view(), name="dre_results"),
    path("dre/pdf/preview/", DrePdfPreviewView.as_view(), name="dre_pdf_preview"),
    path("dre/pdf/", DrePdfView.as_view(), name="dre_pdf"),
    path("dre/excel/", DreExcelView.as_view(), name="dre_excel"),
]
