from django.urls import path
from django.views.generic import RedirectView

from apps.finance.views import (
    EmissionPreviewView,
    EmissionRequestCreateView,
    EmissionWorkOrderKitComponentUpdateView,
    EmissionWorkOrderItemUpdateView,
    CommissionReportView,
    FinancialGroupCreateView,
    FinancialGroupDeleteView,
    FinancialGroupListView,
    FinancialReportsHomeView,
    FinancialGroupUpdateView,
    IssuedDocumentsArchiveDownloadView,
    IssuedDocumentsListView,
    NfeCreateRedirectView,
    NfeAdjustmentDownloadView,
    NfeAdjustmentIssueView,
    NfeComplementaryDownloadView,
    NfeComplementaryPriceQuantityIssueView,
    NfeCorrectionDownloadView,
    NfeCorrectionIssueView,
    NfeDocumentDownloadView,
    NfePreviewPdfView,
    NfeRequestCancelView,
    NfeRequestDetailView,
    NfeRequestInvalidateView,
    NfeRequestListView,
    NfeRequestReconcileView,
    NfeRequestUpdateView,
    NfeReturnDownloadView,
    NfeReturnIssueView,
    NfceDocumentDownloadView,
    NfceDocumentListView,
    NfceManualEmissionView,
    NfceCancellationDownloadView,
    NfceCancellationView,
    NfceDocumentPayloadView,
    NfseCreateRedirectView,
    NfseRequestCancelView,
    NfseDocumentDownloadView,
    NfsePreviewPdfView,
    NfseRequestDetailView,
    NfseRequestListView,
    NfseRequestReconcileView,
    NfseRequestUpdateView,
    TaxClassCreateView,
    TaxClassListView,
    TaxClassPresetCreateView,
    TaxClassPresetListView,
    TaxClassPresetUpdateView,
    TaxClassUpdateView,
    WebhookView,
    WebmaniaCompanyDetailView,
    WebmaniaCompanyListView,
    WebmaniaCompanySyncView,
    WebmaniaCompanyUpdateView,
    DrePdfPreviewView,
    DrePdfView,
    DreExcelView,
    DreReportView,
    DreResultsView,
)

from apps.finance.views.cash_flow import CashFlowView
from apps.finance.views.bank_account import BankAccountListView, BankAccountUpdateView, BankAccountCreateView
from apps.finance.views.financial_movement import (
    FinancialMovementCreateView,
    FinancialMovementDeleteView,
    FinancialMovementUpdateView,
    EntityListView,
    EntityDetailView,
)
from apps.finance.views.payment_method import PaymentMethodListView, PaymentMethodCreateView, PaymentMethodUpdateView
from apps.finance.views.reports import (
    BatchConciliateModalView,
    BatchConciliateView,
    ReportMovementEditView,
    ReportMovementDeleteView,
    FinancialBulkPayView,
)
from apps.finance.views.movement_group import GroupMovementWizardView, GroupMovementDeleteView

app_name = "finance"

urlpatterns = [
    path("reports/", FinancialReportsHomeView.as_view(), name="reports_home"),
    path("reports/movement/<int:pk>/edit/", ReportMovementEditView.as_view(), name="report_movement_edit"),
    path("reports/movement/<int:pk>/delete/", ReportMovementDeleteView.as_view(), name="report_movement_delete"),
    path("reports/batch-conciliate/modal/", BatchConciliateModalView.as_view(), name="batch_conciliate_modal"),
    path("reports/batch-conciliate/", BatchConciliateView.as_view(), name="batch_conciliate"),
    path("reports/bulk-pay/", FinancialBulkPayView.as_view(), name="bulk_pay"),
    path("reports/group/wizard/", GroupMovementWizardView.as_view(), name="group_movement_wizard"),
    path("reports/group/<int:pk>/delete/", GroupMovementDeleteView.as_view(), name="group_movement_delete"),
    path("comissoes/", CommissionReportView.as_view(), name="commission_report"),
    path("notas-emitidas/", IssuedDocumentsListView.as_view(), name="issued_documents_list"),
    path("notas-emitidas/download/<str:document_group>/", IssuedDocumentsArchiveDownloadView.as_view(), name="issued_documents_download"),
    # Financial Groups
    path("financial-groups/", FinancialGroupListView.as_view(), name="financial_groups_list"),
    path("financial-groups/create/", FinancialGroupCreateView.as_view(), name="financial_groups_create"),
    path("financial-groups/<int:pk>/update/", FinancialGroupUpdateView.as_view(), name="financial_groups_update"),
    path("financial-groups/<int:pk>/delete/", FinancialGroupDeleteView.as_view(), name="financial_groups_delete"),
    # Payment Method
    path("payment-methods/", PaymentMethodListView.as_view(), name="payment_methods_list"),
    path("payment-methods/create/", PaymentMethodCreateView.as_view(), name="payment_methods_create"),
    path("payment-methods/<int:pk>/update/", PaymentMethodUpdateView.as_view(), name="payment_methods_update"),
    # Unified emission
    path("emissao/preview/", EmissionPreviewView.as_view(), name="emission_preview"),
    path("emissao/workorder/<int:workorder_pk>/item/<int:item_id>/edit/", EmissionWorkOrderItemUpdateView.as_view(), name="emission_workorder_item_edit"),
    path("emissao/workorder/<int:workorder_pk>/kit-item/<int:item_id>/<str:component_type>/<int:component_id>/edit/", EmissionWorkOrderKitComponentUpdateView.as_view(), name="emission_workorder_kit_component_edit"),
    path("emissao/", EmissionRequestCreateView.as_view(), name="emission_create"),
    # NFE
    path("nfe/", NfeRequestListView.as_view(), name="nfe_emit"),
    path("nfe/list/", NfeRequestListView.as_view(), name="nfe_list"),
    path("nfe/create/", NfeCreateRedirectView.as_view(), name="nfe_create"),
    path("nfe/<int:pk>/", NfeRequestDetailView.as_view(), name="nfe_detail"),
    path("nfe/<int:pk>/reconciliar/", NfeRequestReconcileView.as_view(), name="nfe_reconcile"),
    path("nfe/<int:pk>/inutilizar/", NfeRequestInvalidateView.as_view(), name="nfe_invalidate"),
    path("nfe/<int:pk>/cancelar/", NfeRequestCancelView.as_view(), name="nfe_cancel"),
    path("nfe/<int:pk>/carta-correcao/", NfeCorrectionIssueView.as_view(), name="nfe_correction_issue"),
    path("nfe/<int:pk>/carta-correcao/<int:event_pk>/<str:document>/", NfeCorrectionDownloadView.as_view(), name="nfe_correction_download"),
    path("nfe/<int:pk>/devolucao-estorno/", NfeReturnIssueView.as_view(), name="nfe_return_issue"),
    path("nfe/<int:pk>/devolucao-estorno/<int:document_pk>/<str:document>/", NfeReturnDownloadView.as_view(), name="nfe_return_download"),
    path("nfe/<int:pk>/complementar/preco-quantidade/", NfeComplementaryPriceQuantityIssueView.as_view(), name="nfe_complementary_price_quantity_issue"),
    path("nfe/<int:pk>/complementar/<int:document_pk>/<str:document>/", NfeComplementaryDownloadView.as_view(), name="nfe_complementary_download"),
    path("nfe/<int:pk>/ajuste/", NfeAdjustmentIssueView.as_view(), name="nfe_adjustment_issue"),
    path("nfe/<int:pk>/ajuste/<int:document_pk>/<str:document>/", NfeAdjustmentDownloadView.as_view(), name="nfe_adjustment_download"),
    path("nfe/<int:pk>/documentos/<str:document>/", NfeDocumentDownloadView.as_view(), name="nfe_document_download"),
    path("nfe/<int:pk>/previa/pdf/", NfePreviewPdfView.as_view(), name="nfe_preview_pdf"),
    path("nfe/<int:pk>/edit/", NfeRequestUpdateView.as_view(), name="nfe_update"),
    # NFC-e
    path("nfce/", NfceDocumentListView.as_view(), name="nfce_list"),
    path("nfce/manual/", NfceManualEmissionView.as_view(), name="nfce_manual_emit"),
    path("nfce/<int:pk>/cancelar/", NfceCancellationView.as_view(), name="nfce_cancel"),
    path("nfce/<int:pk>/cancelamento/<int:event_pk>/xml/", NfceCancellationDownloadView.as_view(), name="nfce_cancellation_download"),
    path("nfce/<int:pk>/documentos/<str:document>/", NfceDocumentDownloadView.as_view(), name="nfce_document_download"),
    path("nfce/<int:pk>/payload/", NfceDocumentPayloadView.as_view(), name="nfce_payload"),
    # Classe Imposto
    path("classe-imposto/", TaxClassListView.as_view(), name="tax_class_list"),
    path("classe-imposto/", TaxClassListView.as_view(), name="tax_class_manager"),
    path("classe-imposto/create/", TaxClassCreateView.as_view(), name="tax_class_create"),
    path("classe-imposto/<str:reference>/edit/", TaxClassUpdateView.as_view(), name="tax_class_update"),
    path("classe-imposto/presets/", TaxClassPresetListView.as_view(), name="tax_class_preset_list"),
    path("classe-imposto/presets/create/", TaxClassPresetCreateView.as_view(), name="tax_class_preset_create"),
    path("classe-imposto/presets/<int:pk>/edit/", TaxClassPresetUpdateView.as_view(), name="tax_class_preset_update"),
    # Conta Bancária
    path("bank-account/", BankAccountListView.as_view(), name="bank_account_list"),
    path("bank-account/create/", BankAccountCreateView.as_view(), name="bank_account_create"),
    path("bank-account/<int:pk>/update/", BankAccountUpdateView.as_view(), name="bank_account_update"),
    # Movimentação Financeira
    path("financial-movement/create/", FinancialMovementCreateView.as_view(), name="financial_movement_create"),
    path("financial-movement/<int:pk>/update/", FinancialMovementUpdateView.as_view(), name="financial_movement_update"),
    path("financial-movement/<int:pk>/delete/", FinancialMovementDeleteView.as_view(), name="financial_movement_delete"),
    path("entities", EntityListView.as_view(), name="entities"),
    path("entity_details", EntityDetailView.as_view(), name="entity_details"),
    # NFS-e
    path("nfse/", NfseRequestListView.as_view(), name="nfse_list"),
    path("nfse/create/", NfseCreateRedirectView.as_view(), name="nfse_create"),
    path("nfse/<int:pk>/", NfseRequestDetailView.as_view(), name="nfse_detail"),
    path("nfse/<int:pk>/reconciliar/", NfseRequestReconcileView.as_view(), name="nfse_reconcile"),
    path("nfse/<int:pk>/cancelar/", NfseRequestCancelView.as_view(), name="nfse_cancel"),
    path("nfse/<int:pk>/documentos/<str:document>/", NfseDocumentDownloadView.as_view(), name="nfse_document_download"),
    path("nfse/<int:pk>/previa/pdf/", NfsePreviewPdfView.as_view(), name="nfse_preview_pdf"),
    path("nfse/<int:pk>/edit/", NfseRequestUpdateView.as_view(), name="nfse_update"),
    # WebMania
    path("webmania/empresas/", WebmaniaCompanyListView.as_view(), name="webmania_company_list"),
    path("webmania/empresas/sync/", WebmaniaCompanySyncView.as_view(), name="webmania_company_sync"),
    path("webmania/empresas/<int:pk>/", WebmaniaCompanyDetailView.as_view(), name="webmania_company_detail"),
    path("webmania/empresas/<int:pk>/editar/", WebmaniaCompanyUpdateView.as_view(), name="webmania_company_update"),
    path("webmania/requisicoes/", RedirectView.as_view(pattern_name="workshops:emission_history", permanent=False), name="webmania_requests"),
    path("webmania/webhook/ping/", WebhookView.as_view(), name="webhook_ping"),
    path("webmania/webhook/", WebhookView.as_view(), name="webhook"),
    # Fluxo de Contas
    path("fluxo-de-contas/", CashFlowView.as_view(), name="cash_flow"),
    # DRE
    path("dre/", DreReportView.as_view(), name="dre_report"),
    path("dre/resultados/", DreResultsView.as_view(), name="dre_results"),
    path("dre/pdf/preview/", DrePdfPreviewView.as_view(), name="dre_pdf_preview"),
    path("dre/pdf/", DrePdfView.as_view(), name="dre_pdf"),
    path("dre/excel/", DreExcelView.as_view(), name="dre_excel"),
]
