# Generated by Django 6.0 on 2026-01-14 14:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import localflavor.br.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workshops", "0004_alter_workshopcost_card_rate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "cep",
                    localflavor.br.models.BRPostalCodeField(
                        max_length=9, verbose_name="CEP"
                    ),
                ),
                (
                    "logradouro",
                    models.CharField(max_length=225, verbose_name="Logradouro"),
                ),
                (
                    "numero",
                    models.CharField(
                        max_length=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Número",
                    ),
                ),
                (
                    "complemento",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Complemento",
                    ),
                ),
                ("bairro", models.CharField(max_length=20, verbose_name="Bairro")),
                ("cidade", models.CharField(max_length=20, verbose_name="Cidade")),
                (
                    "estado",
                    localflavor.br.models.BRStateField(
                        max_length=2, verbose_name="Estado"
                    ),
                ),
                (
                    "cnpj",
                    localflavor.br.models.BRCNPJField(
                        max_length=18, verbose_name="CNPJ"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "contact_person",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Responsável",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Telefone"
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Celular"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "registration_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Data de Cadastro",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "workshop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suppliers",
                        to="workshops.workshop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fornecedor",
                "verbose_name_plural": "Fornecedores",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workshop",), name="unique_supplier_per_workshop"
                    )
                ],
            },
        ),
    ]
