# Generated by Django 6.0 on 2026-01-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0002_alter_supplier_numero"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="contact_person",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Responsável"
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="email",
            field=models.EmailField(
                blank=True, default="", max_length=254, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="mobile",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="Celular"
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="phone",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="Telefone"
            ),
        ),
    ]
