# Generated by Django 6.0 on 2026-01-20 21:16

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "suppliers",
            "0003_alter_supplier_contact_person_alter_supplier_email_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="mobile",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                default="",
                max_length=20,
                region="BR",
                verbose_name="Celular",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="numero",
            field=models.PositiveIntegerField(verbose_name="Número"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                default="",
                max_length=20,
                region="BR",
                verbose_name="Telefone",
            ),
        ),
    ]
