# Generated by Django 6.0 on 2026-01-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0004_alter_supplier_mobile_alter_supplier_numero_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="atualizado_em",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Data de Atualização"
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="criado_em",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Data de Criação"
            ),
        ),
    ]
