# Generated by Django 6.0 on 2026-01-20 23:12

import localflavor.br.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0005_alter_supplier_atualizado_em_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="bairro",
            field=models.CharField(default="", max_length=20, verbose_name="Bairro"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="cep",
            field=localflavor.br.models.BRPostalCodeField(
                default="", max_length=9, verbose_name="CEP"
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="cidade",
            field=models.CharField(default="", max_length=20, verbose_name="Cidade"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="estado",
            field=localflavor.br.models.BRStateField(
                default="", max_length=2, verbose_name="Estado"
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="logradouro",
            field=models.CharField(
                default="", max_length=225, verbose_name="Logradouro"
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="numero",
            field=models.PositiveIntegerField(default=1, verbose_name="Número"),
        ),
    ]
