# Generated by Django 6.0 on 2026-03-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0006_alter_supplier_bairro_alter_supplier_cep_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Razão Social"),
        ),
    ]
