# Generated by Django 6.0 on 2026-03-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0007_alter_supplier_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='bairro',
            field=models.CharField(default='', max_length=255, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='cidade',
            field=models.CharField(default='', max_length=255, verbose_name='Cidade'),
        ),
    ]
