# Generated by Django 6.0 on 2026-06-09 12:25

import apps.core.infrastructure.fields.br_cpf_cnpj
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0008_alter_supplier_bairro_alter_supplier_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='cnpj',
            field=apps.core.infrastructure.fields.br_cpf_cnpj.BRCPFCNPJField(max_length=18, verbose_name='Documento'),
        ),
    ]
