# Generated by Django 6.0 on 2026-08-01 22:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0009_alter_supplier_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Razão social'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='registration_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de cadastro'),
        ),
    ]
