# Generated by Django 6.0 on 2026-08-05 14:40

import apps.core.infrastructure.fields.br_cpf_cnpj
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0009_alter_supplier_cnpj"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="cnpj",
            field=apps.core.infrastructure.fields.br_cpf_cnpj.BRCPFCNPJField(
                blank=True,
                default="",
                max_length=18,
                null=True,
                verbose_name="Documento",
            ),
        ),
    ]
