# Generated by Django 6.0 on 2026-10-05 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("workshops", "0045_add_workshop_commission_limits"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, verbose_name="Título")),
                ("problem", models.TextField(verbose_name="Qual o problema")),
                ("reproduction_steps", models.TextField(verbose_name="Como repetir este problema")),
                (
                    "status",
                    models.CharField(
                        choices=[("aberto", "Aberto"), ("em_andamento", "Em andamento"), ("validacao_interna", "Validação interna"), ("aguardando_validacao", "Aguardando validação"), ("reprovado", "Reprovado"), ("fechado", "Fechado"), ("cancelado", "Cancelado")],
                        db_index=True,
                        default="aberto",
                        max_length=32,
                        verbose_name="Status",
                    ),
                ),
                ("cancellation_reason", models.TextField(blank=True, verbose_name="Motivo do cancelamento")),
                ("rejection_reason", models.TextField(blank=True, verbose_name="Motivo da recusa")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Atualizado em")),
                ("captured_at", models.DateTimeField(blank=True, null=True, verbose_name="Capturado em")),
                ("assignee", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="tickets_assigned", to=settings.AUTH_USER_MODEL, verbose_name="Responsável")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="tickets_created", to=settings.AUTH_USER_MODEL, verbose_name="Criado por")),
                ("workshop", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tickets", to="workshops.workshop", verbose_name="Oficina")),
            ],
            options={
                "verbose_name": "Chamado",
                "verbose_name_plural": "Chamados",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="TicketAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file_key", models.CharField(max_length=512, verbose_name="Chave no storage")),
                ("content_type", models.CharField(blank=True, max_length=255, verbose_name="Content-Type")),
                ("original_name", models.CharField(max_length=255, verbose_name="Nome original")),
                ("size_bytes", models.PositiveBigIntegerField(default=0, verbose_name="Tamanho (bytes)")),
                ("source", models.CharField(choices=[("upload", "Upload"), ("screen_recording", "Gravação de tela"), ("rejection", "Recusa")], default="upload", max_length=32, verbose_name="Origem")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("ticket", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attachments", to="tickets.ticket", verbose_name="Chamado")),
                ("uploaded_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="ticket_attachments", to=settings.AUTH_USER_MODEL, verbose_name="Enviado por")),
            ],
            options={
                "verbose_name": "Anexo do chamado",
                "verbose_name_plural": "Anexos do chamado",
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="TicketMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("body", models.TextField(verbose_name="Mensagem")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("author", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="ticket_messages", to=settings.AUTH_USER_MODEL, verbose_name="Autor")),
                ("ticket", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="tickets.ticket", verbose_name="Chamado")),
            ],
            options={
                "verbose_name": "Mensagem do chamado",
                "verbose_name_plural": "Mensagens do chamado",
                "ordering": ("created_at",),
            },
        ),
        migrations.CreateModel(
            name="TicketStatusHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("from_status", models.CharField(blank=True, max_length=32, verbose_name="Status anterior")),
                ("to_status", models.CharField(max_length=32, verbose_name="Novo status")),
                ("note", models.TextField(blank=True, verbose_name="Observação")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="ticket_status_changes", to=settings.AUTH_USER_MODEL, verbose_name="Autor")),
                ("ticket", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="status_history", to="tickets.ticket", verbose_name="Chamado")),
            ],
            options={
                "verbose_name": "Histórico de status do chamado",
                "verbose_name_plural": "Históricos de status do chamado",
                "ordering": ("created_at",),
            },
        ),
    ]
