# Generated by Django 6.0 on 2026-03-13 19:45

import django.db.models.deletion
import localflavor.br.models
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workshops", "0014_alter_workshop_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "cnpj",
                    localflavor.br.models.BRCNPJField(
                        blank=True,
                        default="",
                        max_length=18,
                        null=True,
                        verbose_name="CNPJ",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Razão Social")),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        default="",
                        max_length=20,
                        null=True,
                        region="BR",
                        verbose_name="Telefone",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default="",
                        max_length=254,
                        null=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "workshop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="workshops.workshop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Origem",
                "verbose_name_plural": "Origens",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workshop", "name"),
                        name="unique_source_name_per_workshop",
                    )
                ],
            },
        ),
    ]
