# Generated by Django 6.0 on 2026-08-01 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='E-mail'),
        ),
    ]
