"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "CHANGE_ME_IN_PRODUCTION")

DEBUG = os.getenv("DJANGO_DEBUG", "1").lower() in ("1", "true", "yes")

ALLOWED_HOSTS = [h.strip() for h in os.getenv("DJANGO_ALLOWED_HOSTS", "").split(",") if h.strip()]

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True

CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",") if o.strip()]

# Utilize o ngrok para desenvolvimento local, se não o webhook não funciona
APP_BASE_URL = os.getenv("APP_BASE_URL", "http://localhost:8000")

# Budget Event Config
BUDGET_EVENTS_ENABLED = os.getenv("BUDGET_EVENTS_ENABLED", "0").lower() in ("1", "true", "yes")
BUDGET_POLL_INTERVAL_SECONDS = int(os.getenv("BUDGET_POLL_INTERVAL_SECONDS", "20"))
BUDGET_SSE_CHECK_INTERVAL_SECONDS = float(os.getenv("BUDGET_SSE_CHECK_INTERVAL_SECONDS", "3"))

# Logger config
PERF_LOGGING_ENABLED = os.getenv("PERF_LOGGING_ENABLED", "0").lower() in ("1", "true", "yes")
PERF_LOG_QUERIES = os.getenv("PERF_LOG_QUERIES", "0").lower() in ("1", "true", "yes")
PERF_LOG_MIN_MS = int(os.getenv("PERF_LOG_MIN_MS", "300"))
NFSE_DEBUG_LOGS = os.getenv("NFSE_DEBUG_LOGS", "0").lower() in ("1", "true", "yes")
TAX_CLASS_DEBUG_LOGS = os.getenv("TAX_CLASS_DEBUG_LOGS", "0").lower() in ("1", "true", "yes")

# Environment (required for structured logging)
ENVIRONMENT = os.getenv("ENVIRONMENT", "development")
OTEL_SERVICE_NAME = os.getenv("OTEL_SERVICE_NAME", "hunter-web")
OTEL_SERVICE_NAMESPACE = os.getenv("OTEL_SERVICE_NAMESPACE", "synplai")
OTEL_SERVICE_VERSION = os.getenv("OTEL_SERVICE_VERSION", "0.1.0")
OTEL_METRIC_EXPORT_INTERVAL_MS = int(os.getenv("OTEL_METRIC_EXPORT_INTERVAL_MS", "300000"))

# Grafana Cloud OTLP (OpenTelemetry)
# Endpoint lido automaticamente de OTEL_EXPORTER_OTLP_ENDPOINT (definido no ambiente)
OTLP_AUTH_HEADER = os.getenv("OTLP_AUTH_HEADER", "")  # "Basic base64..."

FIPE_SYNC_EVERY_ACCESS = os.getenv("FIPE_SYNC_EVERY_ACCESS", "0").lower() in ("1", "true", "yes")  # 0. Desligado, 1. Ligado
FIPE_SYNC_ACCESS_INTERVAL = int(os.getenv("FIPE_SYNC_ACCESS_INTERVAL", "500"))
FIPE_FUEL_CACHE_TTL_HOURS = int(os.getenv("FIPE_FUEL_CACHE_TTL_HOURS", "168"))
FIPE_DEV_MODE = os.getenv("FIPE_DEV_MODE", "0").lower() in ("1", "true", "yes")  #  0. Dev, 1. Prod
FIPE_API_TOKEN = os.getenv("FIPE_API_TOKEN", os.getenv("token_vehicle_api", ""))

WEBMANIA_BASE_URL = "https://api.webmania.com.br/2/"
WEBMANIA_B2B_BASE_URL = "https://webmania.com.br/api"
WEBMANIA_AMBIENT = os.getenv("WEBMANIA_AMBIENT", "2")  # 1. Prod, 2. Homolog
WEBMANIA_API_KEY = os.getenv("WEBMANIA_API_KEY", "")
WEBMANIA_CONSUMER_KEY = os.getenv("WEBMANIA_CONSUMER_KEY", "")
WEBMANIA_CONSUMER_SECRET = os.getenv("WEBMANIA_CONSUMER_SECRET", "")
WEBMANIA_ACCESS_TOKEN = os.getenv("WEBMANIA_ACCESS_TOKEN", "")
WEBMANIA_ACCESS_TOKEN_SECRET = os.getenv("WEBMANIA_ACCESS_TOKEN_SECRET", "")
WEBMANIA_B2B_CONSUMER_KEY = os.getenv("WEBMANIA_B2B_CONSUMER_KEY", "")
WEBMANIA_B2B_CONSUMER_SECRET = os.getenv("WEBMANIA_B2B_CONSUMER_SECRET", "")
WEBMANIA_B2B_ACCESS_TOKEN = os.getenv("WEBMANIA_B2B_ACCESS_TOKEN", "")
WEBMANIA_B2B_ACCESS_TOKEN_SECRET = os.getenv("WEBMANIA_B2B_ACCESS_TOKEN_SECRET", "")
WEBMANIA_WEBHOOK_TOKEN = os.getenv("WEBMANIA_WEBHOOK_TOKEN", "")

SUPERSIGN_BASE_URL = os.getenv("SUPERSIGN_BASE_URL", "https://api.sign.supersign.com.br")
SUPERSIGN_ACCOUNT_ID = os.getenv("SUPERSIGN_ACCOUNT_ID", "")
SUPERSIGN_API_KEY = os.getenv("SUPERSIGN_API_KEY", "")
SUPERSIGN_FOLDER_ID = os.getenv("SUPERSIGN_FOLDER_ID", "")

STORAGE_ACCESS_KEY_ID = os.getenv("ACCESS_KEY_ID", "")
STORAGE_SECRET_ACCESS_KEY = os.getenv("SECRET_ACCESS_KEY", "")
STORAGE_BUCKET = os.getenv("BUCKET", "")
STORAGE_ENDPOINT = os.getenv("ENDPOINT", "")
STORAGE_REGION = os.getenv("REGION", "auto")

WHATSAPP_API_URL = os.getenv("WHATSAPP_API_URL", "https://whatsapp-hunter.up.railway.app")
EVOLUTION_API_URL = os.getenv("EVOLUTION_API_URL", "")

if not DEBUG:
    SECURE_SSL_REDIRECT = os.getenv("DJANGO_SECURE_SSL_REDIRECT", "1").lower() in ("1", "true", "yes")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.getenv("DJANGO_SECURE_HSTS_SECONDS", "3600"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

# Application definition

INSTALLED_APPS = [
    # ASGI / realtime (safe when unused by Gunicorn WSGI process)
    "daphne",
    # Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    # Dependencies
    "django_tailwind_cli",
    "crispy_tailwind",
    "crispy_forms",
    "django_filters",
    "django_htmx",
    "localflavor",
    "djmoney",
    "phonenumber_field",
    "simple_history",
    "django_tables2",
    "channels",
    # Local
    "apps.core",
    "apps.accounts",
    "apps.iam",
    "apps.workshops",
    "apps.collaborators",
    "apps.catalog",
    "apps.sources",
    "apps.suppliers",
    "apps.quote",
    "apps.checklist",
    "apps.budget",
    "apps.customer",
    "apps.workorder",
    "apps.scheduling",
    "apps.stock",
    "apps.finance",
    "apps.messaging",
]

MIDDLEWARE = [
    # Local (must be first)
    "apps.core.presentation.middlewares.RequestIdMiddleware",
    # Django
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Dependencies
    "simple_history.middleware.HistoryRequestMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
    # Local
    "apps.core.presentation.middlewares.RequestPerformanceLoggingMiddleware",
    "apps.core.presentation.middlewares.RequireFirstWorkshopMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # Local
                "apps.workshops.context_processors.active_workshops",
                "apps.core.presentation.context_processors.navbar",
            ],
            "builtins": [
                "crispy_forms.templatetags.crispy_forms_tags",
                "crispy_tailwind.templatetags.tailwind_filters",
                "apps.core.templatetags.text_filters",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    }
}

CRISPY_TEMPLATE_PACK = "tailwind"
CRISPY_ALLOWED_TEMPLATE_PACKS = ("tailwind",)

WHATSAPP_API_URL = os.getenv("WHATSAPP_API_URL", "https://whatsapp-hunter.up.railway.app")
EVOLUTION_API_URL = os.getenv("EVOLUTION_API_URL", "")
MESSAGE_WORKER_BASE_URL = os.getenv("MESSAGE_WORKER_BASE_URL", "").strip()
MESSAGE_DISPATCH_STATUS_TOKEN = os.getenv("MESSAGE_DISPATCH_STATUS_TOKEN", "").strip()
MESSAGE_DISPATCH_WS_BASE_URL = os.getenv("MESSAGE_DISPATCH_WS_BASE_URL", "").strip()

# Outbound appointment-alert send window (America/Sao_Paulo via TIME_ZONE).
# End hour is exclusive: default 8–18 means 08:00 <= now < 18:00, Mon–Fri.
OUTBOUND_BUSINESS_HOURS_ENABLED = os.getenv("OUTBOUND_BUSINESS_HOURS_ENABLED", "1").lower() in ("1", "true", "yes")
OUTBOUND_BUSINESS_WEEKDAYS = os.getenv("OUTBOUND_BUSINESS_WEEKDAYS", "0,1,2,3,4").strip()
OUTBOUND_BUSINESS_START_HOUR = int(os.getenv("OUTBOUND_BUSINESS_START_HOUR", "8"))
OUTBOUND_BUSINESS_END_HOUR = int(os.getenv("OUTBOUND_BUSINESS_END_HOUR", "18"))

RABBITMQ_HOST = os.getenv("RABBITMQ_HOST", "localhost")
RABBITMQ_PORT = int(os.getenv("RABBITMQ_PORT", "5672"))
RABBITMQ_USER = os.getenv("RABBITMQ_USER", "guest")
RABBITMQ_PASSWORD = os.getenv("RABBITMQ_PASSWORD", "guest")

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Reuse DB connections within each Gunicorn worker (seconds). 0 = close after each request.
_CONN_MAX_AGE_RAW = os.getenv("CONN_MAX_AGE", "0").strip()
try:
    CONN_MAX_AGE = int(_CONN_MAX_AGE_RAW)
except ValueError:
    CONN_MAX_AGE = 0

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME", "meu_crm"),
        "USER": os.getenv("DB_USER", "usuario_crm"),
        "PASSWORD": os.getenv("DB_PASSWORD", "senha_secreta"),
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": os.getenv("DB_PORT", "5432"),
        "CONN_MAX_AGE": CONN_MAX_AGE,
        "CONN_HEALTH_CHECKS": True,
    }
}

# Cache
# https://docs.djangoproject.com/en/5.2/topics/cache/

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "default-cache",
        "TIMEOUT": 300,
    },
    "fipe": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "fipe-cache",
        "TIMEOUT": 86400,
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTH_USER_MODEL = "accounts.User"


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "pt-br"
TIME_ZONE = "America/Sao_Paulo"
USE_I18N = True
USE_TZ = True

USE_THOUSAND_SEPARATOR = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Tailwind
# TODO: Optimize for production https://github.com/django-commons/django-tailwind-cli?tab=readme-ov-file#production-settings
TAILWIND_CLI_SRC_CSS = os.path.join(BASE_DIR, "static", "css", "main.css")

TAILWIND_CLI_SRC_REPO = "dobicinaitis/tailwind-cli-extra"
TAILWIND_CLI_USE_DAISY_UI = True
TAILWIND_CLI_VERSION = "2.8.2"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Money
DEFAULT_CURRENCY = "BRL"
CURRENCIES = ("BRL",)
CURRENCY_CHOICES = [("BRL", "Real Brasileiro")]
CURRENCY_DECIMAL_PLACES = 2

# Phone Numbers
PHONENUMBER_DEFAULT_REGION = "BR"
PHONENUMBER_DEFAULT_FORMAT = "NATIONAL"

_DEFAULT_LOG_LEVEL = "INFO" if ENVIRONMENT == "production" else "DEBUG"
DJANGO_LOG_LEVEL = os.getenv("DJANGO_LOG_LEVEL", _DEFAULT_LOG_LEVEL).upper()
DJANGO_ROOT_LOG_LEVEL = os.getenv("DJANGO_ROOT_LOG_LEVEL", _DEFAULT_LOG_LEVEL).upper()

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "json": {
            "()": "apps.core.json_formatter.JsonFormatter",
        },
    },
    "filters": {
        "context": {
            "()": "apps.core.logging_filters.ContextFilter",
        },
        "otel_attrs": {
            "()": "apps.core.otel_logging.OtelAttrsFilter",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "json",
            "stream": sys.stdout,
        },
    },
    "loggers": {
        "apps.budget.views.item_views": {
            "handlers": ["console"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": False,
            "filters": ["context", "otel_attrs"],
        },
        "apps.budget.views.kit_views": {
            "handlers": ["console"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": False,
            "filters": ["context", "otel_attrs"],
        },
        "apps.catalog.views.kits": {
            "handlers": ["console"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": False,
            "filters": ["context", "otel_attrs"],
        },
        "apps.catalog.forms.kits": {
            "handlers": ["console"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": False,
            "filters": ["context", "otel_attrs"],
        },
        "apps.accounts.views": {
            "handlers": ["console"],
            "level": DJANGO_LOG_LEVEL,
            "propagate": False,
            "filters": ["context", "otel_attrs"],
        },
        "urllib3.connectionpool": {
            "handlers": ["console"],
            "level": 100,
            "propagate": False,
            "filters": ["context", "otel_attrs"],
        },
        "django.request": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
            "filters": ["context", "otel_attrs"],
        },
    },
    "root": {
        "handlers": ["console"],
        "level": DJANGO_ROOT_LOG_LEVEL,
        "filters": ["context", "otel_attrs"],
    },
}

# OpenTelemetry (logs + traces + metrics)
# Só ativa se ambas as configs estiverem presentes (endpoint + auth)
_otel_endpoint = os.getenv("OTEL_EXPORTER_OTLP_ENDPOINT", "")
_otel_run = os.getenv("RUN_MAIN") == "true" or not os.getenv("RUN_MAIN")
if OTLP_AUTH_HEADER and _otel_endpoint and _otel_run:
    from apps.core.otel_logging import setup_otel  # noqa: PLC0415

    setup_otel(
        service_name=OTEL_SERVICE_NAME,
        environment=ENVIRONMENT,
        auth_header=OTLP_AUTH_HEADER,
        service_namespace=OTEL_SERVICE_NAMESPACE,
        service_version=OTEL_SERVICE_VERSION,
        metric_export_interval_millis=OTEL_METRIC_EXPORT_INTERVAL_MS,
    )
