# Generated by Django 6.0 on 2026-01-19 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workshops", "0004_alter_workshopcost_card_rate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Checklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nome do Checklist"),
                ),
                (
                    "workshop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklists",
                        to="workshops.workshop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Checklist",
                "verbose_name_plural": "Checklists",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="ChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Agrupamento"
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=500, verbose_name="Descrição"),
                ),
                (
                    "response_type",
                    models.CharField(
                        choices=[
                            ("BOM_REGULAR_RUIM", "Bom / Regular / Ruim"),
                            ("SIM_NAO", "Sim / Não"),
                            ("TEXTO_LIVRE", "Texto Livre"),
                            ("NIVEL", "Vazio | 1/4 | 1/2 | 3/4 | Cheio"),
                        ],
                        max_length=30,
                        verbose_name="Tipo de Resposta",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "checklist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="checklist.checklist",
                    ),
                ),
            ],
            options={
                "ordering": ["group", "order"],
            },
        ),
    ]
