# Generated by Django 6.0 on 2026-01-21 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checklist", "0002_alter_checklist_atualizado_em_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="checklist",
            options={"verbose_name": "Checklist", "verbose_name_plural": "Checklists"},
        ),
        migrations.AlterModelOptions(
            name="checklistitem",
            options={},
        ),
    ]
