# Generated by Django 6.0 on 2026-02-19

from django.db import migrations, models


def fill_empty_checklist_item_groups(apps, schema_editor):
    ChecklistItem = apps.get_model("checklist", "ChecklistItem")

    for checklist_item in ChecklistItem.objects.only("id", "group").iterator():
        cleaned_group = (checklist_item.group or "").strip()
        if not cleaned_group:
            cleaned_group = "Geral"

        if cleaned_group != checklist_item.group:
            checklist_item.group = cleaned_group
            checklist_item.save(update_fields=["group"])


class Migration(migrations.Migration):
    dependencies = [
        ("checklist", "0003_alter_checklist_options_alter_checklistitem_options"),
    ]

    operations = [
        migrations.RunPython(fill_empty_checklist_item_groups, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="checklistitem",
            name="group",
            field=models.CharField(max_length=100, verbose_name="Agrupamento"),
        ),
        migrations.AddConstraint(
            model_name="checklistitem",
            constraint=models.CheckConstraint(
                condition=~models.Q(group=""),
                name="checklist_item_group_not_blank",
            ),
        ),
    ]
