# Generated by Django 6.0 on 2026-03-08 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("checklist", "0004_checklistitem_group_required"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="checklistitem",
            options={
                "verbose_name": "Item do Checklist",
                "verbose_name_plural": "Itens do Checklist",
            },
        ),
    ]
