# Generated by Django 6.0 on 2026-04-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0005_alter_checklistitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='checklist_type',
            field=models.CharField(choices=[('AUTOMOTIVE_DIAGNOSTIC', 'Checklist de Diagnóstico Automotivo'), ('INTERNAL', 'Checklists internos'), ('STRUCTURAL', 'Checklist Estruturais'), ('PROCESS', 'Checklist de processos')], default='AUTOMOTIVE_DIAGNOSTIC', max_length=40, verbose_name='Tipo de Checklist'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='pdf_content_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='checklist',
            name='pdf_file_key',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='checklist',
            name='pdf_file_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='checklist',
            name='pdf_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklist',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Crie seu Checklist'), ('PDF', 'Importe seu Checklist')], default='MANUAL', max_length=10, verbose_name='Origem do Checklist'),
        ),
    ]
