# Generated by Django 6.0 on 2026-08-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0006_checklist_checklist_type_checklist_pdf_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='checklist_type',
            field=models.CharField(choices=[('AUTOMOTIVE_DIAGNOSTIC', 'Checklist de diagnóstico automotivo'), ('INTERNAL', 'Checklists internos'), ('STRUCTURAL', 'Checklists estruturais'), ('PROCESS', 'Checklist de processos')], default='AUTOMOTIVE_DIAGNOSTIC', max_length=40, verbose_name='Tipo de Checklist'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='response_type',
            field=models.CharField(choices=[('BOM_REGULAR_RUIM', 'Bom / Regular / Ruim'), ('SIM_NAO', 'Sim / Não'), ('TEXTO_LIVRE', 'Texto livre'), ('NIVEL', 'Vazio | 1/4 | 1/2 | 3/4 | Cheio')], max_length=30, verbose_name='Tipo de Resposta'),
        ),
    ]
