# Generated by Django 6.0 on 2026-03-18 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget', '0027_budget_discount_percentage'),
        ('customer', '0012_alter_customer_bairro_alter_customer_cidade'),
        ('workorder', '0013_workorder_km_final'),
        ('workshops', '0014_alter_workshop_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('title', models.CharField(max_length=120, verbose_name='Titulo')),
                ('starts_at', models.DateTimeField(verbose_name='Data e hora de entrada')),
                ('ends_at', models.DateTimeField(verbose_name='Data e hora de saida')),
                ('block_color', models.CharField(default='#0ea5e9', max_length=7, verbose_name='Cor do bloco')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observacoes')),
                ('status', models.CharField(choices=[('scheduled', 'Agendado'), ('completed', 'Concluido'), ('cancelled', 'Cancelado')], default='scheduled', max_length=20, verbose_name='Status')),
                ('budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='budget.budget', verbose_name='Orcamento vinculado')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='customer.customer', verbose_name='Cliente')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='customer.vehicle', verbose_name='Veiculo')),
                ('workorder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='workorder.workorder', verbose_name='Ordem de servico vinculada')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='workshops.workshop')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'abstract': False,
                'indexes': [models.Index(fields=['workshop', 'starts_at'], name='scheduling__worksho_9127d2_idx'), models.Index(fields=['workshop', 'ends_at'], name='scheduling__worksho_ac3e1a_idx'), models.Index(fields=['workshop', 'status'], name='scheduling__worksho_da3cf6_idx')],
            },
        ),
    ]
