# Generated by Django 6.0 on 2026-03-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='alert_customer',
            field=models.BooleanField(default=False, verbose_name='Alertar cliente'),
        ),
    ]
