# Generated by Django 6.0 on 2026-03-24 15:56

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_alter_customer_bairro_alter_customer_cidade'),
        ('scheduling', '0002_appointment_alert_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='guest_customer_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nome do cliente'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='guest_customer_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, region=None, verbose_name='Telefone do cliente'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='customer.customer', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='customer.vehicle', verbose_name='Veiculo'),
        ),
    ]
