# Generated by Django 5.2 on 2026-04-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0003_appointment_guest_customer_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="guest_customer_cpf",
            field=models.CharField(blank=True, default="", max_length=14, verbose_name="CPF do cliente"),
        ),
        migrations.AddField(
            model_name="appointment",
            name="guest_vehicle_brand",
            field=models.CharField(blank=True, default="", max_length=500, verbose_name="Marca do veiculo"),
        ),
        migrations.AddField(
            model_name="appointment",
            name="guest_vehicle_engine",
            field=models.CharField(blank=True, default="", max_length=30, verbose_name="Motorizacao"),
        ),
        migrations.AddField(
            model_name="appointment",
            name="guest_vehicle_fuel",
            field=models.CharField(blank=True, default="", max_length=30, verbose_name="Combustivel"),
        ),
        migrations.AddField(
            model_name="appointment",
            name="guest_vehicle_model",
            field=models.CharField(blank=True, default="", max_length=500, verbose_name="Modelo do veiculo"),
        ),
        migrations.AddField(
            model_name="appointment",
            name="guest_vehicle_plate",
            field=models.CharField(blank=True, default="", max_length=20, verbose_name="Placa do veiculo"),
        ),
        migrations.AddField(
            model_name="appointment",
            name="guest_vehicle_year_fabrication",
            field=models.CharField(blank=True, default="", max_length=4, verbose_name="Ano de Fabricacao"),
        ),
        migrations.AddField(
            model_name="appointment",
            name="guest_vehicle_year_model",
            field=models.CharField(blank=True, default="", max_length=4, verbose_name="Ano do Modelo"),
        ),
    ]
