# Generated by Django 5.2.9 on 2026-04-11 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_appointment_guest_vehicle_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='guest_vehicle_fuel',
            field=models.CharField(blank=True, choices=[('Gasolina', 'Gasolina'), ('Etanol', 'Etanol'), ('Flex', 'Flex'), ('Diesel', 'Diesel'), ('Híbrido', 'Híbrido'), ('Elétrico', 'Elétrico')], default='', max_length=30, verbose_name='Combustivel'),
        ),
    ]
