# Generated by Django 6.0 on 2026-06-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_alter_appointment_guest_vehicle_engine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='guest_vehicle_engine',
            field=models.CharField(blank=True, choices=[('1.0', '1.0'), ('1.3', '1.3'), ('1.4', '1.4'), ('1.6', '1.6'), ('1.8', '1.8'), ('2.0', '2.0'), ('2.2', '2.2'), ('2.4', '2.4')], default='', max_length=30, verbose_name='Motorizacao'),
        ),
    ]
