# Generated by Django 6.0 on 2026-07-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_alter_appointment_guest_vehicle_engine'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='alert_lead_time',
            field=models.PositiveIntegerField(blank=True, choices=[(30, '30 minutos'), (60, '1 hora'), (120, '2 horas'), (180, '3 horas'), (300, '5 horas'), (1440, '1 dia'), (2880, '2 dias'), (10080, '1 semana')], help_text='Minutos antes do início do agendamento para enviar o alerta.', null=True, verbose_name='Antecedência do alerta'),
        ),
    ]
