# Generated by Django 6.0 on 2026-08-01 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0062_fix_budget_ui_verbose_names'),
        ('customer', '0023_fix_customer_ui_verbose_names'),
        ('scheduling', '0010_review_plan_and_messaging_updates'),
        ('workorder', '0038_review_plan_and_messaging_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='budget.budget', verbose_name='Orçamento vinculado'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='ends_at',
            field=models.DateTimeField(verbose_name='Data e hora de saída'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='guest_vehicle_brand',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Marca do veículo'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='guest_vehicle_engine',
            field=models.CharField(blank=True, choices=[('1.0', '1.0'), ('1.3', '1.3'), ('1.4', '1.4'), ('1.6', '1.6'), ('1.8', '1.8'), ('2.0', '2.0'), ('2.2', '2.2'), ('2.4', '2.4')], default='', max_length=30, verbose_name='Motorização'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='guest_vehicle_fuel',
            field=models.CharField(blank=True, choices=[('Gasolina', 'Gasolina'), ('Etanol', 'Etanol'), ('Flex', 'Flex'), ('Diesel', 'Diesel'), ('Híbrido', 'Híbrido'), ('Elétrico', 'Elétrico')], default='', max_length=30, verbose_name='Combustível'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='guest_vehicle_model',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Modelo do veículo'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='guest_vehicle_plate',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Placa do veículo'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='guest_vehicle_year_fabrication',
            field=models.CharField(blank=True, default='', max_length=4, verbose_name='Ano de fabricação'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='guest_vehicle_year_model',
            field=models.CharField(blank=True, default='', max_length=4, verbose_name='Ano do modelo'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Agendado'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], default='scheduled', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='customer.vehicle', verbose_name='Veículo'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='workorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='workorder.workorder', verbose_name='Ordem de serviço vinculada'),
        ),
    ]
