# Generated by Django 6.0 on 2026-07-31 20:24

import apps.scheduling.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0011_appointment_alert_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='alert_lead_times',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(choices=[(30, '30 minutos'), (60, '1 hora'), (120, '2 horas'), (180, '3 horas'), (300, '5 horas'), (1440, '1 dia'), (2880, '2 dias'), (10080, '1 semana')]), blank=True, default=apps.scheduling.models.default_alert_lead_times, help_text='Minutos antes do início do agendamento para enviar o alerta. É possível selecionar mais de uma opção.', verbose_name='Antecedência do alerta'),
        ),
    ]
