# Generated by Django 6.0 on 2026-08-01 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0011_fix_scheduling_ui_verbose_names'),
        ('scheduling', '0012_alter_appointment_alert_lead_times_default'),
    ]

    operations = [
    ]
