# Generated by Django 5.2.9 on 2026-01-14 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workshops', '0004_alter_workshopcost_card_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestigativeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=255, verbose_name='Pergunta')),
                ('response_type', models.CharField(choices=[('TEXT', 'Texto Livre'), ('CHOICE', 'Múltipla Escolha'), ('BOOL', 'Sim/Não'), ('SCALE', 'Escala (1-10)')], default='TEXT', max_length=10, verbose_name='Tipo de Resposta')),
                ('options', models.JSONField(blank=True, default=list, verbose_name='Opções')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigative_questions', to='workshops.workshop')),
            ],
            options={
                'verbose_name': 'Pergunta Investigativa',
                'verbose_name_plural': 'Perguntas Investigativas',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
