# Generated by Django 6.0 on 2026-01-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quote", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="investigativequestion",
            options={
                "verbose_name": "Pergunta Investigativa",
                "verbose_name_plural": "Perguntas Investigativas",
            },
        ),
        migrations.AlterField(
            model_name="investigativequestion",
            name="order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Ordem em que a pergunta aparecerá (0 = Primeiro)",
                verbose_name="Ordem",
            ),
        ),
    ]
