# Generated by Django 6.0 on 2026-01-23 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0006_budget_current_step"),
        ("quote", "0003_alter_investigativequestion_atualizado_em_and_more"),
        ("workshops", "0005_alter_monthlycost_atualizado_em_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestigativeResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                ("response", models.TextField(verbose_name="Resposta")),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investigative_responses",
                        to="budget.budget",
                        verbose_name="Orçamento",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investigative_responses",
                        to="quote.investigativequestion",
                        verbose_name="Pergunta Investigativa",
                    ),
                ),
                (
                    "workshop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investigative_responses",
                        to="workshops.workshop",
                        verbose_name="Oficina",
                    ),
                ),
            ],
            options={
                "unique_together": {("budget", "question")},
            },
        ),
    ]
