# Generated by Django 6.0 on 2026-03-08 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quote", "0004_investigativeresponse"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="investigativeresponse",
            options={
                "verbose_name": "Resposta da Pergunta Investigativa",
                "verbose_name_plural": "Respostas das Perguntas Investigativas",
            },
        ),
    ]
