# Generated by Django 6.0 on 2026-08-01 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0005_alter_investigativeresponse_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investigativequestion',
            options={'verbose_name': 'Pergunta investigativa', 'verbose_name_plural': 'Perguntas investigativas'},
        ),
        migrations.AlterModelOptions(
            name='investigativeresponse',
            options={'verbose_name': 'Resposta da pergunta investigativa', 'verbose_name_plural': 'Respostas das perguntas investigativas'},
        ),
        migrations.AlterField(
            model_name='investigativequestion',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Ordem em que a pergunta aparecerá (0 = primeiro)', verbose_name='Ordem'),
        ),
        migrations.AlterField(
            model_name='investigativequestion',
            name='response_type',
            field=models.CharField(choices=[('TEXT', 'Texto livre'), ('CHOICE', 'Múltipla escolha'), ('BOOL', 'Sim/Não'), ('SCALE', 'Escala (1-10)')], default='TEXT', max_length=10, verbose_name='Tipo de resposta'),
        ),
        migrations.AlterField(
            model_name='investigativeresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigative_responses', to='quote.investigativequestion', verbose_name='Pergunta investigativa'),
        ),
    ]
