# Generated by Django 6.0 on 2026-01-20 20:51

import django.db.models.deletion
import localflavor.br.models
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workshops", "0004_alter_workshopcost_card_rate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Nome")),
                (
                    "cpf",
                    localflavor.br.models.BRCPFField(max_length=14, verbose_name="CPF"),
                ),
                (
                    "rg",
                    models.CharField(
                        blank=True, max_length=9, null=True, verbose_name="RG"
                    ),
                ),
                ("birth_date", models.DateField(verbose_name="Data de Nascimento")),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Masculino"), ("F", "Feminino"), ("O", "Outro")],
                        max_length=1,
                        null=True,
                        verbose_name="Sexo",
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region=None, verbose_name="Telefone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "workshop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customers",
                        to="workshops.workshop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workshop", "cpf"),
                        name="unique_customer_cpf_per_workshop",
                    )
                ],
            },
        ),
    ]
