# Generated by Django 6.0 on 2026-01-20 23:12

import localflavor.br.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="bairro",
            field=models.CharField(default="", max_length=20, verbose_name="Bairro"),
        ),
        migrations.AddField(
            model_name="customer",
            name="cep",
            field=localflavor.br.models.BRPostalCodeField(
                default="", max_length=9, verbose_name="CEP"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="cidade",
            field=models.CharField(default="", max_length=20, verbose_name="Cidade"),
        ),
        migrations.AddField(
            model_name="customer",
            name="complemento",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Complemento"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="estado",
            field=localflavor.br.models.BRStateField(
                default="", max_length=2, verbose_name="Estado"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="logradouro",
            field=models.CharField(
                default="", max_length=225, verbose_name="Logradouro"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="numero",
            field=models.PositiveIntegerField(default=1, verbose_name="Número"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="atualizado_em",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Data de Atualização"
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="criado_em",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Data de Criação"
            ),
        ),
    ]
