# Generated by Django 6.0 on 2026-01-21 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_customer_bairro_customer_cep_customer_cidade_and_more"),
        ("workshops", "0005_alter_monthlycost_atualizado_em_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                ("plate", models.CharField(max_length=20, verbose_name="Placa")),
                ("brand", models.CharField(max_length=500, verbose_name="Marca")),
                ("model", models.CharField(max_length=500, verbose_name="Modelo")),
                (
                    "year_fabrication",
                    models.CharField(max_length=4, verbose_name="Ano de Fabricação"),
                ),
                (
                    "year_model",
                    models.CharField(max_length=4, verbose_name="Ano do Modelo"),
                ),
                ("color", models.CharField(max_length=30, verbose_name="Cor")),
                (
                    "fuel",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Combustível"
                    ),
                ),
                (
                    "km",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Quilometragem"
                    ),
                ),
                (
                    "engine",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Motor"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Tipo"
                    ),
                ),
                (
                    "renavam",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="Renavam"
                    ),
                ),
                (
                    "chassi",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="Chassi"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="customer.customer",
                    ),
                ),
                (
                    "workshop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="workshops.workshop",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
