# Generated by Django 5.2.9 on 2026-01-29 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_vehicle'),
        ('workshops', '0005_alter_monthlycost_atualizado_em_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customer',
            name='unique_customer_cpf_per_workshop',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cpf',
        ),
        migrations.AddField(
            model_name='customer',
            name='cpf_or_cnpj',
            field=models.CharField(max_length=18, null=True, verbose_name='CPF/CNPJ'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], default='PF', max_length=2),
        ),
        migrations.AddField(
            model_name='customer',
            name='fantasy_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fantasia'),
        ),
        migrations.AddField(
            model_name='customer',
            name='foundation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Fundacao'),
        ),
        migrations.AddField(
            model_name='customer',
            name='municipal_registration',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Inscricao Municipal'),
        ),
        migrations.AddField(
            model_name='customer',
            name='state_registration',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Inscricao Estadual'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('workshop', 'cpf_or_cnpj'), name='unique_customer_document_per_workshop'),
        ),
    ]
