# Generated by Django 5.2.9 on 2026-01-29 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_customer_unique_customer_cpf_per_workshop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cpf_or_cnpj',
            field=models.CharField(max_length=18, verbose_name='CPF/CNPJ'),
        ),
    ]
