# Generated by Django 5.2.9 on 2026-01-29 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_customer_cpf_or_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state_registration',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Inscrição Estadual'),
        ),
    ]
