# Generated by Django 5.2.9 on 2026-01-29 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_customer_state_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='foundation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Fundação'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='municipal_registration',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Inscrição Municipal'),
        ),
    ]
