# Generated by Django 5.2.9 on 2026-02-13

from django.db import migrations, models


def fill_missing_customer_emails(apps, schema_editor):
    Customer = apps.get_model("customer", "Customer")

    missing_email_qs = Customer.objects.filter(models.Q(email__isnull=True) | models.Q(email=""))
    for customer in missing_email_qs.iterator():
        customer.email = f"cliente-{customer.pk}@invalid.local"
        customer.save(update_fields=["email"])


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0007_alter_customer_foundation_date_and_more"),
    ]

    operations = [
        migrations.RunPython(fill_missing_customer_emails, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(verbose_name="Email"),
        ),
    ]
