# Generated by Django 5.2.9 on 2026-02-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_customer_email_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='km',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quilometragem'),
        ),
    ]
