# Generated by Django 5.2.9 on 2026-02-21

from django.db import migrations, models


def _normalize_plate(value: str | None) -> str:
    return (value or "").strip().upper()


def deduplicate_vehicle_plates(apps, schema_editor):
    Vehicle = apps.get_model("customer", "Vehicle")
    Customer = apps.get_model("customer", "Customer")
    Budget = apps.get_model("budget", "Budget")

    impacted_customer_ids = set()

    for vehicle in Vehicle.objects.all().only("id", "plate"):
        normalized_plate = _normalize_plate(vehicle.plate)
        if vehicle.plate != normalized_plate:
            Vehicle.objects.filter(pk=vehicle.pk).update(plate=normalized_plate)

    duplicate_groups = Vehicle.objects.values("workshop_id", "plate").annotate(total=models.Count("id")).filter(total__gt=1)

    for duplicate_group in duplicate_groups:
        grouped_vehicles = list(Vehicle.objects.filter(workshop_id=duplicate_group["workshop_id"], plate=duplicate_group["plate"]).order_by("id").values("id", "customer_id"))

        keeper_vehicle = grouped_vehicles[0]
        duplicate_vehicles = grouped_vehicles[1:]

        duplicate_vehicle_ids = [vehicle["id"] for vehicle in duplicate_vehicles]
        impacted_customer_ids.update(vehicle["customer_id"] for vehicle in duplicate_vehicles if vehicle["customer_id"])

        if duplicate_vehicle_ids:
            Budget.objects.filter(vehicle_id__in=duplicate_vehicle_ids).update(vehicle_id=keeper_vehicle["id"], customer_id=keeper_vehicle["customer_id"])
            Vehicle.objects.filter(id__in=duplicate_vehicle_ids).delete()

    for customer_id in impacted_customer_ids:
        if not Vehicle.objects.filter(customer_id=customer_id).exists():
            Customer.objects.filter(pk=customer_id).delete()


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("budget", "0025_alter_budget_fuel_level"),
        ("customer", "0009_alter_vehicle_km"),
    ]

    operations = [
        migrations.RunPython(deduplicate_vehicle_plates, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="vehicle",
            constraint=models.UniqueConstraint(fields=("workshop", "plate"), name="unique_vehicle_plate_per_workshop"),
        ),
    ]
