# Generated by Django 6.0 on 2026-03-08 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0010_deduplicate_vehicle_plate_and_add_unique_constraint"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vehicle",
            options={"verbose_name": "Veículo", "verbose_name_plural": "Veículos"},
        ),
    ]
