# Generated by Django 5.2.9 on 2026-04-11 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_alter_customer_bairro_alter_customer_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='fuel',
            field=models.CharField(blank=True, choices=[('Gasolina', 'Gasolina'), ('Etanol', 'Etanol'), ('Flex', 'Flex'), ('Diesel', 'Diesel'), ('Híbrido', 'Híbrido'), ('Elétrico', 'Elétrico')], max_length=30, null=True, verbose_name='Combustível'),
        ),
    ]
