# Generated by Django 5.2.9 on 2026-04-11 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_alter_vehicle_fuel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='engine',
            field=models.CharField(blank=True, choices=[('2.0', '2.0'), ('2.2', '2.2'), ('2.4', '2.4'), ('1.3', '1.3'), ('1.8', '1.8')], max_length=30, null=True, verbose_name='Motor'),
        ),
    ]
