# Generated by Django 6.0 on 2026-05-11 03:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0029_copy_fipe_data_from_customer"),
        ("customer", "0015_fipesyncstate_alter_vehicle_engine_fipevehiclebrand_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="fipemodelfuelcache",
            name="unique_fipe_fuel_cache_per_model",
        ),
        migrations.DeleteModel(
            name="FipeSyncState",
        ),
        migrations.RemoveConstraint(
            model_name="fipevehiclebrand",
            name="unique_fipe_brand_per_type",
        ),
        migrations.RemoveConstraint(
            model_name="fipevehiclemodel",
            name="unique_fipe_model_per_brand",
        ),
        migrations.RemoveField(
            model_name="fipevehiclemodel",
            name="brand",
        ),
        migrations.DeleteModel(
            name="FipeModelFuelCache",
        ),
        migrations.DeleteModel(
            name="FipeVehicleBrand",
        ),
        migrations.DeleteModel(
            name="FipeVehicleModel",
        ),
    ]
