# Generated by Django 6.0 on 2026-06-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_remove_fipemodelfuelcache_unique_fipe_fuel_cache_per_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='engine',
            field=models.CharField(blank=True, choices=[('1.0', '1.0'), ('1.3', '1.3'), ('1.4', '1.4'), ('1.6', '1.6'), ('1.8', '1.8'), ('2.0', '2.0'), ('2.2', '2.2'), ('2.4', '2.4')], max_length=30, null=True, verbose_name='Motor'),
        ),
    ]
