# Generated by Django 6.0 on 2026-07-23 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0060_oil_change_tracking'),
        ('customer', '0017_alter_vehicle_engine'),
        ('workorder', '0037_wave2_stored_totals'),
        ('workshops', '0028_oil_change_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='last_oil_change_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data da última troca de óleo'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_oil_change_km',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='KM da última troca de óleo'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='next_oil_change_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data prevista da próxima troca de óleo'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='oil_forecast_reason',
            field=models.CharField(blank=True, choices=[('VALIDADE_POR_DIAS', 'Validade por dias'), ('VALIDADE_POR_QUILOMETRAGEM', 'Validade por quilometragem')], max_length=40, null=True, verbose_name='Motivo da previsão de troca de óleo'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='oil_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='workshops.oiltype', verbose_name='Tipo de óleo'),
        ),
        migrations.CreateModel(
            name='VehicleMileageReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('read_at', models.DateField(verbose_name='Data da leitura')),
                ('odometer_km', models.PositiveIntegerField(verbose_name='Quilometragem')),
                ('source', models.CharField(choices=[('budget', 'Orçamento'), ('workorder_delivery', 'Entrega da O.S.'), ('manual', 'Manual')], max_length=32, verbose_name='Origem da leitura')),
                ('budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mileage_readings', to='budget.budget', verbose_name='Orçamento')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mileage_readings', to='customer.vehicle', verbose_name='Veículo')),
                ('workorder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mileage_readings', to='workorder.workorder', verbose_name='Ordem de serviço')),
            ],
            options={
                'verbose_name': 'Leitura de quilometragem',
                'verbose_name_plural': 'Leituras de quilometragem',
                'indexes': [models.Index(fields=['vehicle', 'read_at', 'odometer_km'], name='customer_ve_vehicle_1bb9e0_idx')],
            },
        ),
        migrations.CreateModel(
            name='VehicleOilChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('changed_at', models.DateField(verbose_name='Data da troca')),
                ('odometer_km', models.PositiveIntegerField(verbose_name='Quilometragem da troca')),
                ('validity_days', models.PositiveIntegerField(verbose_name='Validade do óleo (dias)')),
                ('validity_km', models.PositiveIntegerField(verbose_name='Validade do óleo (km)')),
                ('budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oil_changes', to='budget.budget', verbose_name='Orçamento')),
                ('oil_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oil_changes', to='workshops.oiltype', verbose_name='Tipo de óleo')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oil_changes', to='customer.vehicle', verbose_name='Veículo')),
                ('workorder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oil_changes', to='workorder.workorder', verbose_name='Ordem de serviço')),
            ],
            options={
                'verbose_name': 'Troca de óleo',
                'verbose_name_plural': 'Trocas de óleo',
                'indexes': [models.Index(fields=['vehicle', '-changed_at'], name='customer_ve_vehicle_ab0294_idx'), models.Index(fields=['workorder'], name='customer_ve_workord_935e40_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('workorder__isnull', False)), fields=('workorder',), name='unique_oil_change_per_workorder')],
            },
        ),
    ]
