# Generated by Django 6.0 on 2026-07-28 03:15

from __future__ import annotations

from django.conf import settings
from django.db import migrations, models


def _is_production_environment() -> bool:
    env = str(getattr(settings, "ENVIRONMENT", "") or "").strip().strip("\"'").casefold()
    return env in {"production", "prod"}


def forwards_backfill_accepts_messages(apps, schema_editor) -> None:
    """Em prod/production: liga para todos. Fora de prod: mantém/desliga."""
    Customer = apps.get_model("customer", "Customer")
    Customer.objects.all().update(accepts_messages=_is_production_environment())


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0018_oil_change_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="accepts_messages",
            field=models.BooleanField(default=False, verbose_name="Receber mensagens"),
        ),
        migrations.RunPython(forwards_backfill_accepts_messages, migrations.RunPython.noop),
    ]
