# Generated by Django 6.0 on 2026-07-28 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_oil_change_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='accepts_messages',
            field=models.BooleanField(default=False, verbose_name='Receber mensagens'),
        ),
    ]
