# Generated by Django 6.0 on 2026-07-29 22:17

import apps.customer.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0021_realign_accepts_messages_by_environment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="accepts_messages",
            field=models.BooleanField(default=apps.customer.models.default_customer_accepts_messages, verbose_name="Receber mensagens"),
        ),
    ]
