# Generated by Django 6.0 on 2026-08-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0022_alter_accepts_messages_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='fantasy_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome fantasia'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='foundation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de fundação'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year_fabrication',
            field=models.CharField(max_length=4, verbose_name='Ano de fabricação'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year_model',
            field=models.CharField(max_length=4, verbose_name='Ano do modelo'),
        ),
    ]
