# Generated by Django 5.2.9 on 2026-01-13 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("workshops", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CatalogGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Nome do Grupo")),
                ("workshop", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="catalog_groups", to="workshops.workshop")),
            ],
            options={
                "verbose_name": "Grupo",
                "verbose_name_plural": "Grupos",
                "constraints": [models.UniqueConstraint(fields=("workshop", "name"), name="unique_group_name_per_workshop")],
            },
        ),
    ]
