# Generated by Django 5.2.9 on 2026-01-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cataloggroup',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
    ]
