# Generated by Django 5.2.9 on 2026-01-14 22:32

import django.db.models.deletion
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_cataloggroup_name'),
        ('workshops', '0004_alter_workshopcost_card_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Serviço')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('duration', models.DurationField(verbose_name='Duração')),
                ('suggested_cost_currency', djmoney.models.fields.CurrencyField(choices=[('BRL', 'Real Brasileiro')], default='BRL', editable=False, max_length=3, null=True)),
                ('suggested_cost', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Custo Sugerido')),
                ('selling_price_currency', djmoney.models.fields.CurrencyField(choices=[('BRL', 'Real Brasileiro')], default='BRL', editable=False, max_length=3)),
                ('selling_price', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14, verbose_name='Valor de Venda')),
                ('is_third_party', models.BooleanField(default=False, verbose_name='Serviço de Terceiro')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='workshops.workshop')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'constraints': [models.UniqueConstraint(fields=('workshop', 'name'), name='unique_service_name_per_workshop')],
            },
        ),
    ]
