# Generated by Django 5.2.9 on 2026-01-15 01:46

import apps.catalog.models.products
import django.db.models.deletion
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_service'),
        ('workshops', '0004_alter_workshopcost_card_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, verbose_name='Código da Peça')),
                ('name', models.CharField(max_length=255, verbose_name='Peça')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('unit', models.CharField(choices=[('UND', 'Unidade'), ('PC', 'Peça'), ('JG', 'Jogo'), ('GR', 'Grama'), ('LT', 'Litro'), ('KG', 'Quilo')], max_length=5, verbose_name='Unidade')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('sku', models.CharField(blank=True, max_length=50, verbose_name='SKU')),
                ('barcode', models.CharField(blank=True, help_text='EAN-13 ou EAN-8', max_length=14, validators=[apps.catalog.models.products.validate_ean], verbose_name='Código de Barras')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Localização')),
                ('cost_price_currency', djmoney.models.fields.CurrencyField(choices=[('BRL', 'Real Brasileiro')], default='BRL', editable=False, max_length=3)),
                ('cost_price', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14, verbose_name='Valor de Custo')),
                ('selling_price_currency', djmoney.models.fields.CurrencyField(choices=[('BRL', 'Real Brasileiro')], default='BRL', editable=False, max_length=3)),
                ('selling_price', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=14, verbose_name='Valor de Venda')),
                ('profit_margin', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Margem de Lucro (%)')),
                ('ncm', models.CharField(blank=True, max_length=10, validators=[apps.catalog.models.products.validate_ncm], verbose_name='NCM')),
                ('cest', models.CharField(blank=True, max_length=10, verbose_name='CEST')),
                ('origin_cst', models.IntegerField(choices=[(0, '0 - Nacional'), (1, '1 - Estrangeira (Importação direta)'), (2, '2 - Estrangeira (Adq. mercado interno)'), (3, '3 - Nacional (Conteúdo Importação > 40%)'), (4, '4 - Nacional (Produção conforme PPB)'), (5, '5 - Nacional (Conteúdo Importação <= 40%)'), (6, '6 - Estrangeira (Importação direta, sem similar)'), (7, '7 - Estrangeira (Adq. interno, sem similar)')], default=0, verbose_name='Origem CST A')),
                ('purpose', models.CharField(choices=[('REVENDA', 'Revenda / Aplicação'), ('CONSUMO', 'Consumo Interno / Uso e Consumo'), ('ATIVO', 'Ativo Imobilizado')], default='REVENDA', max_length=20, verbose_name='Finalidade')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Imagem')),
                ('application', models.TextField(blank=True, help_text='Veículos compatíveis', verbose_name='Aplicação')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('equivalent_parts', models.ManyToManyField(blank=True, to='catalog.product', verbose_name='Peças Equivalentes')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.cataloggroup', verbose_name='Grupo')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='workshops.workshop')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'constraints': [models.UniqueConstraint(fields=('workshop', 'code'), name='unique_product_code_per_workshop')],
            },
        ),
    ]
