# Generated by Django 5.2.9 on 2026-01-15 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='profit_margin',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=7, verbose_name='Margem de Lucro'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('UND', 'UND'), ('PC', 'PC'), ('JG', 'JG'), ('GR', 'GR'), ('LT', 'LT'), ('KG', 'KG')], max_length=5, verbose_name='Unidade'),
        ),
    ]
