# Generated by Django 6.0 on 2026-01-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_product_code_alter_product_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='application',
            field=models.TextField(blank=True, verbose_name='Aplicação'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.TextField(blank=True, null=True, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='product',
            name='origin_cst',
            field=models.IntegerField(choices=[(0, '0 - Nacional'), (1, '1 - Estrangeira (Importação direta)'), (2, '2 - Estrangeira (Adq. mercado interno)'), (3, '3 - Nacional (Conteúdo Importação > 40%)'), (4, '4 - Nacional (Produção conforme PPB)'), (5, '5 - Nacional (Conteúdo Importação <= 40%)'), (6, '6 - Estrangeira (Importação direta, sem similar)'), (7, '7 - Estrangeira (Adq. interno, sem similar)'), (8, '8 - Nacional (Conteúdo Importação > 70%)')], default=0, verbose_name='Origem CST A'),
        ),
    ]
