# Generated by Django 6.0 on 2026-01-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_kit_item_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kit",
            name="atualizado_em",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Data de Atualização"
            ),
        ),
        migrations.AlterField(
            model_name="kit",
            name="criado_em",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Data de Criação"
            ),
        ),
        migrations.AlterField(
            model_name="kitproduct",
            name="atualizado_em",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Data de Atualização"
            ),
        ),
        migrations.AlterField(
            model_name="kitproduct",
            name="criado_em",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Data de Criação"
            ),
        ),
        migrations.AlterField(
            model_name="kitservice",
            name="atualizado_em",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Data de Atualização"
            ),
        ),
        migrations.AlterField(
            model_name="kitservice",
            name="criado_em",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Data de Criação"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="atualizado_em",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Data de Atualização"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="criado_em",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Data de Criação"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="atualizado_em",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Data de Atualização"
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="criado_em",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Data de Criação"
            ),
        ),
    ]
