# Generated by Django 6.0 on 2026-02-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_kitservice_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='total_duration',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Duração Total'),
        ),
        migrations.AddField(
            model_name='kit',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True, verbose_name='Valor Total'),
        ),
    ]
