# Generated by Django 6.0 on 2026-02-21 17:52

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0013_kit_total_duration_kit_total_price"),
    ]
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'ALTER TABLE "catalog_kit" '
                        'ALTER COLUMN "total_duration" TYPE interval '
                        "USING NULL::interval;"
                    ),
                    reverse_sql=(
                        'ALTER TABLE "catalog_kit" '
                        'ALTER COLUMN "total_duration" TYPE timestamptz '
                        "USING NULL::timestamptz;"
                    ),
                )
            ],
            state_operations=[
                migrations.AlterField(
                    model_name="kit",
                    name="total_duration",
                    field=models.DurationField(blank=True, null=True, verbose_name="Duração Total"),
                ),
            ],
        ),
    ]
