# Generated by Django 6.0 on 2026-02-21 20:13

import djmoney.models.fields
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_kit_total_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='total_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('BRL', 'Real Brasileiro')], default='BRL', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='kit',
            name='total_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), max_digits=14, verbose_name='Preço Total'),
        ),
    ]
