# Generated by Django 6.0 on 2026-04-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_kit_total_price_currency_alter_kit_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='profit_margin',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7, verbose_name='Margem de Lucro'),
        ),
    ]
