# Generated by Django 5.2.9 on 2026-04-07 16:57

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_product_last_used_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='last_used_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('BRL', 'Real Brasileiro')], default='BRL', editable=False, max_length=3, null=True),
        ),
    ]
