# Generated by Django 5.2.9 on 2026-04-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_kitapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('UND', 'UND'), ('PC', 'PC'), ('JG', 'JG'), ('GR', 'GR'), ('LT', 'LT'), ('KG', 'KG'), ('BIS', 'BIS'), ('CX', 'CX'), ('KIT', 'KIT'), ('TB', 'TB')], max_length=5, verbose_name='Unidade'),
        ),
    ]
