# Generated by Django 5.2.9 on 2026-04-11 16:07

from __future__ import annotations

from decimal import Decimal, InvalidOperation

import djmoney.models.fields
from django.db import migrations


def _parse_decimal(value: object) -> Decimal | None:
    if value in (None, ""):
        return None

    raw_value = str(value).strip()
    if not raw_value:
        return None

    normalized_value = raw_value.replace(".", "").replace(",", ".") if "," in raw_value else raw_value
    try:
        return Decimal(normalized_value)
    except (InvalidOperation, ValueError):
        return None


def backfill_last_purchase_price(apps, schema_editor) -> None:
    Product = apps.get_model("catalog", "Product")
    StockImport = apps.get_model("stock", "StockImport")

    latest_values: dict[int, Decimal] = {}

    completed_imports = StockImport.objects.filter(status="CONCLUIDO").order_by("-criado_em", "-id").values_list("items_data", flat=True)
    for items_data in completed_imports:
        if not isinstance(items_data, list):
            continue

        for item in items_data:
            if not isinstance(item, dict):
                continue

            try:
                product_id = int(item.get("linked_product_id") or 0)
            except (TypeError, ValueError):
                continue

            if not product_id or product_id in latest_values:
                continue

            parsed_value = _parse_decimal(item.get("valor"))
            if parsed_value is None:
                continue

            latest_values[product_id] = parsed_value

    for product_id, last_purchase_price in latest_values.items():
        Product.objects.filter(pk=product_id).update(
            last_purchase_price=last_purchase_price,
            last_purchase_price_currency="BRL",
        )


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0020_alter_product_unit"),
        ("stock", "0011_stocktransfer_operation_type_stocktransfer_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="last_purchase_price",
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name="Ultimo Valor de Compra"),
        ),
        migrations.AddField(
            model_name="product",
            name="last_purchase_price_currency",
            field=djmoney.models.fields.CurrencyField(choices=[("BRL", "Real Brasileiro")], default="BRL", editable=False, max_length=3, null=True),
        ),
        migrations.RunPython(backfill_last_purchase_price, migrations.RunPython.noop),
    ]
