# Generated by Django 5.2.9 on 2026-04-12 01:08

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_product_last_purchase_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitservice',
            name='selling_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor de Venda'),
        ),
        migrations.AddField(
            model_name='kitservice',
            name='selling_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('BRL', 'Real Brasileiro')], default='BRL', editable=False, max_length=3, null=True),
        ),
    ]
