# Generated by Django 5.2.9 on 2026-04-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0022_kitservice_selling_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="kit",
            name="service_pricing_mode",
            field=models.CharField(
                choices=[
                    ("by_duration", "Valor de venda por duração"),
                    ("inserted_value", "Valor de venda inserido"),
                ],
                default="by_duration",
                max_length=20,
                verbose_name="Modo de precificação de serviços",
            ),
        ),
    ]
