# Generated by Django 6.0 on 2026-04-21 01:30

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_kit_service_pricing_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitservice',
            name='cost_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Custo'),
        ),
        migrations.AddField(
            model_name='kitservice',
            name='cost_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('BRL', 'Real Brasileiro')], default='BRL', editable=False, max_length=3, null=True),
        ),
    ]
