# Generated by Django 6.0 on 2026-04-21 02:27

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_kitservice_cost_price_kitservice_cost_price_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitservice',
            name='duration_selling_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor de Venda por Duração'),
        ),
        migrations.AddField(
            model_name='kitservice',
            name='duration_selling_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('BRL', 'Real Brasileiro')], default='BRL', editable=False, max_length=3, null=True),
        ),
    ]
