# Generated by Django 6.0 on 2026-04-23 22:33

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0025_kitservice_duration_selling_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="suggested_cost",
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name="Custo do tempo do serviço"),
        ),
    ]
