# Generated by Django 5.2.9 on 2026-05-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_alter_service_suggested_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit',
            name='service_pricing_mode',
            field=models.CharField(choices=[('by_duration', 'Valor de venda por tempo'), ('inserted_value', 'Valor de venda inserido')], default='by_duration', max_length=20, verbose_name='Escolha qual método esse kit será cobrado'),
        ),
    ]
