# Generated by Django 6.0 on 2026-05-11 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_alter_kit_service_pricing_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='FipeSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('scope', models.CharField(max_length=100, unique=True, verbose_name='Escopo')),
                ('access_count', models.PositiveIntegerField(default=0, verbose_name='Contador de acessos')),
                ('last_full_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Última sincronização completa')),
                ('last_sync_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Último início de sincronização')),
                ('sync_in_progress', models.BooleanField(default=False, verbose_name='Sincronização em andamento')),
                ('last_sync_error', models.TextField(blank=True, default='', verbose_name='Último erro de sincronização')),
            ],
            options={
                'verbose_name': 'Estado de sincronização FIPE',
                'verbose_name_plural': 'Estados de sincronização FIPE',
            },
        ),
        migrations.CreateModel(
            name='FipeVehicleBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('vehicle_type', models.CharField(choices=[('carros', 'Carros'), ('motos', 'Motos'), ('caminhoes', 'Caminhões')], default='carros', max_length=20, verbose_name='Tipo de veículo')),
                ('external_id', models.CharField(max_length=50, verbose_name='ID externo')),
                ('name', models.CharField(max_length=255, verbose_name='Marca')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Marca FIPE',
                'verbose_name_plural': 'Marcas FIPE',
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(fields=('vehicle_type', 'external_id'), name='unique_catalog_fipe_brand_per_type')],
            },
        ),
        migrations.CreateModel(
            name='FipeVehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('vehicle_type', models.CharField(choices=[('carros', 'Carros'), ('motos', 'Motos'), ('caminhoes', 'Caminhões')], default='carros', max_length=20, verbose_name='Tipo de veículo')),
                ('external_id', models.CharField(max_length=50, verbose_name='ID externo')),
                ('name', models.CharField(max_length=255, verbose_name='Modelo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='catalog.fipevehiclebrand')),
            ],
            options={
                'verbose_name': 'Modelo FIPE',
                'verbose_name_plural': 'Modelos FIPE',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='FipeModelFuelCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('vehicle_type', models.CharField(choices=[('carros', 'Carros'), ('motos', 'Motos'), ('caminhoes', 'Caminhões')], default='carros', max_length=20, verbose_name='Tipo de veículo')),
                ('fuel_values', models.JSONField(blank=True, default=list, verbose_name='Combustíveis')),
                ('source_year_count', models.PositiveIntegerField(default=0, verbose_name='Quantidade de anos na origem')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Última sincronização')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_caches', to='catalog.fipevehiclemodel')),
            ],
            options={
                'verbose_name': 'Cache de combustível FIPE',
                'verbose_name_plural': 'Caches de combustível FIPE',
            },
        ),
        migrations.AddConstraint(
            model_name='fipevehiclemodel',
            constraint=models.UniqueConstraint(fields=('vehicle_type', 'brand', 'external_id'), name='unique_catalog_fipe_model_per_brand'),
        ),
        migrations.AddConstraint(
            model_name='fipemodelfuelcache',
            constraint=models.UniqueConstraint(fields=('vehicle_type', 'model'), name='unique_catalog_fipe_fuel_cache_per_model'),
        ),
    ]
