# Generated by Django 6.0 on 2026-06-22 20:45

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0030_service_last_used_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="last_used_price_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("BRL", "Real Brasileiro")],
                default="BRL",
                editable=False,
                max_length=3,
                null=True,
            ),
        ),
    ]
