# Generated by Django 6.0 on 2026-08-01 21:39

import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_service_shipping_service_shipping_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit',
            name='service_pricing_mode',
            field=models.CharField(choices=[('by_duration', 'Valor de venda por tempo'), ('inserted_value', 'Valor de venda inserido')], default='by_duration', max_length=20, verbose_name='Escolha como este kit será cobrado'),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_purchase_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Último Valor de Compra'),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_used_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Último Valor Utilizado'),
        ),
        migrations.AlterField(
            model_name='service',
            name='last_used_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Último Valor Utilizado'),
        ),
    ]
