# Generated by Django 6.0 on 2026-01-22 19:44

import django.core.validators
import django.db.models.deletion
import djmoney.models.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("collaborators", "0003_commission_percentage_fraction"),
        ("customer", "0003_vehicle"),
        ("workshops", "0005_alter_monthlycost_atualizado_em_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                ("expiration_date", models.DateField(verbose_name="Data de Validade")),
                (
                    "problem_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Descrição do Problema"
                    ),
                ),
                (
                    "technical_diagnosis",
                    models.TextField(
                        blank=True, null=True, verbose_name="Diagnóstico Técnico"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "current_km",
                    models.PositiveIntegerField(default=0, verbose_name="KM Atual"),
                ),
                (
                    "base_value_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("BRL", "Real Brasileiro")],
                        default="BRL",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "base_value",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default=Decimal("0.0"),
                        max_digits=14,
                        verbose_name="Valor Subtotal",
                    ),
                ),
                (
                    "discount_value_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("BRL", "Real Brasileiro")],
                        default="BRL",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "discount_value",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default=Decimal("0.0"),
                        max_digits=14,
                        verbose_name="Valor de Desconto",
                    ),
                ),
                (
                    "total_value_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("BRL", "Real Brasileiro")],
                        default="BRL",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "total_value",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default=Decimal("0.0"),
                        max_digits=14,
                        verbose_name="Valor Total",
                    ),
                ),
                (
                    "profit_margin_parts",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="Percentual Lucro de Peças",
                    ),
                ),
                (
                    "profit_margin_labor",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="Percentual Lucro de Mão de Obra",
                    ),
                ),
                (
                    "slider",
                    models.SmallIntegerField(
                        default=0,
                        help_text="Negativo: Peça | Positivo: Mão de Obra",
                        validators=[
                            django.core.validators.MinValueValidator(-100),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Slider",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Em Aberto"),
                            ("approved", "Aprovado"),
                            ("rejected", "Rejeitado"),
                            ("cancelled", "Cancelado"),
                            ("finished", "Concluído"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status do Orçamento",
                    ),
                ),
                (
                    "cancellation_reason",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Motivo do Cancelamento",
                    ),
                ),
                (
                    "collaborator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="budgets",
                        to="collaborators.workshopcollaborator",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="budgets",
                        to="customer.customer",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="budgets",
                        to="customer.vehicle",
                    ),
                ),
                (
                    "workshop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to="workshops.workshop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orçamento",
                "verbose_name_plural": "Orçamentos",
            },
        ),
    ]
