# Generated by Django 6.0 on 2026-01-22 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0001_initial"),
        ("collaborators", "0003_commission_percentage_fraction"),
        ("customer", "0003_vehicle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="collaborator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="budgets",
                to="collaborators.workshopcollaborator",
                verbose_name="Colaborador",
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="budgets",
                to="customer.customer",
                verbose_name="Cliente",
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Em Aberto"),
                    ("approved", "Aprovado"),
                    ("rejected", "Rejeitado"),
                    ("cancelled", "Cancelado"),
                    ("finished", "Concluído"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="vehicle",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="budgets",
                to="customer.vehicle",
                verbose_name="Veículo",
            ),
        ),
    ]
