# Generated by Django 6.0 on 2026-01-22 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0002_alter_budget_collaborator_alter_budget_customer_and_more"),
        ("workshops", "0005_alter_monthlycost_atualizado_em_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="fuel_level",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Nível do Tanque"
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="workshop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budgets",
                to="workshops.workshop",
                verbose_name="Oficina",
            ),
        ),
    ]
