# Generated by Django 6.0 on 2026-01-23 00:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0003_budget_fuel_level_alter_budget_workshop"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="entry_date",
            field=models.DateField(
                default=datetime.datetime(2026, 1, 1, 0, 0),
                verbose_name="Data de Entrada",
            ),
            preserve_default=False,
        ),
    ]
