# Generated by Django 6.0 on 2026-01-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0004_budget_entry_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="expiration_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Validade"
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="notes",
            field=models.TextField(
                blank=True, null=True, verbose_name="Observações Complementares"
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="problem_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Relato principal do cliente"
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="technical_diagnosis",
            field=models.TextField(
                blank=True, null=True, verbose_name="Observações Técnicas"
            ),
        ),
    ]
