# Generated by Django 6.0 on 2026-01-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0005_alter_budget_expiration_date_alter_budget_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="current_step",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Etapa Atual"
            ),
        ),
    ]
