# Generated by Django 6.0 on 2026-01-24 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0006_budget_current_step"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="cost_estimator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="budgets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Orçamentista",
            ),
        ),
    ]
