# Generated by Django 6.0 on 2026-01-26 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0007_budget_cost_estimator"),
        ("workshops", "0005_alter_monthlycost_atualizado_em_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                ("content", models.BinaryField(blank=True, null=True)),
                (
                    "content_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "content_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_image",
                        to="budget.budget",
                    ),
                ),
                (
                    "workshop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_image",
                        to="workshops.workshop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagem do Orçamento",
                "verbose_name_plural": "Imagens do Orçamento",
            },
        ),
        migrations.CreateModel(
            name="Defect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="defects",
                        to="budget.budget",
                    ),
                ),
                (
                    "workshop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="defects",
                        to="workshops.workshop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Defeito",
                "verbose_name_plural": "Defeitos",
            },
        ),
        migrations.AddField(
            model_name="budget",
            name="defect",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="budgets",
                to="budget.defect",
            ),
        ),
        migrations.AddConstraint(
            model_name="defect",
            constraint=models.UniqueConstraint(
                fields=("budget", "name"), name="unique_budget_name_per_defetct"
            ),
        ),
    ]
