# Generated by Django 6.0 on 2026-01-28 19:36

import djmoney.models.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0009_budgetitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetitem",
            name="duration",
            field=models.DurationField(blank=True, null=True, verbose_name="Duração"),
        ),
        migrations.AddField(
            model_name="budgetitem",
            name="product_cost_price",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=14,
                verbose_name="Valor de Custo (Produto)",
            ),
        ),
        migrations.AddField(
            model_name="budgetitem",
            name="product_cost_price_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("BRL", "Real Brasileiro")],
                default="BRL",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="budgetitem",
            name="product_selling_price",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=14,
                verbose_name="Valor de Venda (Produto)",
            ),
        ),
        migrations.AddField(
            model_name="budgetitem",
            name="product_selling_price_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("BRL", "Real Brasileiro")],
                default="BRL",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="budgetitem",
            name="service_cost_price",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=14,
                verbose_name="Valor de Custo (Serviço)",
            ),
        ),
        migrations.AddField(
            model_name="budgetitem",
            name="service_cost_price_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("BRL", "Real Brasileiro")],
                default="BRL",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="budgetitem",
            name="service_selling_price",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=14,
                verbose_name="Valor de Venda (Serviço)",
            ),
        ),
        migrations.AddField(
            model_name="budgetitem",
            name="service_selling_price_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("BRL", "Real Brasileiro")],
                default="BRL",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="budgetitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="Quantidade"),
        ),
    ]
