# Generated by Django 6.0 on 2026-01-28 22:22

import djmoney.models.fields
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0010_budgetitem_duration_budgetitem_product_cost_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="budget",
            name="base_value",
        ),
        migrations.RemoveField(
            model_name="budget",
            name="base_value_currency",
        ),
        migrations.RemoveField(
            model_name="budget",
            name="total_value",
        ),
        migrations.RemoveField(
            model_name="budget",
            name="total_value_currency",
        ),
        migrations.AlterField(
            model_name="budget",
            name="discount_value",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("0.0"),
                max_digits=14,
                verbose_name="Aplicar Desconto (R$)",
            ),
        ),
    ]
