# Generated by Django 6.0 on 2026-01-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0011_remove_budget_base_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Em Aberto"),
                    ("approved", "Aprovado"),
                    ("rejected", "Rejeitado"),
                    ("cancelled", "Cancelado"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
