# Generated by Django 6.0 on 2026-02-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0012_alter_budget_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="fuel_level",
            field=models.PositiveIntegerField(
                choices=[
                    (8, "Cheio"),
                    (7, "7/8"),
                    (6, "3/4"),
                    (5, "1/2"),
                    (4, "1/4"),
                    (3, "1/8"),
                    (2, "Reserva"),
                    (1, "Vazio"),
                ],
                default=8,
                verbose_name="Nível do Tanque",
            ),
        ),
    ]
