# Generated by Django 6.0 on 2026-02-02 13:38

import djmoney.models.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0013_alter_budget_fuel_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetitem",
            name="description",
            field=models.CharField(
                default="", max_length=100, verbose_name="Descrição"
            ),
        ),
        migrations.AddField(
            model_name="budgetitem",
            name="shipping",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=14,
                verbose_name="Frete",
            ),
        ),
        migrations.AddField(
            model_name="budgetitem",
            name="shipping_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("BRL", "Real Brasileiro")],
                default="BRL",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="budgetitem",
            name="product_cost_price",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=14,
                verbose_name="Custo",
            ),
        ),
        migrations.AlterField(
            model_name="budgetitem",
            name="product_selling_price",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=14,
                verbose_name="Valor de Venda",
            ),
        ),
        migrations.AlterField(
            model_name="budgetitem",
            name="service_cost_price",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=14,
                verbose_name="Custo",
            ),
        ),
        migrations.AlterField(
            model_name="budgetitem",
            name="service_selling_price",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=14,
                verbose_name="Valor de Venda",
            ),
        ),
    ]
