# Generated by Django 6.0 on 2026-02-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0014_budgetitem_description_budgetitem_shipping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='is_local',
            field=models.BooleanField(default=False, help_text='Item criado apenas neste orçamento, não cadastrado no banco de dados', verbose_name='Item Local'),
        ),
    ]
