# Generated by Django 6.0 on 2026-02-05 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0015_budgetitem_is_local'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetimage',
            options={'ordering': ['criado_em'], 'verbose_name': 'Imagem do Orçamento', 'verbose_name_plural': 'Imagens do Orçamento'},
        ),
    ]
