# Generated by Django 6.0 on 2026-02-05 03:21

import django.db.models.deletion
import djmoney.models.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0016_alter_budgetimage_options'),
        ('catalog', '0011_alter_kit_atualizado_em_alter_kit_criado_em_and_more'),
        ('workshops', '0010_alter_workshopcost_minimum_hourly_cost_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetitem',
            options={'verbose_name': 'Item do Orçamento', 'verbose_name_plural': 'Itens do Orçamento'},
        ),
        migrations.CreateModel(
            name='BudgetKitItemOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('product_cost_price_currency', djmoney.models.fields.CurrencyField(choices=[('BRL', 'Real Brasileiro')], default='BRL', editable=False, max_length=3)),
                ('product_cost_price', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Custo do Produto')),
                ('product_selling_price_currency', djmoney.models.fields.CurrencyField(choices=[('BRL', 'Real Brasileiro')], default='BRL', editable=False, max_length=3)),
                ('product_selling_price', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Preço de Venda do Produto')),
                ('shipping_currency', djmoney.models.fields.CurrencyField(choices=[('BRL', 'Real Brasileiro')], default='BRL', editable=False, max_length=3)),
                ('shipping', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Frete')),
                ('service_cost_price_currency', djmoney.models.fields.CurrencyField(choices=[('BRL', 'Real Brasileiro')], default='BRL', editable=False, max_length=3)),
                ('service_cost_price', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Custo do Serviço')),
                ('service_selling_price_currency', djmoney.models.fields.CurrencyField(choices=[('BRL', 'Real Brasileiro')], default='BRL', editable=False, max_length=3)),
                ('service_selling_price', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Preço de Venda do Serviço')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Duração')),
                ('budget_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kit_overrides', to='budget.budgetitem')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.service')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kit_overrides', to='workshops.workshop')),
            ],
            options={
                'verbose_name': 'Override de Item do Kit',
                'verbose_name_plural': 'Overrides de Itens do Kit',
                'constraints': [models.UniqueConstraint(condition=models.Q(('product__isnull', False)), fields=('budget_item', 'product'), name='unique_budget_kit_product'), models.UniqueConstraint(condition=models.Q(('service__isnull', False)), fields=('budget_item', 'service'), name='unique_budget_kit_service')],
            },
        ),
    ]
