# Generated by Django 6.0 on 2026-02-05 04:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0017_alter_budgetitem_options_budgetkititemoverride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetkititemoverride',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade'),
        ),
    ]
