# Generated by Django 6.0 on 2026-02-07 22:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0018_alter_budgetkititemoverride_quantity"),
        ("workshops", "0010_alter_workshopcost_minimum_hourly_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetimage",
            name="image_type",
            field=models.CharField(
                choices=[("principal", "Principal"), ("frontal", "Frontal"), ("traseira", "Traseira"), ("direita", "Direita"), ("esquerda", "Esquerda"), ("painel", "Painel"), ("chassi", "Chassi"), ("motor", "Motor"), ("additional", "Adicional")], default="additional", max_length=20, verbose_name="Tipo de Imagem"
            ),
        ),
        migrations.AddConstraint(
            model_name="budgetimage",
            constraint=models.UniqueConstraint(condition=models.Q(("image_type", "additional"), _negated=True), fields=("budget", "image_type"), name="unique_budget_image_type_non_additional"),
        ),
    ]
