# Generated by Django 6.0 on 2026-02-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0019_budgetimage_image_type_alter_budget_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='signature_token_active',
            field=models.BooleanField(default=True, verbose_name='Token de Assinatura Ativo'),
        ),
        migrations.AddField(
            model_name='budget',
            name='signature_token_version',
            field=models.PositiveIntegerField(default=1, verbose_name='ID do PDF do Orçamento'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='status',
            field=models.CharField(choices=[('draft', 'Em Aberto'), ('waiting_client', 'Aguardando Relato do Cliente'), ('waiting_diagnosis', 'Aguardando Diagnóstico'), ('waiting_items', 'Aguardando Itens'), ('waiting_pricing', 'Aguardando Precificação'), ('waiting_review', 'Aguardando Revisão'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('cancelled', 'Cancelado')], default='draft', max_length=20, verbose_name='Status'),
        ),
    ]
