# Generated by Django 6.0 on 2026-02-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0019_budgetimage_image_type_alter_budget_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="step5_calculation_viewed",
            field=models.BooleanField(default=False, verbose_name="Calculo da etapa 5 visualizado"),
        ),
    ]
