# Generated by Django 6.0 on 2026-02-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0020_budget_signature_token_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='signature_external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='signature_request_status',
            field=models.CharField(choices=[('not_sent', 'Não Enviado'), ('sending', 'Enviando'), ('sent', 'Enviado'), ('failed', 'Falha no Envio')], default='not_sent', max_length=30),
        ),
        migrations.AddField(
            model_name='budget',
            name='signature_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
