# Generated by Django 5.2.9 on 2026-02-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0020_budget_step5_calculation_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='status',
            field=models.CharField(choices=[('draft', 'Em Aberto'), ('waiting_client', 'Aguardando Relato do Cliente'), ('waiting_diagnosis', 'Aguardando Diagnóstico'), ('waiting_items', 'Aguardando Itens'), ('waiting_pricing', 'Aguardando Precificação'), ('waiting_review', 'Aguardando Revisão'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('cancelled', 'Cancelado')], default='draft', max_length=20, verbose_name='Status'),
        ),
    ]
