# Generated by Django 6.0 on 2026-02-13 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0021_alter_budget_status'),
        ('budget', '0021_budget_signature_external_id_and_more'),
    ]

    operations = [
    ]
