# Generated by Django 6.0 on 2026-02-16 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0022_merge_20260213_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='signature_request_status',
            field=models.CharField(choices=[('not_sent', 'Não Enviado'), ('sending', 'Enviando'), ('sent', 'Enviado'), ('failed', 'Falha no Envio'), ('approved', 'Aprovado')], default='not_sent', max_length=30),
        ),
    ]
