# Generated by Django 5.2.9 on 2026-02-16 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0023_alter_budget_signature_request_status'),
        ('checklist', '0003_alter_checklist_options_alter_checklistitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='checklist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='checklist.checklist', verbose_name='Checklist'),
        ),
    ]
