# Generated by Django 5.2.9 on 2026-02-18 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0024_budget_checklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='fuel_level',
            field=models.PositiveIntegerField(blank=True, choices=[(8, 'Cheio'), (7, '7/8'), (6, '3/4'), (5, '1/2'), (4, '1/4'), (3, '1/8'), (2, 'Reserva'), (1, 'Vazio')], null=True, verbose_name='Nível do Tanque'),
        ),
    ]
