# Generated by Django 6.0 on 2026-03-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0025_alter_budget_fuel_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='signature_document_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
