# Generated by Django 6.0 on 2026-03-14 18:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0026_budget_signature_document_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=7, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Aplicar Desconto (%)'),
        ),
    ]
