# Generated by Django 6.0 on 2026-03-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0027_budget_discount_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="pdf_observation",
            field=models.CharField(blank=True, default="", max_length=250, verbose_name="Observação do PDF"),
        ),
    ]
