# Generated by Django 6.0 on 2026-03-30 18:47
# Fixed: table already existed in DB on some environments – use SeparateDatabaseAndState
# so the migration is idempotent (IF NOT EXISTS on the DDL side).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0029_drop_legacy_budget_pdf_observation_column"),
        ("collaborators", "0006_workshopcollaborator_timestamps"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # Tell Django ORM that this M2M field now exists in the schema state.
            state_operations=[
                migrations.AddField(
                    model_name="budget",
                    name="collaborators",
                    field=models.ManyToManyField(
                        blank=True,
                        related_name="collaborators_budgets",
                        to="collaborators.workshopcollaborator",
                        verbose_name="Colaboradores",
                    ),
                ),
            ],
            # Create the table only if it doesn't already exist (safe for all envs).
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        CREATE TABLE IF NOT EXISTS "budget_budget_collaborators" (
                            "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                            "budget_id" bigint NOT NULL,
                            "workshopcollaborator_id" bigint NOT NULL
                        );
                    """,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
    ]

