# Generated by Django 6.0 on 2026-03-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0029_drop_legacy_budget_pdf_observation_column"),
        ("collaborators", "0006_workshopcollaborator_timestamps"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="collaborators",
            field=models.ManyToManyField(
                blank=True,
                related_name="collaborators_budgets",
                to="collaborators.workshopcollaborator",
                verbose_name="Colaboradores",
            ),
        ),
    ]
