# Generated by Django 5.2.9 on 2026-04-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0034_budget_is_warranty_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='budget_type',
            field=models.CharField(choices=[('sell', 'Venda'), ('warranty', 'Garantia'), ('courtesy', 'Cortesia')], default='sell', verbose_name='Tipo de Orçamento'),
        ),
    ]
