# Generated by Django 5.2.9 on 2026-04-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0035_budget_budget_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='budget_type',
            field=models.CharField(choices=[('sale', 'Venda'), ('warranty', 'Garantia'), ('courtesy', 'Cortesia')], default='sale', verbose_name='Tipo de Orçamento'),
        ),
    ]
