# Generated by Django 6.0 on 2026-04-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0037_alter_budget_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="budget_type",
            field=models.CharField(
                choices=[
                    ("sale", "Venda"),
                    ("warranty", "Garantia"),
                    ("courtesy", "Cortesia"),
                ],
                default="sale",
                max_length=50,
                verbose_name="Tipo de Orçamento",
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Em Aberto"),
                    ("waiting_client", "Aguardando Relato do Cliente"),
                    ("waiting_diagnosis", "Aguardando Diagnóstico"),
                    ("waiting_items", "Aguardando Itens"),
                    ("waiting_pricing", "Aguardando Precificação"),
                    ("waiting_review", "Aguardando Revisão"),
                    ("approved", "Aprovado"),
                    ("rejected", "Rejeitado"),
                    ("cancelled", "Cancelado"),
                ],
                default="draft",
                max_length=50,
                verbose_name="Status",
            ),
        ),
    ]
