# Generated by Django 6.0 on 2026-04-21 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0038_alter_budget_budget_type_alter_budget_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='kit_snapshot_frozen',
            field=models.BooleanField(default=False, verbose_name='Snapshot do kit congelado'),
        ),
    ]
