# Generated by Django 6.0 on 2026-04-23 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0039_budgetitem_kit_snapshot_frozen"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="reference_budget",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_budgets",
                to="budget.budget",
                verbose_name="Orçamento de Referência",
            ),
        ),
    ]
