# Generated by Django 5.2.9 on 2026-04-23 23:40

import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0040_budget_reference_budget"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="pricing_hourly_cost_value",
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name="Valor hora congelado"),
        ),
        migrations.AddField(
            model_name="budget",
            name="pricing_hourly_cost_value_currency",
            field=djmoney.models.fields.CurrencyField(choices=[("BRL", "Real Brasileiro")], default="BRL", editable=False, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="budget",
            name="pricing_minimum_hourly_cost",
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name="Custo hora mínimo congelado"),
        ),
        migrations.AddField(
            model_name="budget",
            name="pricing_minimum_hourly_cost_currency",
            field=djmoney.models.fields.CurrencyField(choices=[("BRL", "Real Brasileiro")], default="BRL", editable=False, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="budget",
            name="pricing_productive_salary_total",
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name="Total congelado de salários produtivos"),
        ),
        migrations.AddField(
            model_name="budget",
            name="pricing_productive_salary_total_currency",
            field=djmoney.models.fields.CurrencyField(choices=[("BRL", "Real Brasileiro")], default="BRL", editable=False, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="budget",
            name="pricing_profitability_multiplier",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Multiplicador congelado"),
        ),
        migrations.AddField(
            model_name="budget",
            name="pricing_reference_month",
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name="Mês de referência da precificação"),
        ),
        migrations.AddField(
            model_name="budget",
            name="pricing_reference_year",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Ano de referência da precificação"),
        ),
        migrations.AddField(
            model_name="budget",
            name="pricing_working_hours_per_month",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Horas úteis/mês congeladas"),
        ),
    ]
