# Generated by Django 6.0 on 2026-04-24 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0041_budget_pricing_hourly_cost_value_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Em Aberto"),
                    ("waiting_client", "Aguardando Relato do Cliente"),
                    ("waiting_diagnosis", "Aguardando Diagnóstico"),
                    ("waiting_items", "Aguardando Itens"),
                    ("waiting_pricing", "Aguardando Precificação"),
                    ("waiting_review", "Aguardando Revisão"),
                    ("waiting_approval", "Aguardando Aprovação"),
                    ("approved", "Aprovado"),
                    ("rejected", "Rejeitado"),
                    ("cancelled", "Cancelado"),
                ],
                default="draft",
                max_length=50,
                verbose_name="Status",
            ),
        ),
    ]
