# Generated by Django 6.0 on 2026-04-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0042_alter_budget_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="customer_agreed_departure_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Data de saída combinada com o Cliente"),
        ),
        migrations.AddField(
            model_name="budget",
            name="service_expected_completion_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Data prevista de término do serviço"),
        ),
    ]
