# Generated by Django 6.0 on 2026-05-18 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0045_normalize_rejected_status_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('action', models.CharField(choices=[('reopened', 'Orçamento reaberto')], max_length=30, verbose_name='Ação')),
                ('reason', models.TextField(blank=True, verbose_name='Justificativa')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='budget.budget')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_history_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico do orçamento',
                'verbose_name_plural': 'Histórico dos orçamentos',
                'ordering': ['-criado_em', '-pk'],
            },
        ),
    ]
