# Generated by Django 6.0 on 2026-06-03 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0046_budgethistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='observations',
            field=models.TextField(blank=True, default='', verbose_name='Observações'),
        ),
    ]
