# Generated by Django 6.0 on 2026-06-03 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0047_budget_observations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='pdf_observation',
        ),
    ]
