# Generated by Django 6.0 on 2026-06-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0048_remove_budget_pdf_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='pricing_method',
            field=models.CharField(blank=True, choices=[('hunter', 'Hunter'), ('traditional', 'Tradicional')], max_length=20, null=True, verbose_name='Método de Precificação'),
        ),
    ]
