# Generated by Django 6.0 on 2026-06-26 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0051_budgetitem_item_benefit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgethistory',
            name='snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='Snapshot dos itens'),
        ),
    ]
