# Generated by Django 6.0 on 2026-06-30 19:30

import djmoney.models.fields
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0051_budgetitem_item_benefit_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetitem",
            name="service_shipping",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=14,
                verbose_name="Frete do Serviço",
            ),
        ),
        migrations.AddField(
            model_name="budgetitem",
            name="service_shipping_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("BRL", "Real Brasileiro")],
                default="BRL",
                editable=False,
                max_length=3,
            ),
        ),
    ]
