# Generated by Django 6.0 on 2026-07-01 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0053_budgetitem_service_shipping_and_more'),
        ('budget', '0053_merge_20260701_0052_budget_leaves'),
    ]

    operations = [
    ]
