# Generated by Django 6.0 on 2026-07-06 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0054_budgetpdfrenderjob'),
        ('budget', '0054_merge_20260630_2305'),
    ]

    operations = [
    ]
