# Generated by Django 6.0 on 2026-07-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0055_merge_20260706_0122"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(fields=["workshop", "status", "entry_date"], name="budget_ws_status_entry_idx"),
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(fields=["workshop", "entry_date"], name="budget_ws_entry_idx"),
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(fields=["customer", "criado_em"], name="budget_customer_criado_idx"),
        ),
    ]
