# Generated by Django 5.2.9 on 2026-07-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0055_merge_20260706_0122"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="budgetpdfrenderjob",
            options={
                "verbose_name": "Fila de renderização de PDF do orçamento",
                "verbose_name_plural": "Filas de renderização de PDFs do orçamento",
            },
        ),
        migrations.AlterField(
            model_name="budgetpdfrenderjob",
            name="atualizado_em",
            field=models.DateTimeField(auto_now=True, verbose_name="Data de Atualização"),
        ),
        migrations.AlterField(
            model_name="budgetpdfrenderjob",
            name="criado_em",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Data de Criação"),
        ),
    ]
