# Generated by Django 6.0 on 2026-07-12 18:26

import djmoney.models.fields
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0057_alter_budgetpdfrenderjob_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='stored_total_amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), help_text='Total denormalizado para agregações (dashboard). Atualizado no write path.', max_digits=14, verbose_name='Total armazenado do orçamento'),
        ),
        migrations.AddField(
            model_name='budget',
            name='stored_total_amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('BRL', 'Real Brasileiro')], default='BRL', editable=False, max_length=3),
        ),
    ]
