# Generated by Django 5.2.5 on 2026-07-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0059_merge_0056_alter_0058_stored_totals"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="rejection_reason",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Motivo da Reprovação",
            ),
        ),
    ]
