# Generated by Django 6.0 on 2026-07-23 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0059_merge_0056_alter_0058_stored_totals'),
        ('workshops', '0028_oil_change_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='last_oil_change_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data da última troca de óleo'),
        ),
        migrations.AddField(
            model_name='budget',
            name='last_oil_change_km',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='KM da última troca de óleo'),
        ),
        migrations.AddField(
            model_name='budget',
            name='oil_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='workshops.oiltype', verbose_name='Tipo de óleo'),
        ),
    ]
