# Generated by Django 6.0 on 2026-08-01 21:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0061_review_plan_and_messaging_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='customer_agreed_departure_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de saída combinada com o cliente'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='discount_type',
            field=models.CharField(choices=[('products', 'Apenas Produtos'), ('services', 'Apenas Serviços'), ('both', 'Produtos e Serviços')], default='both', max_length=10, verbose_name='Tipo de desconto'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='slider',
            field=models.SmallIntegerField(default=0, help_text='Negativo: Peça | Positivo: Mão de Obra', validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)], verbose_name='Controle de margem'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='step5_calculation_viewed',
            field=models.BooleanField(default=False, verbose_name='Cálculo da etapa 5 visualizado'),
        ),
    ]
