# Generated by Django 6.0 on 2026-08-03 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0060_alter_budgetitem_is_customer_supplied'),
        ('budget', '0061_review_plan_and_messaging_updates'),
    ]

    operations = [
    ]
