# Generated by Django 6.0 on 2026-08-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0062_fix_budget_ui_verbose_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='discount_type',
            field=models.CharField(choices=[('products', 'Apenas produtos'), ('services', 'Apenas serviços'), ('both', 'Produtos e serviços')], default='both', max_length=10, verbose_name='Tipo de desconto'),
        ),
    ]
