# Generated by Django 6.0 on 2026-08-05 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0060_add_rejection_reason_field"),
        ("budget", "0062_merge_20260803_1522"),
    ]

    operations = []
