# Generated by Django 6.0 on 2026-08-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0062_merge_20260803_1522"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Data de fechamento"),
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(fields=["workshop", "status", "closed_at"], name="budget_ws_status_closed_idx"),
        ),
    ]
