# Generated by Django 6.0 on 2026-08-07 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0062_merge_20260803_1522"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="first_approved_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Data da primeira aprovação"),
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(fields=["workshop", "status", "first_approved_at"], name="budget_ws_status_1st_appr_idx"),
        ),
    ]
