# Generated by Django 6.0 on 2026-08-07 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0063_merge_20260805_1742"),
        ("budget", "0065_budget_number_and_workshop_sequence"),
    ]

    operations = []
