# Generated by Django 6.0 on 2026-08-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0066_merge_20260807_1113"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetitem",
            name="description",
            field=models.CharField(default="", max_length=500, verbose_name="Descrição"),
        ),
    ]
