# Generated by Django 6.0 on 2026-08-07 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0066_merge_20260807_1041"),
        ("budget", "0066_merge_20260807_1113"),
    ]

    operations = []
