# Generated by Django 6.0 on 2026-08-07 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0066_merge_20260807_1113"),
        ("budget", "0066_merge_closed_at_and_budget_number"),
    ]

    operations = []
