# Generated by Django 6.0 on 2026-08-20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0067_alter_budgetitem_description_max_length"),
        ("collaborators", "0014_merge_20260722_1538"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="cancellation_responsible",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="cancelled_budgets", to="collaborators.workshopcollaborator", verbose_name="Responsável pelo atendimento no cancelamento"),
        ),
        migrations.AddField(
            model_name="budget",
            name="rejection_responsible",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="rejected_budgets", to="collaborators.workshopcollaborator", verbose_name="Responsável pelo atendimento na reprovação"),
        ),
    ]
