# Generated by Django 5.2.9 on 2026-08-20 18:38
# Adjusted for correcoes_lucas_main: 0068_budget_created_by was removed with the
# redesign cleanup, so this merge only depends on the cancellation responsible leaf.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0068_budget_cancellation_responsible_and_more"),
    ]

    operations = []
