# Generated by Django 6.0 on 2026-08-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0069_merge_budget_cancellation_responsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetkititemoverride',
            name='excluded_from_composition',
            field=models.BooleanField(default=False, help_text='Remove o serviço da execução do kit mantendo o valor no total.', verbose_name='Excluído da composição'),
        ),
    ]
