# Generated by Django 5.2.9 on 2026-08-25 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0068_custo_de_frete'),
        ('budget', '0069_merge_budget_cancellation_responsible'),
    ]

    operations = [
    ]
