# Generated by Django 6.0 on 2026-01-29 15:01

import django.db.models.deletion
import djmoney.models.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("budget", "0011_remove_budget_base_value_and_more"),
        ("workshops", "0006_workshop_pdf_observation"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "budget",
                    models.ForeignKey(
                        help_text="Orçamento Aprovado vinculado à esta O.S.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workorders",
                        to="budget.budget",
                    ),
                ),
                (
                    "workshop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workorders",
                        to="workshops.workshop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ordem de Serviço",
                "verbose_name_plural": "Ordens de Serviço",
            },
        ),
        migrations.CreateModel(
            name="WorkOrderAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                ("file", models.FileField(upload_to="workorders/attachments/")),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="workorder.workorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Imagem da OS",
                "verbose_name_plural": "Imagens da OS",
            },
        ),
        migrations.CreateModel(
            name="WorkOrderPaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "atualizado_em",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CREDITO", "Cartão de Crédito"),
                            ("DEBITO", "Cartão de Débito"),
                            ("PIX", "Pix"),
                            ("DINHEIRO", "Dinheiro"),
                            ("BOLETO", "Boleto"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "installments_count",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Número de Parcelas"
                    ),
                ),
                (
                    "first_installment_amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("BRL", "Real Brasileiro")],
                        default="BRL",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "first_installment_amount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default=Decimal("0.0"),
                        max_digits=14,
                        verbose_name="Valor da Primeira Parcela)",
                    ),
                ),
                (
                    "remaining_installments_amount_currency",
                    djmoney.models.fields.CurrencyField(
                        choices=[("BRL", "Real Brasileiro")],
                        default="BRL",
                        editable=False,
                        max_length=3,
                    ),
                ),
                (
                    "remaining_installments_amount",
                    djmoney.models.fields.MoneyField(
                        decimal_places=2,
                        default=Decimal("0.0"),
                        max_digits=14,
                        verbose_name="Valor das Parcelas Restantes",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="workorder.workorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plano de Pagamento",
                "verbose_name_plural": "Planos de Pagamento",
            },
        ),
    ]
