# Generated by Django 6.0 on 2026-01-29 18:22

import djmoney.models.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="workorderattachment",
            old_name="work_order",
            new_name="workorder",
        ),
        migrations.RenameField(
            model_name="workorderpaymentmethod",
            old_name="work_order",
            new_name="workorder",
        ),
        migrations.AlterField(
            model_name="workorderpaymentmethod",
            name="first_installment_amount",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("0.0"),
                max_digits=14,
                verbose_name="Valor da Primeira Parcela",
            ),
        ),
        migrations.AlterField(
            model_name="workorderpaymentmethod",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("CREDITO", "Cartão de Crédito"),
                    ("DEBITO", "Cartão de Débito"),
                    ("PIX", "Pix"),
                    ("DINHEIRO", "Dinheiro"),
                    ("BOLETO", "Boleto"),
                ],
                max_length=20,
                verbose_name="Forma de Pagamento",
            ),
        ),
    ]
