# Generated by Django 6.0 on 2026-01-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0002_rename_work_order_workorderattachment_workorder_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workorderattachment",
            name="description",
        ),
        migrations.RemoveField(
            model_name="workorderattachment",
            name="file",
        ),
        migrations.AddField(
            model_name="workorderattachment",
            name="content",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workorderattachment",
            name="content_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="workorderattachment",
            name="content_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
