# Generated by Django 6.0 on 2026-01-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0003_remove_workorderattachment_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="status",
            field=models.CharField(
                choices=[("draft", "Em Aberto"), ("approved", "Aprovado")],
                default="draft",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
