# Generated by Django 5.2.9 on 2026-02-15 14:17

import django.core.validators
import django.db.models.deletion
import djmoney.models.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_kitservice_duration'),
        ('workorder', '0004_workorder_status'),
        ('workshops', '0013_alter_workshop_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='discount_value',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), max_digits=14, verbose_name='Desconto da O.S. (R$)'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='discount_value_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('BRL', 'Real Brasileiro')], default='BRL', editable=False, max_length=3),
        ),
        migrations.CreateModel(
            name='WorkOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('description', models.CharField(default='', max_length=100, verbose_name='Descrição')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('shipping_currency', djmoney.models.fields.CurrencyField(choices=[('BRL', 'Real Brasileiro')], default='BRL', editable=False, max_length=3)),
                ('shipping', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Frete')),
                ('product_cost_price_currency', djmoney.models.fields.CurrencyField(choices=[('BRL', 'Real Brasileiro')], default='BRL', editable=False, max_length=3)),
                ('product_cost_price', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Custo')),
                ('product_selling_price_currency', djmoney.models.fields.CurrencyField(choices=[('BRL', 'Real Brasileiro')], default='BRL', editable=False, max_length=3)),
                ('product_selling_price', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Valor de Venda')),
                ('service_cost_price_currency', djmoney.models.fields.CurrencyField(choices=[('BRL', 'Real Brasileiro')], default='BRL', editable=False, max_length=3)),
                ('service_cost_price', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Custo')),
                ('service_selling_price_currency', djmoney.models.fields.CurrencyField(choices=[('BRL', 'Real Brasileiro')], default='BRL', editable=False, max_length=3)),
                ('service_selling_price', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Valor de Venda')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Duração')),
                ('kit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.kit')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.service')),
                ('workorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='workorder.workorder')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workorder_items', to='workshops.workshop')),
            ],
            options={
                'verbose_name': 'Item da O.S.',
                'verbose_name_plural': 'Itens da O.S.',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderKitItemOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade')),
                ('product_cost_price_currency', djmoney.models.fields.CurrencyField(choices=[('BRL', 'Real Brasileiro')], default='BRL', editable=False, max_length=3)),
                ('product_cost_price', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Custo do Produto')),
                ('product_selling_price_currency', djmoney.models.fields.CurrencyField(choices=[('BRL', 'Real Brasileiro')], default='BRL', editable=False, max_length=3)),
                ('product_selling_price', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Preço de Venda do Produto')),
                ('shipping_currency', djmoney.models.fields.CurrencyField(choices=[('BRL', 'Real Brasileiro')], default='BRL', editable=False, max_length=3)),
                ('shipping', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Frete')),
                ('service_cost_price_currency', djmoney.models.fields.CurrencyField(choices=[('BRL', 'Real Brasileiro')], default='BRL', editable=False, max_length=3)),
                ('service_cost_price', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Custo do Serviço')),
                ('service_selling_price_currency', djmoney.models.fields.CurrencyField(choices=[('BRL', 'Real Brasileiro')], default='BRL', editable=False, max_length=3)),
                ('service_selling_price', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Preço de Venda do Serviço')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Duração')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.service')),
                ('workorder_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kit_overrides', to='workorder.workorderitem')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workorder_kit_overrides', to='workshops.workshop')),
            ],
            options={
                'verbose_name': 'Override de Item do Kit da O.S.',
                'verbose_name_plural': 'Overrides de Itens do Kit da O.S.',
                'constraints': [models.UniqueConstraint(condition=models.Q(('product__isnull', False)), fields=('workorder_item', 'product'), name='unique_workorder_kit_product'), models.UniqueConstraint(condition=models.Q(('service__isnull', False)), fields=('workorder_item', 'service'), name='unique_workorder_kit_service')],
            },
        ),
    ]
