# Generated by Django 5.2.9 on 2026-02-15 14:18

from django.db import migrations


def copy_budget_items_to_workorder(apps, schema_editor):
    WorkOrder = apps.get_model("workorder", "WorkOrder")
    WorkOrderItem = apps.get_model("workorder", "WorkOrderItem")
    WorkOrderKitItemOverride = apps.get_model("workorder", "WorkOrderKitItemOverride")
    BudgetItem = apps.get_model("budget", "BudgetItem")
    BudgetKitItemOverride = apps.get_model("budget", "BudgetKitItemOverride")

    db_alias = schema_editor.connection.alias

    workorders = WorkOrder.objects.using(db_alias).select_related("budget").all()
    for workorder in workorders.iterator():
        WorkOrderItem.objects.using(db_alias).filter(workorder_id=workorder.id).delete()

        budget_items = list(BudgetItem.objects.using(db_alias).filter(budget_id=workorder.budget_id).order_by("id"))
        created_items = WorkOrderItem.objects.using(db_alias).bulk_create(
            [
                WorkOrderItem(
                    workshop_id=workorder.workshop_id,
                    workorder_id=workorder.id,
                    product_id=budget_item.product_id,
                    service_id=budget_item.service_id,
                    kit_id=budget_item.kit_id,
                    description=budget_item.description,
                    quantity=budget_item.quantity,
                    shipping=budget_item.shipping,
                    shipping_currency=budget_item.shipping_currency,
                    product_cost_price=budget_item.product_cost_price,
                    product_cost_price_currency=budget_item.product_cost_price_currency,
                    product_selling_price=budget_item.product_selling_price,
                    product_selling_price_currency=budget_item.product_selling_price_currency,
                    service_cost_price=budget_item.service_cost_price,
                    service_cost_price_currency=budget_item.service_cost_price_currency,
                    service_selling_price=budget_item.service_selling_price,
                    service_selling_price_currency=budget_item.service_selling_price_currency,
                    duration=budget_item.duration,
                )
                for budget_item in budget_items
            ]
        )

        budget_to_workorder_item = {budget_item.id: workorder_item.id for budget_item, workorder_item in zip(budget_items, created_items)}

        if budget_to_workorder_item:
            budget_overrides = BudgetKitItemOverride.objects.using(db_alias).filter(budget_item_id__in=list(budget_to_workorder_item.keys()))
            WorkOrderKitItemOverride.objects.using(db_alias).bulk_create(
                [
                    WorkOrderKitItemOverride(
                        workshop_id=workorder.workshop_id,
                        workorder_item_id=budget_to_workorder_item[override.budget_item_id],
                        product_id=override.product_id,
                        service_id=override.service_id,
                        quantity=override.quantity,
                        product_cost_price=override.product_cost_price,
                        product_cost_price_currency=override.product_cost_price_currency,
                        product_selling_price=override.product_selling_price,
                        product_selling_price_currency=override.product_selling_price_currency,
                        shipping=override.shipping,
                        shipping_currency=override.shipping_currency,
                        service_cost_price=override.service_cost_price,
                        service_cost_price_currency=override.service_cost_price_currency,
                        service_selling_price=override.service_selling_price,
                        service_selling_price_currency=override.service_selling_price_currency,
                        duration=override.duration,
                    )
                    for override in budget_overrides
                ]
            )

        workorder.discount_value = workorder.budget.discount_value
        workorder.discount_value_currency = workorder.budget.discount_value_currency
        workorder.save(update_fields=["discount_value", "discount_value_currency"])


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0017_alter_budgetitem_options_budgetkititemoverride"),
        ("workorder", "0005_workorder_discount_value_and_more"),
    ]

    operations = [
        migrations.RunPython(copy_budget_items_to_workorder, noop_reverse),
    ]
