# Generated by Django 5.2.9 on 2026-02-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0006_workorder_snapshot_backfill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Em Aberto'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('cancelled', 'Cancelado')], default='draft', max_length=20, verbose_name='Status'),
        ),
    ]
