# Generated by Django 5.2.9 on 2026-03-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0007_alter_workorder_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="signature_external_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="workorder",
            name="signature_request_status",
            field=models.CharField(
                choices=[
                    ("not_sent", "Não Enviado"),
                    ("sending", "Enviando"),
                    ("sent", "Enviado"),
                    ("failed", "Falha no Envio"),
                    ("approved", "Aprovado"),
                ],
                default="not_sent",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="signature_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
