# Generated by Django 6.0 on 2026-03-08 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0011_paymentmethod"),
        ("workorder", "0007_alter_workorder_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workorderpaymentmethod",
            name="payment_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="finance.paymentmethod",
                verbose_name="Forma de Pagamento",
            ),
        ),
    ]
