# Generated by Django 6.0 on 2026-03-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0008_workorder_signature_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='signature_token_active',
            field=models.BooleanField(default=True, verbose_name='Token de Assinatura Ativo'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='signature_token_version',
            field=models.PositiveIntegerField(default=1, verbose_name='ID do PDF da Ordem de Serviço'),
        ),
    ]
