# Generated by Django 6.0 on 2026-03-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0008_alter_workorderpaymentmethod_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="signature_external_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="workorder",
            name="signature_request_status",
            field=models.CharField(
                choices=[
                    ("not_sent", "Não Enviado"),
                    ("sending", "Enviando"),
                    ("sent", "Enviado"),
                    ("failed", "Falha no Envio"),
                    ("approved", "Aprovado"),
                ],
                default="not_sent",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="signature_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workorder",
            name="signature_token_active",
            field=models.BooleanField(
                default=True, verbose_name="Token de Assinatura Ativo"
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="signature_token_version",
            field=models.PositiveIntegerField(
                default=1, verbose_name="ID do PDF da Ordem de Serviço"
            ),
        ),
    ]
