# Generated by Django 6.0 on 2026-03-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0009_workorder_signature_external_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='signature_document_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
