# Generated by Django 6.0 on 2026-03-11 14:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0009_workorder_signature_external_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderpaymentmethod',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Vencimento'),
        ),
    ]
