# Generated by Django 6.0 on 2026-03-11 14:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workorder", "0010_workorder_signature_document_id"),
        ("workorder", "0010_workorderpaymentmethod_due_date"),
    ]

    operations = []
