# Generated by Django 6.0 on 2026-03-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0012_workorder_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='km_final',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='KM Final'),
        ),
    ]
