# Generated by Django 6.0 on 2026-04-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0007_collaboratorbenefit_collaboratorcommissionentry_and_more'),
        ('workorder', '0013_workorder_km_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='workorders', to='collaborators.workshopcollaborator', verbose_name='Colaboradores'),
        ),
    ]
