# Generated by Django 6.0 on 2026-05-08 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0038_remove_financialgroup_dre_type"),
        ("workorder", "0015_alter_workorder_status_labels"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorderpaymentmethod",
            name="movement_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workorder_payments",
                to="finance.movementgroup",
            ),
        ),
    ]
