# Generated by Django 5.2.9 on 2026-05-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0022_add_reopen_workorder_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Aprovado'), ('approved', 'Veículo Entregue'), ('rejected', 'Reprovado'), ('cancelled', 'Cancelado')], default='draft', max_length=20, verbose_name='Status'),
        ),
    ]
