# Generated by Django 6.0 on 2026-05-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0023_alter_workorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='budget_type',
            field=models.CharField(choices=[('sale', 'Venda'), ('warranty', 'Garantia'), ('courtesy', 'Cortesia')], default='sale', max_length=50, verbose_name='Tipo'),
        ),
    ]
