# Generated by Django 6.0 on 2026-05-14 21:30

from django.db import migrations


def backfill_budget_type(apps, schema_editor):
    WorkOrder = apps.get_model("workorder", "WorkOrder")
    db_alias = schema_editor.connection.alias

    WorkOrder.objects.using(db_alias).filter(budget_type="").update(budget_type="sale")

    qs = (
        WorkOrder.objects.using(db_alias)
        .filter(
            budget_type="sale",
        )
        .select_related("budget")
        .only("pk", "budget_type", "budget__budget_type")
    )

    updates = []
    for wo in qs:
        if wo.budget and wo.budget.budget_type in ("warranty", "courtesy"):
            wo.budget_type = wo.budget.budget_type
            updates.append(wo)

    if updates:
        WorkOrder.objects.using(db_alias).bulk_update(updates, fields=["budget_type"])


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0035_budget_budget_type"),
        ("workorder", "0024_workorder_budget_type"),
    ]

    operations = [
        migrations.RunPython(backfill_budget_type, migrations.RunPython.noop),
    ]
