# Generated by Django 6.0 on 2026-06-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0025_backfill_workorder_budget_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='pricing_method',
            field=models.CharField(blank=True, choices=[('hunter', 'Hunter'), ('traditional', 'Tradicional')], max_length=20, null=True, verbose_name='Método de Precificação'),
        ),
    ]
