# Generated by Django 6.0 on 2026-06-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0026_add_pricing_method_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='discount_type',
            field=models.CharField(choices=[('products', 'Apenas Produtos'), ('services', 'Apenas Serviços'), ('both', 'Produtos e Serviços')], default='both', max_length=10, verbose_name='Tipo de Desconto'),
        ),
    ]
