# Generated by Django 6.0 on 2026-07-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0035_workorderitem_is_customer_supplied"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(fields=["workshop", "status", "delivered_at"], name="workorder_ws_status_deliv_idx"),
        ),
        migrations.AddIndex(
            model_name="workorder",
            index=models.Index(fields=["workshop", "status", "criado_em"], name="workorder_ws_status_criado_idx"),
        ),
        migrations.AddIndex(
            model_name="workorderpaymentmethod",
            index=models.Index(fields=["due_date", "workorder"], name="wo_payment_due_wo_idx"),
        ),
    ]
