# Generated by Django 6.0 on 2026-07-12 18:26

import djmoney.models.fields
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0036_phase3_hot_path_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='stored_paid_amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), help_text='Soma denormalizada dos planos de pagamento. Atualizado no write path.', max_digits=14, verbose_name='Total pago armazenado da O.S.'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='stored_paid_amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('BRL', 'Real Brasileiro')], default='BRL', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='workorder',
            name='stored_total_amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), help_text='Total denormalizado para agregações (dashboard). Atualizado no write path.', max_digits=14, verbose_name='Total armazenado da O.S.'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='stored_total_amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('BRL', 'Real Brasileiro')], default='BRL', editable=False, max_length=3),
        ),
    ]
