# Generated by Django 6.0 on 2026-07-29 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0038_merge_20260715_0157'),
        ('workshops', '0038_review_plan_and_messaging_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='last_oil_change_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data da última troca de óleo'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='last_oil_change_km',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='KM da última troca de óleo'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='review_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workorders', to='workshops.reviewplan', verbose_name='Plano de revisão'),
        ),
    ]
