# Generated by Django 6.0 on 2026-08-01 22:30

import django.db.models.deletion
import djmoney.models.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0063_fix_budget_discount_type_choice_labels'),
        ('finance', '0085_fix_finance_ui_verbose_names'),
        ('workorder', '0038_review_plan_and_messaging_updates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workorder',
            options={'permissions': [('reopen_workorder', 'Pode reabrir ordem de serviço')], 'verbose_name': 'Ordem de serviço', 'verbose_name_plural': 'Ordens de serviço'},
        ),
        migrations.AlterModelOptions(
            name='workorderattachment',
            options={'verbose_name': 'Imagem da O.S.', 'verbose_name_plural': 'Imagens da O.S.'},
        ),
        migrations.AlterModelOptions(
            name='workorderkititemoverride',
            options={'verbose_name': 'Substituição de item do kit da O.S.', 'verbose_name_plural': 'Substituições de itens do kit da O.S.'},
        ),
        migrations.AlterModelOptions(
            name='workorderpaymentmethod',
            options={'verbose_name': 'Plano de pagamento', 'verbose_name_plural': 'Planos de pagamento'},
        ),
        migrations.AlterField(
            model_name='workorder',
            name='budget',
            field=models.ForeignKey(help_text='Orçamento aprovado vinculado a esta O.S.', on_delete=django.db.models.deletion.CASCADE, related_name='workorders', to='budget.budget'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da entrega'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='discount_type',
            field=models.CharField(choices=[('products', 'Apenas produtos'), ('services', 'Apenas serviços'), ('both', 'Produtos e serviços')], default='both', max_length=10, verbose_name='Tipo de desconto'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='km_final',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='KM final'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='pricing_method',
            field=models.CharField(blank=True, choices=[('hunter', 'Hunter'), ('traditional', 'Tradicional')], max_length=20, null=True, verbose_name='Método de precificação'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='Justificativa da rejeição'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='signature_request_status',
            field=models.CharField(choices=[('not_sent', 'Não enviado'), ('sending', 'Enviando'), ('sent', 'Enviado'), ('failed', 'Falha no envio'), ('approved', 'Aprovado')], default='not_sent', max_length=30),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='signature_token_active',
            field=models.BooleanField(default=True, verbose_name='Token de assinatura ativo'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='signature_token_version',
            field=models.PositiveIntegerField(default=1, verbose_name='ID do PDF da ordem de serviço'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Aprovado'), ('approved', 'Veículo entregue'), ('rejected', 'Reprovado'), ('cancelled', 'Cancelado')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='workorderitem',
            name='item_benefit_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('warranty', 'Garantia'), ('courtesy', 'Cortesia')], default='normal', max_length=20, verbose_name='Tipo de benefício'),
        ),
        migrations.AlterField(
            model_name='workorderitem',
            name='kit_snapshot_frozen',
            field=models.BooleanField(default=False, verbose_name='Snapshot do kit congelado'),
        ),
        migrations.AlterField(
            model_name='workorderitem',
            name='product_selling_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Valor de venda'),
        ),
        migrations.AlterField(
            model_name='workorderitem',
            name='service_selling_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Valor de venda'),
        ),
        migrations.AlterField(
            model_name='workorderitem',
            name='service_shipping',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Frete do serviço'),
        ),
        migrations.AlterField(
            model_name='workorderkititemoverride',
            name='product_cost_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Custo do produto'),
        ),
        migrations.AlterField(
            model_name='workorderkititemoverride',
            name='product_selling_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Preço de venda do produto'),
        ),
        migrations.AlterField(
            model_name='workorderkititemoverride',
            name='service_cost_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Custo do serviço'),
        ),
        migrations.AlterField(
            model_name='workorderkititemoverride',
            name='service_selling_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Preço de venda do serviço'),
        ),
        migrations.AlterField(
            model_name='workorderpaymentmethod',
            name='first_installment_amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), max_digits=14, verbose_name='Valor da primeira parcela'),
        ),
        migrations.AlterField(
            model_name='workorderpaymentmethod',
            name='installments_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Número de parcelas'),
        ),
        migrations.AlterField(
            model_name='workorderpaymentmethod',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.paymentmethod', verbose_name='Forma de pagamento'),
        ),
        migrations.AlterField(
            model_name='workorderpaymentmethod',
            name='remaining_installments_amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), max_digits=14, verbose_name='Valor das parcelas restantes'),
        ),
    ]
