# Generated by Django 6.0 on 2026-07-31 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0038_merge_20260715_0157'),
        ('workorder', '0038_review_plan_and_messaging_updates'),
    ]

    operations = [
    ]
