# Generated by Django 5.2.9 on 2026-08-01 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0038_merge_20260715_0157'),
        ('workorder', '0039_fix_workorder_ui_verbose_names'),
    ]

    operations = [
    ]
