# Generated by Django 6.0 on 2026-07-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0039_review_plan_and_messaging_updates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workorderitem",
            name="is_customer_supplied",
            field=models.BooleanField(
                default=False, verbose_name="Peça fornecida pelo cliente"
            ),
        ),
    ]
