# Generated by Django 6.0 on 2026-08-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0040_merge_20260801_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='warranty_plan',
            field=models.CharField(blank=True, choices=[('days_30', '30 dias'), ('days_90', '90 dias'), ('days_180', '180 dias'), ('days_365', '365 dias'), ('none', 'Serviço sem garantia')], max_length=20, null=True, verbose_name='Plano de garantia'),
        ),
    ]
