# Generated by Django 6.0 on 2026-08-03 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0039_alter_workorderitem_is_customer_supplied'),
        ('workorder', '0041_workorder_warranty_plan'),
    ]

    operations = [
    ]
