# Generated by Django 6.0 on 2026-08-07 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collaborators', '0014_merge_20260722_1538'),
        ('workorder', '0042_merge_20260803_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='previous_mechanic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='collaborators.workshopcollaborator', verbose_name='Mecânico responsável pelo serviço anterior'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='courtesy_reason_type',
            field=models.CharField(blank=True, choices=[('part_defect', 'Defeito de peça'), ('labor_failure', 'Falha de mão de obra'), ('both', 'Ambos')], max_length=20, null=True, verbose_name='Motivo da cortesia/garantia'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='courtesy_reason_description',
            field=models.TextField(blank=True, verbose_name='Descrição do motivo da cortesia/garantia'),
        ),
    ]