# Generated by Django 6.0 on 2026-08-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0042_merge_20260803_1522"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="signature_decline_pending",
            field=models.BooleanField(
                default=False, verbose_name="Recusa de assinatura pendente"
            ),
        ),
    ]
