# Generated by Django 6.0 on 2026-08-21 05:35

from django.db import migrations


def migrate_waiting_delivery_to_draft(apps, schema_editor):
    """
    O status 'waiting_delivery' foi renomeado para 'draft' (label: Aprovado).
    Atualiza todos os registros legados no banco.
    """
    WorkOrder = apps.get_model("workorder", "WorkOrder")
    updated = WorkOrder.objects.filter(status="waiting_delivery").update(status="draft")
    if updated:
        print(f"  Migrated {updated} WorkOrder(s) from 'waiting_delivery' to 'draft'.")


def reverse_migrate(apps, schema_editor):
    WorkOrder = apps.get_model("workorder", "WorkOrder")
    WorkOrder.objects.filter(status="draft").update(status="waiting_delivery")


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0043_workorder_signature_decline_pending"),
    ]

    operations = [
        migrations.RunPython(
            migrate_waiting_delivery_to_draft,
            reverse_code=reverse_migrate,
        ),
    ]
