# Generated by Django 6.0 on 2026-08-07 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0043_workorder_courtesy_reason_fields"),
        ("workorder", "0043_workorder_signature_decline_pending"),
    ]

    operations = []
