# Generated by Django 6.0 on 2026-08-15 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0044_merge_20260807_1204'),
        ('workorder', '0045_workorder_waiting_statuses'),
    ]

    operations = [
    ]
