# Generated by Django 5.2.5 on 2026-08-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0047_workorder_courtesy_reason_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorderitem",
            name="is_local",
            field=models.BooleanField(default=False, verbose_name="Item Local"),
        ),
        migrations.AddField(
            model_name="workorderitem",
            name="local_item_type",
            field=models.CharField(
                blank=True,
                choices=[("product", "Produto"), ("service", "Serviço")],
                default="",
                max_length=20,
                verbose_name="Tipo do Item Local",
            ),
        ),
    ]
