# Generated by Django 5.2.9 on 2026-08-20 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0044_workorder_created_by'),
        ('workorder', '0048_clamp_current_step_after_removing_invoice'),
    ]

    operations = [
    ]
