# Generated by Django 5.2.5 on 2026-08-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0048_workorderitem_is_local_workorderitem_local_item_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorderkititemoverride",
            name="excluded_from_composition",
            field=models.BooleanField(default=False),
        ),
    ]
