# Generated by Django 5.2.5 on 2026-08-28 19:43

import django.db.models.deletion
from django.db import migrations, models


def backfill_warranty_origin(apps, schema_editor):
    WorkOrder = apps.get_model("workorder", "WorkOrder")
    # For warranties that have a budget with a reference_budget, link warranty_origin to the WO of that reference_budget.
    for wo in WorkOrder.objects.filter(budget_type="warranty", budget__reference_budget__isnull=False):
        try:
            origin_wo = WorkOrder.objects.get(budget=wo.budget.reference_budget)
            wo.warranty_origin = origin_wo
            wo.save(update_fields=["warranty_origin"])
        except WorkOrder.DoesNotExist:
            pass

class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0049_workorderkititemoverride_excluded_from_composition"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="warranty_origin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="warranty_children",
                to="workorder.workorder",
                verbose_name="WO de venda que originou a garantia",
            ),
        ),
        migrations.RunPython(
            backfill_warranty_origin,
            reverse_code=migrations.RunPython.noop,
        )
    ]
