# Generated by Django 5.2.9 on 2026-08-25 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0044_custo_de_frete'),
        ('workorder', '0044_migrate_waiting_delivery_to_draft'),
    ]

    operations = [
    ]
