# Generated by Django 5.2.9 on 2026-08-25 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0046_leftover_courtesy_reason_default"),
        ("workorder", "0051_merge_20260824_2208"),
    ]

    operations = []
