# Generated by Django 6.0 on 2026-08-28 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0050_add_warranty_origin"),
        ("workorder", "0054_merge_excluded_composition_and_os_tip"),
    ]

    operations = []
