# Generated by Django 5.2.9 on 2026-09-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0056_remove_workorder_item_description_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='budget_type',
            field=models.CharField(choices=[('sale', 'Venda'), ('direct_sale', 'Venda Direta'), ('warranty', 'Garantia'), ('courtesy', 'Cortesia')], default='sale', max_length=50, verbose_name='Tipo'),
        ),
    ]
