# Generated by Django 6.0 on 2026-09-23 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0073_alter_budget_budget_type"),
        ("workorder", "0058_merge_20260922_1329"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorderitem",
            name="budget_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workorder_items",
                to="budget.budgetitem",
            ),
        ),
        migrations.AlterField(
            model_name="workorderhistory",
            name="action",
            field=models.CharField(
                choices=[
                    ("reopened", "O.S. reaberta"),
                    ("delivery_date_changed", "Data de entrega alterada"),
                ],
                max_length=30,
                verbose_name="Ação",
            ),
        ),
    ]
