# Generated by Django 6.0 on 2026-09-22 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workorder", "0058_merge_20260911_1600"),
        ("workorder", "0058_merge_20260922_1329"),
    ]

    operations = []
