# Generated by Django 6.0 on 2026-09-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("info", "Informação"),
                    ("warning", "Aviso"),
                    ("alert", "Alerta"),
                ],
                default="info",
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
    ]
